src/patternfly/components/ContextSelector/examples/context-selector.md

fix(context-selector-a11y): fixed id concat

---

scripts/sizeReport/helpers.js
scripts/sizeReport/package.json
scripts/sizeReport/sizeReport.js

@redallen fixes sizeReport build error

fix(size-report): update size report

---

UPGRADE-GUIDE.md
src/patternfly/components/Form/examples/Form.md
src/patternfly/components/Form/form.scss

feat(form-section): added form section

---

src/patternfly/layouts/Flex/examples/Flex.md
src/patternfly/layouts/Flex/flex.scss
src/patternfly/layouts/Grid/examples/Grid.md
src/patternfly/layouts/Grid/grid.scss

closes #3245
closing https://github.com/patternfly/patternfly/pull/3253 in favor of this

feat(flex-grid): added ordering to grid and flex

---

src/patternfly/components/Form/examples/Form.md
src/patternfly/components/Form/form-alert.hbs
src/patternfly/components/Form/form.scss
src/patternfly/demos/Alert/examples/Alert.md
src/patternfly/demos/Alert/examples/horizontal-form.hbs
src/patternfly/demos/Alert/examples/page-default.hbs
src/patternfly/demos/Alert/examples/stacked-form.hbs

feat(alert): add inline variation demo

---

src/patternfly/demos/Alert/examples/horizontal-form.hbs
src/patternfly/demos/Alert/examples/stacked-form.hbs

fix(ally-01102020): fix ally errors

---

src/patternfly/components/DataList/data-list.scss
src/patternfly/components/_all.scss

fixes https://github.com/patternfly/patternfly/issues/3539

fix(data-list): made data-list-grid an import in data-list

---

src/patternfly/components/ModalBox/examples/ModalBox.md
src/patternfly/components/ModalBox/modal-box-title-icon.hbs
src/patternfly/components/ModalBox/modal-box-title-text.hbs
src/patternfly/components/ModalBox/modal-box-title.hbs
src/patternfly/components/ModalBox/modal-box.hbs
src/patternfly/components/ModalBox/modal-box.scss

fixes https://github.com/patternfly/patternfly/issues/3562

fix(modal-box): added icon variant, renamed error to danger

---

RELEASE-NOTES.md
src/patternfly/components/ModalBox/modal-box.scss

Also fixes a small issue found in testing - adds text truncation to the `pf-c-modal-box__title-text` element

fix(release-notes): added #3563 to release notes

---

src/patternfly/sass-utilities/mixins.scss

feat(var-stack-mixin): added css var stack mixin

---

src/patternfly/base/_variables.scss
src/patternfly/sass-utilities/scss-variables.scss

fixes https://github.com/patternfly/patternfly/issues/3512

fix(vars): added quotes around sass vars to retain quotes when compiled

---

src/patternfly/layouts/Grid/grid.scss

This just updates the order blocks to the new variable stack mixin.

refactor(grid-layout-order): updated order to use mixin

---

src/patternfly/components/TreeView/examples/TreeView.md
src/patternfly/components/TreeView/tree-view-node.hbs
src/patternfly/components/TreeView/tree-view.scss

fixes https://github.com/patternfly/patternfly/issues/3592

fix(treeview): moved actions element out of node

---

src/patternfly/components/Card/card-expandable-content.hbs
src/patternfly/components/Card/card-header-toggle-icon.hbs
src/patternfly/components/Card/card-header-toggle.hbs
src/patternfly/components/Card/card.scss
src/patternfly/components/Card/examples/Card.md

fixes https://github.com/patternfly/patternfly/issues/3554

feat(card): added expandable variation

---

src/patternfly/components/ToggleGroup/toggle-group.scss

fixes https://github.com/patternfly/patternfly/issues/3379

fix(togglegroup): updated button height to match other form elements

---

src/patternfly/components/ExpandableSection/expandable-section.scss

fixes https://github.com/patternfly/patternfly/issues/3493

fix(expandable-section): fixed nested component icon transform

---

src/patternfly/components/FormControl/form-control.scss

fixes https://github.com/patternfly/patternfly/issues/3580
@mceledonia @mcarrano This is what they look like together in this PR

fix(formcontrol): updated select arrow to align with other menu toggles

---

src/patternfly/components/DataList/data-list.scss
src/patternfly/components/DataList/examples/DataList.md

fixes https://github.com/patternfly/patternfly/issues/3544

fix(data-list): added variation to avoid shift when item is dragged over

---

src/patternfly/components/DualListSelector/dual-list-selector-actions-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector-controls-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector-controls.hbs
src/patternfly/components/DualListSelector/dual-list-selector-header-title-text.hbs
src/patternfly/components/DualListSelector/dual-list-selector-header.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item-main.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item-text.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector-list-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector-list.hbs
src/patternfly/components/DualListSelector/dual-list-selector-menu.hbs
src/patternfly/components/DualListSelector/dual-list-selector-pane.hbs
src/patternfly/components/DualListSelector/dual-list-selector-status-text.hbs
src/patternfly/components/DualListSelector/dual-list-selector-status.hbs
src/patternfly/components/DualListSelector/dual-list-selector-title-text.hbs
src/patternfly/components/DualListSelector/dual-list-selector-title.hbs
src/patternfly/components/DualListSelector/dual-list-selector-tools-actions.hbs
src/patternfly/components/DualListSelector/dual-list-selector-tools-filter.hbs
src/patternfly/components/DualListSelector/dual-list-selector-tools.hbs
src/patternfly/components/DualListSelector/dual-list-selector.hbs
src/patternfly/components/DualListSelector/dual-list-selector.scss
src/patternfly/components/DualListSelector/examples/DualListSelector.md
src/patternfly/components/_all.scss

fixes https://github.com/patternfly/patternfly/issues/3556
In the interest of time and a consideration on how the list is structured, I've only created the basic desktop version for now. In the next milestone we can add responsive design w/ breakpoint modifiers and variations of the menu/list types.

feat(dual-list-selector): added dual list selector component

---

src/patternfly/components/Table/examples/Table.md

fixes https://github.com/patternfly/patternfly/issues/3572
@jessiehuff we have `aria-controls` on the expandable table row toggle buttons and I don't see that attribute in the react component. Can you confirm which is correct?

chore(table): added examples with multiple expandable cells

---

src/patternfly/components/ActionList/action-list-group.hbs
src/patternfly/components/ActionList/action-list-item.hbs
src/patternfly/components/ActionList/action-list.hbs
src/patternfly/components/ActionList/action-list.scss
src/patternfly/components/ActionList/examples/ActionList.md
src/patternfly/components/_all.scss

feat(actionlist): add component

---

src/patternfly/components/Toolbar/examples/Toolbar.md
src/patternfly/components/Toolbar/toolbar-expand-all-icon.hbs
src/patternfly/components/Toolbar/toolbar-item-expand-all.hbs
src/patternfly/components/Toolbar/toolbar.scss
src/patternfly/demos/Table/table-collapsed-table.hbs
src/patternfly/demos/Table/table-expanded-table.hbs
src/patternfly/demos/Toolbar/examples/Toolbar.md

fixes https://github.com/patternfly/patternfly/issues/3600
https://patternfly-pr-3601.surge.sh/components/toolbar/html-demos/toolbar-expand-all-collapsed/
https://patternfly-pr-3601.surge.sh/components/toolbar/html-demos/toolbar-expand-all-expanded/

feat(toolbar): added support for expand all button

---

src/patternfly/components/Page/page.scss

https://github.com/patternfly/patternfly/issues/360

fix(page): made last child fill available space, not last-of-type

---

src/patternfly/components/DescriptionList/description-list.scss

fixes https://github.com/patternfly/patternfly/issues/3612

fix(description-list): updated auto-fit var names

---

src/patternfly/sass-utilities/scss-variables.scss

fixes https://github.com/patternfly/patternfly/issues/3618

fix(global-vars): updated active-color--300 and 400

---

src/patternfly/components/Form/examples/Form.md
src/patternfly/demos/Form/examples/BasicForms.md

fixes https://github.com/patternfly/patternfly/issues/2929
@mcarrano @mceledonia added an example of a form using a grid layout and updated the non-primary action to be a link button instead of secondary.

chore(form): added grid example, tidy hbs, change 2nd action to link

---

src/patternfly/demos/Drawer/drawer-demo-default.hbs
src/patternfly/demos/Drawer/examples/Drawer.md
src/patternfly/demos/Page/page-template-header-tools-elements.hbs

fixes https://github.com/patternfly/patternfly/issues/3620

chore(drawer): update demos, remove notification drawer demos

---

src/patternfly/components/Popover/examples/Popover.css
src/patternfly/components/Popover/examples/Popover.md
src/patternfly/components/Popover/popover.scss

fixes https://github.com/patternfly/patternfly/issues/3644

feat(popover): added variations for no-padding, auto-width

---

src/patternfly/components/JumpLinks/examples/JumpLinks.md
src/patternfly/components/JumpLinks/jump-links.scss

feat(jumplinks): add subsections

---

src/patternfly/components/ActionList/action-list.scss

fix(action-list): refactor css

---

src/patternfly/components/DualListSelector/dual-list-selector-actions-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector-controls-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector-controls.hbs
src/patternfly/components/DualListSelector/dual-list-selector-header.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item-check.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item-count.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item-main.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item-text.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item-toggle-icon.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item-toggle.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector-list-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector-list.hbs
src/patternfly/components/DualListSelector/dual-list-selector-menu.hbs
src/patternfly/components/DualListSelector/dual-list-selector-pane.hbs
src/patternfly/components/DualListSelector/dual-list-selector-status-text.hbs
src/patternfly/components/DualListSelector/dual-list-selector-status.hbs
src/patternfly/components/DualListSelector/dual-list-selector-title-text.hbs
src/patternfly/components/DualListSelector/dual-list-selector-title.hbs
src/patternfly/components/DualListSelector/dual-list-selector-tools-actions.hbs
src/patternfly/components/DualListSelector/dual-list-selector-tools-filter.hbs
src/patternfly/components/DualListSelector/dual-list-selector-tools.hbs
src/patternfly/components/DualListSelector/dual-list-selector.hbs
src/patternfly/components/DualListSelector/dual-list-selector.scss
src/patternfly/components/DualListSelector/examples/DualListSelector.md

feat(duallistselector): add tree view feat

---

src/patternfly/components/TreeView/examples/TreeView.md
src/patternfly/components/TreeView/tree-view.scss

Fix(tree-view): Fix indentation

---

src/patternfly/components/CalendarMonth/calendar-month.scss
src/patternfly/components/CalendarMonth/examples/CalendarMonth.md

part of https://github.com/patternfly/patternfly/issues/3668, differentiates hover and focus styles

fix(calendar-month): differentiate hover/focus styles

---

.github/stale.yml

Make config consistent with React's

fix(stalebot): add pinned to exemptLabels

---

src/patternfly/components/Dropdown/dropdown.scss

fix(plain-dropdown-toggle-height): changed to inline-block

---

src/patternfly/components/TreeView/examples/TreeView.md
src/patternfly/components/TreeView/tree-view-list-item.hbs

fixes https://github.com/patternfly/patternfly/issues/3672

chore(tree-view): remove references to pf-m-expandable

---

src/patternfly/components/Card/card.scss
src/patternfly/components/Card/examples/Card.md

fix(card-and-divider-padding): added padding to divider + section

---

src/patternfly/components/CalendarMonth/calendar-month.scss

fixes https://github.com/patternfly/patternfly/issues/3704

fix(calendar-month): updated in-range bg to stay within cell padding

---

src/patternfly/layouts/Gallery/examples/Gallery.md
src/patternfly/layouts/Gallery/gallery.scss

feat(gallery): added max variable

---

src/patternfly/components/Drawer/drawer.scss

fixes https://github.com/patternfly/patternfly/issues/3718

fix(drawer): kept content from shifting when panel resizes

---

src/patternfly/components/InputGroup/examples/InputGroup.md
src/patternfly/components/InputGroup/input-group-text.hbs
src/patternfly/components/InputGroup/input-group.scss
src/patternfly/components/Slider/examples/Slider.md
src/patternfly/components/Slider/slider-actions.hbs
src/patternfly/components/Slider/slider-main.hbs
src/patternfly/components/Slider/slider-rail-track.hbs
src/patternfly/components/Slider/slider-rail.hbs
src/patternfly/components/Slider/slider-step-label.hbs
src/patternfly/components/Slider/slider-step-tick.hbs
src/patternfly/components/Slider/slider-step.hbs
src/patternfly/components/Slider/slider-steps.hbs
src/patternfly/components/Slider/slider-thumb.hbs
src/patternfly/components/Slider/slider-value.hbs
src/patternfly/components/Slider/slider.hbs
src/patternfly/components/Slider/slider.scss
src/patternfly/components/_all.scss

fixes https://github.com/patternfly/patternfly/issues/296
**SLIDER LINK - https://patternfly-pr-3711.surge.sh/components/slider**
Designs - https://www.sketch.com/s/6f81d099-0c11-407a-8962-5672df30dcf2/a/j5KAvW
WAI-ARIA example - https://www.w3.org/TR/wai-aria-practices/examples/slider/slider-1.html

feat(slider): added slider component

---

src/patternfly/components/TreeView/tree-view.scss

fixes https://github.com/patternfly/patternfly/issues/3727

fix(tree-view): made toggle size/indentation same between core and react

---

src/patternfly/components/Table/table.scss

fixes https://github.com/patternfly/patternfly/issues/3731

fix(table): added var for sortable text, updated sortable favorite color

---

RELEASE-NOTES.md
src/patternfly/components/DualListSelector/dual-list-selector-item-check.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector.scss
src/patternfly/components/DualListSelector/examples/DualListSelector.md

fixes https://github.com/patternfly/patternfly/issues/3729

fix(dual-list-selector): fixed alignment, check selected style, examples

---

src/patternfly/patternfly-base-no-reset.scss

fixes https://github.com/patternfly/patternfly/issues/3735

feat(global): made variation of patternfly-base.css w/o global reset

---

RELEASE-NOTES.md
src/patternfly/components/DualListSelector/dual-list-selector-list-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector.scss
src/patternfly/components/DualListSelector/examples/DualListSelector.md

fixes https://github.com/patternfly/patternfly/issues/3733

fix(dual-list-selector): fixed alignment issue

---

scripts/template/src/patternfly/{folder}/{name}/{nameDasherized}.hbs

fixes https://github.com/patternfly/patternfly/issues/3738

chore(template): updated thing template to not escape --attribute

---

src/patternfly/components/Accordion/accordion.scss

fixes https://github.com/patternfly/patternfly/issues/3722

fix(accordion): updated expanded content color to use correct global var

---

src/patternfly/components/Spinner/examples/Spinner.md
src/patternfly/components/Spinner/spinner.hbs
src/patternfly/components/Spinner/spinner.scss

closes #2257 
closes #3640 
This PR converts the spinner to an SVG. It retains the same base variables.
Preview: https://patternfly-pr-3690.surge.sh/components/spinner/

fix(spinner): added svg variation

---

src/patternfly/components/Check/check.scss
src/patternfly/components/Radio/radio.scss
src/patternfly/components/Switch/switch.scss

closes #3210 
To test, add a long text string to `__label`.

feat(switch-radio-check): updated input height and grid

---

src/patternfly/components/ToggleGroup/toggle-group-button.hbs

fixes https://github.com/patternfly/patternfly/issues/3759

chore(toggle-group): added type=button to buttons

---

src/patternfly/components/Wizard/examples/Wizard.md
src/patternfly/components/Wizard/wizard-footer-cancel.hbs
src/patternfly/components/Wizard/wizard.scss
src/patternfly/demos/Wizard/examples/Wizard.md

fixes https://github.com/patternfly/patternfly/issues/1894
Once the action list component is promoted, we can use that here for more flexibility.

fix(wizard): added cancel button element to increase cancel spacer

---

src/patternfly/components/DataList/data-list.scss
src/patternfly/components/DataList/examples/DataList.md

closes #3412 
Preview: https://patternfly-pr-3750.surge.sh/components/data-list

fix(datalist-alignment): updated alignment settings

---

src/patternfly/components/Page/page.scss

fixes https://github.com/patternfly/patternfly/issues/3764

fix(page): fixed page section responsive padding

---

src/patternfly/components/AlertGroup/examples/AlertGroup.md

fix(alert-group): update examples and documentation

---

src/patternfly/base/_common.scss

Fixes #3774
Added class for proper alignment of SVG icons in **patternfly-react** to replace inlined style.

feat(styles): added SVG vertical-align class for patternfly-react

---

src/patternfly/components/SearchInput/examples/SearchInput.css
src/patternfly/components/SearchInput/examples/SearchInput.md
src/patternfly/components/SearchInput/search-input-bar.hbs
src/patternfly/components/SearchInput/search-input-menu.hbs
src/patternfly/components/SearchInput/search-input-search-button.hbs
src/patternfly/components/SearchInput/search-input-toggle.hbs
src/patternfly/components/SearchInput/search-input.hbs
src/patternfly/components/SearchInput/search-input.scss

fixes https://github.com/patternfly/patternfly/issues/3771

feat(search-input): added advanced search

---

src/patternfly/components/Drawer/drawer.scss

fixes https://github.com/patternfly/patternfly/issues/3784

fix(drawer): fixed inline bottom panel layout issues

---

src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu-drilldown-example.hbs
src/patternfly/components/Menu/menu.scss

Updates height control in `pf-c-drilldown`

fix(drilldown-menu): update __content height

---

src/patternfly/components/FormControl/examples/FormControl.md
src/patternfly/components/FormControl/form-control.scss

fixes https://github.com/patternfly/patternfly/issues/3623
After chatting with @kmcfaul the most flexible way to do this is to dynamically toggle a class based off of the chosen option.

feat(form-control): added placeholder variation for form select

---

src/patternfly/components/JumpLinks/jump-links.scss

fixes https://github.com/patternfly/patternfly/issues/3747

fix(jump-links): updated focus styles to match hover

---

src/patternfly/components/Table/table.scss

fix(table-header-alignment): fixed th align

---

src/patternfly/components/JumpLinks/examples/JumpLinks.md
src/patternfly/components/JumpLinks/jump-links-header.hbs
src/patternfly/components/JumpLinks/jump-links-label.hbs
src/patternfly/components/JumpLinks/jump-links-toggle-icon.hbs
src/patternfly/components/JumpLinks/jump-links-toggle.hbs
src/patternfly/components/JumpLinks/jump-links.hbs
src/patternfly/components/JumpLinks/jump-links.scss

fixes https://github.com/patternfly/patternfly/issues/3697
Allows you to specify breakpoints for expandable and non-expandable (regular) vertical jump links. Also adds a modifier for the label/title so that it is only visible when in the expandable state.

feat(jump-links): added expandable

---

src/patternfly/components/Sidebar/examples/Sidebar.css
src/patternfly/components/Sidebar/examples/Sidebar.md
src/patternfly/components/Sidebar/sidebar-content.hbs
src/patternfly/components/Sidebar/sidebar-main.hbs
src/patternfly/components/Sidebar/sidebar-panel.hbs
src/patternfly/components/Sidebar/sidebar.hbs
src/patternfly/components/Sidebar/sidebar.scss
src/patternfly/components/_all.scss
src/patternfly/demos/JumpLinks/examples/JumpLinks.md

fixes https://github.com/patternfly/patternfly/issues/3653
This adds a basic sidebar component. In a follow up sprint, I would like to add responsive support to the stack layout, split layout, gutters, sticky, and right panel modifiers.

feat(sidebar): added sidebar component

---

src/patternfly/components/List/examples/List.md
src/patternfly/components/List/list-item-icon.hbs
src/patternfly/components/List/list-item-main.hbs
src/patternfly/components/List/list-item-text.hbs
src/patternfly/components/List/list-item.hbs
src/patternfly/components/List/list.scss

closes #3743 
@mcoker @mattnolting When the text is multiline, I could only align the icon/logo in the center. Do you have any idea about how to align it to the top of the text? Because if I simply align it to the top, the icon will not be on the same height with the text when the text is single line.

fix(list): add new list variants

---

src/patternfly/components/Drawer/drawer.scss

fixes https://github.com/patternfly/patternfly/issues/3831

fix(drawer): disabled drawer transitions, pointer-events while resizing

---

src/patternfly/components/Label/label.scss

fixes https://github.com/patternfly/patternfly/issues/3810

fix(label): updated colors to work better on a gray background

---

src/patternfly/components/SearchInput/search-input.scss

fixes https://github.com/patternfly/patternfly/issues/3842

fix(search-input): fixed input hover bottom border

---

src/patternfly/components/CalendarMonth/calendar-month.scss

fixes https://github.com/patternfly/patternfly/issues/3839

fix(calendar-month): fixed var name

---

src/patternfly/components/ModalBox/modal-box.scss

fixes https://github.com/patternfly/patternfly/issues/3825

fix(modal-box): updated modal-box__header to not shrink

---

src/patternfly/components/Login/__login-footer.hbs
src/patternfly/components/Login/__login-header.hbs
src/patternfly/components/Login/__login-main-footer.hbs
src/patternfly/components/Login/__login-main-header.hbs
src/patternfly/components/Login/examples/Login.md

fixes https://github.com/patternfly/patternfly/issues/3770

feat(login): added support for hide/show password

---

src/patternfly/components/Tabs/examples/Tabs.md
src/patternfly/components/Tabs/tabs-toggle-button.hbs
src/patternfly/components/Tabs/tabs-toggle-icon.hbs
src/patternfly/components/Tabs/tabs-toggle-text.hbs
src/patternfly/components/Tabs/tabs-toggle.hbs
src/patternfly/components/Tabs/tabs.hbs
src/patternfly/components/Tabs/tabs.scss

fixes https://github.com/patternfly/patternfly/issues/3698

feat(tabs): added responsive state for vertical tabs

---

src/patternfly/components/DescriptionList/description-list-term.hbs
src/patternfly/components/DescriptionList/description-list-text.hbs
src/patternfly/components/DescriptionList/description-list.scss
src/patternfly/components/DescriptionList/examples/DescriptionList.md

feat(description-list): added help text support

---

src/patternfly/components/DescriptionList/description-list.scss
src/patternfly/components/DescriptionList/examples/DescriptionList.md

feat(description-list): added hor/vert responsive mods

---

src/patternfly/components/Slider/slider.scss

fixes https://github.com/patternfly/patternfly/issues/3858

fix(slider): increased thumb target size

---

src/patternfly/layouts/Split/examples/Split.md
src/patternfly/layouts/Split/split.scss

fixes https://github.com/patternfly/patternfly/issues/3885

feat(split): added variation to allow children to wrap

---

src/patternfly/components/Check/check-body.hbs
src/patternfly/components/Check/check-description.hbs
src/patternfly/components/Check/check.scss
src/patternfly/components/Check/examples/Check.md
src/patternfly/components/Radio/examples/Radio.md
src/patternfly/components/Radio/radio-body.hbs
src/patternfly/components/Radio/radio-description.hbs
src/patternfly/components/Radio/radio.scss

fixes https://github.com/patternfly/patternfly/issues/3717
@mceledonia @mcarrano there is an 8px spacer between the label and description, so I added a 16px spacer above the body and whatever precedes it. Does that look OK?

feat(check/radio): added support for custom body content

---

src/patternfly/components/Slider/examples/Slider.md
src/patternfly/components/Slider/slider-thumb.hbs
src/patternfly/components/Slider/slider.hbs
src/patternfly/components/Slider/slider.scss

fixes https://github.com/patternfly/patternfly/issues/3864

feat(slider): added support for disabled

---

src/patternfly/components/Table/Tree-table/table-tree-view--basic.hbs
src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table-tree-view.scss

fix(table): fixed treeview alignment

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table-grid.scss
src/patternfly/components/Table/table.scss

fix(table): fixed hoverable, selectable table

---

src/patternfly/components/Breadcrumb/breadcrumb-link.hbs
src/patternfly/components/Breadcrumb/examples/Breadcrumb.md
src/patternfly/components/Menu/templates/menu-breadcrumbs--Drilldown.hbs

fixes https://github.com/patternfly/patternfly/issues/3896

fix(breadcrumb): added docs, example for items as buttons

---

src/patternfly/components/SearchInput/search-input.scss

fixes https://github.com/patternfly/patternfly/issues/3903

fix(search-input): fixed underline bug

---

src/patternfly/components/Check/check-body.hbs
src/patternfly/components/Check/check-description.hbs
src/patternfly/components/Check/examples/Check.md
src/patternfly/components/Radio/examples/Radio.md
src/patternfly/components/Radio/radio-body.hbs
src/patternfly/components/Radio/radio-description.hbs

fixes https://github.com/patternfly/patternfly/issues/3944

chore(check/radio): updated body/description elements to be spans

---

src/patternfly/components/Form/form-field-group.hbs
src/patternfly/components/Form/form.scss

fixes https://github.com/patternfly/patternfly/issues/3941

chore(form): removed used of pf-m-expandable from field groups

---

src/patternfly/components/ClipboardCopy/clipboard-copy-actions-item.hbs
src/patternfly/components/ClipboardCopy/clipboard-copy-actions.hbs
src/patternfly/components/ClipboardCopy/clipboard-copy-text.hbs
src/patternfly/components/ClipboardCopy/clipboard-copy.hbs
src/patternfly/components/ClipboardCopy/clipboard-copy.scss
src/patternfly/components/ClipboardCopy/examples/ClipboardCopy.md

fixes https://github.com/patternfly/patternfly/issues/3906

feat(clipboard-copy): added inline variant

---

src/patternfly/components/Button/button.scss
src/patternfly/components/Button/examples/Button.md

fixes https://github.com/patternfly/patternfly/issues/1094
this adds active states to the new variations that match https://github.com/patternfly/patternfly/pull/3928

feat(button): added secondary/link danger variations

---

src/patternfly/components/Wizard/examples/Wizard.md
src/patternfly/components/Wizard/wizard-nav-item.hbs
src/patternfly/components/Wizard/wizard-nav-link-text.hbs
src/patternfly/components/Wizard/wizard-nav-link-toggle-icon.hbs
src/patternfly/components/Wizard/wizard-nav-link.hbs
src/patternfly/components/Wizard/wizard.scss

fixes https://github.com/patternfly/patternfly/issues/3904

feat(wizard): added expandable subsections

---

src/patternfly/components/Button/button.scss

fixes https://github.com/patternfly/patternfly/issues/3948

fix(button): reverted active state styling with new danger variations

---

src/patternfly/components/Form/examples/Form.md

fixes https://github.com/patternfly/patternfly/issues/3972

docs(form): updated element list for section title

---

src/patternfly/demos/Card/templates/cardview-demo--template-gallery.hbs

fix(card): add empty state card back into demo

---

src/patternfly/components/Table/Tree-table/table-tr--tree.hbs
src/patternfly/components/Table/Tree-table/table-tree-view--basic.hbs
src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table-details-toggle-icon.hbs
src/patternfly/components/Table/table-tr.hbs
src/patternfly/components/Table/table-tree-view-content.hbs
src/patternfly/components/Table/table-tree-view-details-toggle.hbs
src/patternfly/components/Table/table-tree-view-text.hbs
src/patternfly/components/Table/table-tree-view.scss

closes #3900 
Preview: https://patternfly-pr-3943.surge.sh/components/table#tree-table

feat(table): update tree table responsiveness

---

src/patternfly/components/Card/card.scss

fixes https://github.com/patternfly/patternfly/issues/3980

fix(card): fixed expandable toggle rotation

---

src/patternfly/components/Menu/examples/Menu.css
src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu.scss

fixes https://github.com/patternfly/patternfly/issues/3938

feat(menu): added variation for top and left flyout menus

---

src/patternfly/components/Toolbar/toolbar.scss

fixes https://github.com/patternfly/patternfly/issues/3983

fix(toolbar): changed expand content zindex to sm to match other menus

---

src/patternfly/demos/Card/templates/cardview-demo--template-gallery.hbs

fix(card): updated empty state text in card view demo

---

src/patternfly/components/Table/table-tree-view.scss

closes #3995 
Added `display: flex;` to `.pf-c-table__tree-view-text`

fix(table): fixed tree text display

---

src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu.scss

closes #3919 
Not totally sure what to do about the flyout menu. We'll probably need to create a followup for that.

feat(menu): add scrollable support

---

src/patternfly/components/InputGroup/input-group.scss

closes #3926 
Added `z-index` to `:focus`

fix(input-group): added z-index

---

src/patternfly/components/ContextSelector/context-selector.scss
src/patternfly/components/ContextSelector/examples/context-selector.md

fixes https://github.com/patternfly/patternfly/issues/3971

fix(context-selector): left aligned footer

---

src/patternfly/components/Select/examples/Select.md
src/patternfly/components/Select/select-toggle.hbs
src/patternfly/components/Select/select.hbs
src/patternfly/components/Select/select.scss

fixes https://github.com/patternfly/patternfly/issues/4007
cc @tlabaj

feat(select): added warning and success states

---

src/patternfly/components/Table/table-tree-view.scss

fixes https://github.com/patternfly/patternfly/issues/4014

fix(table): fixed indendation for non-expandable tree table rows

---

src/patternfly/components/Dropdown/dropdown-toggle.hbs
src/patternfly/components/LogViewer/examples/LogViewer.css
src/patternfly/components/LogViewer/examples/LogViewer.md
src/patternfly/components/LogViewer/log-viewer-header.hbs
src/patternfly/components/LogViewer/log-viewer-index.hbs
src/patternfly/components/LogViewer/log-viewer-list-item.hbs
src/patternfly/components/LogViewer/log-viewer-list.hbs
src/patternfly/components/LogViewer/log-viewer-main.hbs
src/patternfly/components/LogViewer/log-viewer-text.hbs
src/patternfly/components/LogViewer/log-viewer-timestamp.hbs
src/patternfly/components/LogViewer/log-viewer.hbs
src/patternfly/components/LogViewer/log-viewer.scss
src/patternfly/components/LogViewer/templates/__log-viewer-dropdown-menu.hbs
src/patternfly/components/LogViewer/templates/__log-viewer-li.hbs
src/patternfly/components/LogViewer/templates/__log-viewer-main.hbs
src/patternfly/components/LogViewer/templates/__log-viewer-toolbar-select.hbs
src/patternfly/components/LogViewer/templates/__log-viewer-toolbar.hbs
src/patternfly/components/Menu/menu-item.hbs
src/patternfly/components/Menu/menu.hbs
src/patternfly/components/Menu/menu.scss
src/patternfly/components/OverflowMenu/overflow-menu-control.hbs
src/patternfly/components/SearchInput/search-input-nav.hbs
src/patternfly/components/Select/select-menu.hbs
src/patternfly/components/Select/select.hbs
src/patternfly/components/Toolbar/toolbar-toggle.hbs
src/patternfly/components/_all.scss

closes #3811
Preview: https://patternfly-pr-4029.surge.sh/components/log-viewer
Designs here: https://marvelapp.com/prototype/bia3j2d
React issue: https://github.com/patternfly/patternfly-react/issues/5341

feat(log-viewer): added log viewer

---

src/patternfly/components/Divider/divider.scss

fixes https://github.com/patternfly/patternfly/issues/4013

fix(divider): updated to not shrink in flex layouts

---

src/patternfly/components/DataList/data-list.scss
src/patternfly/components/DataList/examples/DataList.md

fixes https://github.com/patternfly/patternfly/issues/2177

fix(data-list): fixed toggle icon bug with nested data lists

---

src/patternfly/components/Card/card.scss
src/patternfly/components/Card/examples/Card.md

chore(card): put expandable right aligned toggle in regular DOM order

---

src/patternfly/components/LogViewer/examples/LogViewer.md
src/patternfly/components/LogViewer/log-viewer-scroll-container.hbs
src/patternfly/components/LogViewer/log-viewer.scss
src/patternfly/components/LogViewer/templates/__log-viewer-dynamic-data.hbs
src/patternfly/components/LogViewer/templates/__log-viewer-main.hbs

closes #4040 
* Removes hover style
* Adds `scroll-container`
* Uses generated html from React PR / react-window

refactor(log-viewer): removed hover, added scroller

---

src/patternfly/components/Card/card--check.hbs
src/patternfly/components/Card/card.scss

fixes https://github.com/patternfly/patternfly/issues/4049

fix(card): updated right aligned expandable toggle spacing

---

src/patternfly/components/ToggleGroup/toggle-group.scss

small bug caught after merging https://github.com/patternfly/patternfly/pull/4054

fix(toggle-group): moved borders to before pseudo element

---

src/patternfly/components/Menu/menu.scss

fixes https://github.com/patternfly/patternfly/issues/4077

fix(menu): added z-index

---

src/patternfly/components/Dropdown/dropdown-menu--template--simple.hbs
src/patternfly/components/Dropdown/dropdown.scss
src/patternfly/components/Dropdown/examples/Dropdown.css
src/patternfly/components/Dropdown/examples/Dropdown.md

fixes https://github.com/patternfly/patternfly/issues/3680

feat(dropdown): added support for aria-disabled items

---

src/patternfly/components/DescriptionList/description-list.scss

fix(description-list): removed two duplicate variables

---

src/patternfly/demos/Page/page-template-header-tools-elements.hbs

fixes https://github.com/patternfly/patternfly/issues/4069

chore(demos): updated page header user dropdown to use plain toggle

---

src/patternfly/components/Menu/menu.scss

fix(menu): hid scroll on transition

---

src/patternfly/components/Drawer/drawer.scss

fix(drawer): added panel min-width

---

src/patternfly/layouts/Flex/examples/Flex.md
src/patternfly/layouts/Gallery/examples/Gallery.md
src/patternfly/layouts/Gallery/gallery-item.hbs
src/patternfly/layouts/Gallery/gallery.hbs
src/patternfly/layouts/Grid/examples/Grid.md
src/patternfly/layouts/Grid/grid-item.hbs
src/patternfly/layouts/Grid/grid.hbs

docs(layouts): added examples using lists

---

src/patternfly/components/SimpleList/simple-list.scss

fixes https://github.com/patternfly/patternfly/issues/4085
This PR removes the bold text. Do we want to make any other changes?

fix(simple-list): remove bold on focus, active, selected/current

---

src/patternfly/components/Skeleton/skeleton.scss

fixes https://github.com/patternfly/patternfly/issues/3965

fix(skeleton): improved animation performance

---

RELEASE-NOTES.md
src/patternfly/components/Select/select.scss

fixes https://github.com/patternfly/patternfly/issues/4125

fix(select): fixed specificity issue with toggle typeahead

---

src/patternfly/components/Toolbar/examples/Toolbar.md
src/patternfly/components/Toolbar/toolbar.scss

feat(toolbar): added sticky

---

src/patternfly/components/Label/examples/Label.md

fixes https://github.com/patternfly/patternfly/issues/4092

chore(label): replaced overflow with truncate in truncation examples

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table-draggable-button.hbs
src/patternfly/components/Table/table-td.hbs
src/patternfly/components/Table/table.scss

fixes https://github.com/patternfly/patternfly/issues/4065

feat(table): added draggable variant

---

src/patternfly/components/Table/Tree-table/table-tr--tree.hbs
src/patternfly/components/Table/Tree-table/table-tree-view--basic.hbs
src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table-tree-view-details-toggle.hbs
src/patternfly/components/Table/table-tree-view.scss

closes #4075 
Previews start here: https://patternfly-pr-4135.surge.sh/components/table#tree-table

fix(tree-table): added actions support

---

src/patternfly/components/ContextSelector/context-selector-toggle.hbs
src/patternfly/components/ContextSelector/context-selector.scss
src/patternfly/components/ContextSelector/examples/context-selector.css
src/patternfly/components/ContextSelector/examples/context-selector.md

fix(context-selector): added plain text variant and example

---

src/patternfly/components/HelperText/examples/HelperText.md
src/patternfly/components/HelperText/helper-text.scss

fixes https://github.com/patternfly/patternfly/issues/4139

fix(helper-text): renamed invalid state to error

---

src/patternfly/components/ContextSelector/context-selector.scss
src/patternfly/components/ContextSelector/examples/context-selector.md
src/patternfly/components/Dropdown/dropdown.scss
src/patternfly/components/Dropdown/examples/Dropdown.md
src/patternfly/components/Masthead/masthead.scss
src/patternfly/demos/Masthead/examples/Masthead.md

feat(dropdowns): added dropdown, context selector full height mods

---

src/patternfly/components/ExpandableSection/examples/ExpandableSection.md
src/patternfly/components/ExpandableSection/expandable-section.hbs
src/patternfly/components/ExpandableSection/expandable-section.scss

This adds a display-lg variant to the expandable section. 
Note: pending font size and max-width confirmation from design
@ajacobs21e 
fixes #3952

feat(expandable-section): added large variation

---

src/patternfly/components/ContextSelector/context-selector.scss
src/patternfly/components/Dropdown/dropdown.scss

fix(context-selector-dropdown): fix full height border active, focus

---

src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu.scss

fix(menu): updated content overflow

---

src/patternfly/components/Form/form.scss

fix(form): add missing padding to labels in collapsed horizontal mode

---

src/patternfly/components/Table/table.scss

fix(table): added background color to draggable ghost row

---

src/patternfly/components/Form/form-helper-text.hbs
src/patternfly/demos/HelperText/examples/HelperText.md

This adds a demo to the helper text showing how to add it to form fields.
Fixes #4161

feat(helper-text): added demo

---

src/patternfly/components/LogViewer/examples/LogViewer.md
src/patternfly/components/LogViewer/log-viewer-string.hbs
src/patternfly/components/LogViewer/log-viewer.scss
src/patternfly/components/LogViewer/templates/__log-viewer-dynamic-data.hbs
src/patternfly/components/LogViewer/templates/__log-viewer-toolbar.hbs

fixes https://github.com/patternfly/patternfly/issues/4163
https://patternfly-pr-4166.surge.sh/components/log-viewer

feat(log-viewer): added string element with current/match support

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table.scss

fixes https://github.com/patternfly/patternfly/issues/4168

fix(table): added overflow-anchor to draggable table

---

src/patternfly/components/MenuToggle/examples/MenuToggle.css
src/patternfly/components/MenuToggle/examples/MenuToggle.md
src/patternfly/components/MenuToggle/menu-toggle.scss

feat(menu-toggle): added full height variant

---

src/patternfly/components/ContextSelector/context-selector.scss
src/patternfly/components/Dropdown/dropdown.scss

fix(contextext-selector-dropdown): changed display type

---

src/patternfly/components/SearchInput/examples/SearchInput.md
src/patternfly/components/SearchInput/search-input-search-button.hbs
src/patternfly/components/SearchInput/search-input.hbs

fixes #4036 
Added a variant of the SearchInput component with a submit button, also added an example on the component page for SearchInput.

feat(search-input): added variant with submit button

---

src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu.scss

fixes https://github.com/patternfly/patternfly/issues/4191

fix(menu): added vars for menu top, left, and right position offset

---

release.config.js
src/site/pages/accessibility-guide.md

Should fix releasing from main.

fix(ci): renamed master to main

---

src/patternfly/components/Toolbar/examples/Toolbar.md
src/patternfly/components/Toolbar/toolbar.scss

fix(toolbar): fix hidden/visible mods

---

src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu.scss

fixes https://github.com/patternfly/patternfly/issues/4198

fix(menu): moved menu position modifers to menu element

---

src/patternfly/components/Button/examples/Button.md

docs(button): updated accessibility table

---

src/patternfly/base/_common.scss
src/patternfly/base/patternfly-icons.scss

to support this https://github.com/patternfly/patternfly-react/pull/5275

feat(icons): added styles to represent different SVG icon sizes and alignment for patternfly-react

---

src/patternfly/components/ContextSelector/context-selector.scss
src/patternfly/components/Dropdown/dropdown.scss

This reverts commit 0853dbc02fa5bdc83ac57cec14a55f13518cd50d in https://github.com/patternfly/patternfly/pull/4182

fix(context-selector,dropdown): revert move ::before values to ::after

---

src/site/pages/contribution.md

fixes https://github.com/patternfly/patternfly/issues/4076

docs(icons): added instructions to add icon to pficon font

---

src/patternfly/components/Switch/examples/Switch.md
src/patternfly/components/Switch/switch.scss

CSS changes to prepare for [#6059](https://github.com/patternfly/patternfly-react/issues/6059)

feat(switch): added reverse layout

---

src/patternfly/components/MenuToggle/menu-toggle.scss

fixes https://github.com/patternfly/patternfly/issues/4232

fix(menu-toggle): truncated overflow text

---

src/patternfly/components/JumpLinks/jump-links.scss

fixes https://github.com/patternfly/patternfly/issues/3881

fix(jump-links): forced vertical layout with expandable

---

src/patternfly/components/Wizard/examples/Wizard.md
src/patternfly/components/Wizard/wizard-toggle-list-item.hbs
src/patternfly/components/Wizard/wizard-toggle-list.hbs

fixes #2202 
Needs double checking; I'm not sure where in my dev server to find the relevant demos to verify that this is correct 😨

fix(wizard): switched ol to span in wizard toggle

---

.circleci/upload-preview.js

Fix pf4.patternfly.org publishing.

fix(surge): replace master with main

---

src/patternfly/components/TreeView/examples/TreeView.md
src/patternfly/components/TreeView/templates/tree-view--base.hbs
src/patternfly/components/TreeView/tree-view-list-item.hbs
src/patternfly/components/TreeView/tree-view-node-container.hbs
src/patternfly/components/TreeView/tree-view-node-content.hbs
src/patternfly/components/TreeView/tree-view-node-text.hbs
src/patternfly/components/TreeView/tree-view-node-title.hbs
src/patternfly/components/TreeView/tree-view-node.hbs
src/patternfly/components/TreeView/tree-view.scss

closes #4177 
[Previews start here](https://patternfly-pr-4242.surge.sh/components/tree-view#guides)

feat(tree-view): added compact, bordered, and background transparent variants

---

src/patternfly/components/Masthead/examples/masthead.md
src/patternfly/components/Masthead/masthead.scss

fix(masthead): added inset support

---

src/patternfly/components/Tabs/__tabs-list-secondary.hbs
src/patternfly/components/Tabs/__tabs-list.hbs
src/patternfly/components/Tabs/examples/Tabs.md
src/patternfly/components/Tabs/tabs-link.hbs
src/patternfly/components/Tabs/tabs.scss

fixes https://github.com/patternfly/patternfly/issues/4257
added disabled tabs to the existing examples where there is a unique design for a variation.
LINK: https://patternfly-pr-4278.surge.sh/components/tabs

feat(tabs): added disabled/aria-disabled support

---

src/patternfly/components/Tabs/examples/Tabs.md
src/patternfly/demos/PasswordStrength/examples/PasswordStrength.md

Updates text in password strength demo.
Adds `.pf-m-page-insets` to the main usage section.
fixes #4299

chore(documentation): update tabs and pwd strength

---

src/patternfly/utilities/BackgroundColor/BackgroundColor.scss
src/patternfly/utilities/BackgroundColor/examples/BackgroundColor.md
src/patternfly/utilities/Text/examples/Text.md
src/patternfly/utilities/Text/text.scss

This adds in additional text color and background color utilities.
Fixes #3642

feat(utilities): add text and background utilities

---

src/patternfly/components/ActionList/examples/ActionList.md
src/patternfly/components/Drawer/examples/Drawer.md
src/patternfly/components/InlineEdit/examples/InlineEdit.md
src/patternfly/components/NumberInput/examples/NumberInput.md
src/patternfly/components/Skeleton/examples/Skeleton.md
src/patternfly/components/ToggleGroup/examples/toggle-group.md
src/patternfly/utilities/BackgroundColor/examples/BackgroundColor.md
src/patternfly/utilities/Text/examples/Text.md

fixes https://github.com/patternfly/patternfly/issues/4264
Promotes following components out of beta:
ActionList
Drawer
InlineEdit
NumberInput
Skeleton
ToggleGroup
Utilities: Background color
Utilities: Text

chore(various): removed beta tag from promoted components

---

src/patternfly/components/DescriptionList/description-list.scss
src/patternfly/components/DescriptionList/examples/DescriptionList.md

fixes #3367 
Might not be fully ready; the line heights have been updated but have not created `pf-m-compact` and `pf-m-fluid` yet. Will update here once those are created.

fix(description-list): updated spacing, added compact and fluid

---

src/patternfly/components/Toolbar/toolbar--template.hbs
src/patternfly/demos/Table/examples/Table.md

fixes https://github.com/patternfly/patternfly/issues/4019
demo - https://patternfly-pr-4307.surge.sh/components/table/html-demos/sortable/

chore(table): added mobile sort to sortable demo

---

src/patternfly/demos/Card/examples/Card.md

fixes https://github.com/patternfly/patternfly/issues/4310

chore(card): linked a url in detail card demo

---

src/patternfly/components/Dropdown/dropdown.scss

fixes https://github.com/patternfly/patternfly/issues/4313

fix(menu): scoped menu component styles in dropdown

---

src/patternfly/components/LogViewer/log-viewer.scss

fixes https://github.com/patternfly/patternfly/issues/4315

fix(log-viewer): removed border from log viewer in dark theme

---

.github/upload-preview.js
.github/workflows-src/pr-preview.yml
package.json
yarn.lock

Followup to #4342 to fix pr previews

chore(ci): actions followup

---

.github/renovate.json
.github/workflows-src/release.yml
.github/workflows/release.yml

Need to add some secrets for releasing.

fix(ci): upload pf4.patternfly.org

---

.github/workflows-src/pr-preview.yml
.github/workflows/pr-preview.yml

This will allow faster debugging.

fix(ci): test breaking change lint

---

.github/workflows-src/pr-preview.yml
.github/workflows/pr-preview.yml

Temporarily until I can figure out what Github actions is doing.

chore(ci): remove breaking change lint

---

src/patternfly/components/LogViewer/log-viewer.scss
src/patternfly/components/LogViewer/templates/__log-viewer-dynamic-data.hbs

fixes https://github.com/patternfly/patternfly/issues/4323

fix(log-viewer): updated to support dynamic size list

---

src/patternfly/components/ModalBox/examples/ModalBox.md
src/patternfly/components/ModalBox/modal-box.hbs
src/patternfly/components/Popover/examples/Popover.md
src/patternfly/components/Popover/popover.hbs

fixes https://github.com/patternfly/patternfly/issues/2538

docs(popover/modal): updated use, docs re: dialog role

---

src/patternfly/components/Nav/examples/Navigation.css
src/patternfly/components/Nav/examples/Navigation.md
src/patternfly/components/Nav/nav-item.hbs
src/patternfly/components/Nav/nav-link.hbs
src/patternfly/components/Nav/nav-toggle-icon.hbs
src/patternfly/components/Nav/nav.scss
src/patternfly/components/Nav/templates/nav--drilldown--nav-item-submenu.hbs
src/patternfly/components/Nav/templates/nav--drilldown.hbs
src/patternfly/components/Nav/templates/nav--flyout--nav-item-submenu.hbs

feat(nav): added drilldown variant

---

src/patternfly/components/DataList/examples/DataList.md
src/patternfly/components/DualListSelector/dual-list-selector-draggable-button.hbs
src/patternfly/components/DualListSelector/dual-list-selector-draggable.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item-check.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item-text.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector-list-item-row.hbs
src/patternfly/components/DualListSelector/dual-list-selector-list-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector.scss
src/patternfly/components/DualListSelector/examples/DualListSelector.md
src/patternfly/components/Table/examples/Table.md

fixes https://github.com/patternfly/patternfly/issues/4319

feat(dual-list-selector): added drag/drop

---

src/patternfly/components/Tabs/examples/Tabs.md
src/patternfly/components/Tabs/tabs-toggle-button.hbs
src/patternfly/components/Tabs/tabs-toggle.hbs
src/patternfly/components/Tabs/tabs.scss

fixes https://github.com/patternfly/patternfly/issues/4174
I left legacy examples since we need to support both variations of the markup until a breaking change. I'll open a breaking change PR to remove the legacy support if this PR is merged.

fix(tabs): moved text into expandable toggle

---

src/patternfly/components/JumpLinks/examples/JumpLinks.md
src/patternfly/components/JumpLinks/jump-links-header.hbs
src/patternfly/components/JumpLinks/jump-links-label.hbs
src/patternfly/components/JumpLinks/jump-links-toggle-text.hbs
src/patternfly/components/JumpLinks/jump-links.hbs
src/patternfly/components/JumpLinks/jump-links.scss
src/patternfly/demos/JumpLinks/examples/JumpLinks.md

fixes https://github.com/patternfly/patternfly/issues/4175

fix(jump-links): moved text into expandable toggle

---

src/patternfly/demos/Card/examples/Card.md

fixes https://github.com/patternfly/patternfly/issues/4368

chore(card): updated log view and event view demos

---

src/patternfly/components/TreeView/examples/TreeView.md
src/patternfly/components/TreeView/tree-view.scss

fix(compact-tree): addressed followup issues

---

src/patternfly/demos/Card/templates/card-demo--chart.hbs

fixes https://github.com/patternfly/patternfly/issues/4379

chore(card): fixed demo image paths

---

src/patternfly/components/FormControl/examples/FormControl.md
src/patternfly/components/Select/__select-single.hbs
src/patternfly/components/Select/examples/Select.css
src/patternfly/components/Select/examples/Select.md
src/patternfly/components/Select/select-toggle.hbs
src/patternfly/components/Select/select.scss

fixes https://github.com/patternfly/patternfly/issues/4190
examples - https://patternfly-pr-4377.surge.sh/components/select#placeholder
I added support for all of the ways you can use a placeholder in our current form select in:
core: https://codepen.io/mcoker/pen/XWgzeae
react: https://codesandbox.io/s/distracted-darkness-txput

feat(select): added support for placeholder in toggle

---

src/patternfly/components/Label/examples/Label.md
src/patternfly/components/Label/label.scss
src/patternfly/demos/Card/examples/Card.md

feat(label): added compact variant

---

src/patternfly/patternfly-drag-drop.scss

fixes https://github.com/patternfly/patternfly/issues/4376
* `.pf-c-draggable` is a draggable thing
* `.pf-m-dragging` when it's being dragged
* `.pf-m-drag-outside` when its out of bounds
* `.pf-c-droppable` is a droppable thing
* `.pf-m-dragging` when it's being dragged over
* `.pf-m-drag-outside` when the dragged thing is out of bounds

feat(drag-drop): added drag drop

---

src/patternfly/components/Backdrop/backdrop.scss

fixes https://github.com/patternfly/patternfly/issues/4390

fix(backdrop): added var for position to allow customization

---

src/patternfly/components/DataList/data-list.scss
src/patternfly/components/DualListSelector/dual-list-selector-item-check.hbs
src/patternfly/components/DualListSelector/dual-list-selector-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector-list-item.hbs
src/patternfly/components/DualListSelector/dual-list-selector.scss
src/patternfly/components/DualListSelector/examples/DualListSelector.md

Needed for: https://github.com/patternfly/patternfly-react/issues/6250

feat(dual-list-selector): add support for disabled items

---

src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu.scss
src/patternfly/components/Menu/templates/menu--Drilldown.hbs
src/patternfly/components/Menu/templates/menu--long-list.hbs

fixes https://github.com/patternfly/patternfly/issues/4027

feat(menu): added scrollable and plain modifiers

---

src/patternfly/components/LogViewer/log-viewer.scss

fixes https://github.com/patternfly/patternfly/issues/4405

fix(log-viewer): made text fill available space in container

---

src/patternfly/components/Masthead/masthead.scss

fix(masthead): updated column-end

---

src/patternfly/components/TextInputGroup/examples/TextInputGroup.md
src/patternfly/components/TextInputGroup/templates/text-input-group--chip-group.hbs
src/patternfly/components/TextInputGroup/text-input-group-clear.hbs
src/patternfly/components/TextInputGroup/text-input-group-icon.hbs
src/patternfly/components/TextInputGroup/text-input-group-main.hbs
src/patternfly/components/TextInputGroup/text-input-group-row.hbs
src/patternfly/components/TextInputGroup/text-input-group-text-input.hbs
src/patternfly/components/TextInputGroup/text-input-group-text.hbs
src/patternfly/components/TextInputGroup/text-input-group-utilities.hbs
src/patternfly/components/TextInputGroup/text-input-group.hbs
src/patternfly/components/TextInputGroup/text-input-group.scss
src/patternfly/components/_all.scss

fixes https://github.com/patternfly/patternfly/issues/4374

feat(text-input-group): added component

---

src/patternfly/components/MenuToggle/examples/MenuToggle.md
src/patternfly/components/MenuToggle/menu-toggle.hbs
src/patternfly/components/MenuToggle/menu-toggle.scss

feat(menu-toggle): added plain w/text variant

---

src/patternfly/components/OptionsMenu/examples/options-menu.md
src/patternfly/components/OptionsMenu/options-menu-toggle.hbs
src/patternfly/components/OptionsMenu/options-menu.scss

fix(options-menu): moved text into button in plain text variant

---

src/patternfly/components/LogViewer/examples/LogViewer.md
src/patternfly/components/LogViewer/log-viewer-scroll-container.hbs
src/patternfly/components/LogViewer/log-viewer.hbs
src/patternfly/components/LogViewer/log-viewer.scss
src/patternfly/components/LogViewer/templates/__log-viewer-dynamic-data.hbs
src/patternfly/components/LogViewer/templates/__log-viewer-main.hbs

fixes https://github.com/patternfly/patternfly/issues/4435

feat(log-viewer): added nowrap variation

---

src/patternfly/components/LogViewer/log-viewer.scss

fixes https://github.com/patternfly/patternfly/issues/4503

fix(log-viewer): update way dark theme is applied

---

README.md
package.json

fixes https://github.com/patternfly/patternfly/issues/4478

chore(readme): updated a11y docs, s/npm run/yarn

---

src/patternfly/components/Dropdown/dropdown.scss
src/patternfly/components/Dropdown/examples/Dropdown.css
src/patternfly/components/Dropdown/examples/Dropdown.md

fix(dropdown): applied primary styling to split

---

src/patternfly/components/Dropdown/dropdown.scss
src/patternfly/components/Dropdown/examples/Dropdown.css
src/patternfly/components/Dropdown/examples/Dropdown.md
src/patternfly/components/MenuToggle/examples/MenuToggle.md
src/patternfly/components/MenuToggle/menu-toggle.hbs
src/patternfly/components/MenuToggle/menu-toggle.scss

feat(dropdown): added secondary variant to dropdown

---

src/patternfly/demos/Button/examples/Button.md

fixes https://github.com/patternfly/patternfly/issues/4354

docs(button): adds demo for progress button completion state

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table.scss

fixes https://github.com/patternfly/patternfly/issues/4280

fix(table): removed extra padding from nested table cells

---

.github/upload-preview.js
.github/workflows-src/partials/build-test.yml
.github/workflows/pr-preview.yml
.github/workflows/release.yml

fixes https://github.com/patternfly/patternfly/issues/4525

chore(build): added a11y coverage report action

---

src/patternfly/components/Select/examples/Select.md
src/patternfly/demos/Card/examples/Card.md

Fixes #4471 
Note: The width limiter was removed because it causes an overflow in the expanded menu.

chore(card): put selects into demos

---

src/patternfly/components/DescriptionList/description-list.scss
src/patternfly/components/DescriptionList/examples/DescriptionList.md

feat(description-list): added columnar layout

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table-check.hbs
src/patternfly/components/Table/table-draggable-button.hbs
src/patternfly/components/Table/table-favorite-button.hbs
src/patternfly/components/Table/table-nested.hbs
src/patternfly/components/Table/table-td.hbs
src/patternfly/components/Table/table.scss
src/patternfly/components/Table/templates/table--check.hbs
src/patternfly/components/Table/templates/table--node.hbs
src/patternfly/components/Table/templates/table--radio.hbs
src/patternfly/components/Table/templates/table--scrollable.hbs
src/patternfly/components/Table/templates/table-tbody--expandable.hbs
src/patternfly/components/Table/templates/table-tr--basic.hbs

closes #4355 
Updates start here: https://patternfly-pr-4546.surge.sh/components/table#checkboxes-and-actions-example
Each example including a  checkbox is updated

fix(table): added label to checkbox

---

src/patternfly/components/Dropdown/dropdown.scss
src/patternfly/components/Dropdown/examples/Dropdown.md

fix(dropdown): added disabled styles

---

src/patternfly/components/Dropdown/dropdown-toggle.hbs
src/patternfly/components/Dropdown/dropdown.scss
src/patternfly/components/Dropdown/examples/Dropdown.css
src/patternfly/components/Dropdown/examples/Dropdown.md

feat(dropdown): added plain text variant

---

src/patternfly/components/ExpandableSection/expandable-section-toggle.hbs
src/patternfly/components/MultipleFileUpload/__multiple-file-upload-default.hbs
src/patternfly/components/MultipleFileUpload/examples/MultipleFileUpload.md
src/patternfly/components/MultipleFileUpload/multiple-file-upload-info.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-main.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-status-item-close.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-status-item-icon.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-status-item-main.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-status-item-progress-size.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-status-item-progress-text.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-status-item-progress.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-status-item.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-status-list.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-status-progress-icon.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-status-progress-text.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-status-progress.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-status.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-title-icon.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-title-text-separator.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-title-text.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-title.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload-upload.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload.hbs
src/patternfly/components/MultipleFileUpload/multiple-file-upload.scss
src/patternfly/components/Progress/progress-description.hbs
src/patternfly/components/_all.scss

fixes https://github.com/patternfly/patternfly/issues/4521

feat(multiplefileupload): added component

---

src/patternfly/components/ExpandableSection/examples/ExpandableSection.md
src/patternfly/components/ExpandableSection/expandable-section.hbs
src/patternfly/components/ExpandableSection/expandable-section.scss

fixes https://github.com/patternfly/patternfly/issues/4566

feat(expandable-section): added indented variation

---

.stylelintrc
scripts/gulp/sass.js
yarn.lock

chore(gulp): update the watcher to handle crashes

---

src/patternfly/components/LogViewer/log-viewer.scss

fixes https://github.com/patternfly/patternfly/issues/4585
@DaoDaoNoCode I left the border as a `::before` so all the vars still work as they did before in case someone has modified those.

fix(log-viewer): update scroll, add footer

---

src/patternfly/components/Button/button.scss
src/patternfly/components/Button/examples/Button.md

fixes https://github.com/patternfly/patternfly/issues/4561

feat(button): added progress support with plain variation

---

src/patternfly/components/DescriptionList/description-list__example.hbs
src/patternfly/components/DescriptionList/examples/DescriptionList.md

fixes https://github.com/patternfly/patternfly/issues/4592

chore(description-list): removed unnecessary column fill examples

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table.scss

fixes https://github.com/patternfly/patternfly/issues/4564

feat(table): added striped rows

---

src/patternfly/components/Masthead/masthead.scss
src/patternfly/demos/Masthead/examples/Masthead.md

closes #4624 
Related to https://github.com/patternfly/patternfly/issues/4622

feat(masthead): added resize observer conditional

---

src/patternfly/components/Menu/menu.scss
src/patternfly/components/Nav/nav.scss
src/patternfly/components/ProgressStepper/progress-stepper.scss
src/patternfly/components/Sidebar/sidebar.scss
src/patternfly/components/Table/table-scrollable.scss
src/patternfly/components/Table/table.scss
src/patternfly/components/Toolbar/toolbar.scss

chore(vars): udpated/removed unused/undefined vars

---

src/patternfly/components/ProgressStepper/progress-stepper.scss

Fixes #4633 by explicitly setting a 0 margin after the last step.
https://patternfly-pr-4636.surge.sh/components/progress-stepper#vertical-with-descriptions

fix(ProgressStepper): remove extra space below

---

src/patternfly/components/Table/Tree-table/table-tr--tree.hbs
src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table-tree-view.scss

feat(table): updated tree table checkbox padding

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table.scss
src/patternfly/components/Table/templates/table--overflow-menu.hbs

feat(table): added overflow menu examples

---

src/patternfly/components/TextInputGroup/examples/TextInputGroup.md
src/patternfly/components/TextInputGroup/text-input-group-text-input.hbs
src/patternfly/components/TextInputGroup/text-input-group.scss

Closes #4577 
This PR adds styling for placeholder text styling for `text input group`

feat(textinputgroup): added placeholder styling

---

src/patternfly/components/AlertGroup/alert-group-overflow-button.hbs
src/patternfly/components/AlertGroup/alert-group.scss
src/patternfly/components/AlertGroup/examples/AlertGroup.md

feat(alert): added overflow alert button

---

src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu-list-item.hbs
src/patternfly/components/Menu/templates/menu--Drilldown.hbs
src/patternfly/components/Nav/examples/Navigation.md
src/patternfly/components/Nav/nav.scss
src/patternfly/components/Nav/templates/nav--drilldown.hbs

fix(nav): updated nav menu styling

---

src/patternfly/demos/Card/examples/Card.css
src/patternfly/demos/Card/examples/Card.md

fixes https://github.com/patternfly/patternfly/issues/4553
fixes https://github.com/patternfly/patternfly/issues/4621
@mcarrano I just added custom CSS to change the card action/title position so they're aligned to baseline.

chore(card): updated card demo select to be plain, fixed alignment

---

src/patternfly/components/Dropdown/dropdown.scss

fixes https://github.com/patternfly/patternfly/issues/4631

fix(button): fixed primary toggle state styles

---

src/patternfly/components/CodeEditor/code-editor-content.hbs
src/patternfly/components/CodeEditor/code-editor-header-main.hbs
src/patternfly/components/CodeEditor/code-editor-keyboard-shortcuts.hbs
src/patternfly/components/CodeEditor/code-editor.scss
src/patternfly/components/CodeEditor/examples/CodeEditor.md

closes #4658 
Preview: http://localhost:8001/components/code-editor#with-optional-header-content-and-keyboard-shortcuts

feat(code-editor): added header content section

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table.scss
src/patternfly/demos/Table/examples/Table.md

fixes https://github.com/patternfly/patternfly/issues/4680

fix(table): fixed expand all button in compact table

---

src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu-item.hbs
src/patternfly/components/Menu/menu-list-item.hbs
src/patternfly/components/Menu/menu-list.hbs

feat(menu): added aria attributes

---

src/patternfly/components/Select/select.scss

Fixes #4632 
Used individual width variables instead of the combined width variable that's marked for removal at breaking change.

fix(select): fix active focus states bottom border

---

src/patternfly/demos/JumpLinks/examples/JumpLinks.md

fixes https://github.com/patternfly/patternfly/issues/4645

chore(jump-links): fixed outdated code in demos

---

src/patternfly/components/Masthead/masthead.scss
src/patternfly/demos/Masthead/templates/masthead-template-content-icon-group.hbs

fix(masthead): updated toggle borders

---

src/patternfly/components/Table/examples/Table.md

fix(table): updated overflow menu examples

---

RELEASE-NOTES.md
src/patternfly/components/MenuToggle/menu-toggle.scss

fixes https://github.com/patternfly/patternfly/issues/4726

fix(menu-toggle): fixed self referencing var

---

src/patternfly/components/FormControl/examples/FormControl.md
src/patternfly/components/FormControl/form-control.scss

fixes https://github.com/patternfly/patternfly/issues/4731

fix(form-control): updated invalid sprite css, examples

---

src/patternfly/components/Menu/menu.scss
src/patternfly/components/MenuToggle/examples/MenuToggle.md
src/patternfly/components/MenuToggle/menu-toggle.hbs
src/patternfly/components/MenuToggle/menu-toggle.scss
src/patternfly/components/TextInputGroup/text-input-group.scss

feat(menu-toggle/text-input-group): update menu-toggle for text inputs & add plain text input group

---

src/patternfly/components/Accordion/accordion.scss
src/patternfly/components/Accordion/examples/Accordion.md

fixes https://github.com/patternfly/patternfly/issues/4729
Added a link in the first bordered example that wasn't clickable before.

fix(accordion): made links at bottom of bordered item clickable

---

src/patternfly/components/MenuToggle/examples/MenuToggle.md

fixes https://github.com/patternfly/patternfly/issues/4742

chore(menu-toggle): added example of secondary with icon

---

src/patternfly/components/OptionsMenu/examples/options-menu.md
src/patternfly/components/OptionsMenu/options-menu-toggle-button.hbs
src/patternfly/components/Pagination/examples/Pagination.css
src/patternfly/components/Pagination/examples/Pagination.md
src/patternfly/components/Pagination/pagination-options-menu.hbs
src/patternfly/components/Toolbar/toolbar--template.hbs
src/patternfly/components/Toolbar/toolbar-item-pagination.hbs
src/patternfly/demos/CardView/examples/CardView.md
src/patternfly/demos/DataList/data-list-pagination-footer-static.hbs
src/patternfly/demos/DataList/data-list-pagination-footer.hbs
src/patternfly/demos/PrimaryDetail/primary-detail-card-toolbar.hbs
src/patternfly/demos/PrimaryDetail/primary-detail-toolbar.hbs
src/patternfly/demos/Skeleton/table-skeleton-toolbar.hbs
src/patternfly/demos/Table/table-pagination-footer-static.hbs
src/patternfly/demos/Table/table-pagination-footer.hbs
src/patternfly/demos/Tabs/examples/Tabs.md
src/patternfly/demos/Toolbar/examples/Toolbar.md

fixes https://github.com/patternfly/patternfly/issues/4629

chore(pagination): updated options menu toggle so whole toggle is clickable

---

src/patternfly/themes/dark/_patternfly-theme-dark.scss
src/patternfly/themes/dark/scss-variables.scss

fix(dark-theme): fixes dark theme shadow pf-size-prem

---

src/patternfly/components/Switch/examples/Switch.md
src/patternfly/components/Switch/switch-toggle-icon.hbs
src/patternfly/components/Switch/switch.scss

feat(switch): updates to switch states, adds checked + label example

---

src/patternfly/components/Form/form.scss

fixes https://github.com/patternfly/patternfly/issues/4769

fix(form): changes width limited form max width from 500 to 800px

---

src/patternfly/components/Page/themes/dark/page.scss

fixes https://github.com/patternfly/patternfly/issues/4790

fix(page): updated dark theme main section bgcolor

---

src/patternfly/demos/DataList/examples/DataList.md
src/patternfly/demos/Toolbar/toolbar-template.hbs

fixes https://github.com/patternfly/patternfly/issues/4767

chore(data-list): updated expandable demo to include expand/collapse all in toolbar

---

src/patternfly/components/LogViewer/templates/__log-viewer-toolbar-select.hbs
src/patternfly/components/Login/__login-main-header.hbs
src/patternfly/components/Login/examples/Login.md
src/patternfly/components/Login/login-main-header-utilities.hbs
src/patternfly/components/Login/login.scss
src/patternfly/components/Select/__select-single.hbs
src/patternfly/components/Select/select-menu.hbs
src/patternfly/components/Select/select-toggle.hbs

fixes https://github.com/patternfly/patternfly/issues/4745

feat(login): add support for any language selector menu

---

src/patternfly/components/Drawer/drawer.scss
src/patternfly/components/Page/examples/Page.md
src/patternfly/components/Page/page.scss
src/patternfly/components/Wizard/examples/Wizard.md
src/patternfly/components/Wizard/wizard.scss
src/patternfly/demos/Wizard/examples/Wizard.md
src/patternfly/demos/Wizard/wizard-template-nav.hbs

feat(wizard): added drawer

---

src/patternfly/components/TreeView/tree-view.scss

fix(tree-view): add z-index to prevent guide from disappearing on focus

---

src/patternfly/components/Tabs/tabs.scss

fixes https://github.com/patternfly/patternfly/issues/4819

fix(tabs): fixed add button focus outline

---

src/patternfly/demos/PrimaryDetail/primary-detail-template-card-view.hbs

fixes https://github.com/patternfly/patternfly/issues/4792

chore(primary-detail): updated card view demo to use new selectable styles

---

src/patternfly/components/Tooltip/themes/dark/tooltip.scss
src/patternfly/patternfly.scss

fixes https://github.com/patternfly/patternfly/issues/4771

fix(tooltip): added dark theme border

---

src/patternfly/demos/Drawer/examples/Drawer.md
src/patternfly/demos/Drawer/examples/drawer-jump-links.hbs
src/patternfly/demos/JumpLinks/examples/JumpLinks.md
src/patternfly/demos/JumpLinks/examples/jump-links-template-content.hbs

fixes https://github.com/patternfly/patternfly/issues/4512
drawer collapsed - https://patternfly-pr-4608.surge.sh/components/drawer/html-demos/drawer-with-jump-links
drawer expanded - https://patternfly-pr-4608.surge.sh/components/drawer/html-demos/expanded-drawer-with-jump-links

chore(drawer): added demos with jumplinks

---

src/patternfly/components/Table/examples/Table.md

Closes #4837 
Preview: https://patternfly-pr-4852.surge.sh/components/table#expandable-with-set-width-columns-example

chore(table): added expanded set column width example

---

src/patternfly/components/Page/page.scss

fixes https://github.com/patternfly/patternfly/issues/4838

fix(page): add masthead to header/nav/main stacking context order

---

src/patternfly/components/CalendarMonth/calendar-month.scss
src/patternfly/components/CalendarMonth/examples/CalendarMonth.md

Closes #4760 
[Calendar Month preview build](https://patternfly-pr-4862.surge.sh/components/calendar-month)

fix(CalendarMonth): improve layout of nav controls

---

src/patternfly/sass-utilities/themes/dark/scss-variables.scss

fixes https://github.com/patternfly/patternfly/issues/4860

fix(theme): update dark theme default text color

---

src/patternfly/demos/Drawer/examples/drawer-jump-links.hbs

fix(drawer): removed duplicate __body on jumplinks demo

---

src/patternfly/components/Dropdown/dropdown.scss
src/patternfly/components/Dropdown/examples/Dropdown.css
src/patternfly/components/Dropdown/examples/Dropdown.md

feat(dropdown): added secondary split toggle

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table-tr.hbs
src/patternfly/components/Table/table.scss
src/patternfly/components/Table/templates/table-tr--nested-column-header.hbs

closes #4846 
https://patternfly-pr-4857.surge.sh/components/table#nested-column-headers
https://patternfly-pr-4857.surge.sh/components/table#nested-column-headers-sticky-header

fix(table): added tr border to sticky nested table header

---

src/patternfly/components/ProgressStepper/examples/ProgressStepper.md
src/patternfly/components/ProgressStepper/progress-stepper-step-title.hbs
src/patternfly/components/ProgressStepper/progress-stepper.scss

fixes https://github.com/patternfly/patternfly/issues/4898

fix(progress-stepper): use button for step title help text

---

scripts/gulp/html.js
src/patternfly/components/Tabs/__tabs-item.hbs
src/patternfly/components/Tabs/__tabs-list.hbs
src/patternfly/components/Tabs/examples/Tabs.md
src/patternfly/components/Tabs/tabs-item-toggle-icon.hbs
src/patternfly/components/Tabs/tabs-item.hbs
src/patternfly/components/Tabs/tabs-link-toggle-icon.hbs
src/patternfly/components/Tabs/tabs-link.hbs
src/patternfly/components/Tabs/tabs.scss

Closes #4800
Convenience link: https://patternfly-pr-4876.surge.sh/components/tabs#horizontal-overflow

feat(tabs): add expandable overflow styling

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table-tr.hbs

fix(table): added aria-hidden to table border row

---

src/patternfly/components/Drawer/drawer.scss

fixes https://github.com/patternfly/patternfly/issues/4948

fix(drawer): fixed broken var names

---

src/patternfly/components/Page/page.scss
src/patternfly/components/Page/themes/dark/page.scss

fixes https://github.com/patternfly/patternfly/issues/4925

fix(sidebar): add light/dark theme border, remove desktop shadow

---

patternfly-docs/patternfly-docs.css.js

fixes https://github.com/patternfly/patternfly/issues/4952

chore(workspace): remove react css imports

---

src/patternfly/base/themes/dark/_variables.scss
src/patternfly/sass-utilities/themes/dark/scss-variables.scss
src/patternfly/utilities/Text/themes/dark/text.scss

fixes https://github.com/patternfly/patternfly/issues/4955
----
visited link example in content component - https://patternfly-pr-4964.surge.sh/components/text/
visited link utility class - https://patternfly-pr-4964.surge.sh/utilities/text

fix(global): updated dark theme visited link color

---

.github/workflows-src/partials/build-test.yml
.github/workflows/pr-preview.yml
.github/workflows/release.yml

fixes https://github.com/patternfly/patternfly/issues/4966

chore(build): update github workflow to publish docs before a11y tests

---

src/patternfly/components/Drawer/drawer.scss

fixes https://github.com/patternfly/patternfly/issues/4970

fix(drawer): fix sticky page sections when in drawer

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/templates/table--scrollable--th.hbs

fix(table): removed truncate from sticky hrs

---

src/patternfly/components/DescriptionList/description-list-group.hbs

chore(description-list): removed dl group mod in examples

---

src/patternfly/components/Tabs/examples/Tabs.md
src/patternfly/components/Tabs/tabs.hbs
src/patternfly/components/Tabs/tabs.scss

fixes https://github.com/patternfly/patternfly/issues/5004

fix(tabs): added overflow variation for horiz overflow variation

---

src/patternfly/base/_common.scss
src/patternfly/sass-utilities/mixins.scss

feat(a11y): add new screen reader element class

---

src/patternfly/components/Check/check-input.hbs
src/patternfly/components/TreeView/examples/TreeView.md
src/patternfly/components/TreeView/tree-view-node-check.hbs
src/patternfly/components/TreeView/tree-view-node-text.hbs
src/patternfly/components/TreeView/tree-view-node-toggle.hbs
src/patternfly/components/TreeView/tree-view-node.hbs
src/patternfly/components/TreeView/tree-view.scss

fixes https://github.com/patternfly/patternfly/issues/4990

fix(treeview): selectable/expandable node bugs

---

src/patternfly/components/ExpandableSection/examples/ExpandableSection.md
src/patternfly/components/ExpandableSection/expandable-section-content.hbs
src/patternfly/components/ExpandableSection/expandable-section-toggle.hbs
src/patternfly/components/ExpandableSection/expandable-section.hbs
src/patternfly/components/ExpandableSection/expandable-section.scss

fixes https://github.com/patternfly/patternfly/issues/4881

feat(expandable-section): added truncate variant

---

src/patternfly/components/Card/examples/Card.css

fixes https://github.com/patternfly/patternfly/issues/5021

chore(card): updated body fill example to show fill behavior

---

src/patternfly/components/Wizard/themes/dark/wizard.scss

fix(wizard): adjust dark theme colors

---

src/patternfly/components/Button/themes/dark/button.scss
src/patternfly/sass-utilities/themes/dark/colors.scss

fixes https://github.com/patternfly/patternfly/issues/5040

fix(theme): improved contrast of red-8888, warning button text

---

src/patternfly/components/Timestamp/timestamp.scss

feat(Timestamp): update outlineoffset and display styles

---

src/patternfly/components/ExpandableSection/expandable-section.scss

fix(ExpandableSection): remove top margin on toggle

---

patternfly-docs/site/pages/guidelines.md

chore(docs): better describe variable naming

---

src/patternfly/components/Tabs/tabs-link.hbs
src/patternfly/components/Tabs/tabs-scroll-button.hbs

Fixes issues with tabs when used with form
fixes: #5056

fix(tabs): fixed button type for tab link (#5056)

---

patternfly-a11y.config.js
src/patternfly/components/DualListSelector/dual-list-selector-draggable-button.hbs
src/patternfly/components/FormControl/examples/FormControl.md
src/patternfly/components/LogViewer/examples/LogViewer.md
src/patternfly/components/TabContent/examples/TabContent.md

Closes: https://github.com/patternfly/patternfly/issues/5065

chore(a11y): update coverage to include docs

---

src/patternfly/components/FormControl/examples/FormControl.md
src/patternfly/components/FormControl/form-control.scss

feat(Inputs): add plain read only variant

---

src/patternfly/components/Banner/banner.scss
src/patternfly/components/Banner/examples/Banner.md
src/patternfly/components/Banner/themes/dark/banner.scss

Applies to update feature for issue #5013

feat(banner): added support/docs for status icons and text

---

src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu.scss

feat(menu): added danger menu item variation

---

scripts/gulp/html.js
src/patternfly/components/Form/examples/Form.md
src/patternfly/components/Form/form-group-label-help.hbs
src/patternfly/components/Form/form-label.hbs
src/patternfly/components/Form/form.scss

fix(form-group): fixed help wrapping

---

src/patternfly/demos/Drawer/examples/drawer-jump-links.hbs

fix(sidebar): fixed demos

---

src/patternfly/components/Button/button-progress.hbs
src/patternfly/components/Button/button.hbs
src/patternfly/components/Button/button.scss
src/patternfly/components/Button/examples/Button.md
src/patternfly/components/Spinner/examples/Spinner.md
src/patternfly/components/Spinner/spinner.hbs
src/patternfly/components/Spinner/spinner.scss

Closes #4994 
[Button progress examples](https://patternfly-pr-5104.surge.sh/components/button#progress)

feat(Button): added progress support for inline link

---

src/patternfly/components/Tabs/tabs.hbs
src/patternfly/demos/Page/page-template-title.hbs
src/patternfly/demos/Tabs/examples/Tabs.md
src/patternfly/demos/Tabs/tabs--page-grid-view.hbs
src/patternfly/demos/Tabs/tabs--table.hbs

refactor(tabs): updated demos

---

.github/workflows/extensions.yml

Automatically add any issues tagged with 'extensions' label to the PatternFly extensions github project

Create new extensions github workflow

---

src/patternfly/components/SkipToContent/examples/SkipToContent.md
src/patternfly/components/SkipToContent/skip-to-content.hbs
src/patternfly/components/SkipToContent/skip-to-content.scss
src/patternfly/demos/NotificationDrawer/notification-drawer-demo.hbs
src/patternfly/demos/Page/page-demo-expandable-nav.hbs
src/patternfly/demos/Page/page-template-skip-to-content.hbs

Closes: #4972 
Attempt to see if this creates a new patternfly-five/patternfly alpha release

fix(skip-to-content): separate pf-c-skip-to-content from pf-c-button

---

src/patternfly/components/ContextSelector/context-selector.scss

follow up from https://github.com/patternfly/patternfly/pull/5189

fix(context-selector): updated static props

---

src/patternfly/components/Wizard/examples/Wizard.md
src/patternfly/components/Wizard/wizard-footer.hbs
src/patternfly/demos/Wizard/examples/Wizard.md

Changed the button order in an effort to improve user experience and common mental models when using wizards.
closes #5110

chore(wizard): updated button order

---

src/patternfly/components/CalendarMonth/examples/CalendarMonth.md
src/patternfly/components/CodeEditor/examples/CodeEditor.md
src/patternfly/components/DualListSelector/examples/DualListSelector.md
src/patternfly/components/FormControl/examples/FormControl.md
src/patternfly/components/LabelGroup/examples/LabelGroup.md
src/patternfly/components/Masthead/examples/masthead.md
src/patternfly/components/MenuToggle/examples/MenuToggle.md
src/patternfly/components/MultipleFileUpload/examples/MultipleFileUpload.md
src/patternfly/components/NotificationDrawer/examples/NotificationDrawer.md
src/patternfly/components/Panel/examples/Panel.md
src/patternfly/components/Select/examples/Select.md
src/patternfly/components/Slider/examples/Slider.md
src/patternfly/components/TreeView/examples/TreeView.md
src/patternfly/demos/Masthead/examples/Masthead.md

Closes #5178
Remove beta tags:
Calendar month
Card: raised variant
Code editor
Dual list selector
Form group: icon sprites
Label group (except editable variant)
Masthead
Menu toggle
File upload - multiple
Notification drawer
Panel
Select: view more, loading variant
Slider
Tree view

chore(beta-components): promote 2022.14 candidates

---

src/patternfly/components/AboutModalBox/about-modal-box.scss
src/patternfly/components/Breadcrumb/breadcrumb.scss
src/patternfly/components/Divider/divider.scss
src/patternfly/components/Drawer/drawer.scss
src/patternfly/components/Form/form.scss
src/patternfly/components/InlineEdit/inline-edit.scss
src/patternfly/components/JumpLinks/jump-links.scss
src/patternfly/components/Label/label.scss
src/patternfly/components/Menu/menu.scss
src/patternfly/components/Pagination/pagination.scss
src/patternfly/components/Progress/progress.scss
src/patternfly/components/Switch/switch.scss
src/patternfly/components/Table/table-grid.scss
src/patternfly/components/Table/table-tree-view.scss
src/patternfly/components/Table/table.scss
src/patternfly/components/Tabs/tabs.scss
src/patternfly/components/Toolbar/toolbar.scss
src/patternfly/components/Wizard/wizard.scss
src/patternfly/sass-utilities/placeholders.scss

fix(all): removed visibility CSS for JAWS bug

---

src/patternfly/components/Check/check.scss
src/patternfly/components/Radio/radio.scss

fixes https://github.com/patternfly/patternfly/issues/5141

fix(check/radio): set description/body to fill available width

---

src/patternfly/components/Pagination/examples/Pagination.md
src/patternfly/components/Pagination/pagination.scss
src/patternfly/components/Tabs/examples/Tabs.md

fix(pagination): added support for insets

---

src/patternfly/demos/Tabs/tabs--page-grid-view.hbs

fixes https://github.com/patternfly/patternfly/issues/5244

chore(tabs): updated nested demo heading levels

---

src/patternfly/components/InputGroup/examples/InputGroup.md
src/patternfly/components/InputGroup/input-group-text.hbs
src/patternfly/components/InputGroup/input-group.scss
src/patternfly/components/InputGroup/themes/dark/input-group.scss
src/patternfly/components/Slider/examples/Slider.md
src/patternfly/components/Slider/slider.scss

Closes #5176 
[Slider preview build](https://patternfly-pr-5249.surge.sh/components/slider)
Added styling to the input group text CSS to match a disabled input as well.

fix(Slider): updated value input styling

---

.github/workflows/release.yml
package.json
release.config.js

feat(release): release v5 branch to alpha channel

---

src/patternfly/demos/Card/templates/card-demo--notification-drawer.hbs
src/patternfly/demos/Card/templates/card-template-status.hbs

fixes https://github.com/patternfly/patternfly/issues/5305

chore(card): removed unnecessary class from labels in demos

---

src/patternfly/demos/Wizard/examples/Wizard.md

fix(wizard): move wizard footer below steps/nav

---

src/patternfly/components/Drawer/drawer.scss

fixes https://github.com/patternfly/patternfly/issues/4797

fix(drawer): removed body min-height

---

src/patternfly/components/Tabs/tabs-item-action.hbs
src/patternfly/components/Tabs/tabs.scss

fixes https://github.com/patternfly/patternfly/issues/5240
The help action feature is marked as beta in core and react, safe to remove. This will need a react follow up to remove the custom class.

fix(tabs): removed help action specific styling

---

src/patternfly/components/Content/content.scss
src/patternfly/components/Content/examples/Content.md

fixes https://github.com/patternfly/patternfly/issues/5336
convenience link - https://patternfly-pr-5337.surge.sh/components/text (under the heading "Plain list example")

feat(content): added plain list variation

---

src/patternfly/demos/Banner/examples/Banner.md
src/patternfly/demos/DescriptionList/examples/DescriptionList.md
src/patternfly/demos/HelperText/examples/HelperText.md
src/patternfly/demos/Page/examples/Page.md
src/patternfly/demos/PasswordStrength/examples/PasswordStrength.md

Closes: https://github.com/patternfly/patternfly/issues/5320

fix(beta): cleaned up beta tags for v4

---

src/patternfly/base/_common.scss
src/patternfly/sass-utilities/scss-variables.scss

chore(base): remove breaking styles from _common.scss

---

src/patternfly/components/Popover/themes/dark/popover.scss
src/patternfly/components/Tooltip/themes/dark/tooltip.scss

fix(tooltip-popover): updated bg color, border, box shadow

---

src/patternfly/components/LabelGroup/examples/LabelGroup.md

fixes https://github.com/patternfly/patternfly/issues/5352

chore(label-group): removed close button from editable active example

---

src/patternfly/components/Popover/themes/dark/popover.scss
src/patternfly/components/Tooltip/themes/dark/tooltip.scss
src/patternfly/components/Tooltip/tooltip.scss

fixes https://github.com/patternfly/patternfly/issues/5358
Also added a tooltip arrow bg var to match popover

fix(tooltip): updated tooltip arrow to match dark theme

---

src/patternfly/components/Menu/menu.scss

fixes https://github.com/patternfly/patternfly/issues/5374

fix(menu): fixed nested drilldown list visibility

---

src/patternfly/base/_icons.scss
src/patternfly/base/_svg-icons.scss

fix(icons): replace svg size variations with new class

---

src/patternfly/components/Card/card-title-text.hbs
src/patternfly/components/Card/card-title.hbs
src/patternfly/components/Card/card.scss
src/patternfly/components/Card/examples/Card.md
src/patternfly/components/Chip/chip.scss
src/patternfly/demos/Card/card-template-gallery.hbs
src/patternfly/demos/Card/examples/Card.md
src/patternfly/demos/Card/templates/card-demo--template-gallery.hbs
src/patternfly/demos/Card/templates/card-template-data-list.hbs
src/patternfly/demos/Card/templates/card-template-events.hbs
src/patternfly/demos/Card/templates/card-template-expandable-status.hbs
src/patternfly/demos/Card/templates/card-template-line-chart.hbs
src/patternfly/demos/PrimaryDetail/primary-detail-template-card-view.hbs
src/patternfly/demos/Tabs/examples/Tabs.md

Closes #5234 
This PR:
Removes:
- `--pf-c-card__title--FontFamily`
- `--pf-c-card__title--FontSize`
- `--pf-c-card__title--FontWeight`
- `--pf-c-card--m-display-lg__title--FontSize`
- `--pf-c-card__title--FontSize`
Adds: 
- `--pf-c-card__title-text--FontFamily`
- `--pf-c-card__title-text--FontSize`
- `--pf-c-card__title-text--FontWeight`
- `--pf-c-card__title-text--LineHeight`
- `--pf-c-card--m-display-lg__title-text--FontSize`
- `--pf-c-card__title-text--FontSize`

fix(card): updated title weight/added title-text

---

src/patternfly/components/Banner/banner.scss
src/patternfly/components/Chip/chip.scss

fix(banner): replaced status with color

---

src/patternfly/components/LogViewer/examples/LogViewer.md
src/patternfly/components/Popover/examples/Popover.md
src/patternfly/components/Popover/popover-title-icon.hbs
src/patternfly/components/Popover/popover-title.hbs
src/patternfly/components/Popover/popover.scss
src/patternfly/demos/Card/templates/card-demo--popover.hbs

fixes https://github.com/patternfly/patternfly/issues/5411

fix(popover): removed references to pf-m-icon class

---

src/patternfly/components/OptionsMenu/options-menu.scss

chore(OptionsMenu): removed lineHeight css variable

---

src/patternfly/components/CalendarMonth/examples/CalendarMonth.md
src/patternfly/components/DatePicker/examples/DatePicker.md
src/patternfly/components/FileUpload/examples/FileUpload.md
src/patternfly/components/FormControl/form-control.hbs
src/patternfly/components/InputGroup/examples/InputGroup.md
src/patternfly/components/InputGroup/input-group-item.hbs
src/patternfly/components/InputGroup/input-group-text.hbs
src/patternfly/components/InputGroup/input-group.hbs
src/patternfly/components/InputGroup/input-group.scss
src/patternfly/components/InputGroup/themes/dark/input-group.scss
src/patternfly/components/NumberInput/examples/NumberInput.md
src/patternfly/components/SearchInput/search-input.hbs
src/patternfly/components/Slider/examples/Slider.md
src/patternfly/components/TextInputGroup/examples/TextInputGroup.md
src/patternfly/components/Toolbar/toolbar-item-search-filter.hbs
src/patternfly/demos/Form/examples/BasicForms.md
src/patternfly/demos/Masthead/examples/Masthead.md
src/patternfly/demos/PasswordGenerator/examples/PasswordGenerator.md
src/patternfly/demos/PasswordStrength/examples/PasswordStrength.md

fix(input-group): refactor to be more flexible, added items

---

src/patternfly/components/Progress/examples/Progress.md
src/patternfly/demos/PasswordStrength/examples/PasswordStrength.md

fixes https://github.com/patternfly/patternfly/issues/5429
fixes https://github.com/patternfly/patternfly/issues/5427

docs(progress, password strength): fixed demo, updated docs

---

src/patternfly/components/DatePicker/date-picker-helper-text.hbs
src/patternfly/components/DatePicker/date-picker.hbs
src/patternfly/components/DatePicker/date-picker.scss
src/patternfly/components/DatePicker/examples/DatePicker.md
src/patternfly/components/FileUpload/examples/FileUpload.md
src/patternfly/components/Form/examples/Form.md
src/patternfly/components/Form/form-helper-text-icon.hbs
src/patternfly/components/Form/form-helper-text.hbs
src/patternfly/components/HelperText/examples/HelperText.md
src/patternfly/components/HelperText/helper-text-item-icon.hbs
src/patternfly/components/HelperText/helper-text-item-text.hbs
src/patternfly/components/HelperText/helper-text-item.hbs
src/patternfly/components/HelperText/helper-text.hbs
src/patternfly/components/HelperText/helper-text.scss
src/patternfly/components/Login/examples/Login.md
src/patternfly/components/Progress/examples/Progress.md
src/patternfly/components/Progress/progress-helper-text.hbs
src/patternfly/components/Progress/progress.hbs
src/patternfly/demos/Alert/alert-template-horizontal-form.hbs
src/patternfly/demos/Alert/alert-template-stacked-form.hbs
src/patternfly/demos/Form/examples/BasicForms.md
src/patternfly/demos/HelperText/examples/HelperText.md
src/patternfly/demos/PasswordStrength/examples/PasswordStrength.md
src/patternfly/demos/Toolbar/examples/Toolbar.md

fix(helper-text): replaced component helper text

---

src/patternfly/components/CalendarMonth/examples/CalendarMonth.md

Want to move the Calendat month component into the Date and Time group with other like components.

Add calendar month to date and time group

---

src/patternfly/components/DatePicker/examples/DatePicker.md
src/patternfly/components/Dropdown/examples/Dropdown.md
src/patternfly/components/Icon/examples/Icon.md
src/patternfly/components/LogViewer/examples/LogViewer.md
src/patternfly/components/ProgressStepper/examples/ProgressStepper.md
src/patternfly/components/SearchInput/examples/SearchInput.md
src/patternfly/components/Tabs/examples/Tabs.md
src/patternfly/components/TextInputGroup/examples/TextInputGroup.md
src/patternfly/components/Tile/examples/Tile.md
src/patternfly/components/Truncate/examples/Truncate.md
src/patternfly/demos/Page/examples/Page.md

Closes: https://github.com/patternfly/patternfly/issues/5321
Date picker
Dropdown: bulk select loading state
Icon
Log viewer
Page demos (html)
Progress stepper
SearchInput
Tabs: dynamic
Tabs: horizontal overflow
Tabs: actions
Tabs: close button props
Text input group
Tile
Truncate

fix(docs): promote various components/features out of beta for v5

---

src/patternfly/components/Form/form.scss

This fixes https://github.com/patternfly/patternfly-react/issues/8951

fix(form): add transparent background to form group help label

---

src/patternfly/components/FileUpload/examples/FileUpload.md
src/patternfly/demos/ContextSelector/examples/ContextSelector.md

Clean up 2 errors found in testing new website organization:
- Rename Text File Upload to Simple File Upload (was just File Upload in v4)
- Move Context Selector demo under Menus

Chore(docs): IA clean up

---

src/patternfly/base/_chart-globals.scss

Removed leading `c-` from charts selector

feat(charts): updated charts selector

---

src/patternfly/components/AboutModalBox/about-modal-box.scss

fixes https://github.com/patternfly/patternfly/issues/5542

fix(about-modal): fixed close button icon size

---

src/patternfly/layouts/Level/level.scss
src/patternfly/layouts/Split/split.scss
src/patternfly/layouts/Stack/stack.scss

fixes https://github.com/patternfly/patternfly/issues/5584

fix(layouts): update level, split, stack to use gap

---

src/patternfly/components/FormControl/form-control.scss
src/patternfly/components/Slider/examples/Slider.md

fixes https://github.com/patternfly/patternfly/issues/5589

fix(form-control): update disabled state in slider, update to span full width

---

patternfly-docs/site/pages/accessibility-guide.md
src/patternfly/components/Banner/examples/Banner.md
src/patternfly/components/CalendarMonth/examples/CalendarMonth.md
src/patternfly/components/Card/card--hidden-input.hbs
src/patternfly/components/InputGroup/examples/InputGroup.md
src/patternfly/components/Popover/examples/Popover.md
src/patternfly/utilities/Accessibility/examples/Accessibility.md

fixes https://github.com/patternfly/patternfly/issues/5596

fix(card): fixed screen-reader class on clickable card radio

---

src/patternfly/layouts/Flex/flex.scss

fixes https://github.com/patternfly/patternfly/issues/5599

fix(flex): added xs gap spacer

---

src/patternfly/base/_variables.scss
src/patternfly/patternfly-charts.scss
src/patternfly/sass-utilities/_init.scss
src/patternfly/themes/dark/_patternfly-charts-theme-dark.scss

fix(theme): fix dark theme global var specificity

---

src/patternfly/components/CodeEditor/code-editor.scss
src/patternfly/components/CodeEditor/themes/dark/code-editor.scss
src/patternfly/components/FormControl/themes/dark/form-control.scss

fixes https://github.com/patternfly/patternfly/issues/5627

fix(form-control): fixed dark theme readonly/disabled styles

---

src/patternfly/demos/Card/examples/Card.md
src/patternfly/layouts/Flex/examples/Flex.md
src/patternfly/layouts/Flex/flex.scss

fixes https://github.com/patternfly/patternfly/issues/5591
fixes https://github.com/patternfly/patternfly/issues/5614

fix(flex): fixed nested spacer issue, card demos

---

src/patternfly/components/Page/page.scss
src/patternfly/components/Page/themes/dark/page.scss

feat(page): moved vars to root

---

src/patternfly/components/Drawer/examples/Drawer.md
src/patternfly/components/Nav/examples/Navigation.md
src/patternfly/demos/Nav/examples/Nav.md

Changed "light-200" in text to "secondary." Also added deprecated tags where needed.
closes: [#5649](https://github.com/patternfly/patternfly/issues/5649)

fix: updated some text, and added deprecated tags where needed

---

src/patternfly/components/Card/themes/dark/card.scss

fixes https://github.com/patternfly/patternfly/issues/5586

fix(card): updated selectable dark theme styles

---

src/patternfly/base/_variables.scss
src/patternfly/base/themes/dark/_variables.scss
src/patternfly/components/TextInputGroup/text-input-group.scss
src/patternfly/sass-utilities/placeholders.scss
src/patternfly/sass-utilities/scss-variables.scss
src/patternfly/sass-utilities/themes/dark/placeholders.scss
src/patternfly/sass-utilities/themes/dark/scss-variables.scss

fixes https://github.com/patternfly/patternfly/issues/5670

fix(text-input-group): updates to fix when used in dark block

---

src/patternfly/base/_fonts.scss

fixes https://github.com/patternfly/patternfly/issues/5677

fix(font): fixed RHD bold incorrect font mapping to italic font

---

src/patternfly/base/themes/dark/_chart-globals.scss

fixes https://github.com/patternfly/patternfly/issues/5672

fix(charts): fixed dark theme chart var prefix

---

src/patternfly/components/DescriptionList/examples/DescriptionList.md
src/patternfly/components/FormControl/examples/FormControl.md
src/patternfly/components/Icon/examples/Icon.md
src/patternfly/utilities/BackgroundColor/examples/BackgroundColor.md
src/patternfly/utilities/Text/examples/Text.md

Fixes broken links found in testing the v5 website.
Closes #5687

fix(workspace): fix broken links for v5 website

---

src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu-item-action.hbs
src/patternfly/components/Menu/menu-item.hbs
src/patternfly/components/Menu/menu-list-item.hbs
src/patternfly/components/Menu/menu.scss

feat(Menu): added aria-disabled styling

---

src/patternfly/components/Chip/chip-group-label.hbs
src/patternfly/components/Chip/chip-group.hbs
src/patternfly/components/Chip/examples/Chip.md

closes: [#5258](https://github.com/patternfly/patternfly/issues/5258)

fix(chip): added role and aria-label to match react

---

.github/ISSUE_TEMPLATE/devX_request.md

Closes https://github.com/patternfly/patternfly/issues/5683

chore: fixed DX issue template typo

---

src/patternfly/components/TreeView/tree-view.scss

chore(tree-view): added default flag to max nesting var

---

src/patternfly/components/AboutModalBox/about-modal-box.scss
src/patternfly/components/Button/examples/Button.md

Closes: [#5634](https://github.com/patternfly/patternfly/issues/5634)

fix(aboutmodal): added variable for background image

---

src/patternfly/components/Button/examples/Button.md
src/patternfly/components/Wizard/wizard-nav-link.hbs

Fixed the button type so it no longer submits when clicked.
closes: [#5463](https://github.com/patternfly/patternfly/issues/5463)

chore(wizard): fixed button type for wizard

---

src/patternfly/components/Button/examples/Button.md

Added the pf-m-warning class and description into the usage table on button page.
Closes: [#5654](https://github.com/patternfly/patternfly/issues/5654)

"chore: added pf-m-warning to the button usage table"

---

src/patternfly/components/AppLauncher/app-launcher-menu-item.hbs
src/patternfly/components/AppLauncher/app-launcher-menu-wrapper.hbs
src/patternfly/components/AppLauncher/app-launcher-menu.hbs
src/patternfly/components/AppLauncher/deprecated/application-launcher.md
src/patternfly/components/ContextSelector/__context-selector-menu-menu.hbs
src/patternfly/components/ContextSelector/context-selector-menu-list-item.hbs
src/patternfly/components/ContextSelector/context-selector-menu-menu.hbs
src/patternfly/components/Dropdown/deprecated/Dropdown.md
src/patternfly/components/Dropdown/dropdown-menu-item.hbs
src/patternfly/components/Dropdown/dropdown-menu-list-item.hbs
src/patternfly/components/Dropdown/dropdown-menu-list.hbs
src/patternfly/components/Dropdown/dropdown-menu.hbs
src/patternfly/components/LogViewer/templates/__log-viewer-toolbar.hbs
src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/OptionsMenu/options-menu-menu-item.hbs
src/patternfly/components/OptionsMenu/options-menu-menu.hbs
src/patternfly/components/OverflowMenu/overflow-menu-control.hbs
src/patternfly/components/OverflowMenu/overflow-menu-dropdown-item.hbs
src/patternfly/components/ProgressStepper/progress-stepper-step.hbs
src/patternfly/components/Select/__select-single.hbs
src/patternfly/components/Select/select-menu.hbs
src/patternfly/components/Tabs/tabs-item.hbs
src/patternfly/components/Tabs/tabs-link.hbs
src/patternfly/components/Tabs/tabs-list.hbs
src/patternfly/components/Tabs/tabs.hbs

closes: [#5385](https://github.com/patternfly/patternfly/issues/5385)

fix(role): update roles to match React

---

.github/upload-preview.js
.github/workflows/pr-preview.yml
.github/workflows/release.yml
package.json
release.config.js

BREAKING CHANGE: 6.0.0-alpha.0

feat(breaker): bump this version to 6.0

---

package.json

fixes https://github.com/patternfly/patternfly/issues/5797
Usage when you've pulled in significant changes to package.json and want to start with a fresh repo:
```
yarn superclean
yarn install
yarn start
```

chore: add superclean npm script

---

src/patternfly/components/OptionsMenu/options-menu-group.hbs
src/patternfly/components/OptionsMenu/options-menu-groups.hbs
src/patternfly/components/OptionsMenu/options-menu-list.hbs
src/patternfly/components/OptionsMenu/options-menu-menu-item.hbs
src/patternfly/components/OptionsMenu/options-menu-menu.hbs
src/patternfly/components/OptionsMenu/options-menu-multiple.hbs

fixes https://github.com/patternfly/patternfly/issues/5796
fixes https://github.com/patternfly/patternfly/issues/5805

chore(options-menu): updated markup to match react component

---

patternfly-docs/patternfly-docs.config.js

fixes https://github.com/patternfly/patternfly/issues/5858

chore: enable RTL switcher on full page examples

---

src/patternfly/components/Accordion/accordion.scss
src/patternfly/components/ExpandableSection/expandable-section.scss

chore(Accordion,ExpandableSection): added more RTL styling

---

src/patternfly/base/_common.scss
src/patternfly/base/_globals.scss
src/patternfly/base/_variables.scss
src/patternfly/components/Accordion/accordion.scss
src/patternfly/components/DualListSelector/dual-list-selector.scss
src/patternfly/components/ExpandableSection/expandable-section.scss
src/patternfly/components/Pagination/pagination.scss
src/patternfly/components/Slider/slider.scss
src/patternfly/components/Switch/switch.scss
src/patternfly/components/Wizard/wizard.scss
src/patternfly/sass-utilities/functions.scss
src/patternfly/sass-utilities/mixins.scss

* Refactors the global mixins/functions
* Updates previously worked on components to use new mixin names
* https://github.com/patternfly/patternfly/pull/5860
* dual list selector
* pagination
* switch
* wizard
* https://github.com/patternfly/patternfly/pull/5861/
* accordion
* expandable section
* Adds RTL styles for slider

fix(RTL): refactor mixins, add slider rtl styles

---

src/patternfly/components/Nav/examples/Navigation.css
src/patternfly/components/Nav/examples/Navigation.md
src/patternfly/components/Nav/nav-link-text.hbs
src/patternfly/components/Nav/nav-link.hbs

fixes https://github.com/patternfly/patternfly/issues/5857

fix(nav): added optional text wrapper for nav text

---

src/patternfly/components/Toolbar/toolbar-item-pagination.hbs

chore(Toolbar): updated toolbar pagination structure

---

src/patternfly/components/ClipboardCopy/clipboard-copy.scss

fixes https://github.com/patternfly/patternfly/issues/5832

fix(clipboard-copy): added rtl styles

---

src/patternfly/components/Page/page.scss

fixes https://github.com/patternfly/patternfly/issues/5759

fix(page): added rtl styles

---

src/patternfly/components/CalendarMonth/calendar-month.scss

fixes https://github.com/patternfly/patternfly/issues/5831

fix(calendar-month): rtl support

---

src/patternfly/components/Card/card.scss
src/patternfly/demos/Card/examples/Card.md

Mirror the expand caret, and add an icon element around the icon in the CTA button in the card demo so that it will mirror.
Fixes #5823

chore(Card,Tile): apply RTL fixes

---

src/patternfly/components/DataList/data-list.scss
src/patternfly/components/NotificationBadge/notification-badge.hbs

chore(DataList): added additional rtl styling

---

src/patternfly/components/TreeView/tree-view.scss

fixes https://github.com/patternfly/patternfly/issues/5822

fix(tree-view): added rtl styles

---

src/patternfly/components/Drawer/drawer.scss

Drawer needed transforms reversed and shadows needed to be reversed - instead of mathing them, I conditionally applied the opposite shadow. WDYT?
Panel, sidebar, and tab content were ok.
Fixes #5815

chore(Drawer): transforms and shadows on RTL drawer

---

src/patternfly/components/Form/form.scss
src/patternfly/sass-utilities/mixins.scss

fix(forms): updated rtl styles

---

src/patternfly/components/Skeleton/skeleton.scss
src/patternfly/demos/Skeleton/card-skeleton.hbs

fixes https://github.com/patternfly/patternfly/issues/5835

fix(skeleton): added rtl styles

---

src/patternfly/components/Slider/slider.scss

fixes https://github.com/patternfly/patternfly/issues/5892

fix(slider): added root decl for var to create react token

---

src/patternfly/base/_common.scss
src/patternfly/sass-utilities/mixins.scss

fixes https://github.com/patternfly/patternfly/issues/5911

fix: remove workspace RTL classes

---

.stylelintrc
src/patternfly/base/_globals.scss
src/patternfly/base/_variables.scss
src/patternfly/base/tokens/_tokens-default.scss
src/patternfly/base/tokens/_tokens-font.scss
src/patternfly/components/Button/button.scss

This is not all of 5851, which was written to be all the hackathon styles, but updates some tokens and styles buttons based on the tokens. More to come.

feat(Button): adds tokens and applies to buttons

---

src/patternfly/components/AboutModalBox/about-modal-box.scss

fixes https://github.com/patternfly/patternfly/issues/5921

fix: mirror bg image position in rtl

---

src/patternfly/components/Progress/progress.scss

fix(progress): updated indicator direction

---

src/patternfly/components/ClipboardCopy/clipboard-copy-expandable-content.hbs
src/patternfly/components/ClipboardCopy/examples/ClipboardCopy.md

fixes https://github.com/patternfly/patternfly/issues/5926
from the react PR https://github.com/patternfly/patternfly-react/pull/9629

chore(clipboard-copy): add code example with rtl support

---

src/patternfly/components/Card/card.scss
src/patternfly/components/Card/examples/Card.md

fixes https://github.com/patternfly/patternfly/issues/5846

fix(card): removed border from clickable/selectable selected

---

src/patternfly/components/Icon/icon-content.hbs
src/patternfly/components/Menu/examples/Menu.css
src/patternfly/components/Menu/templates/menu-breadcrumbs--Drilldown.hbs
src/patternfly/components/Menu/templates/menu-breadcrumbs--dropdown.hbs

fixes https://github.com/patternfly/patternfly/issues/5890

fix(menu): updated drilldown breadcrumb menu icons to work in RTL

---

src/patternfly/components/Toolbar/toolbar-expand-all-icon.hbs
src/patternfly/components/Toolbar/toolbar.scss

follow up to https://github.com/patternfly/patternfly-react/pull/9605
fixes https://github.com/patternfly/patternfly/issues/5936

fix(toolbar): fix expand all icon in RTL

---

src/patternfly/base/tokens/_tokens-font.scss
src/patternfly/components/Table/table.scss
src/patternfly/components/Toolbar/toolbar.scss
src/patternfly/demos/Page/examples/Penta.md

Tokens on table; minimal changes to toolbar.
Adds shadow tokens that will need to be broken out because they'll come from Figma styles (not variables) for now.
Next up will be to straighten out the token files (and update) but for now I've added them into the section with the font styles.

feat(table): apply tokens from hackathon

---

src/patternfly/components/Nav/examples/Navigation.css
src/patternfly/components/Nav/nav.scss
src/patternfly/components/Page/page.scss

Clearly some parts of nav need additional work; this is just the changes from hackathon.

feat(nav): adds tokens to page and nav

---

src/patternfly/components/Check/check-body.hbs
src/patternfly/components/Check/check-description.hbs
src/patternfly/components/Check/check-input.hbs
src/patternfly/components/Check/check-label.hbs
src/patternfly/components/Check/check.hbs
src/patternfly/components/Check/examples/Check.md
src/patternfly/components/MenuToggle/examples/MenuToggle.md
src/patternfly/components/MenuToggle/menu-toggle--check.hbs
src/patternfly/components/Radio/examples/Radio.md
src/patternfly/components/Radio/radio-body.hbs
src/patternfly/components/Radio/radio-description.hbs
src/patternfly/components/Radio/radio-input.hbs
src/patternfly/components/Radio/radio-label.hbs
src/patternfly/components/Radio/radio.hbs
src/patternfly/components/Select/__select-checkbox-checked.hbs
src/patternfly/components/Select/__select-checkbox-counts.hbs
src/patternfly/components/Select/__select-checkbox-groups-checked.hbs
src/patternfly/components/Select/__select-checkbox-groups.hbs
src/patternfly/components/Select/select-menu-item-check.hbs
yarn.lock

fix(check-radio): added aria-labelledby to check/radio

---

src/patternfly/base/tokens/_tokens-font.scss
src/patternfly/components/Button/button.scss

fixes https://github.com/patternfly/patternfly/issues/5993

fix(tokens): add dark theme blend mode token

---

src/patternfly/components/Table/table.scss

fixes https://github.com/patternfly/patternfly/issues/6024

fix(table): fix clickable overlay

---

src/patternfly/components/Badge/badge-icon.hbs
src/patternfly/components/Badge/badge.hbs
src/patternfly/components/Badge/badge.scss
src/patternfly/components/Badge/examples/Badge.md
src/patternfly/components/Badge/themes/dark/badge.scss

towards #5716
fixes https://github.com/patternfly/patternfly/issues/5957

fix(badge): adds tokens, dropdown toggle icon

---

src/patternfly/base/_globals.scss

fixes https://github.com/patternfly/patternfly/issues/6043

fix(globals): update invalid selector in global css

---

src/patternfly/components/Hint/hint.scss
src/patternfly/components/Hint/themes/dark/hint.scss

feat(hint): apply tokens

---

src/patternfly/base/_globals.scss
src/patternfly/base/tokens/_tokens-font.scss
src/patternfly/components/Content/content.scss
src/patternfly/components/List/list.scss
src/patternfly/components/Title/examples/Title.md
src/patternfly/components/Title/title.scss

Fixes #5730 
PR right before vacation so... 🤪 
Also adds modifiers for heading styles to the title component.

feat(text, title, list): apply tokens

---

src/patternfly/components/SkipToContent/skip-to-content.scss

feat(SkipToContent): refactor with tokens

---

src/patternfly/components/Form/form.scss

fixes https://github.com/patternfly/patternfly/issues/6062

fix(form): keep form groups/controls from growing too wide

---

src/patternfly/base/tokens/_tokens-default.scss
src/patternfly/components/EmptyState/empty-state.scss
src/patternfly/components/EmptyState/examples/EmptyState.md

Fixes #5733 
This also adds status modifiers for the empty state per conversation with @andrew-ronaldson. These set the icon's color to the appropriate status color.

feat(EmptyState): apply tokens

---

src/patternfly/components/Banner/banner.scss

Closes #6140 
Convenience link: https://patternfly-pr-6141.surge.sh/components/banner/#status

fix(banner): add missing custom modifier

---

src/patternfly/components/Button/button.hbs
src/patternfly/components/Button/button.scss
src/patternfly/components/Button/examples/Button.md

fixes https://github.com/patternfly/patternfly/issues/6170

fix(button): better support for span button, fix plain bugs

---

src/patternfly/components/Button/button.hbs
src/patternfly/components/Form/examples/Form.md
src/patternfly/components/Form/form-group-label-help.hbs
src/patternfly/components/Form/form.scss

fixes https://github.com/patternfly/patternfly/issues/6172

fix(form): convert field level help to button component

---

src/patternfly/components/Timestamp/timestamp.scss

Closes https://github.com/patternfly/patternfly/issues/5739

feat(Timestamp): apply tokens

---

src/patternfly/components/Button/button.scss

fixes https://github.com/patternfly/patternfly/issues/6215

fix(button): fix link background, add base display prop

---

src/patternfly/components/JumpLinks/jump-links-link.hbs
src/patternfly/components/JumpLinks/jump-links.scss

feat(JumpLinks): add tokens

---

src/patternfly/components/DescriptionList/description-list.scss
src/patternfly/sass-utilities/mixins.scss

closes #6101 
with new v6 branch. Old PR: #6102

feat(DescriptionList): apply tokens

---

src/patternfly/components/DescriptionList/description-list.scss

Follow up for comments on #6129

feat(DescriptionList): followup updates

---

CODE_OF_CONDUCT.md
src/patternfly/components/AboutModalBox/about-modal-box.scss

This reverts commit 3e4eb4ea09f97eba413dc6f9854877478c6f85fb, reversing
changes made to 1b48cb810df3c2867e88531cb3a06280172b6382.

Revert "Merge branch 'v6' of https://github.com/patternfly/patternfly into v6"

---

src/patternfly/components/ActionList/action-list.scss
src/patternfly/components/ActionList/examples/ActionList.md
src/patternfly/components/Button/button.scss
src/patternfly/components/LogViewer/templates/__log-viewer-toolbar.hbs
src/patternfly/components/Masthead/masthead.scss
src/patternfly/components/OverflowMenu/overflow-menu.scss
src/patternfly/components/Pagination/pagination.scss
src/patternfly/components/Toolbar/examples/Toolbar.css
src/patternfly/components/Toolbar/examples/Toolbar.md
src/patternfly/components/Toolbar/templates/toolbar--chip-group.hbs
src/patternfly/components/Toolbar/templates/toolbar--item-chip-group.hbs
src/patternfly/components/Toolbar/templates/toolbar--overflow-menu.hbs
src/patternfly/components/Toolbar/toolbar-group.hbs
src/patternfly/components/Toolbar/toolbar-toggle.hbs
src/patternfly/components/Toolbar/toolbar.scss
src/patternfly/demos/Masthead/examples/Masthead.md
src/patternfly/demos/Masthead/masthead-template-content-icon-group.hbs
src/patternfly/demos/Masthead/masthead-template-content.hbs
src/patternfly/demos/Page/examples/Penta.md
src/patternfly/demos/Toolbar/examples/Toolbar.md
src/patternfly/demos/Toolbar/toolbar-template.hbs

closes #5713 
https://codepen.io/bobcatTaco/pen/MWxjpVr?editors=1100
Changes affect:
- https://patternfly-pr-6057.surge.sh/components/action-list/
- https://patternfly-pr-6057.surge.sh/components/overflow-menu/
- https://patternfly-pr-6057.surge.sh/components/toolbar
- https://patternfly-pr-6057.surge.sh/components/toolbar/html-demos/

fix(toolbar-action-list-overflow-menu): added tokens, new design spec

---

src/patternfly/components/Label/label.scss

fixes https://github.com/patternfly/patternfly/issues/6266

fix(label): fixed editable active cursor

---

src/patternfly/components/Divider/divider.scss
src/patternfly/components/Divider/examples/Divider.md

fixes https://github.com/patternfly/patternfly/issues/6270

fix(divider): support use in flex layout

---

src/patternfly/components/Pagination/pagination.scss

fixes https://github.com/patternfly/patternfly/issues/6231
page gutter is now the large spacer at all breakpoints.

fix(pagination): remove inset change at xl breakpoint

---

src/patternfly/components/Alert/alert.scss

Closes https://github.com/patternfly/patternfly/issues/6233

fix(alerts): update font family

---

src/patternfly/components/Table/table-grid.scss

references https://github.com/patternfly/patternfly/issues/5728
Added table grid view tokens

chore(table): added table grid tokens

---

src/patternfly/components/Table/table.scss

references https://github.com/patternfly/patternfly/issues/5728
added table tokens

chore(table): added tokens

---

src/patternfly/components/Table/table-scrollable.scss

references #5728 
added table scrollable tokens

chore(table): added scrollable tokens

---

src/patternfly/components/Table/table-grid.scss
src/patternfly/components/Table/table.scss

references #5728 
Removes xl padding udpates

Chore table tokens xl

---

src/patternfly/components/ModalBox/examples/ModalBox.md
src/patternfly/components/ModalBox/modal-box--status-modifiers.hbs
src/patternfly/components/ModalBox/modal-box-title.hbs
src/patternfly/components/ModalBox/modal-box.hbs
src/patternfly/components/ModalBox/modal-box.scss

fixes https://github.com/patternfly/patternfly/issues/6091

fix(modal): add support for status modifiers on title

---

src/patternfly/components/TreeView/tree-view.scss

fixed a renamed var, ran script from https://github.com/patternfly/patternfly/pull/6282#issuecomment-1934944287

fix(tree-view): fixed renamed var

---

src/patternfly/components/DualListSelector/dual-list-selector.scss
src/patternfly/components/DualListSelector/themes/dark/dual-list-selector.scss

Closes #5741
Think I've got it in enough shape for a first pass. The padding around the toggle icon has changed and I'm unsure if it's matching the figma properly. ~~I'm also not sure about how to go about styling the text input group at the top of DualListSelector. We don't currently override any text input group css, and I could add in that for the border radius/background etc. I was I wondering if text input will be done separately, or if we do need overrides in DualListSelector.~~
Edit - per conversation, the text input group that acts as the search input for DLS should be updated separately and no overrides for DLS are needed.

feat(DualListSelector): apply tokens

---

scripts/helpers.mjs
src/patternfly/components/Breadcrumb/breadcrumb.scss
src/patternfly/components/Button/button.hbs
src/patternfly/components/Menu/examples/Menu.css
src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu-item-action.hbs
src/patternfly/components/Menu/menu-item.hbs
src/patternfly/components/Menu/menu-list-item.hbs
src/patternfly/components/Menu/menu.scss
src/patternfly/components/Menu/templates/menu--long-list.hbs
src/patternfly/demos/PasswordGenerator/examples/PasswordGenerator.md

chore(menu): add tokens

---

src/patternfly/components/Login/login.scss

fixes https://github.com/patternfly/patternfly/issues/6332

fix(login): bump footer icon size

---

src/patternfly/components/DualListSelector/dual-list-selector-menu.hbs
src/patternfly/components/DualListSelector/dual-list-selector.scss

Closes #6311.
Updates some tokens, cleans up hover styling on list-item-row, removes tiny border radius from items.

feat(DualListSelector): more penta updates

---

src/patternfly/components/MenuToggle/examples/MenuToggle.md
src/patternfly/components/MenuToggle/menu-toggle.scss

Closes #6337 
Also added a full width example/documentation

fix(MenuToggle): updated spacing between content and controls

---

src/patternfly/components/Menu/menu.scss

fix(menu): added transition values

---

src/patternfly/base/tokens/_tokens-font.scss

chore(tokens): remove extraneous dark box shadows

---

scripts/init.mjs
src/patternfly/sass-utilities/_init.scss

fix(v6): bumped prefix from 5 to 6

---

src/patternfly/components/ActionList/action-list.scss
src/patternfly/components/ActionList/examples/ActionList.md

feat(action-list): added icon group variable update

---

src/patternfly/components/Menu/examples/Menu.css
src/patternfly/components/Menu/examples/Menu.md

followup for [6319](https://github.com/patternfly/patternfly/issues/6319)

fix(menu): fixed Penta menu followups

---

src/patternfly/components/DescriptionList/description-list-order.scss
src/patternfly/components/DragDrop/examples/DragDrop.css

Followup to: https://github.com/patternfly/patternfly/commit/f1a6d7abd2c2ab124fccc7672042a625402d03fb

chore(drag-drop-description-list): updated version

---

src/patternfly/components/DescriptionList/description-list-order.scss

Reverts `pf-v6-apply-breakpoint` to `pf-v5-apply-breakpoint`

fix(description-list): revert utility

---

src/patternfly/components/CalendarMonth/examples/CalendarMonth.md

closes #6356 
Preview: https://patternfly-pr-6357.surge.sh/components/date-and-time/calendar-month

fix(calendar-month): updated .hbs

---

src/patternfly/components/MenuToggle/examples/MenuToggle.md
src/patternfly/components/MenuToggle/menu-toggle-icon.hbs
src/patternfly/components/MenuToggle/menu-toggle-toggle-icon.hbs
src/patternfly/components/MenuToggle/menu-toggle.hbs
src/patternfly/components/MenuToggle/menu-toggle.scss

fix(menu-toggle): added small variant

---

src/patternfly/components/Card/card.scss

fixes https://github.com/patternfly/patternfly/issues/6352

fix(card): fix clickable label positioning

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table-grid.scss
src/patternfly/components/Table/table-tree-view.scss
src/patternfly/components/Table/table.scss

references #5728 
references #6369

chore(table): * global to th/td

---

src/patternfly/components/Table/table-column-help-action.hbs
src/patternfly/components/Table/table.scss

chore(table): buttons

---

src/patternfly/components/Table/table-grid.scss
src/patternfly/components/Table/table.scss

chore(table): remove shadows

---

src/patternfly/components/MenuToggle/examples/MenuToggle.md
src/patternfly/components/MenuToggle/menu-toggle-icon.hbs
src/patternfly/components/MenuToggle/menu-toggle.hbs
src/patternfly/components/MenuToggle/menu-toggle.scss

followup for https://github.com/patternfly/patternfly/pull/6349#discussion_r1504217888

fix(menu-toggle): dropped toggle from toggle-toggle

---

src/patternfly/components/Table/table.scss
src/patternfly/components/Table/templates/table--scrollable--tbody--tr.hbs
src/patternfly/components/Table/templates/table--scrollable--thead--tr.hbs

chore(table): updated borders

---

.github/ISSUE_TEMPLATE/bug_report.md

This hopefully adds some checkboxes to the issue template to indicate the version of PF that the issue is against.

Update issue template with version

---

src/patternfly/components/Masthead/masthead.scss
src/patternfly/components/Nav/examples/Navigation.css
src/patternfly/components/Nav/examples/Navigation.md
src/patternfly/components/Nav/nav-scroll-button.hbs
src/patternfly/components/Nav/nav.hbs
src/patternfly/components/Nav/nav.scss
src/patternfly/components/Page/examples/Page.md
src/patternfly/components/Page/page.scss
src/patternfly/components/Toolbar/toolbar.scss
src/patternfly/demos/Masthead/masthead-template-content-toolbar-content.hbs
src/patternfly/demos/Nav/examples/Nav.md
src/patternfly/demos/Page/page-template-horizontal-subnav.hbs

fixes https://github.com/patternfly/patternfly/issues/6299

fix(nav): updates to horizontal subnav

---

src/patternfly/components/FormControl/form-control.scss

Towards https://github.com/patternfly/patternfly/issues/5695 and https://github.com/patternfly/patternfly/issues/5751
Related to https://github.com/patternfly/patternfly/pull/6397

fix(FormControl): updated select styling for v6 branch

---

src/patternfly/components/Table/examples/Table.css
src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table-scrollable.scss
src/patternfly/components/Table/table-th.hbs
src/patternfly/components/Table/table-tree-view.scss
src/patternfly/components/Table/table.scss

relates to #5728 
Remaining known issues
https://github.com/patternfly/patternfly/issues/6293

chore(table): color and padding updates

---

src/patternfly/components/MenuToggle/examples/MenuToggle.md
src/patternfly/components/MenuToggle/menu-toggle-status-icon.hbs
src/patternfly/components/MenuToggle/menu-toggle.hbs
src/patternfly/components/MenuToggle/menu-toggle.scss

fixes https://github.com/patternfly/patternfly/issues/6242

fix(menu-toggle): added support for validation/status

---

src/patternfly/components/Nav/examples/Navigation.css
src/patternfly/components/Nav/examples/Navigation.md
src/patternfly/components/Nav/nav.scss
src/patternfly/components/Nav/templates/nav--flyout.hbs

fix(Nav): updated var placement for nav flyout menus

---

src/patternfly/components/Table/table.scss

chore(table): remove unused variables

---

src/patternfly/components/Check/check.scss

fix(check): changed height to min-height

---

src/patternfly/base/tokens/_tokens-charts.scss
src/patternfly/base/tokens/_tokens-dark.scss
src/patternfly/base/tokens/_tokens-default.scss
src/patternfly/base/tokens/_tokens-palette.scss

Updates to tokens from design. Modifies status colors and adds a border color on secondary.

chore(tokens): update tokens with new status colors and border on secondary

---

src/patternfly/components/Label/examples/Label.md
src/patternfly/components/Label/label--variants.hbs
src/patternfly/components/Label/label-content.hbs
src/patternfly/components/Label/label.hbs
src/patternfly/components/Label/label.scss

fixes https://github.com/patternfly/patternfly/issues/6442

fix(label): added disabled styles

---

src/patternfly/components/Badge/badge.hbs
src/patternfly/components/Badge/examples/Badge.md
src/patternfly/components/Breadcrumb/examples/Breadcrumb.css
src/patternfly/components/Breadcrumb/examples/Breadcrumb.md
src/patternfly/components/Menu/templates/menu-breadcrumbs--dropdown.hbs
src/patternfly/components/MenuToggle/examples/MenuToggle.md

chore(Badge/MenuToggle): updated implementation of badge toggle

---

src/patternfly/base/tokens/_tokens-charts.scss
src/patternfly/base/tokens/_tokens-dark.scss
src/patternfly/base/tokens/_tokens-default.scss
src/patternfly/base/tokens/_tokens-palette.scss

Adds the compact semantic control spacers
Further fixes #6472 😄

chore(tokens): add compact semantic spacers

---

src/patternfly/components/Avatar/avatar.scss
src/patternfly/components/Brand/brand.scss
src/patternfly/components/DataList/data-list-grid.scss
src/patternfly/components/Divider/divider.scss
src/patternfly/components/Drawer/drawer.scss
src/patternfly/components/Dropdown/dropdown.scss
src/patternfly/components/Form/form.scss
src/patternfly/components/FormControl/form-control.scss
src/patternfly/components/JumpLinks/jump-links.scss
src/patternfly/components/Masthead/masthead.scss
src/patternfly/components/Menu/menu.scss
src/patternfly/components/NumberInput/number-input.scss
src/patternfly/components/Pagination/pagination.scss
src/patternfly/components/ProgressStepper/progress-stepper.scss
src/patternfly/components/Sidebar/sidebar.scss
src/patternfly/components/Tabs/tabs.scss
src/patternfly/components/ToggleGroup/toggle-group.scss
src/patternfly/components/Toolbar/toolbar.scss
src/patternfly/patternfly-charts-theme-dark-unversioned.scss
src/patternfly/patternfly-charts-theme-dark.scss
src/patternfly/sass-utilities/placeholders.scss
src/patternfly/sass-utilities/scss-variables.scss
src/patternfly/themes/dark/_patternfly-charts-theme-dark.scss
src/patternfly/utilities/Spacing/spacing.scss

More updates of v5 to v6 on the remaining mixins, extends, etc.
Part of #6366

chore(maps): more breakpoint maps and other mixins

---

src/patternfly/base/tokens/_tokens-font.scss
src/patternfly/components/Toolbar/examples/Toolbar.css
src/patternfly/components/Toolbar/examples/Toolbar.md
src/patternfly/components/Toolbar/toolbar.scss

fixes https://github.com/patternfly/patternfly/issues/6489

fix(toolbar): added sticky background, addl bg variants

---

src/patternfly/utilities/BackgroundColor/BackgroundColor.scss
src/patternfly/utilities/BackgroundColor/examples/BackgroundColor.md
src/patternfly/utilities/Text/examples/Text.md
src/patternfly/utilities/Text/text.scss

Changes text and background utilities to align with new tokens.
Fixes #6486

feat(utilities): provide token based options

---

src/patternfly/demos/Card/examples/Card.md
src/patternfly/demos/Card/templates/card-demo--notification-list.hbs
src/patternfly/demos/Card/templates/card-template-status.hbs
src/patternfly/demos/DescriptionList/examples/DescriptionList.md

This removes and updates some places where utility classes of old colors were used.
Fixes #6491

feat(utilities): update uses of color utilities

---

src/patternfly/base/_variables.scss
src/patternfly/components/Button/button.scss
src/patternfly/components/Menu/menu.scss
src/patternfly/components/Page/page.scss
src/patternfly/components/Toolbar/toolbar.scss

fixes https://github.com/patternfly/patternfly/issues/6500
fixes https://github.com/patternfly/patternfly/issues/6501

fix(page/toolbar): fix page section padding, toolbar z-index

---

scripts/helpers.mjs
src/patternfly/components/Content/content--element.hbs
src/patternfly/components/Content/content--kitchen-sink.hbs
src/patternfly/components/Content/content.scss
src/patternfly/components/Content/examples/Content.md

fixes https://github.com/patternfly/patternfly/issues/5966
This keeps the existing functionality (just writing HTML without classes), at least for the time being. IMO it's worth looking at whether we want to keep that and how useful it is.
The only difference I could find is this small shift with the plain list in the [plain html in content wrapper example](https://patternfly-pr-6511.surge.sh/components/text#plain-html-in-content-wrapper). I glanced at that nothing stood out as to what's causing it? 
And because the SCSS is a little complicated, including the compiled CSS below 
```css
:where(:root),
:where(.pf-v6-c-content) {
--pf-v6-c-content--MarginBottom: var(--pf-t--global--spacer--md);
--pf-v6-c-content--LineHeight: var(--pf-t--global--font--line-height--body); …
```

fix(content): add class support to styled elements

---

src/patternfly/demos/PasswordStrength/examples/PasswordStrength.md

chore(PasswordStrength): removed help popover icon in v5 demos

---

src/patternfly/demos/PasswordStrength/examples/PasswordStrength.md

chore(PasswordStrength): removed help popover icon from demos

---

src/patternfly/utilities/Alignment/examples/Alignment.css
src/patternfly/utilities/Display/examples/Display.css
src/patternfly/utilities/Flex/examples/Flex.css
src/patternfly/utilities/Float/examples/Float.css
src/patternfly/utilities/Sizing/examples/Sizing.css
src/patternfly/utilities/Spacing/examples/Spacing.css

Closes #6619 
This PR updates the borders/padding in utility examples to match updates made to layout examples using new tokens.

chore(docs): update utility example tokens

---

src/patternfly/base/tokens/tokens-charts-dark.scss
src/patternfly/base/tokens/tokens-charts.scss
src/patternfly/base/tokens/tokens-dark.scss
src/patternfly/base/tokens/tokens-default.scss
src/patternfly/base/tokens/tokens-palette.scss

fixes https://github.com/patternfly/patternfly/issues/6625

chore(tokens): get latest tokens from figma

---

src/patternfly/components/Wizard/wizard.scss

feat(Wizard): set flexbasis with height var

---

src/patternfly/patternfly-charts.scss

fixes https://github.com/patternfly/patternfly/issues/6649
also fixes a few typos and deletes a dupe var

fix(charts): include tokens in charts css, typos

---

src/patternfly/utilities/Display/display.scss
src/patternfly/utilities/Display/examples/Display.css
src/patternfly/utilities/Display/examples/Display.md

fixes https://github.com/patternfly/patternfly/issues/6581

fix(display-utility): added grid, inline grid, docs

---

src/patternfly/utilities/Display/display.scss
src/patternfly/utilities/Display/examples/Display.css
src/patternfly/utilities/Display/examples/Display.md

fixes https://github.com/patternfly/patternfly/issues/6634

fix(display-utility): added grid, inline-grid, docs

---

package.json
yarn.lock

This includes the fix for `.page-loaded` @evwilkin made in https://github.com/patternfly/patternfly-org/pull/4013 and unblocks https://github.com/patternfly/patternfly/issues/6602

chore(deps): update docs-framework version

---

src/patternfly/components/LogViewer/log-viewer.scss

fixes https://github.com/patternfly/patternfly/issues/6596

fix(log-viewer): update search match text color

---

src/patternfly/components/Wizard/wizard.scss

fixes https://github.com/patternfly/patternfly/issues/6612

chore(wizard): remove unused styles

---

src/patternfly/components/Page/page.scss
src/patternfly/components/Wizard/wizard-footer-cancel.hbs
src/patternfly/components/Wizard/wizard-footer.hbs
src/patternfly/components/Wizard/wizard.scss

chore(Wizard): resolved scroll issue and used ActionList for wizard buttons

---

src/patternfly/base/tokens/tokens-charts-dark.scss
src/patternfly/base/tokens/tokens-charts.scss
src/patternfly/base/tokens/tokens-dark.scss
src/patternfly/base/tokens/tokens-default.scss
src/patternfly/base/tokens/tokens-palette.scss

Adds vertical breakpoint tokens, brings in string variables used in charts, and motion tokens.

chore(tokens): update with latest tokens

---

src/patternfly/components/Toolbar/examples/Toolbar.md
src/patternfly/components/Toolbar/toolbar.scss

fix(toolbar): updated toolbar spacers

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table.scss
src/patternfly/components/Table/templates/table-tbody--expandable.hbs

chore(table): updated clickable expandable example

---

src/patternfly/base/tokens/tokens-charts-dark.scss
src/patternfly/base/tokens/tokens-charts.scss
src/patternfly/base/tokens/tokens-dark.scss
src/patternfly/base/tokens/tokens-default.scss
src/patternfly/base/tokens/tokens-palette.scss

feat(tokens): updated tokens

---

src/patternfly/patternfly-charts.scss

fixes https://github.com/patternfly/patternfly/issues/6669
uses the tokens that were imported from https://github.com/patternfly/design-tokens/commit/35e3214ab64b6b6a1fb313c34d46dfd3503765b4

fix(charts): update strings to tokens

---

src/patternfly/components/Button/button.scss

Fixes #6589 
There is no reduced-motion variation for this one.
Figma specs: https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/YIxfglww1fRdQGclApv1nm/PatternFly-6%3A-Components?m=auto&node-id=23613%3A1181&t=yaDSp7SyRyKeEd2A-1

feat(button): add animation for hover and clicked

---

src/patternfly/patternfly-charts.scss

fixes https://github.com/patternfly/patternfly/issues/6693

fix(charts): renamed cyan to teal, gold to yellow

---

src/patternfly/components/Table/examples/Table.md
src/patternfly/components/Table/table-favorite-sort.hbs
src/patternfly/components/Table/table-sort-indicator.hbs
src/patternfly/components/Table/table-th.hbs
src/patternfly/components/Table/table.scss

feat(table-button): added table button plain

---

src/patternfly/components/ActionList/action-list.scss

fix(action-list): updated icon spacer to xs

---

src/patternfly/components/MenuToggle/menu-toggle.scss

Adds transitions to the menu toggle.
Implements just the menu toggle part of #6590

feat(menu-toggle): add transitions

---

src/patternfly/components/MenuToggle/menu-toggle.scss
src/patternfly/components/TextInputGroup/examples/TextInputGroup.css
src/patternfly/components/TextInputGroup/examples/TextInputGroup.md
src/patternfly/components/TextInputGroup/text-input-group.scss

fix(MenuToggle): updated borderradius and filter padding

---

src/patternfly/base/patternfly-variables.scss
src/patternfly/base/tokens/tokens-charts-dark.scss
src/patternfly/base/tokens/tokens-charts.scss
src/patternfly/base/tokens/tokens-dark.scss
src/patternfly/base/tokens/tokens-default.scss
src/patternfly/base/tokens/tokens-palette.scss
src/patternfly/components/Banner/banner.scss
src/patternfly/components/Banner/examples/Banner.md
src/patternfly/components/Label/examples/Label.md
src/patternfly/components/Label/label--colors.hbs
src/patternfly/components/Label/label.scss
src/patternfly/components/Table/templates/table-tr--nested-column-header.hbs
src/patternfly/demos/Card/templates/card-demo--notification-drawer.hbs
src/patternfly/demos/Card/templates/card-template-status.hbs
src/patternfly/demos/DescriptionList/examples/DescriptionList.md
src/patternfly/demos/Tabs/examples/Tabs.md

fixes https://github.com/patternfly/patternfly/issues/6742
related design tokens PR with this change https://github.com/patternfly/design-tokens/pull/63/files
The 3 commits in this PR:
* https://github.com/patternfly/patternfly/commit/f743b2a98763486c30dc1a04270efa4c62c0b59f
* copy/pasta of built CSS from design tokens PR reference above
* Manually fixed these stylelint errors by wrapping the font family names in quotes and changed the heading line-height to 1.3.
```
src/patternfly/base/tokens/tokens-default.scss
67:43  ✖  Expected "1.2999999523162842" to be "1.3000"  number-max-precision
72:38  ✖  Unexpected named color "Red"                  color-named
73:38  ✖  Unexpected named color "Red"                  color-named
74:38  ✖  Unexpected named color "Red"                  color-named …
```

fix(tokens): update cyan/gold to teal/yellow

---

.github/workflows/stale.yml

Towards: https://github.com/patternfly/patternfly-react/issues/10525

chore(ci): prevent stale action from closing things, rename label

---

src/patternfly/components/Nav/nav.scss

fixes https://github.com/patternfly/patternfly/issues/6765

fix(nav): remove underline on hover

---

src/patternfly/components/JumpLinks/jump-links.scss

fixes https://github.com/patternfly/patternfly/issues/6797
figma below

fix(jump-links): remove negative margins from expandable toggle

---

src/patternfly/components/Toolbar/toolbar.scss

fix(toolbar): removed margin modifiers, updated gap declaration 

---

src/patternfly/components/Switch/examples/Switch.md
src/patternfly/components/Switch/switch-input.hbs
src/patternfly/components/Switch/switch.scss

fix(Switch): updated a11y by removing dynamic labeling

---

src/patternfly/components/Truncate/truncate.scss

fix(truncate): updated white-space

---

src/patternfly/components/Accordion/examples/Accordion.md
src/patternfly/components/Button/examples/Button.md
src/patternfly/components/Label/examples/Label.md
src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/MenuToggle/examples/MenuToggle.md
src/patternfly/components/ModalBox/examples/ModalBox.md
src/patternfly/components/Nav/examples/Navigation.md
src/patternfly/components/Spinner/examples/Spinner.md
src/patternfly/components/Timestamp/examples/Timestamp.md

Closes: https://github.com/patternfly/patternfly/issues/6749

fix(docs): promote various components/features out of beta

---

src/patternfly/components/Wizard/wizard.scss

fix(Wizard): updated styling for wizard body

---

src/patternfly/assets/images/img_avatar-dark.svg
src/patternfly/assets/images/img_avatar-light.svg
src/patternfly/components/MenuToggle/examples/MenuToggle.md

Closes https://github.com/patternfly/patternfly/issues/6758
Minor change to the svg for the avatar component to align with the v6 Figma library.

chore(avatar): update avatar svg

---

src/patternfly/components/Wizard/wizard.scss

Closes https://github.com/patternfly/patternfly/issues/6803

fix(wizard): added border to wizard header

---

src/patternfly/components/Content/content.scss
src/patternfly/components/List/list.scss

fixes https://github.com/patternfly/patternfly/issues/6800
Backstop report - [backstop-lists-6.25.24.pdf](https://github.com/user-attachments/files/15981476/backstop-lists-6.25.24.pdf)

fix(lists): adjust list and content list indentation

---

src/patternfly/components/NotificationDrawer/examples/NotificationDrawer.md
src/patternfly/components/NotificationDrawer/notification-drawer-basic-list.hbs
src/patternfly/components/NotificationDrawer/notification-drawer.scss

fixes https://github.com/patternfly/patternfly/issues/6577

fix(notification-drawer): fix action alignment, add no-offset mod

---

src/patternfly/components/TextInputGroup/examples/TextInputGroup.md
src/patternfly/components/TextInputGroup/text-input-group-icon.hbs
src/patternfly/components/TextInputGroup/text-input-group-main.hbs
src/patternfly/components/TextInputGroup/text-input-group-template-status.hbs
src/patternfly/components/TextInputGroup/text-input-group.hbs
src/patternfly/components/TextInputGroup/text-input-group.scss

feat(TextInputGroup): added validation

---

src/patternfly/components/Icon/icon.scss

fixes https://github.com/patternfly/patternfly/issues/6744

fix(icon): update default to use icon color/size tokens

---

src/patternfly/components/Form/examples/Form.md
src/patternfly/components/Form/form.scss

fixes https://github.com/patternfly/patternfly/issues/6032 (for v6)

fix(form): support label addl info in horizontal form

---

package.json

this PR is from running `corepack use yarn@1.x`

chore(build): corepack use yarn@1.x

---

src/patternfly/base/tokens/tokens-charts-dark.scss
src/patternfly/base/tokens/tokens-charts.scss
src/patternfly/base/tokens/tokens-dark.scss
src/patternfly/base/tokens/tokens-default.scss
src/patternfly/base/tokens/tokens-palette.scss

fixes https://github.com/patternfly/patternfly/issues/6879

chore(tokens): get latest tokens, fixes line-height

---

src/patternfly/base/normalize.scss
src/patternfly/base/tokens/tokens-charts-dark.scss
src/patternfly/base/tokens/tokens-charts.scss
src/patternfly/base/tokens/tokens-dark.scss
src/patternfly/base/tokens/tokens-default.scss
src/patternfly/base/tokens/tokens-local.scss
src/patternfly/base/tokens/tokens-palette.scss
src/patternfly/components/Accordion/accordion.scss
src/patternfly/components/Badge/badge.scss
src/patternfly/components/Button/button.scss
src/patternfly/components/CalendarMonth/calendar-month.scss
src/patternfly/components/Card/card.scss
src/patternfly/components/Check/check.scss
src/patternfly/components/Content/content.scss
src/patternfly/components/EmptyState/empty-state.scss
src/patternfly/components/Form/form.scss
src/patternfly/components/HelperText/helper-text.scss
src/patternfly/components/Menu/menu.scss
src/patternfly/components/ModalBox/modal-box.scss
src/patternfly/components/MultipleFileUpload/multiple-file-upload.scss
src/patternfly/components/Nav/nav.scss
src/patternfly/components/NotificationDrawer/notification-drawer.scss
src/patternfly/components/Page/page.scss
src/patternfly/components/ProgressStepper/progress-stepper.scss
src/patternfly/components/Radio/radio.scss
src/patternfly/components/Table/table.scss
src/patternfly/components/Title/title.scss
src/patternfly/components/Wizard/wizard.scss
src/patternfly/utilities/Text/text.scss

fixes https://github.com/patternfly/patternfly/issues/6883
A backstop run (using the desktop viewport size) before/after these changes showed 0 differences

fix(tokens): pull in changes to font weight tokens

---

src/patternfly/sass-utilities/scss-variables.scss

fixes https://github.com/patternfly/patternfly/issues/6882

fix(breakpoints): update scss vars to use rems

---

src/patternfly/components/Label/examples/Label.md
src/patternfly/components/Label/label.scss

fixes https://github.com/patternfly/patternfly/issues/6862

fix(label): fix close button color

---

src/patternfly/components/DataList/data-list.scss
src/patternfly/components/Table/table-grid.scss
src/patternfly/components/Table/table-tree-view.scss

fixes https://github.com/patternfly/patternfly/issues/6640

fix(vars): clean up references to old button spacers

---

src/patternfly/demos/Masthead/masthead-template-content-icon-group.hbs

resolves `fix-masthead-template-icon-group.hbs` conflict
fixes https://github.com/patternfly/patternfly/issues/6904

fix(masthead): resolved conflict

---

src/patternfly/components/Table/table-tree-view.scss

fix(table-tree-view): reset table tree view th header cell min/max-width, width , and display

---

src/patternfly/components/Button/button.hbs
src/patternfly/demos/Card/templates/card-template-expandable-status.hbs

fixes https://github.com/patternfly/patternfly/issues/6887
Here's the same button from the issue description after this PR

chore(button): unescaped button--id attribute

---

src/patternfly/components/Table/table.scss

fix(Table): favorite icon styles

---

src/patternfly/components/FormControl/form-control.scss

Closes #6866 
Also removed some focus styles/vars that weren't actually being applied anywhere.

fix(FormControl): updated status hover styling

---

src/patternfly/components/Card/card--actionable.hbs

chore(Card): added aria-disabled to link cards

---

src/patternfly/components/MenuToggle/menu-toggle.scss

fixes https://github.com/patternfly/patternfly/issues/6950
Here's a backstop report of just examples with "menu-toggle" in the title - let me know if you'd like me to run the full report:
* [menu-toggle-plain-all.pdf](https://github.com/user-attachments/files/16604123/menu-toggle-plain-all.pdf)
* [menu-toggle-plain-fails.pdf](https://github.com/user-attachments/files/16604124/menu-toggle-plain-fails.pdf)

fix(menu-toggle): updates plain padding, removes refs to m-button

---

src/patternfly/components/Nav/nav.scss

feat(nav): style drilldown menu for nav

---

src/patternfly/components/ModalBox/examples/ModalBox.md
src/patternfly/components/ModalBox/modal-box-header.hbs
src/patternfly/components/ModalBox/modal-box.scss

Fixes #6964 
Backstop report: https://drive.google.com/file/d/1uDWk76QpkLyzWxknMYCe0ckIlyI9necb/view?usp=sharing

feat(modal): adjust close button alignment

---

src/patternfly/components/Banner/banner.scss
src/patternfly/components/Content/content.scss
src/patternfly/components/Timestamp/examples/Timestamp.md
src/patternfly/components/Timestamp/timestamp.scss

Closes https://github.com/patternfly/patternfly/issues/6907, https://github.com/patternfly/patternfly/issues/6729 and https://github.com/patternfly/patternfly/issues/6871

fix(components): various fixes for banner, timestamp, and content dl

---

src/patternfly/demos/Table/examples/Table.md

fixes https://github.com/patternfly/patternfly/issues/7028
Old & busted: https://pf6.patternfly.org/components/table/html-demos/sticky-header-and-multiple-columns/
New hotness: https://patternfly-pr-7027.surge.sh/components/table/html-demos/sticky-header-and-multiple-columns/

chore(page): fix demo id, fixes masthead logo

---

src/patternfly/base/tokens/tokens-charts-dark.scss
src/patternfly/base/tokens/tokens-charts.scss
src/patternfly/base/tokens/tokens-dark.scss
src/patternfly/base/tokens/tokens-default.scss
src/patternfly/base/tokens/tokens-palette.scss
src/patternfly/components/FormControl/form-control.scss

fixes https://github.com/patternfly/patternfly/issues/7056

fix(form-control): update readonly background/border

---

src/patternfly/components/Drawer/drawer.scss

feat(Drawer): update panel background color token

---

src/patternfly/components/TextInputGroup/text-input-group.scss

feat(TextInputGroup): use icon--color--on-disabled token

---

src/patternfly/components/Page/page.scss

towards https://github.com/patternfly/patternfly-design/issues/1315

fix(page): adjust main container and sidebar scrollbars

---

src/patternfly/components/Button/button.scss

fixes https://github.com/patternfly/patternfly/issues/7036

fix(buttons): border transition update

---

src/patternfly/components/DragDrop/examples/DragDrop.md
src/patternfly/components/Table/examples/Table.md

Closes https://github.com/patternfly/patternfly/issues/7118

fix: promote drag drop out of beta, mark draggable table beta

---

src/patternfly/components/Table/table-grid.scss
src/patternfly/components/Table/table.scss

fixes https://github.com/patternfly/patternfly/issues/7124
table examples/demos backstop report - https://drive.google.com/file/d/1fFEQ0lUKaZ3EnY2A49E2CeXuiCafOlcn/view?usp=sharing

fix(table): adjust inset, column help icon alignment

---

src/patternfly/components/Drawer/drawer.scss
src/patternfly/components/Page/page.scss
src/patternfly/demos/NotificationDrawer/notification-drawer-template.hbs

fixes https://github.com/patternfly/patternfly/issues/7127

fix(page): fixed fill/scroll with notification drawer

---

src/patternfly/components/Table/examples/Table.md

fixes https://github.com/patternfly/patternfly/issues/7199

chore(table): fix draggable beta label

---

src/patternfly/components/Label/examples/Label.css
src/patternfly/components/Label/examples/Label.md
src/patternfly/components/Label/label-group.scss
src/patternfly/components/Label/label.scss

fixes: https://github.com/patternfly/patternfly/issues/7104
[Labels with truncation](https://patternfly-pr-7176.surge.sh/components/label#labels-with-truncation)

fix(label-group): truncate labels within label-group

---

src/patternfly/components/Wizard/wizard.scss

Fixes issue #7001 by setting the z-index correctly for the wizard navigation.

fix: fixes z-index issue with wizard navigation.

---

src/patternfly/layouts/Level/examples/Level.css
src/patternfly/layouts/Level/examples/Level.md
src/patternfly/layouts/Level/level.scss
src/patternfly/layouts/Split/examples/Split.css
src/patternfly/layouts/Split/examples/Split.md
src/patternfly/layouts/Split/split.scss
src/patternfly/layouts/Stack/examples/Stack.css
src/patternfly/layouts/Stack/examples/Stack.md
src/patternfly/layouts/Stack/stack.scss

fixes https://github.com/patternfly/patternfly/issues/7190

fix(split/stack): allow pf-m-fill to apply to any direct child

---

src/patternfly/components/Menu/examples/Menu.md
src/patternfly/components/Menu/menu-item-action.hbs
src/patternfly/components/Menu/menu.scss

fixes https://github.com/patternfly/patternfly/issues/7180
https://patternfly-pr-7184.surge.sh/components/menus/menu#with-favorites

fix(menu): enable menu items with favorites to show star icon and set icon color when favorited

---

src/patternfly/components/Label/examples/Label.md
src/patternfly/components/Label/label.scss

fixes https://github.com/patternfly/patternfly/issues/7215
Set label `min-width` to equal height

fix(label): update label min-width to match height

---

src/patternfly/components/MenuToggle/menu-toggle.scss

Fixes https://github.com/patternfly/patternfly/issues/7223

fix(menu-toggle): add variable for menu toggle plain border radius for MUI theme support

---

src/patternfly/components/MenuToggle/menu-toggle.scss

Closes https://github.com/patternfly/patternfly/issues/7241

fix(menu toggle): remove bg secondary
