patternfly/patternfly

- src/pages/react-reference.md
Issue: https://github.com/patternfly/patternfly-next/issues/41
Preview: https://deploy-preview-42--pf-next.netlify.com/react-reference#use-components-with-multiple-child-slots
> Add multi child usage example to react reference

- gulpfile.js
- package.json
The distribution build wasn't adding components and layouts to the sass file. This was caused by an incorrect path being used in the 'copy-source' task in the gulpfile.
> Fix issue with components not adding to distributed sass file

- README.md
- src/pages/guidelines.md
This adds documentation on how install PatternFly Next, and it includes a link to the documentation on how to customize with css variables.
> Add documentation for using PatternFly Next

- gatsby-node.js
- src/templates/documentation.js
- src/templates/page.js
When a developer runs `npm run dev` to launch the dev environment, the console is cluttered with warnings. This was caused by a conflicting property that was being used in the config.
To resolve the conflict, the `path` context property was changed to `pagePath`
Issue: https://github.com/patternfly/patternfly-next/issues/64
> Change path property in context to pagePath

- src/patternfly/components/Alert/styles.scss
- src/patternfly/components/Button/styles.scss
- src/patternfly/utilities/bs-variables.scss
- src/patternfly/utilities/variables.scss
This updates the spacer variables according to [this](https://github.com/patternfly/patternfly-next/issues/59)
I've removed the xxl and xxxl because they are no longer defined. Because of this I've updated the `.bs-variables.scss` to use the new `$pf-global--spacer--md` spacer for the gutter, which fixed a build error.
In the same `.bs-variables.scss` file there are a bunch of other spacers being used but I did not update this. @andresgalante let me know if you'd like me to go in and do that.
I've also updated the alert and button spacers to more closely match the new values. The button spacers match what is called for in the design but the alerts have to be finalized so this may need to be revisited.
> updates spacer variables

- src/pages/layouts/stack/index.js
- src/workspace.scss
There was a misunderstanding about where the example content should go. This moves the content from the workspace css, and back into the example.
Involves comment from here: https://github.com/patternfly/patternfly-next/pull/80
> Move the Stack example content from the workspace css to the example

- src/pages/layouts/split/index.js
- src/patternfly/layouts/Split/docs.md
- src/patternfly/layouts/Split/index.js
- src/patternfly/layouts/Split/styles.scss
A Split layout is a layout the displays the children horizontally. One of the children is considered the primary and will expand to fill the container as needed.
resolve #75
> Unify split layout with conventions

- gatsby-node.js
- package-lock.json
- package.json
- src/pages/demos/dashboard/index.js
- src/pages/demos/dashboard/styles.scss
- src/pages/demos/dashboard/template.hbs
- src/patternfly/components/Button/button.hbs
- src/patternfly/components/Button/index.js
- src/patternfly/components/Example/example.hbs
- src/patternfly/layouts/Level/level-item.hbs
- src/patternfly/layouts/Level/level.hbs
As a team we've decided to use Handlebars instead of React components to build out the markup for visualizing the PatternFly Next styles. This PR introduces a handlebars loader into Gatsby's Webpack config, and provides an example implementation for reference.
Preview: https://deploy-preview-120--pf-next.netlify.com/demos/dashboard/
Resolves #111 
- adds support for handlebars
- adds automatic loading of components and layouts as partials to handlebars templates
- add a new handlebars-loader dependency (handlebars-loader)
- adds a new dependencies for working with the filesystem in node (fs-extra)
- implements a dashboard demo that makes use of the Level layout and the Button component
- adds example handlebars implementation of the Button component
- adds example handlebars …
> Add loader and demo for Handlebars

- gatsby-node.js
- plugins/gatsby-plugin-page-creator/gatsby-node.js
- src/layouts/demo.js
- src/site/layouts/demo.js
- src/site/layouts/index.js
Use gatsby's `createLayouts` hook to create layouts under site/layouts.  Added a default layout for the page creator plugin we are using. Otherwise, it defaults to the old path.
Extension of https://github.com/patternfly/patternfly-next/pull/138
> chore(site/layouts): Move layouts under src/site/layouts

- src/site/pages/guidelines.md
This replaces all the css variable examples with Sass variables. 
@andresgalante can you confirm that what I've written for Sass variables on line 308 is accurate. 
Also we use the term "lintable" in a couple places, I don't think this is a word, it does seem to be used in other places though. Do we want to just go with it or reword ?
> updates variables

- src/patternfly/components/Backdrop/backdrop.hbs
- src/patternfly/components/Backdrop/docs/code.md
- src/patternfly/components/Backdrop/docs/design.md
- src/patternfly/components/Backdrop/examples/backdrop-example.hbs
- src/patternfly/components/Backdrop/examples/index.js
- src/patternfly/components/Backdrop/styles.scss
Implements the backdrop that will darken and blur the background behind a modal. 
This uses `backdrop-filter`, which has very limited support in browsers. It will gracefully degrade to a dark backdrop without the blur.
> feat(Backdrop): Implements backdrop (#255)

- src/patternfly/components/Title/styles.scss
One leftover `pf-is` in the title styles fixed to be `pf-m`
> fix(title): fixes leftover -is in title to be -m

- build/blueprints/component/files/src/patternfly/components/__moduleName__/docs/code.md
- build/blueprints/component/files/src/patternfly/components/__moduleName__/examples/__nameDasherized__-example1.hbs
- build/blueprints/component/files/src/patternfly/components/__moduleName__/examples/__nameDasherized__-example2.hbs
- build/blueprints/component/files/src/patternfly/components/__moduleName__/examples/example1.hbs
- build/blueprints/component/files/src/patternfly/components/__moduleName__/examples/example2.hbs
- build/blueprints/component/files/src/patternfly/components/__moduleName__/examples/index.js
- build/blueprints/component/files/src/patternfly/components/__moduleName__/styles.scss
- build/patternfly-cli/pf.js
fixes https://github.com/patternfly/patternfly-next/issues/271
@dgutride can you advise re: removing spaces from the output in [index.js](https://github.com/michael-coker/patternfly-next/blob/component-generator-updates/build/blueprints/component/files/src/patternfly/components/__moduleName__/examples/index.js) - in the `return()` block, the spaces in `{ {{name}}Example1 }` and `{ {{name}}Example2 }`?
> refactor(component generator): address some erros in the component generator and bring output closer inline with contribution guidelines

- build/blueprints/template/files/src/patternfly/__typeDirectory__/__namePascalized__/docs/design.md
Replacing the placeholder design.md file in the Blueprints folder with the template that we will use for design documents.
Closes #248
> Replace empty design.md with template

- src/patternfly/components/Button/styles.scss
- src/patternfly/components/Dropdown/styles.scss
- src/patternfly/components/Form/styles.scss
- src/patternfly/components/ModalBox/styles.scss
Update the borders for buttons and input fields to appear in high contrast mode on Edge in Windows 10.
fixes https://github.com/patternfly/patternfly-next/issues/286
> fix(borders): update borders for high contrast mode

- src/patternfly/components/Button/docs/code.md
- src/patternfly/components/Button/examples/buttonTypes.hbs
- src/patternfly/demos/Modal/examples/modal-example.hbs
- src/patternfly/demos/Modal/examples/modal-lg-example.hbs
- src/patternfly/demos/Modal/examples/modal-scroll-example.hbs
- src/patternfly/demos/SimpleFormDemo/examples/simple-form-demo-example.hbs
Adds `aria-label` attribute to the accessibility documentation for Button, and includes this attribute wherever the button with `pf-m-action` modifier class is used (i.e. the class used when using icons instead of text as the button label). 
Closes #320
> fix(button): Adds aria-label to pf-m-action buttons

- src/site/pages/accessibility-guide.md
- src/site/workspace.scss
The following changes have been included:
* restructured the outline — the new structure makes it easier for us to add our own PF guidelines and techniques, while still including a concise checklist to guidelines that we follow (which are mostly WCAG, but can include other guidelines that are documented that we want to adopt)
* changed the checklist from a bulleted list to a table
* updated links from WCAG 2.0 resources to WCAG 2.1 resources
* added styles for table, and modified the heading level 2 styles for more separation between content sections.
* Included WCAG added for 2.1
* Included link to WAVE webAIM tool for disabling styles (in Test section)
* Included extra step in Test section to check color contrast
* Included example techniques for defining accessible names for form …
> accessibility guide updates

- src/patternfly/demos/CardUpgradeExamples/card-upgrade-examples.hbs
- src/patternfly/demos/CardUpgradeExamples/docs/code.md
- src/patternfly/demos/CardUpgradeExamples/examples/card-upgrade-examples-example1.hbs
- src/patternfly/demos/CardUpgradeExamples/examples/card-upgrade-examples-example2.hbs
- src/patternfly/demos/CardUpgradeExamples/examples/index.js
- src/patternfly/demos/CardUpgradeExamples/styles.scss
This PR adds an upgrade example for those looking to move from PatternFly 3 to PatternFly 4. This particular example demonstrates the differences between Cards in PF3 vs PF4.
related to https://github.com/patternfly/patternfly-next/issues/334
> feat(upgrades): Add Upgrade Examples for Cards

- src/patternfly/components/Badge/styles.scss
- src/patternfly/components/Button/styles.scss
- src/patternfly/components/Check/check.hbs
- src/patternfly/components/Check/docs/code.md
- src/patternfly/components/Check/docs/design.md
- src/patternfly/components/Check/examples/check-checkbox-example.hbs
- src/patternfly/components/Check/examples/check-radio-example.hbs
- src/patternfly/components/Check/examples/index.js
- src/patternfly/components/Check/styles.scss
- src/patternfly/components/Dropdown/styles.scss
- src/patternfly/components/FormControls/docs/code.md
- src/patternfly/components/FormControls/docs/design.md
- src/patternfly/components/FormControls/examples/form-controls-input-example.hbs
- src/patternfly/components/FormControls/examples/form-controls-select-example.hbs
- src/patternfly/components/FormControls/examples/form-controls-textarea-example.hbs
- src/patternfly/components/FormControls/examples/index.js
- src/patternfly/components/FormControls/form-controls.hbs
- src/patternfly/components/FormControls/styles.scss
- src/patternfly/utilities/variables.scss
This PR is doing a couple different things:
1. the main purpose of this was to decouple the form elements from the form itself in order to be used in various components.
2. I've created a form-controls component to cover textual form controls (inputs, textarea, and select)
3. I've created a check component to cover checkbox and radios.
4. I've included styles for the login form inputs here as well. I'm not sure about the modifier `pf-m-login` it may be too specific.
5. I've asked the question on the pf4 channel about naming in handlebars. It becomes quite verbose to namespace everything so I think further discussion is needed around that. 
I've not included a11y consideration or most of the classes in the docs because I believe those will live in the form docs.
I have removed the hover …
> feat(form-controls):add form controls

- src/site/pages/accessibility-guide.md
Updates included:
- Replaces WCAG item for target area size with size recommendations from @kybaker  (although I kept the link to the WCAG item for future reference, and included a footnote below the table to clarify this)
- Adds a few details to the Testing section
- Includes some minor edits to Form Fields section under Labels and Accessible Names
> docs(accessibility guide): update target area requirements

- src/patternfly/components/Backdrop/backdrop.hbs
- src/patternfly/components/Button/button.hbs
- src/patternfly/components/ModalBox/docs/code.md
- src/patternfly/components/ModalBox/examples/index.js
- src/patternfly/components/ModalBox/examples/modal-box-basic-example.hbs
- src/patternfly/components/ModalBox/examples/modal-box-lg-example.hbs
- src/patternfly/components/ModalBox/examples/modal-box-no-header-example.hbs
- src/patternfly/components/ModalBox/modal-box-body.hbs
- src/patternfly/components/ModalBox/modal-box-button-close.hbs
- src/patternfly/components/ModalBox/modal-box-close.hbs
- src/patternfly/components/ModalBox/modal-box-footer.hbs
- src/patternfly/components/ModalBox/modal-box-header-title.hbs
- src/patternfly/components/ModalBox/modal-box-header.hbs
- src/patternfly/components/ModalBox/modal-box.hbs
- src/patternfly/components/ModalBox/styles.scss
- src/patternfly/demos/Modal/docs/code.md
- src/patternfly/demos/Modal/examples/modal-example.hbs
- src/patternfly/demos/Modal/examples/modal-lg-example.hbs
- src/patternfly/demos/Modal/examples/modal-scroll-example.hbs
- src/patternfly/demos/Modal/modal.hbs
- src/patternfly/layouts/Bullseye/bullseye.hbs
- src/site/workspace.scss
Fixes #433 
Closes #336 
Closes #445
- Added close button to modal
- Added title to modal
- Updated modal width to accommodate margin left/right for smaller viewport widths
- Updated documentation
- Added styling for footer buttons
Note: I updated the handlebars attributes as some were prefixed and some were not. This approach, aside from prefix--modifier is most concise/makes most sense to me.
> Add close button, add title, update documentation, space footer buttons

- src/patternfly/components/Button/button-link.hbs
- src/patternfly/components/Button/button.hbs
- src/patternfly/components/Button/docs/code.md
- src/patternfly/components/Button/examples/button-link-example.hbs
- src/patternfly/components/Button/examples/buttonStates.hbs
- src/patternfly/components/Button/examples/index.js
- src/patternfly/components/Button/styles.scss
- src/patternfly/components/Dropdown/docs/code.md
- src/patternfly/components/Dropdown/dropdown.hbs
Closes #402 
Add hyperlink button examples, updated documentation for disabled states for buttons and links, as well as dropdowns.
Updates `disabled="disabled"` to `disabled` according to w3 spec https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.3.4.2
> Authors should be aware that many user agents only recognize the minimized form of boolean attributes and not the full form.
> update(button, link, dropdown): add link button examples, updates documentation for buttons, links and dropdowns

- src/patternfly/components/Alert/styles.scss
- src/patternfly/components/Card/styles.scss
- src/patternfly/components/Dropdown/dropdown.hbs
- src/patternfly/components/Form/docs/code.md
- src/patternfly/components/Form/examples/form-check-radio-example.hbs
- src/patternfly/components/Form/examples/form-input-group-example.hbs
- src/patternfly/components/Form/examples/form-text-input-example.hbs
- src/patternfly/components/Form/styles.scss
- src/patternfly/components/FormControls/docs/code.md
- src/patternfly/components/FormControls/examples/form-controls-input-example.hbs
- src/patternfly/components/FormControls/examples/form-controls-select-example.hbs
- src/patternfly/components/FormControls/examples/form-controls-textarea-example.hbs
- src/patternfly/components/FormControls/form-controls.hbs
- src/patternfly/components/FormControls/styles.scss
- src/patternfly/components/InputGroup/docs/code.md
- src/patternfly/components/InputGroup/examples/input-group-example.hbs
- src/patternfly/components/InputGroup/styles.scss
- src/patternfly/sass-utilities/variables.scss
This adds the error state and required styles to the form-control component.
Included in this is the help messaging (both standard and error).
I have a few questions. @mattnolting I'm making use of your mixin for the icon for the error state. I'm not aware of the discussion around this and why it was marked as temporary. Do we want to take this approach or something else? Also, @kybaker in the sketch file I didn't see a form select with an error, but I've gone ahead and added it, I removed the icon because it conflicts with the arrow for the select. Please advise if you'd like to take another approach.
@jgiardino can you confirm that I'm implementing the proper Aria attributes for the error state?
On the topic of accessibility the helper text size is 12px and the color was `pf-black-700` …
> feat(forms):adds error/required styles to forms and form-control

- src/patternfly/components/ModalBox/docs/code.md
- src/patternfly/components/ModalBox/examples/modal-box-basic-example.hbs
- src/patternfly/components/ModalBox/examples/modal-box-lg-example.hbs
- src/patternfly/components/ModalBox/examples/modal-box-no-header-example.hbs
- src/patternfly/components/Popover/docs/code.md
- src/patternfly/components/Popover/popover.hbs
The “Close Dialog” value of aria-label is now just “Close” in both the examples and docs. This should be clearer to users who don’t know/care about the difference. Resolves #525.
> Changed aria-label of ModalBox & Popover X buttons

- src/patternfly/components/ModalBox/docs/code.md
- src/patternfly/components/Popover/docs/code.md
Added the second L to the misspelled “aria-labeledby” attribute in the ModalBox and Popover documentation. Resolves #590.
> Corrected “aria-labelledby” spelling in docs

- .travis.yml
- package-lock.json
- src/site/layouts/demo.js
- test-a11y/a11yViolationsReporter.js
- test-a11y/index.js
This PR adds support for attaching custom a11y reporting to our continuous integration. It also improves the a11y audit reporter by ironing out some small bugs and maximizing what can be tested depending on the environment.
This is an incremental step toward solving https://github.com/patternfly/patternfly-next/issues/522
This addresses exposing the results for contributors, but not yet storing or publishing the results in any persistent manner. Publishing the results has quite a number of considerations on its own, so I thought it would be good to include that as a separate PR.
So, if a user posts a PR that introduces more a11y violations than we currently have, they'll see a red x for continuous-integration/travis-ci/pr status reporter and can select the Details link for it which will …
> A11y Support in CI

- README.md
This PR clarifies steps required to run the a11y audit locally. Specifically, we need to mention installing chromedriver and adding to your system path.
Without this knowledge, users trying to run the script will see an error like the one below and it's not so obvious how to fix.
`Error: The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.`
Sort of related to https://github.com/patternfly/patternfly-next/issues/528. It's one of the first experiences one may have in doing a11y stuff with Patternfly, so it would be good to explain all the things upfront, rather than allow user to run into this error and then figure out how to fix it. …
> fix(doc): update README

- package-lock.json
- test-a11y/a11yViolationsReporter.js
- test-a11y/config.js
- test-a11y/index.js
- test-a11y/utils.js
This PR adds a status reporter for our a11y audit, which can now be ran automatically as part of a standard build on travis.
After a travis build is kicked off, the audit runs. Once the audit has started, a new status will be reported to the PR in a "pending" status. For example, like the screenshot below.
If the total number of violations has increased beyond the threshold we've set (currently 18) we'll fail the build and include a status reported back to the PR so users can understand what went wrong more quickly. For example, like in the screenshot below.
If the total number of violations is below the active threshold, we include a status back to the PR indicating success scenario. For example, like in the screenshot below.
Status can also be seen from commit view. For example, like in …
> feat(reporting): add PR status indicator for a11y audit

- src/patternfly/_variables.scss
- src/patternfly/components/AboutModalBox/styles.scss
- src/patternfly/components/Dropdown/styles.scss
- src/patternfly/components/NavSystem/styles.scss
- src/patternfly/components/Popover/styles.scss
- src/patternfly/components/Tooltip/styles.scss
This PR is fixing problems with wrong assignment of sass variables to css variables. All of var reassign is fixed and uses `--var: #{$sass-var}` and custom functions as well, however build in functions should be either covered in seperate PR or differently so this PR is not that big.
> fix(variable assigns): when assigning sass variable use #{} so css vars knows the value

- src/patternfly/components/List/docs/code.md
- src/patternfly/components/List/examples/index.js
- src/patternfly/components/List/examples/list-grid-example.hbs
- src/patternfly/components/List/examples/list-inline-example.hbs
- src/patternfly/components/List/examples/list-simple-example.hbs
- src/patternfly/components/List/list.hbs
- src/patternfly/components/List/styles.scss
Introduces the list component with two modifiers (inline and grid) that change the presentation of list items. If the list component is used without modifiers, it gets the same styling as lists within the content component.
The inline modifier displays the list items in a horizontal line using flexbox. The grid modifier positions list items within a flexible grid with a minimum column width of 100px.
This closes #675.
> feat(list): add list component

- src/patternfly/components/InputGroup/docs/code.md
- src/patternfly/components/InputGroup/examples/input-group-example.hbs
- src/patternfly/components/InputGroup/input-group-action.hbs
- src/patternfly/components/InputGroup/input-group-text.hbs
- src/patternfly/components/InputGroup/styles.scss
After discussing this with @mceledonia I've adjusted the design to drop the action and just use either the text or a standard button.
This simplifies the input group and makes it more usable. One thing we may want to change is how there is a mixin for the error state icon. If we only end up having one state icon then it makes sense to simplify this as well.
Thanks in advance for reviewing!
> fix(input-group):simplifies input group

- src/patternfly/sass-utilities/scss-variables.scss
This issue fixes issue #737.
Removal of dormant `$pf-global--DropShadow` variable from `sass-utilities` directory and in sub file `scss-variables.scss`.
> refactor(utilities): removal of dormant variables, Remove `$pf-global--DropShadow-2`

- src/patternfly/components/Progress/styles.scss
Without `max-width` the progress bar could overflow out of progress container.
> fix(progress): set max-width for progress

- src/patternfly/upgrade-examples/CardUpgradeExamples/card-upgrade-examples.hbs
- src/patternfly/upgrade-examples/CardUpgradeExamples/docs/code.md
- src/patternfly/upgrade-examples/CardUpgradeExamples/examples/card-upgrade-examples-example2.hbs
This PR closes #760. 
The card upgrade example documentation now aligns with the documentation for other components and also compares pf3 and pf4: 
| PF3 Class | Applied To | PF4 Class | Applied To | Outcome |
Also edit the pf4 card to update with the latest handlebars params.
> Documentation for Card Upgrade Example revised

- README.md
- src/site/pages/accessibility-guide.md
Closes #528  
Adds section to README.md on how to test for accessibility. Moves the section added in #615 down to this section and explains how to handle the violations that are flagged. 
Also adds a bullet to the Accessibility Guide in the Testing section to recommend aXe and link back to the README.md.
> docs(a11y): add section on testing for a11y

- src/patternfly/components/BackgroundImage/background-image.scss
- src/patternfly/components/BackgroundImage/examples/examples.scss
- src/site/gatsby-variables.scss
This change allows CSS image paths to be overridden via variables. For example, when the CSS is imported by react-core components and/or when the same SASS files are compiled for different image paths associated with the Gatsby site.
The $pf-global--image-path is overridden via the Gatsby build.
Fixes https://github.com/patternfly/patternfly-react/issues/682
> fix(backgroundImage): Add variables to support background images

- src/patternfly/components/Check/check.hbs
- src/patternfly/components/Dropdown/docs/code.md
- src/patternfly/components/Dropdown/docs/dropdown-basic.md
- src/patternfly/components/Dropdown/docs/dropdown-multi-select.md
- src/patternfly/components/Dropdown/docs/dropdown-select.md
- src/patternfly/components/Dropdown/dropdown-basic.hbs
- src/patternfly/components/Dropdown/dropdown-menu.hbs
- src/patternfly/components/Dropdown/dropdown-multi-select.hbs
- src/patternfly/components/Dropdown/dropdown-select.hbs
- src/patternfly/components/Dropdown/dropdown.hbs
- src/patternfly/components/Dropdown/examples/dropdown-align-right-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-basic-expanded-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-collapsed-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-expanded-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-kebab-align-right-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-kebab-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-kebab-right-aligned-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-multi-select-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-multi-select-expanded-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-select-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-select-expanded-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-select-expanded-selected-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-top-example.hbs
- src/patternfly/components/Dropdown/examples/index.js
Differentiates a select-type dropdown and multi-select dropdown from the existing action/link dropdown and puts in appropriate a11y.
NOTE: Multi-select needs the chip component in order to display the selected items properly. This should be done in a future issue.
Fixes #708
> Dropdown select 708

- src/patternfly/components/Button/button.scss
Adds `user-select: none;` (and necessary vendor prefixes) to disable text selection within the button component and any of its sub-elements.
This closes #802.
> fix(button): Disable text selection within buttons

- src/site/workspace.scss
The original Login Layout PR #665 didn't include workspace CSS adjustments to display a dashed border around the primary elements of the demo. This PR fixes that.
The color contrast issue described in #620 still needs to be addressed before this demo looks totally normal.
> fix(login): Add dashed border to workspace's login layout demo

- src/patternfly/utilities/Alignment/docs/code.md
Adds `align` to the utility class names in the documentation. Resolves #812.
> fix(alignment): Update class name documentation

- src/patternfly/components/LoginBox/login-box.scss
- src/patternfly/demos/LoginPage/examples/login-page-simple-example.hbs
Adds form and list components to the login demo. Input styling doesn’t align with the mockup, but it should in the future when the new FormControl is implemented (the current alternative input style is being ditched).
This closes #717.
> fix(login): Add basic form and list components to demo

- src/patternfly/_variables.scss
- src/patternfly/components/Breadcrumb/breadcrumb-item.hbs
- src/patternfly/components/Breadcrumb/breadcrumb-link.hbs
- src/patternfly/components/Breadcrumb/breadcrumb-list.hbs
- src/patternfly/components/Breadcrumb/breadcrumb.hbs
- src/patternfly/components/Breadcrumb/breadcrumb.scss
- src/patternfly/components/Breadcrumb/docs/breadcrumb-with-title.md
- src/patternfly/components/Breadcrumb/docs/code.md
- src/patternfly/components/Breadcrumb/docs/design.md
- src/patternfly/components/Breadcrumb/examples/breadcrumb-example.hbs
- src/patternfly/components/Breadcrumb/examples/breadcrumb-with-title-example.hbs
- src/patternfly/components/Breadcrumb/examples/breadcrumb-without-home-link-example.hbs
- src/patternfly/components/Breadcrumb/examples/index.js
- src/patternfly/components/Nav/nav.scss
- src/patternfly/sass-utilities/scss-variables.scss
Feature: https://github.com/patternfly/patternfly-next/issues/33
This PR handles:
* Basic, single line breadcrumb
* Basic, single line breadcrumb without a home link
* Breadcrumb with the last list item styled as Page Title
> Feat(breadcrumb): Implements Breadcrumb Component

- src/patternfly/components/Dropdown/docs/code.md
- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/Dropdown/examples/dropdown-align-right-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-kebab-align-right-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-kebab-right-aligned-example.hbs
- src/patternfly/components/Dropdown/examples/dropdown-top-example.hbs
- src/patternfly/components/Dropdown/examples/index.js
I had to leave `.pf-m-top` on the `.pf-c-dropdown` element because that class also flips the toggle icon when the dropdown is expanded, so I scoped the menu styles to `.pf-c-dropdown.pf-m-top` https://github.com/patternfly/patternfly-next/issues/836
> refactor(dropdown): pf-m-align-right class shuffle, other workspace bug fixes

- .vscode/settings.json
- src/patternfly/components/Nav/docs/code.md
- src/patternfly/components/Nav/nav.hbs
- src/patternfly/demos/PageLayout/examples/page-layout-default-nav-example.hbs
- src/patternfly/demos/PageLayout/examples/page-layout-expandable-nav-example.hbs
- src/patternfly/demos/PageLayout/examples/page-layout-grouped-nav-example.hbs
- src/patternfly/demos/PageLayout/examples/page-layout-horizontal-nav-example.hbs
- src/patternfly/demos/PageLayout/examples/page-layout-simple-nav-example.hbs
- src/patternfly/demos/PageLayout/page-template-header-brand-elements.hbs
- src/patternfly/layouts/Page/docs/code.md
- src/patternfly/layouts/Page/page.hbs
- src/patternfly/layouts/Page/page.scss
This is doing a couple things but its core purpose is to add the CSS that will allow the header to condense on scroll. So you will see the class `.pf-m-scroll-content` and `.pf-m-condensed` added to the page layout. 
I also removed the JS that is associated with the navigation to keep core clean of any JS. 
I've updated the docs for page and did a few clean up tasks here as well.
This closes #768 and #818 
Questions: 
Do we want`.pf-m-scroll-content` to be a modifier or should be default behaviour?
Naming is hard, does `.pf-m-condensed` make sense for the header modifier?
> Masthead scroll

- src/patternfly/utilities/BoxShadow/box-shadow.scss
Adds the missing leftward variants of the Box Shadow utility. Resolves #856.
> fix(box shadow utility): Add left variants

- src/site/_site/Preview/styles.scss
This changes the white background of the `.Preview__body` in the workspace to instead be transparent, so that the background of a component can show through.
> fix(workspace): Change bg of preview body to allow component bg to show

- src/patternfly/components/Nav/docs/code.md
- src/patternfly/components/Nav/nav.scss
- src/patternfly/demos/PageLayout/examples/index.js
- src/patternfly/demos/PageLayout/examples/page-layout-default-nav-tall-header-example.hbs
- src/patternfly/demos/PageLayout/examples/page-layout-grouped-nav-example.hbs
- src/patternfly/demos/PageLayout/examples/page-layout-horizontal-nav-example.hbs
- src/patternfly/layouts/Page/docs/code.md
- src/patternfly/layouts/Page/examples/page-layout-nav-horizontal-example.hbs
- src/patternfly/layouts/Page/examples/page-layout-nav-vertical-example.hbs
- src/patternfly/layouts/Page/page-header-selector.hbs
- src/patternfly/layouts/Page/page.scss
This moves the styles that were in the page layout for horizontal nav back to the nav component. Also moves the spacing for the toolbar to the header tools layout and not the toolbar layout.
> fix(page-layout):move nav styles to component

- src/patternfly/components/Card/card.scss
- src/patternfly/components/Card/docs/code.md
Updated card css to target `header`, `body`, `footer` for automatic layout rather than generic first/last descendant elements.
Opened to address use with table example #841 
Closes #835
> enhancement(update card for generic container use):Expand card implementation

- src/patternfly/layouts/Grid/grid.scss
fixes https://github.com/patternfly/patternfly-next/issues/920
> fix(grid): add min-width/height 0 to override min-content

- src/patternfly/components/AboutModalBox/about-modal-box.scss
fixes https://github.com/patternfly/patternfly-next/issues/1016
this was broken in Edge.
> fix(aboutmodalbox): center close icon button

- package-lock.json
- src/patternfly/upgrade-examples/PopoverUpgradeExamples/docs/code.md
- src/patternfly/upgrade-examples/PopoverUpgradeExamples/examples/index.js
- src/patternfly/upgrade-examples/PopoverUpgradeExamples/examples/popover-upgrade-examples-example1.hbs
- src/patternfly/upgrade-examples/PopoverUpgradeExamples/examples/popover-upgrade-examples-example2.hbs
- src/patternfly/upgrade-examples/PopoverUpgradeExamples/popover-upgrade-examples.hbs
fixes #418.
**MIGRATION DOC**
Popover Upgrade Examples
**Features:**
- added PF3 popover based classes and code examples
- added PF4 popover based classes and code examples
- added content to the class comparison documentation at the bottom of the page.
> feat(PopoverUpgradeExamples): Adding PF3 and PF4 right popover for comparison

- .stylelintrc
fixes https://github.com/patternfly/patternfly-next/issues/1090
> chore(stylelint): remove selector-max-universal

- src/patternfly/components/AboutModalBox/about-modal-box-logo-image.hbs
- src/patternfly/components/AboutModalBox/about-modal-box-logo.hbs
- src/patternfly/components/AboutModalBox/about-modal-box.scss
- src/patternfly/components/AboutModalBox/docs/code.md
- src/patternfly/components/AboutModalBox/examples/about-modal-box-example.hbs
- src/patternfly/components/Backdrop/backdrop.scss
- src/patternfly/components/Content/content.scss
- src/patternfly/demos/AboutModal/examples/about-modal-example.hbs
This is work requested by @kybaker for the Openshift POC.
The about modal has been simplified a bit by removing the secondary logo.
Also a bunch of minor design changes :)
> fix(about-modal): makes changes for Openshift POC

- src/patternfly/components/Tabs/tabs.scss
fixes https://github.com/patternfly/patternfly-next/issues/1002
@andybraren @mattnolting can you guys peek at this and tell me if it looks OK to you? I made 2 commits. One for the initial refactor work. Another for making the tab buttons visible when the start/end arrow buttons are visible. re: the second commit, that's how I would expect the tabs to look with the directional arrows, but I'm assuming the way it was initially was on purpose?
> refactor(tabs): refactor css vars

- build/blueprints/template/files/src/patternfly/__typeDirectory__/__namePascalized__/examples/index.js
fixes https://github.com/patternfly/patternfly-next/issues/1214
> fix(build): blueprint index.js should import {{nameDasherized}}.scss instead of {{nameCamelized}}.scss

- src/patternfly/components/AlertGroup/alert-group.hbs
- src/patternfly/components/AlertGroup/alert-group.scss
- src/patternfly/components/AlertGroup/alert-item.hbs
- src/patternfly/components/AlertGroup/docs/alert-group.md
- src/patternfly/components/AlertGroup/docs/code.md
- src/patternfly/components/AlertGroup/docs/design.md
- src/patternfly/components/AlertGroup/docs/toast-group.md
- src/patternfly/components/AlertGroup/examples/alert-group-example.hbs
- src/patternfly/components/AlertGroup/examples/index.js
- src/patternfly/components/AlertGroup/examples/toast-group-example.hbs
Alert Groups are used to contain and align consecutive alerts, either inline alongside a page's content or in the top-right corner as toast notifications.
This implementation is based on [this visual design](https://redhat.invisionapp.com/share/MFOCVXG3R5S#/screens/323130343):
The width of a toast group is set by `--pf-c-alert-group--MaxWidth` with an initial value of 600px. Regular alert groups are fullwidth.
Padding is used to space the toast group in the corner and keep it centered in smaller viewports. `pointer-events: none;` allows users to click through that padding (to click nav items, tabs, etc.) and `pointer-events: initial;` is applied to the group’s direct children to make sure alerts themselves are still clickable.
- Do we want to enable developers to position toasts in places …
> feat(AlertGroup): Introduce Alert Group component

- src/patternfly/_base.scss
- src/patternfly/assets/fontawesome/solid.scss
- src/patternfly/components/Button/button.scss
- src/patternfly/components/Dropdown/dropdown.scss
fixes https://github.com/patternfly/patternfly-next/issues/976
I created this branch from the workspace/FA updates I made in https://github.com/patternfly/patternfly-next/pull/1221
@dgutride we have this issue where any of the properties defined in the "PF shield" (the bit of CSS that lets you drop PF4 CSS on the page and it only applies reset styles to classes that start with `.pf-[cul]-`) where, if any of the properties in the shield are undefined on a patternfly component/layout element and are expected to inherit from it's ancestor elements, the shield breaks the inheritance by explicitly setting the property.
For example, the shield sets `font-family: var(--pf-global--FontFamily--sans-serif);` and `color: var(--pf-global--Color--100);` to any element with a `pf-[cul]-` class. If you …
>  refactor(base.scss): try writing the shield in a different way

- src/patternfly/components/Alert/alert.scss
- src/patternfly/components/Alert/docs/code.md
Bottom spacer for title was too small when text breaks to second line. This uses margin which breaks our rule but it seems like an appropriate way to break it :)
> fix(alert): spacing update

- src/patternfly/components/AboutModalBox/examples/about-modal-box-example.hbs
- src/patternfly/components/Title/docs/code.md
- src/patternfly/demos/AboutModal/examples/about-modal-example.hbs
closes #1190 
@jgiardino I think you are right, it doesn't seem like the right move to have an H1 in a dialog. From what I've read it is an acceptable approach but could lead to issues with assistive technologies. I've changed this to an `<h2>` but I wonder if we should be also documenting this? Can we be that prescriptive if it's more just a suggestion?
> fix(modal): update heading types

- src/site/_site/Documentation/index.js
- src/site/_site/Preview/index.js
* Wtih Gatsby v2, the target attribute is no longer passed through to
the underlying anchor tag.
Do not render regular layout in full page view
* We do not determine whether or not we are in a full page view
until after the component has mounted. The result is, when refreshing
the browser while viewing a full page example, the regular layout will
flash on the screen before being replaced with the full page layout.
* If we default the initial isFull state to null, we can initially
render nothing while we determine what kind of view we're in. Then,
once the component has mounted, render the appropriate view using the
calculated state.
***NOTES***
1. Full page examples open a new tab again
2. I noticed that when refreshing the page while viewing a full page example, the regular layout was …
> Replace Gatsby Links with anchor tags

- src/patternfly/_base.scss
fixes https://github.com/patternfly/patternfly-next/issues/1334
Verified in my local version of Openshift Console.
> refactor(base.scss): create mixin/extend for elements that get shield attr selector styles

- test-a11y/config.js
- test-a11y/index.js
This PR removes the color-contrast, html-has-lang, and document-title checks from the a11y audit. There seems to be a configuration bug in around the color contrast checks, and the other two appear to be flaky in general. This turns these problematic checks off so that we can unblock the open PR's while we work through fixing the configuration issue.
> feat(a11y): relax the a11y audit checks

- src/patternfly/components/Table/docs/table-sortable.md
- src/patternfly/components/Table/table-th.hbs
- src/patternfly/components/Table/table.scss
- src/site/pages/modifiers.md
> fix(table): remove ascending and descending modifiers from sortable table heads

- src/patternfly/components/AboutModalBox/about-modal-box-hero-image.hbs
- src/patternfly/components/AboutModalBox/about-modal-box.scss
- src/patternfly/components/AboutModalBox/docs/code.md
- src/patternfly/components/AboutModalBox/examples/about-modal-box-example.hbs
- src/patternfly/components/AboutModalBox/examples/examples.scss
- src/patternfly/components/AboutModalBox/examples/index.js
- src/patternfly/demos/AboutModal/examples/about-modal-example.hbs
closes #1351 
I've also added in `position:sticky;` on the close button so it's stays in place when there is a lot of content and you scroll.
> fix(about-modal): fixes image stretch with scroll

- src/patternfly/components/Form/form.scss
redo of https://github.com/patternfly/patternfly-next/issues/1364, followed up on this with @kybaker and he said the spacing should be 16px.
> fix(form): horizontal space between buttons in form action row

- src/patternfly/components/AboutModalBox/about-modal-box.scss
adds `top:0;` to get `position:sticky;` to work properly.
> fix(about-modal): adds top to close button

- src/patternfly/components/FormControl/form-control.scss
fixes https://github.com/patternfly/patternfly-next/issues/674
browsers handle the font-size and line-height differently in form elements. setting a height using the existing variables that should define the ultimate height works consistently across browsers. verified in chrome, safari, firefox, edge.
> fix(formcontrol): add height property for browser consistency

- .travis.yml
- package-lock.json
- package.json
- test-a11y/config.js
- test-a11y/index.js
This PR aims to further stablize our a11y test suite by upgrading related packages to the latest version and adding some strategic timeouts before running each page audit so that we can be sure we're auditing pages when they are in an ideal state, and not still in the process of rendering. I also added some missing catch() handlers to some of the reporter internals, these were resulting in `UnhandledPromiseRejectionWarning` errors being thrown in some of the builds from earlier today. This change should make those occurrences produce friendlier error messages. 
Before I added the these waits, the reporter reported a different number of errors most of the times I ran it locally. After the adjustments, I'm getting reports of 19 errors each run.
bump version of chromedriver
bump version of …
> feat(error-handling): add missing error handlers, upgrade a11y pkgs

- src/patternfly/_base.scss
We disabled `-moz-focus-inner` for a reason a while back, but I can't recall what the reason was. I removed that CSS and tested in Firefox and everything looks OK to me. Please give everything a good look and focus on buttons and make sure nothing breaks :)
fixes https://github.com/patternfly/patternfly-next/issues/1023
> fix(base.scss): enable -moz-focus-inner on buttons

- src/site/_site/CodepenButton/index.js
Use unpkg as our CDN instead of https://pf4.patternfly.org/styles.css. Reference #1435.
Example [codepen.](https://codepen.io/anon/pen/wNOJre?&editable=true) There's still the detail of figuring out assets other than CSS, like the Patternfly logo.
> fix(docs): update CDN url

- src/patternfly/components/Table/docs/table-compound-expansion.md
- src/patternfly/components/Table/docs/table-expandable.md
- src/patternfly/components/Table/examples/table-compound-expansion-example.hbs
- src/patternfly/components/Table/examples/table-expandable-example.hbs
- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Table/table-nested.hbs
- src/patternfly/components/Table/table-tr.hbs
- src/patternfly/components/Table/table.hbs
- src/patternfly/components/Table/table.scss
Fix #1424 
Expandable rows in tables should have the same padding as expandable rows in data lists. Currently in tables, we use the columns from the above row to determine spacing around content, but this is not robust enough for products to use.
Fix: expandable rows by default have no padding i.e. if you want to include something that has its own padding / the nested table in compound expansion / or when there is no required padding. 
using `.pf-c-table__expandable-row-content` as the child of `.pf-c-table__expandable-row` will apply the necessary spacing.
> Change padding around expandable rows.

- README.md
Closes #893 
I opened this issue a few months ago. The idea was to harden CSS/React implementation. 
Do we think this is still necessary/is there anything to add?
> docs(readme): update the readme to include css checklist

- src/patternfly/components/DataList/data-list-icon.hbs
- src/patternfly/components/DataList/data-list.scss
- src/patternfly/components/DataList/docs/data-list-expandable.md
- src/patternfly/components/DataList/examples/data-list-expandable-example.hbs
Closes #1389 
Adds a class called `.pf-c-data-list__icon` which styles an icon similar to a checkbox in the data table. Added icon the expandable table example - but it would be good to clarify which examples should use this icon/if any.
> Add icon in Data List 

- src/patternfly/_base.scss
I considered just adding `color: var(--pf-global--Color--100;` to the `button,
input,
optgroup,
select,
textarea ` selector in `_base.scss`, since those elements don't inherit color anyways. This would just make those elements (not all in all browsers, but most) our default color instead of the browser's default. I put together an example to test at https://codepen.io/mcoker/pen/NoXwgd.
The only problem I could see with that approach is if someone loaded the pf4 CSS after their app's CSS, and if they had declared a unique button color in their CSS with the same specificity as our element selector, we would change the color of their buttons.  But we're already going to do that with a lot of things in our base scss, like setting `font-weight` on heading elements, `color` on `a`/`a:hover` …
> fix(base.scss): add default color to form elements

- src/patternfly/components/Login/examples/login-invalid-example.hbs
Fix: #1438
This ticketed issue highlights several aria issue when performing an audit. As mentioned by @seanforyou23 in #1438, multiple demos exhibit the same issues. But after a more thorough look, it turns out two of the three issues has already been dealt with.
1) /components/Login/examples-full/
2) /components/Switch/examples-full/
3) /upgrade-examples/LoginUpgradeExamples/examples-full/
@christiemolloy is working on the Switch issue which is covered on https://github.com/patternfly/patternfly-next/pull/1473.
@srambach is working on the Login example, specifically the with the `filter id=""` issue on https://github.com/patternfly/patternfly-next/pull/1480. 
The only piece that I fixed was a missing `invalid-` text for some of the markup attributes.
**ARIA AUDIT 1**
**ARIA AUDIT 2** …
> feat(FormElementLabels): missing text in markup attributes

- src/patternfly/_variables.scss
- src/patternfly/components/BackgroundImage/background-image.hbs
- src/patternfly/components/Title/title.hbs
- src/patternfly/components/Wizard/docs/code.md
- src/patternfly/components/Wizard/docs/design.md
- src/patternfly/components/Wizard/examples/index.js
- src/patternfly/components/Wizard/examples/wizard-example.hbs
- src/patternfly/components/Wizard/examples/wizard-expanded-example.hbs
- src/patternfly/components/Wizard/wizard-body.hbs
- src/patternfly/components/Wizard/wizard-description.hbs
- src/patternfly/components/Wizard/wizard-footer.hbs
- src/patternfly/components/Wizard/wizard-header.hbs
- src/patternfly/components/Wizard/wizard-inner-wrap.hbs
- src/patternfly/components/Wizard/wizard-main.hbs
- src/patternfly/components/Wizard/wizard-nav-item.hbs
- src/patternfly/components/Wizard/wizard-nav-link.hbs
- src/patternfly/components/Wizard/wizard-nav-list.hbs
- src/patternfly/components/Wizard/wizard-nav.hbs
- src/patternfly/components/Wizard/wizard-outer-wrap.hbs
- src/patternfly/components/Wizard/wizard-toggle-divider.hbs
- src/patternfly/components/Wizard/wizard-toggle-icon.hbs
- src/patternfly/components/Wizard/wizard-toggle-list-item.hbs
- src/patternfly/components/Wizard/wizard-toggle-list.hbs
- src/patternfly/components/Wizard/wizard-toggle-num.hbs
- src/patternfly/components/Wizard/wizard-toggle.hbs
- src/patternfly/components/Wizard/wizard.hbs
- src/patternfly/components/Wizard/wizard.scss
- src/patternfly/sass-utilities/scss-variables.scss
fixes https://github.com/patternfly/patternfly-next/issues/755
* need to figure out a good way to have ellipsis overflow on the mobile steps toggle button
> feat(wizard): add wizard component

- README.md
This PR makes a small enhancement to the readme. Streamlining the doc around running the a11y audit for macOS users.
> fix(readme): clean up readme

- LICENSE.txt
Closes http://github.com/patternfly/patternfly/issues/1093 - we've decided to move the PatternFly libraries to the MIT package to be consistent.
> chore(license): add MIT license text

- src/patternfly/components/AboutModalBox/about-modal-box.scss
- src/patternfly/components/Form/form.scss
- src/patternfly/components/Nav/nav.scss
- src/patternfly/components/Page/page.scss
- src/patternfly/components/Progress/progress.scss
- src/patternfly/components/Switch/switch.scss
- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Table/table.scss
- src/patternfly/components/Toolbar/toolbar.scss
- src/patternfly/components/Wizard/wizard.scss
Fix #1421 but also addresses every component where this applies:
- about-modal
- form
- nav
- page
- pagination --- addressed this in #1482 
- progress
- switch
- table
- toolbar
- wizard
Note: `visibility: hidden` has to be set second in the case of breakpoints, but for modifiers use `visibility: visible` to make the element visible again.
> fix(multiple components): add visibility:hidden where there is display: none

- src/patternfly/components/Table/examples/table-compact-example.hbs
- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Table/table-td.hbs
- src/patternfly/components/Table/table-th.hbs
- src/patternfly/components/Table/table.scss
Fix #1450 
`.pf-c-table__check` is currently set to `vertical-align: top`. This works for "table with checkbox and actions" / "table expandable" because the checkbox lines up with the expandable arrow and the table columns are wider so it is less likely for the content to wrap more than 2 lines. However in the "compact table" the columns are so narrow that content will wrap over multiple lines - the checkbox set to top alignment looks visually off - note the image in #1450. Setting `.pf-c-table__check` to vertical-align: middle` for the compact table solves this problem.
> fix(table): update compact table check box

- src/patternfly/components/Table/docs/table-simple.md
- src/patternfly/components/Table/examples/table-expandable-example.hbs
- src/patternfly/components/Table/examples/table-simple-with-checkboxes-example.hbs
- src/patternfly/components/Table/examples/table-width-example.hbs
- src/patternfly/components/Table/table-cell-content.hbs
- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Table/table-td.hbs
- src/patternfly/components/Table/table-th.hbs
fix #1491 
* Include documentation for `<td><div></div></td> & <th><div></div></th>`
> fix(table): fix bug with content in table cells

- src/patternfly/components/Form/form.scss
- src/patternfly/demos/BasicForms/examples/horizontal-form-demo-example.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1549
To see the issue @karelhala brought up, put a form with an action row in a parent that has no padding and `overflow: auto`. For example, you can drop it in the body of a modal:
> fix(form): update basic form demo, form action overflow

- src/patternfly/components/Form/form.scss
> helper text will always appear below a form field
Adds a default top margin to helper text when it's in a form group. An example of when helper text is not in a form group is in the [login component invalid state](https://pf4.patternfly.org/components/Login/examples-full?component=Login%20Invalid)
fixes https://github.com/patternfly/patternfly-next/issues/1546
> fix(form): helper text missing top margin

- src/patternfly/components/Switch/docs/code.md
- src/patternfly/components/Switch/examples/switch-disabled-example.hbs
- src/patternfly/components/Switch/examples/switch-example.hbs
- src/patternfly/components/Switch/examples/switch-no-label-example.hbs
- src/patternfly/components/Switch/switch-input.hbs
- src/patternfly/components/Switch/switch-label.hbs
- src/patternfly/components/Switch/switch.scss
Fix #1452 
Fixes what we discussed in CSS Army. The switch label is not written in the CSS anymore, it is in the html. I feel like there are many variations on how to do this, so if you have any suggestions let me know :)
> fix(switch): remove label from css

- src/patternfly/components/Select/select-toggle.hbs
- src/patternfly/components/Select/select.scss
> fix(select): make 100% width and fix button and badge position

- src/patternfly/components/FormControl/form-control.scss
> feat(clipboardcopy): add ellipsis when text overflows in the input box

- src/patternfly/components/Table/docs/table-compact-expandable.md
- src/patternfly/components/Table/docs/table-compact-no-border-rows.md
- src/patternfly/components/Table/examples/index.js
- src/patternfly/components/Table/examples/table-compact-expandable-example.hbs
- src/patternfly/components/Table/examples/table-compact-no-border-rows-example.hbs
- src/patternfly/components/Table/examples/table-expandable-example.hbs
- src/patternfly/components/Table/table-nested.hbs
- src/patternfly/components/Table/table.hbs
- src/patternfly/components/Table/table.scss
- test-a11y/config.js
fixes https://github.com/patternfly/patternfly-next/issues/1560
> fix(table): compact table expanded state styling

- src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly-next/issues/1678
I've been testing with different image sizes by using placehold.it as the src. For example `http://placehold.it/800x50` or `http://placehold.it/350x50`
> refactor(page): do not limit brand img width, use grid in header

- src/patternfly/components/Card/card-header.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1465
I don't think we're doing this where we combine BEM blocks/elements, but looks like it's a supported BEM technique called a mix.
http://getbem.com/faq/#can-i-create-global-modifier
https://en.bem.info/methodology/key-concepts/#mix
> refactor(card): make card header a lg title

- src/patternfly/components/Tabs/tabs.scss
Fixes the cut-off focus ring by adjusting the `outline-offset` of the button that is inside the tab getting focus. This moves the focus ring in a bit so it isn't cut off.
This is not something I have played with much, so if you see an issue please let me know.
Fixes #1113
> fix(tab): adjusts focus ring

- src/patternfly/components/Table/docs/table-hidden-visible.md
- src/patternfly/components/Table/examples/index.js
- src/patternfly/components/Table/examples/table-hidden-visible-example.hbs
- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Table/table.scss
- src/patternfly/sass-utilities/mixins.scss
- src/patternfly/sass-utilities/placeholders.scss
- src/patternfly/sass-utilities/scss-variables.scss
fixes https://github.com/patternfly/patternfly-next/issues/1725
I had originally made this block of hidden/visible-on-* CSS a mixin that could be included in any component that takes an argument for the `display` property (for `block`, `table`, `flex`, etc). That might be a good idea in the future if we want to add this kind of functionality to other components.
> feat(table): add support to hide/show cells at breakpoints

- src/patternfly/components/ClipboardCopy/clipboard-copy.scss
fixes https://github.com/patternfly/patternfly-next/issues/1750
verified in chrome, firefox, safari, edge.
> fix(copytoclipboard): add word-wrap to expandable content area

- src/patternfly/components/OptionsMenu/examples/options-menu-align-right-example.hbs
- src/patternfly/components/OptionsMenu/examples/options-menu-multiple-example.hbs
- src/patternfly/components/OptionsMenu/examples/options-menu-plain-example.hbs
- src/patternfly/components/OptionsMenu/examples/options-menu-plain-text-example.hbs
- src/patternfly/components/OptionsMenu/examples/options-menu-single-example.hbs
- src/patternfly/components/OptionsMenu/examples/options-menu-top-example.hbs
- src/patternfly/components/OptionsMenu/options-menu-menu.hbs
- src/patternfly/components/OptionsMenu/options-menu-toggle-button.hbs
- src/patternfly/components/OptionsMenu/options-menu-toggle.hbs
- src/patternfly/components/OptionsMenu/options-menu.hbs
- src/patternfly/components/Pagination/examples/pagination-bottom-example.hbs
- src/patternfly/components/Pagination/examples/pagination-top-example.hbs
- src/patternfly/components/Pagination/examples/pagination-top-expanded-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-expanded-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-filter-expanded-checked-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-filter-expanded-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-mobile-filter-checked-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-mobile-filter-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-pagination-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-simple-example.hbs
- src/patternfly/demos/DataList/data-list-pagination.hbs
- src/patternfly/demos/DataList/data-list-toolbar.hbs
- src/patternfly/demos/DataList/data-list-without-pagination-toolbar.hbs
- src/patternfly/demos/DataTable/data-table-pagination.hbs
- src/patternfly/demos/DataTable/data-table-toolbar-no-sort.hbs
- src/patternfly/demos/DataTable/data-table-toolbar.hbs
This removes the hidden span labeling the options menu, and adjusts the aria-labelled by attribute to point to the toggle.
This meant that the handlebars parameter `options-menu--label-text` was unused and has been removed both from the options menu component and wherever the options menu was used (pagination, toolbar, data list, and data table)
Fixes #1758
> fix(a11y): fixes aria tagging on options menu

- src/patternfly/components/Alert/alert.scss
fixes https://github.com/patternfly/patternfly-next/issues/1804
> fix(alert): only adjust warning alert webfont icon font-size

- src/site/pages/guidelines.md
fixes https://github.com/patternfly/patternfly-next/issues/1809
> fix(guidelines): punctuation, formatting

- src/patternfly/components/Table/table.scss
Close #1770 
I think min-height was added to the button to increase the focus ring, but this was causing issues with `vertical-align: baseline`.
So removed the min-height which also fixes how the text in the cells align.
> fix(table): remove min-height from buttons in expansion toggle

- src/patternfly/components/Content/content.scss
Close #1841 
@mcoker not sure how you expected this to go, `<small>` was already added to lines 117 - 130 but the small element already has a margin bottom set, so I just added in the last-child selector there.
> fix(content): change margin bottom for small element

- src/patternfly/components/Nav/nav.scss
- src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly-next/issues/1794, fixes https://github.com/patternfly/patternfly-next/issues/1797
> fix(nav): fix horizontal nav spacing, background color

- src/patternfly/_variables.scss
- src/patternfly/layouts/Gallery/docs/code.md
- src/patternfly/layouts/Gallery/gallery.scss
- src/patternfly/layouts/Grid/docs/code.md
- src/patternfly/layouts/Grid/grid.scss
- src/patternfly/layouts/Level/docs/code.md
- src/patternfly/layouts/Level/level.scss
- src/patternfly/layouts/Split/docs/code.md
- src/patternfly/layouts/Split/split.scss
- src/patternfly/layouts/Stack/docs/code.md
- src/patternfly/layouts/Stack/stack.scss
- src/patternfly/sass-utilities/scss-variables.scss
fixes https://github.com/patternfly/patternfly-next/issues/1822
> fix(gutter): update mobile gutter spacing in layouts that have gutters

- src/patternfly/components/Alert/alert.scss
- src/patternfly/components/Alert/docs/code.md
- src/patternfly/components/Alert/examples/alert-inline-example.hbs
- src/patternfly/components/Alert/examples/alert-inline-variations-example.hbs
- src/patternfly/components/Alert/examples/index.js
Based on design doc at https://docs.google.com/document/d/1HTkvK8_zFJAX-rhBw1aNrmZYzywixik31DzaiKCUbW4/edit#
Fixes #1390 
Note: The icon padding should be broken into parts but is a breaking change so there is an issue for this in #1773
> feat(alert): adds inline modifier

- src/patternfly/components/Popover/popover.scss
fixes https://github.com/patternfly/patternfly-next/issues/1856
> fix(popover): scope title class to popover component

- src/patternfly/components/Alert/alert.scss
A quick fix to have the title text colour align with the alert type. This was included in the original design and seems like it should be included. 
@bdellasc @srambach let me know if this was intentional and we can just close this :)
> fix: remove colour override from title

- src/patternfly/components/Form/form.scss
- src/patternfly/components/Login/login.scss
- src/patternfly/components/Wizard/wizard.scss
Fixed order of variables which was causing the IE conversion script to generate undefined.  Also removed a login variable that was not needed.  This was also causing the IE scripts to generate undefined. 
This resolves issue: https://github.com/patternfly/patternfly-next/issues/1869
> fix(form/login/wizard): fixed undefined issues with IE11 script

- src/patternfly/components/Switch/examples/switch-no-label-example.hbs
- src/patternfly/components/Switch/switch.scss
This adds a focus indicator to the switch component. 
After discussion with @mceledonia, we'll go with a 2px #06C border, 8 px from the edge, but no fill. This allows us to use the outline property rather than creating a pseudo-element, which would have potentially caused z-index problems.
Fixes #1824
> fix(switch): add focus indicator

- .travis.yml
- build/npm-scripts/ie-conversion-utils.js
- build/npm-scripts/ie-convert-all.js
- package.json
Use existing conversion utilities to write `patternfly-ie.css` which contains all components + base styles.
Closes https://github.com/patternfly/patternfly-react/issues/2092
> feat(ie11): add ie11 to build

- src/patternfly/components/Accordion/accordion.scss
Close #1887 
Follow up issue to remove the class on the icon: #1888
> fix(accordion): remove need for class on toggle icon

- src/patternfly/components/DataList/data-list.scss
- src/patternfly/components/DataList/docs/data-list-check-action.md
- src/patternfly/components/DataList/examples/data-list-check-action-example.hbs
This collapses actions into a kebab menu by using modifiers specifying what breakpoint to show/hide the menu toggle and action buttons.
Closes #1704
> fix(datalist): adds breakpoints for actions

- src/patternfly/components/Table/table-grid.scss
- src/patternfly/patternfly-charts.scss
fix #1823 
Fixes the table so that when the table breaks to grid form, the border width changes to 8px, and the border color matches the background color.
> fix(table): media query matches border

- src/patternfly/components/AboutModalBox/about-modal-box.scss
fix #1784 
Longs strings of words now break in the content section in the About Modal.
> fix(aboutmodalbox): add word break to content

- src/patternfly/components/Toolbar/examples/toolbar-expanded-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-filter-expanded-checked-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-filter-expanded-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-mobile-filter-checked-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-mobile-filter-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-pagination-example.hbs
- src/patternfly/components/Toolbar/examples/toolbar-simple-example.hbs
- src/patternfly/components/Wizard/wizard-toggle.hbs
- src/patternfly/demos/CardView/card-view-demo-toolbar.hbs
- test-a11y/config.js
- test-a11y/index.js
This PR updates the window size used for the browser that our a11y audit is run against. I've noticed for a while that we get more errors reported on CI that we do locally, was about to file a bug when I realized using a smaller than "maximized" size causes the audit to produce consistent results across both local and CI. We've been wanting to start testing smaller viewports anyway, as many components change in appearance and behavior at smaller dimensions. So, here we use the size of an iPad in portrait orientation.
Should help close; https://github.com/patternfly/patternfly-next/issues/1602 and https://github.com/patternfly/patternfly-next/issues/1906
> chore(a11y): use tablet viewport size when auditing

- src/patternfly/components/ClipboardCopy/clipboard-copy-expandable-content.hbs
- src/patternfly/components/ClipboardCopy/clipboard-copy.scss
- src/patternfly/components/ClipboardCopy/examples/clipboard-copy-expansion-example.hbs
close #1764 
@srambach I know you were working on these focus rings. Do you think it looks odd for only one button to have a negative outline-offset. In tabs they aren't consistent so maybe this is fine for now...
@mceledonia the input field when the clipboardcopy component is expanded, is now "Read-Only" which means that to be consistent it takes on the gray background of our "Read-Only" form control. I can override the background-color to be white here like it was before. I dont know if that will have a usability problem as users may think it is editable. Was wondering what you thought?
> fix(clipboardcopy): fix focus ring and add content editable to expanded

- src/patternfly/components/AboutModalBox/about-modal-box.scss
- src/patternfly/components/AppLauncher/app-launcher.scss
- src/patternfly/components/Backdrop/backdrop.scss
- src/patternfly/components/ContextSelector/context-selector.scss
- src/patternfly/components/DataList/data-list.scss
- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/FormControl/form-control.scss
- src/patternfly/components/InputGroup/input-group.scss
- src/patternfly/components/ModalBox/modal-box.scss
- src/patternfly/components/Nav/nav.scss
- src/patternfly/components/OptionsMenu/options-menu.scss
- src/patternfly/components/Select/select.scss
- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Table/table.scss
- src/patternfly/components/Tabs/tabs.scss
- src/patternfly/components/Wizard/wizard.scss
Close #1668 
I've been testing the Z-Index Orders of our components at these code pens:
https://codepen.io/christiemolloyy/pen/PvvNqK
https://codepen.io/christiemolloyy/pen/eaazJz
https://codepen.io/christiemolloyy/pen/GaaLYZ
https://codepen.io/christiemolloyy/pen/yWWWGW
I was looking at a system for how we should assign Z-Indexes across the system: 
100 (xs): Reserved for order within elements in a component. Example: The buttons in the nav/tabs should sit above the other elements in the component.
200 (sm): Reserved for Menus that need to sit above components that are in the same order level. They need to sit above 100 order elements like scroll buttons.
300 (md): Reserved for the Page Header (the highest order within the page component)
400 (lg): Reserved for the Backdrop. It sits …
> fix(zindex): reorder indexes and remove some.

- src/patternfly/components/Page/page.scss
fix #1917 
When I remove 1px from the breakpoint it fixes the issue of `top: var(--pf-c-page__header-nav--c-nav__scroll-button--lg--Top);` and `background-color: var(--pf-c-page__header-nav--c-nav__scroll-button--lg--BackgroundColor);` being assigned too early and causing a bug.
This also fixes the nav background-color changing to transparent before it is used for the background color of the scroll buttons.
I think its happening because the grid in the header nav changes at a minimum breakpoint of lg, and these assignments are happening at a maximum breakpoint of lg, although I can't fully pinpoint the issue. @mcoker wondering if you have any insight into this?
> fix(nav): change breakpoint to fix bug

- src/patternfly/components/AppLauncher/app-launcher.scss
- src/patternfly/components/AppLauncher/examples/index.js
fixes https://github.com/patternfly/patternfly-next/issues/1934
also updates workspace example height
> fix(applauncher): use icon var for icon height/width

- src/patternfly/components/Table/table.scss
Added word-wrap to td's in table, now wraps when on mobile size.  
Close #1791
> fix(tables): fixed word wrap (iss1791)

- src/patternfly/components/Form/docs/code.md
- src/patternfly/components/Form/examples/form-help-text-example.hbs
- src/patternfly/components/Form/form-label-text.hbs
- src/patternfly/components/Form/form-label.hbs
- src/patternfly/components/Form/form.scss
fixes https://github.com/patternfly/patternfly-next/issues/1943
per @kybaker & @mceledonia only the label text should be bold, not the icons or anything else that a user might add. So added an element to target the label text and make that bold. Should look like
> fix(form): add element for form label text, make it bold

- src/patternfly/components/Dropdown/examples/index.js
- src/site/workspace.scss
fixes https://github.com/patternfly/patternfly-next/issues/1891
> docs(dropdown): increase height of examples that overflow

- src/patternfly/components/Card/card.scss
- src/patternfly/components/Card/docs/code.md
- src/patternfly/components/Card/examples/card-compact-example.hbs
- src/patternfly/components/Card/examples/index.js
- src/patternfly/demos/CardView/card-view-demo-template-gallery.hbs
closes #1946 
@mceledonia  @gdoyle1 should the font-size in the header still be 16px for the compact card?
Here is how the card view demo looks using the compact card:
> feat(card): add compact variation

- src/patternfly/components/Button/button.hbs
- src/patternfly/components/Button/docs/code.md
- src/patternfly/components/Button/examples/button-types-example.hbs
- src/patternfly/components/Button/examples/button-variations-example.hbs
- src/patternfly/components/Button/examples/index.js
- src/patternfly/components/Expandable/expandable-toggle.hbs
- src/patternfly/components/Form/examples/form-action-group-example.hbs
- src/patternfly/components/Login/examples/login-invalid-example.hbs
- src/patternfly/components/Login/examples/login-simple-example.hbs
- src/patternfly/components/Wizard/examples/wizard-compact-nav-example.hbs
- src/patternfly/components/Wizard/examples/wizard-example.hbs
- src/patternfly/components/Wizard/examples/wizard-expanded-example.hbs
- src/patternfly/components/Wizard/examples/wizard-finished-example.hbs
- src/patternfly/components/Wizard/examples/wizard-full-width-full-height-example.hbs
- src/patternfly/demos/BasicForms/examples/horizontal-form-demo-example.hbs
- src/patternfly/demos/BasicForms/examples/simple-form-demo-example.hbs
close #1980 
I think the problem was that there was no "type" set on the toggle button in the expandable component, so when it was added to a form the type defaulted to submit. 
I think its safe to add the type as button to this component because I couldnt see it being a reset/submit type. 
Maybe we should also evaluate the variations of the button component.
> fix(expandable): add type to the button

- src/patternfly/components/Accordion/accordion-expanded-content.hbs
- src/patternfly/components/Accordion/accordion-toggle.hbs
- src/patternfly/components/Accordion/accordion.hbs
- src/patternfly/components/Accordion/docs/code.md
- src/patternfly/components/Accordion/examples/accordion-definition-list-example.hbs
- src/patternfly/components/Accordion/examples/index.js
> feat(accordion): add two variations of html markup

- README.md
- experimental-features.js
- gatsby-node.js
- gulpfile.js
- src/site/_site/Layout/index.js
> chore(exp): add experimental feature support

- src/patternfly/_chart-globals.scss
- src/patternfly/patternfly-charts.scss
This adjust 3 chart tooltip color vars and adds two new ones. This will ensure tooltips can be seen over the current background color.
Fixes https://github.com/patternfly/patternfly-next/issues/2037
> fix(chart): adjust chart tooltip colors

- src/patternfly/components/AboutModalBox/about-modal-box.scss
fixes https://github.com/patternfly/patternfly-next/issues/2034
> fix(aboutmodal): use break-word on content area instead of break-all

- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/OptionsMenu/options-menu.scss
closes #1847
Replaced `justify-content: center;` with `justify-content: space-between;` 
Also updated the options menu component, looks like the select and context selector already use `justify-content: space-between`
> fix(dropdown): add space-between when width of dropdown grows

- src/patternfly/components/Nav/nav.scss
closes #1808 
I went with just replacing 600px with 100%, since it seems like no product is currently relying on that large of a value for max-height.
> fix(nav): change max-height to 100% for subnav

- src/patternfly/components/Table/docs/code.md
- src/patternfly/components/Table/docs/table-headers-wrap.md
- src/patternfly/components/Table/examples/index.js
- src/patternfly/components/Table/examples/table-headers-wrap-example.hbs
closes #2048 
@KendraMar I added an example of how to make column headers wrap. We should create a new issue if you would like to be able to set max-widths on the columns.
> fix(table): add example of modifier

- src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly-next/issues/2074
> fix(select): update class selector, stacking context for typeahead input

- src/patternfly/components/ChipGroup/chip-group.scss
Fixed padding so the padding-left is now 0 to align with the spacer system. closes #1983
> fix(chip label): updated padding(iss1983)

- src/patternfly/components/AppLauncher/app-launcher-toggle.hbs
- src/patternfly/components/AppLauncher/app-launcher.scss
- src/patternfly/components/AppLauncher/docs/code.md
- src/patternfly/components/AppLauncher/examples/app-launcher-align-right-example.hbs
- src/patternfly/components/AppLauncher/examples/app-launcher-disabled-example.hbs
- src/patternfly/components/AppLauncher/examples/app-launcher-top-example.hbs
- src/patternfly/components/AppLauncher/examples/index.js
fixes: #1972 
relates to: https://github.com/patternfly/patternfly-react/issues/2322
> fix(applauncher): add support for right and top alignment

- src/patternfly/components/Page/docs/code.md
- src/patternfly/components/Page/page-main.hbs
- src/patternfly/components/Page/page.scss
- src/patternfly/components/SkipToContent/docs/code.md
- src/patternfly/components/SkipToContent/examples/skip-to-content-example.hbs
- src/patternfly/demos/CardView/examples/card-view-demo-example.hbs
- src/patternfly/demos/DataList/examples/data-list-actionable-demo.hbs
- src/patternfly/demos/DataList/examples/data-list-expandable-demo.hbs
- src/patternfly/demos/DataList/examples/data-list-simple-demo.hbs
- src/patternfly/demos/DataList/examples/data-list-simple-without-pagination-demo.hbs
- src/patternfly/demos/Page/examples/page-component-expandable-nav-example.hbs
- src/patternfly/demos/Page/examples/page-component-grouped-nav-example.hbs
- src/patternfly/demos/Page/examples/page-component-horizontal-nav-example.hbs
- src/patternfly/demos/Page/examples/page-component-tertiary-nav-example.hbs
- src/patternfly/demos/Page/page-demo-default.hbs
- src/patternfly/demos/Table/examples/table-compact-demo.hbs
- src/patternfly/demos/Table/examples/table-compound-expansion-demo.hbs
- src/patternfly/demos/Table/examples/table-expandable-demo.hbs
- src/patternfly/demos/Table/examples/table-simple-demo.hbs
- src/patternfly/demos/Table/examples/table-sortable-demo.hbs
This PR swaps the target element for SkipToContent from being an anchor to being the primary page container. It requires that we supply the `<main>` element with `tabindex="-1" so this region can receive focus programmatically. It's related to https://github.com/patternfly/patternfly-react/pull/2519
I did notice that unless a heading is an immediate child of the main container, we still don't get the headings read aloud for free when using a screen reader, however, I believe this is still a step in the right direction. The technique is described in one of the training courses over at dequeuniversity.com.
Should we do something about the new focus ring that appears as a result of focusing on the main content region?
add doc for new attribute requirements in Page, SkipToContent
update …
> chore(a11y): ensure SkipToContent sends focus to page content

- .travis.yml
This PR turns off a failing CI test. It's just temporary so that existing work isn't blocked. Will continue working on a long term fix in another PR.
Should help close https://github.com/patternfly/patternfly-next/issues/2118
> chore(build): temporarily disable problematic ci checks

- src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly-next/issues/2136
> fix(page): take main elements grid-area value out of custom property

- src/patternfly/_chart-globals.scss
- src/patternfly/patternfly-charts.scss
Need to refactor bullet chart vars. The existing vars were created from a mock, but they need to be updated to match the implementation in react-charts.
For example, we need a red color scale to show negative primary measures. Additional vars were needed, while some vars are no longer used at all. A few var names have changed slightly as well.
Note: These changes have been built, installed, and tested with the react-charts package.
Fixes https://github.com/patternfly/patternfly-next/issues/2158
> fix(charts): refactor bullet chart vars

- src/patternfly/_chart-globals.scss
The `--pf-chart-axis--axis-label--Padding` variable is currently set as 100. This pushes the axis label way out of bounds for charts. The value should be 40.
Fixes https://github.com/patternfly/patternfly-next/issues/2180
> Adjust chart axis label padding

- src/patternfly/components/DataToolbar/data-toolbar.scss
- put `space-items` and `spacer` modifiers in separate loops so any `spacer` value overrides any `space-items` modifier, regardless of breakpoint.
- remove `--pf-c-data-toolbar__item--child--focus--ZIndex: var(--pf-global--ZIndex--xs);` as we've opened any issue to investigate this: https://github.com/patternfly/patternfly-next/issues/2184
> fix(toolbar): put space-items and spacer modifiers in separate loop

- src/patternfly/components/Form/docs/code.md
- src/patternfly/components/Form/examples/form-horizontal-align-labels-example.hbs
- src/patternfly/components/Form/form.scss
- src/patternfly/demos/BasicForms/examples/horizontal-form-demo-example.hbs
closes #2167 
Spoke with @kybaker about how we should handle form labels. We came to the conclusion that: - 
- for form labels adjacent to a form control with one line, the label should be vertically aligned in the center.
- for form labels adjacent to a form control with two lines, the label should be aligned to the top.
This should allow for these labels to more flexible, especially with font-sizes changing. The downside is that the user will have to add a modifier to change the label to align to the top.
Here is the example in the horizontal form demo: 
Bootstrap does something similar:
> fix(form): update label alignment

- src/patternfly/layouts/Flex/docs/code.md
- src/patternfly/layouts/Flex/docs/flex-alignment.md
- src/patternfly/layouts/Flex/docs/flex-basic.md
- src/patternfly/layouts/Flex/docs/flex-intro.md
- src/patternfly/layouts/Flex/docs/flex-justification.md
- src/patternfly/layouts/Flex/docs/flex-layout-responsive.md
- src/patternfly/layouts/Flex/docs/flex-layout.md
- src/patternfly/layouts/Flex/docs/flex-spacing.md
- src/patternfly/layouts/Flex/examples/flex-alignment-example.hbs
- src/patternfly/layouts/Flex/examples/flex-basic-example.hbs
- src/patternfly/layouts/Flex/examples/flex-justification-example.hbs
- src/patternfly/layouts/Flex/examples/flex-layout-column-example.hbs
- src/patternfly/layouts/Flex/examples/flex-layout-example.hbs
- src/patternfly/layouts/Flex/examples/flex-layout-responsive-example.hbs
- src/patternfly/layouts/Flex/examples/flex-spacing-example.hbs
- src/patternfly/layouts/Flex/flex.scss
- src/patternfly/layouts/Flex/l-flex-item.hbs
- src/patternfly/sass-utilities/functions.scss
- src/patternfly/sass-utilities/mixins.scss
- src/site/workspace.scss
fixes #1984 
- wrap all `.pf-l-flex` items in `.pf-l-flex__item`
- update css - fixes responsive spacer bug
> refactor(flex-layout): wrap flex items, update css

- src/patternfly/_chart-globals.scss
This updates the area chart opacity to 30%, per my discussion with @mceledonia.
Fixes https://github.com/patternfly/patternfly-next/issues/2232
> Charts: Update area chart opacity

- src/patternfly/patternfly-charts.scss
In order to help eliminate contrast issues, we want to add the following CSS rule to patternfly-charts.scss.
`.pf-c-chart svg g[clip-path] { mix-blend-mode: multiply }`
Fixes https://github.com/patternfly/patternfly-next/issues/2238
> Charts: Set mix-blend-mode for better color contrast

- src/patternfly/_chart-globals.scss
We want to adjust the padding for pie and donut charts from 8 to 20 to help display tooltips within the boundary of the svg.
Fixes https://github.com/patternfly/patternfly-next/issues/2246
> Charts: Adjust padding for pie and donut charts

- src/patternfly/components/EmptyState/docs/code.md
- src/patternfly/components/EmptyState/empty-state-icon.hbs
- src/patternfly/components/EmptyState/empty-state-primary.hbs
- src/patternfly/components/EmptyState/empty-state.scss
- src/patternfly/components/EmptyState/examples/empty-state-primary-example.hbs
- src/patternfly/components/EmptyState/examples/index.js
- src/patternfly/components/Table/docs/table-simple.md
- src/patternfly/components/Table/table-tr.hbs
- src/patternfly/components/Table/table.scss
- src/patternfly/demos/Table/examples/index.js
- src/patternfly/demos/Table/examples/table-empty-state-demo.hbs
- src/patternfly/demos/Table/examples/table-loading-demo.hbs
- src/patternfly/demos/Table/table-empty-state-table.hbs
- src/patternfly/demos/Table/table-loading-table.hbs
* also added primary action container to empty state to support designs
fixes https://github.com/patternfly/patternfly-next/issues/2171
> fix(demo): add empty and loading state table demos

- src/patternfly/components/Page/page.scss
What: This fixes the sidebar appearing and closing when resizing window from md to sm when sidebar is closed.
fixes #2252
> fix(Page): Keep sidebar collapsed between sizes

- src/patternfly/components/Select/docs/select-multi-typeahead.md
- src/patternfly/components/Select/docs/select-single-typeahead.md
- src/patternfly/components/Select/select-toggle-typeahead-form.hbs
- src/patternfly/components/Select/select-toggle-typeahead.hbs
- src/patternfly/components/Select/select.scss
closes #2130 
- `.pf-c-form-control` `height` property throws off vertical alignment of typeahead text. Setting to `auto` allows for `input` to scale correctly.
- added `form.pf-c-select__toggle-form` to match [PF-React implementation](https://patternfly-react.surge.sh/patternfly-4/components/select/)
- remove `pf-c-select__toggle.pf-m-typeahead` `padding-top` as this adjusts height of select 
- add `margin-top` to `.pf-c-chip-group` to retain proper spacing
> fix(typeahead-select): add form wrapper, udpate css

- src/patternfly/_chart-globals.scss
- src/patternfly/patternfly-charts.scss
Added a variable for the new ChartThreshold React component. Victory's, `strokeDasharray` prop defines the length and spacing between dashes in the lines below.
Fixes https://github.com/patternfly/patternfly-next/issues/2313
> Add strokeDasharray variable for ChartThreshold

- src/patternfly/components/InputGroup/docs/code.md
- src/patternfly/components/InputGroup/input-group.scss
fixes #2286
Not sure how to move `label` into `.pf-c-input-group__text` as the order needs to be `label.pf-c-input-group__text`
cc @mcoker
> fix(input-group): unnest text class

- src/patternfly/_chart-globals.scss
- src/patternfly/patternfly-charts.scss
Adds size variables to support interactive data points with the `ChartScatter` component in react-charts.
Fixes https://github.com/patternfly/patternfly-next/issues/2339
> Add size variables for scatter chart

- src/patternfly/components/Alert/examples/Alert.md
Adds the inline modifier back to the inline alert examples.
> chore(alert): fix inline alert examples

- src/patternfly/components/FormControl/examples/FormControl.md
- src/patternfly/components/FormControl/form-control.scss
fixes https://github.com/patternfly/patternfly-next/issues/2251
> feat(textarea): add horizontal and vertical resize variants

- gatsby-node.js
- gulpfile.js
- package-lock.json
- package.json
Bump gatsby-plugin-patternfly-org which now will:
- Throw an error if Handlebars can't compile
- Pretty Handlebars HTML after it compiles
Also fix import path and GraphQL schema for `patternfly-next` to work as a submodule in `gatsby-theme-patternfly-org`.
> feat(docs): add html formatting

- src/patternfly/components/Form/examples/Form.md
- src/patternfly/components/Form/form.scss
- src/patternfly/components/FormControl/examples/FormControl.md
- src/patternfly/components/FormControl/form-control.scss
Fixes #2320 
Updates colors used for --pf-global--success-color--100 and --pf-global--success-color--200 for better a11y. See #2320
New Validated input:
Updates due to success color changes:
cc @mceledonia @kybaker @serenamarie125
> feat(form): add validated form modifier

- src/patternfly/components/Select/examples/Select.css
- src/patternfly/components/Select/examples/Select.md
- src/patternfly/components/Select/select-single.hbs
fixes https://github.com/patternfly/patternfly-next/issues/2333
> chore(select): add example of empty menu with a div

- src/patternfly/_variables.scss
- src/patternfly/sass-utilities/scss-variables.scss
fixes https://github.com/patternfly/patternfly-next/issues/2268
To test this, you can pull down the branch and update some component to use `font-family: var(--pf-global--FontFamily--monospace);`, then make sure the computed `font-family` is "liberation mono", then remove `.pf-m-redhat-font` from the `<html>` element and make sure the computed `font-family` is "overpass-mono".
> feat(font): add monospace stack for opt in redhat font

- src/patternfly/components/AppLauncher/app-launcher-menu-item-text.hbs
- src/patternfly/components/AppLauncher/app-launcher-separator.hbs
- src/patternfly/components/AppLauncher/app-launcher.scss
- src/patternfly/components/AppLauncher/examples/AppLauncher.css
- src/patternfly/components/AppLauncher/examples/AppLauncher.md
- src/patternfly/components/Dropdown/dropdown-menu-groups.hbs
- src/patternfly/components/Dropdown/dropdown-menu.hbs
- src/patternfly/components/Dropdown/dropdown-separator.hbs
- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/Dropdown/examples/Dropdown.css
- src/patternfly/components/Dropdown/examples/Dropdown.md
- src/patternfly/components/OptionsMenu/options-menu-multiple.hbs
- src/patternfly/components/OptionsMenu/options-menu.scss
- src/patternfly/components/OverflowMenu/examples/OverflowMenu.md
fixes https://github.com/patternfly/patternfly-next/issues/2102
Updated our examples to show a divider in a list (as an `<li>`), as the last `<li>` in a list as a way to separate groups (how the react examples use it), and also as an `<hr>` between groups per the new spacing @mceledonia and I discussed.
> fix(menus): fix menu group space - dropdown, options menu, app launcher

- gulpfile.js
- src/patternfly/components/SkipToContent/skip-to-content.scss
See #2405
Closes #2404 
> When importing patternfly.scss as a dependency in a project, a series of errors are thrown for not finding /components/_all.scss and /layouts/_all.scss files.
In fact, when installing PF4 via npm install @patternfly/patternfly --save the two files are not currently copied over.
> The PR also fixes a second error thrown by gulp after manually patching the _all.scss files: the @import "../../patternfly-imports" in components/SkipToContent/skip-to-content.scss doesn't specify an extension and gulp is not sure whether it would need to import patternfly-imports.css or patternfly-imports.scss.
> chore(build): allow consumers to build patternfly.scss

- gulpfile.js
Don't compile this file for consumers. Let them default to the SCSS.
> fix(patternfly-imports): don't compile patternfly-imports

- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/Dropdown/examples/Dropdown.css
- src/patternfly/components/Dropdown/examples/Dropdown.md
fixes https://github.com/patternfly/patternfly-next/issues/2448
> fix(dropdown): fixed bottom border for split button w/ action expanded

- src/patternfly/components/DataList/data-list.scss
- src/patternfly/components/DataList/examples/DataList.md
fixes https://github.com/patternfly/patternfly-next/issues/2370
Notes:
* We removed the ability to select multiple rows in a data-list. Selecting multiple rows should be via checkbox select, not this kind of select.
* I refactored the way we draw the left border on expanded/selected rows to be able to remove `position: relative` from list items, so that I can use `position` to create a stacking context for selected rows, then only have to assign a single `z-index` to hovered rows to get the shadow stacking order correct.
* Moved the background from the data list to the items as that's needed so the shadows on a row don't show up behind adjacent rows.
* The [first commit](https://github.com/patternfly/patternfly-next/pull/2491/commits/f6f08c3714706a23b08e52a4b1ffb4eb5bb71096) has the …
> feat(datalist): added selectable/hoverable row variations

- experimental-features.js
- gatsby-browser.js
- src/patternfly/components/NotificationDrawer/examples/NotificationDrawer.md
- src/patternfly/components/NotificationDrawer/notification-drawer-basic-list.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-body.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-group-list.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-group-toggle-count.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-group-toggle-icon.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-group-toggle-title.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-group-toggle.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-group.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-header-action.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-header-status.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-header-title.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-header.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-list-item-action.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-list-item-description.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-list-item-header-icon.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-list-item-header-title.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-list-item-header.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-list-item-timestamp.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-list-item.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-list.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer.scss
fixes https://github.com/patternfly/patternfly-next/issues/1787
Given the number of overrides that would be needed to fit the accordion to this component, I opted just to create a unique element in this component. That may change in the future.
* The notification drawer should fill the height of its container.
* Unread notifications should be clickable to mark them as read.
* Expanded groups should push all of the other groups underneath it down until 1) all of the items in the group are visible, or 2) the groups underneath hit the bottom of the container at which point the list of notifications should scroll within the group. A couple of visuals showing this:
* Expanded groups have a min-height of 300px, so if the viewport shrinks in height and there isn't enough space to display the …
> feat(notification-drawer): added notification drawer component

- package.json
if we are not using 'Main' property asn entry point it should be removed, it is not a required property
In the case of the codesandbox it is causing the following error
"Error: Could not fetch dependencies, please try again in a couple seconds: Something went wrong while packaging the
dependency @patternfly/patternfly@2.43.1: ENOENT: no such file or directory, scandir '/tmp/960130286/node_modules/@patternfly/patternfly/n'"
> chore(fix): should not include "Main" property in package.json

- src/patternfly/components/ChipGroup/chip-group.scss
fixes https://github.com/patternfly/patternfly-next/issues/2524
@matthewcarleton tagging you since you made this change in https://github.com/patternfly/patternfly-next/pull/1287. Here's the commit - https://github.com/patternfly/patternfly-next/pull/1287/commits/967855b2ba3545fc5ff2758137ddf453f1c8f16d
As far as I can tell, that isn't needed as we don't apply any flex properties to children in it. If it was to make it an inline element regardless the element used for the label, we could use `inline-block` instead.
> fix(chip-group): fixed chip label overflow ellipsis

- src/patternfly/components/NotificationDrawer/notification-drawer.scss
> fix(notification-drawer): fixed flex shorthand bug resulting in 0 height

- package-lock.json
- src/patternfly/components/Button/button-text.hbs
- src/patternfly/components/Button/button.scss
- src/patternfly/components/Button/examples/Button.md
- test-a11y/pf_a11y_violations.json
closes #2507 
@mcoker @mattnolting Instead of making a new class for the text inside of the link button, I just left it as a span. In a future breaking change release I was thinking that we could remove the class around the button, and have a class around the text instead, which can control the margin-left and margin-right. This way we only need one class, rather than two.
> feat(button): add ability to have icon on left or ride side of text

- .circleci/config.yml
- .circleci/upload-docs.sh
- package-lock.json
- package.json
- src/patternfly/components/AppLauncher/examples/AppLauncher.md
- src/patternfly/components/Dropdown/dropdown-menu.hbs
- src/patternfly/components/FormControl/examples/FormControl.md
- src/patternfly/demos/CardView/card-view-demo-template-gallery.hbs
- src/site/pages/accessibility-guide.md
Closes #2580
Reporting and formatting is greatly improved in [patternfly-a11y](https://github.com/patternfly/patternfly-a11y) per @seanforyou23 's [request](https://github.com/patternfly/patternfly-next/pull/2453#pullrequestreview-329177034).
- If there are errors, console reporting gives summary at the [end that's grouped by component](https://circleci.com/gh/patternfly/patternfly-next/3209) in addition to logging each page's status as it goes along
- An HTML report gets created and saved as an artifact in CI in addition to the XML and JSON reports. It's also uploaded to https://patternfly-next-pr-2585.surge.sh/a11y-report.html
Alt image and duplicate ID errors in examples have been fixed. Some errors are still ignored per @jessiehuff 's request using `--ignore …
> feat(a11y): turn a11y checker back on

- src/patternfly/components/Card/card-head-main.hbs
- src/patternfly/components/Card/card-image.hbs
- src/patternfly/components/Card/examples/Card.md
closes #2562 
There may be a few solutions to this problem, I went with the solution of wrapping the image in its own container, because we don't know how the user will give it height/width. So even if width is added to the image in the html or the svg, it will still size proportionally down. But interested to hear what you guys think @mcoker @mattnolting
> fix(card): add wrapper to img

- src/patternfly/components/Drawer/drawer-content-body.hbs
- src/patternfly/components/Drawer/drawer-content.hbs
- src/patternfly/components/Drawer/drawer-panel.hbs
- src/patternfly/components/Drawer/drawer.hbs
- src/patternfly/components/Drawer/drawer.scss
- src/patternfly/components/Drawer/examples/Drawer.css
- src/patternfly/components/Drawer/examples/Drawer.md
- src/patternfly/components/Page/page.scss
- src/patternfly/demos/Drawer/drawer-demo-default.hbs
- src/patternfly/demos/Drawer/examples/Drawer.md
> feat(master-detail): added master-detail layout updates

- src/patternfly/components/Popover/popover.scss
fixes https://github.com/patternfly/patternfly-next/issues/2632
@mceledonia can you confirm that you don't consider this a visual breaking change?
> fix(popover): matched min/max-width so popover has consistent width

- src/patternfly/components/_all.scss
fixes https://github.com/patternfly/patternfly-next/issues/2683
```
cur=`pwd`
base="src/patternfly"
for dir in layouts components; do
path="$cur/$base/$dir"
file="_all.scss"
cd $path
find . -name "*.scss" | grep -v $file | sed -e 's/^/@import "/g' | sed -e 's/$/";/g' | sort > $file
done
```
> chore(components): updated _all.scss with missing components

- src/patternfly/components/Title/title.scss
fixes https://github.com/patternfly/patternfly-next/issues/2661
> fix(title): enabled long strings to wrap

- src/patternfly/components/Switch/switch.scss
fixes https://github.com/patternfly/patternfly-next/issues/2593
> fix(switch): moved nested element rules to the root

- package-lock.json
- src/patternfly/components/Login/login.scss
fixes https://github.com/patternfly/patternfly-next/issues/2729
> fix(login): centered login on larger viewports

- .circleci/config.yml
Add check so semantic release doesn't do a major release by accident.
> chore(build): add breaking change lint

- src/patternfly/components/BackgroundImage/background-image.hbs
fixes https://github.com/patternfly/patternfly-next/issues/2738
note - there is a bug in safari where relative paths to files in `url()` that are used in a custom property aren't evaluated correctly. To get around that, just take whatever the `url()` is in the custom property value and assign it directly to `background-image` in the CSS (you can do it in dev tools).
So for the background-image component, get the value of `--pf-c-background-image--BackgroundImage--lg` (or whatever image path you want to test) and assign that value directly to the `.pf-c-babckground-image::before` element's `background-image` property.
> fix(background-image): removed empty width attribute

- .circleci/upload-preview.js
I think this will fix releasing on master. Git tags `2.66.1`, `2.66.2`, and `2.66.3` were accidentally published, so hopefully this will fix that? I'm not sure why semantic-release is not picking those up.
> feat(nothing): try a minor version bump

- src/patternfly/components/FileUpload/examples/FileUpload.md
- src/patternfly/components/FileUpload/file-upload-message.hbs
- src/patternfly/components/FileUpload/file-upload.hbs
- src/patternfly/components/FileUpload/file-upload.scss
fixes https://github.com/patternfly/patternfly-next/issues/2797
> fix(file-upload): removed message container, added form to error example

- src/patternfly/components/ChipGroup/chip-group.scss
fixes #2765 
1. Changed max-width for `--pf-c-chip-group__label--Maxwidth` to 160px
> fix(chipgroup): modify max width for chip label

- .circleci/config.yml
Patch CircleCI so when doing this merging `master` into `v4` in Github in the future it won't trigger a release of `v4` to NPM...
Parity to https://github.com/patternfly/patternfly-react/pull/3921
> chore(v4): prevent merging in github from triggering release

- src/patternfly/components/Tooltip/tooltip.scss
Part of https://github.com/patternfly/patternfly-next/issues/2653. Breaking change, don't merge to master. 
* Reduces spacers around tooltip
> fix(tooltip): reduced space around component

- src/patternfly/components/Popover/examples/Popover.md
- src/patternfly/components/Popover/popover-header.hbs
- src/patternfly/components/Popover/popover.scss
Part of https://github.com/patternfly/patternfly-next/issues/2653. This is a breaking change so shouldn't be merged to master.
* Space around popover changed from `--pf-global--spacer--xl` to `--pf-global--spacer--md`
* Increased right padding of element displayed to the left of the close button to make more room for the close button. That padding changed from `--pf-global--spacer--xl` to `--pf-global--spacer--2xl`
* Title component size changes from `pf-m-xl` to `pf-m-md`
* Popover's `font-size` changed to `--pf-global--FontSize--sm`
* Space below title changed from `--pf-global--spacer--md` to `--pf-global--spacer--sm`
* Space above footer changed from `--pf-global--spacer--lg` to `--pf-global--spacer--md`
> fix(popover): reduced space between/around elements

- src/patternfly/components/DataList/data-list.scss
part of https://github.com/patternfly/patternfly-next/issues/2653.
This just modifies the existing compact spacing and leaves the modifier and default behavior in place.
We're also not going to update the button alignment to center if the space below exceeds 8px. 
* Changes compact data-list font-size to `--pf-global--FontSize--sm`
> fix(datalist): update compact font-size

- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Table/table.scss
part of https://github.com/patternfly/patternfly-next/issues/2653.
This just modifies the existing compact spacing and leaves the modifier and default behavior in place.
We're also not going to update the button alignment to center if the space below exceeds 8px. 
This also doesn't modify the pagination because that spacing is currently controlled by the old toolbar, and that toolbar isn't in use by anyone since it isn't a react component. So I think this spacing is something we'll need to discuss. That could potentially be a variation of the data-toolbar, but since we don't use the data-toolbar in demos yet (since it's still beta), I think it's OK to figure out how to best handle that spacing once the toolbar is promoted. I created an issue to address that in …
> fix(table): update compact spacing

- src/patternfly/components/ContextSelector/context-selector-menu-input.hbs
- src/patternfly/components/ContextSelector/context-selector-menu-search.hbs
- src/patternfly/components/ContextSelector/context-selector.scss
- src/patternfly/components/ContextSelector/examples/ContextSelector.md
- src/patternfly/components/Select/examples/Select.md
- src/patternfly/components/Select/select-checkbox-checked.hbs
- src/patternfly/components/Select/select-checkbox-groups-checked.hbs
- src/patternfly/components/Select/select-menu-input.hbs
- src/patternfly/components/Select/select-menu-search.hbs
- src/patternfly/components/Select/select.scss
closes #2438 
* changes `pf-c-context-selector__menu-input` to `pf-c-context-selector__menu-search`
* changes `pf-c-select__menu-input` to `pf-c-select__menu-search`
* changes `--pf-c-context-selector__menu-input--PaddingTop` to `--pf-c-context-selector__menu-search--PaddingTop`
* changes `--pf-c-context-selector__menu-input--PaddingRight` to `--pf-c-context-selector__menu-search--PaddingRight`
* changes `--pf-c-context-selector__menu-input--PaddingBottom` to `--pf-c-context-selector__menu-search--PaddingBottom`
* changes `--pf-c-context-selector__menu-input--PaddingLeft` to `--pf-c-context-selector__menu-search--PaddingLeft`
*  changes `--pf-c-context-selector__menu-input--BottomBorderColor` to `--pf-c-context-selector__menu-search--BorderBottomColor`
* changes …
> fix(select/contextselector): update name for menu search

- src/patternfly/components/Accordion/accordion.scss
- src/patternfly/components/Accordion/examples/Accordion.md
Part of the updates for https://github.com/patternfly/patternfly-next/issues/2653. Note this is a breaking change so we won't merge to master.
@mcarrano @lboehling @mceledonia I removed the box shadow and "no box shadow" variation. Let me know if that's OK.
* Reduces left/right padding from `--pf-global--spacer--xl` to `--pf-global--spacer--md`
* Removes the box shadow and outer padding. Removes vars:
* `--pf-c-accordion--BorderWidth`
* `--pf-c-accordion--BoxShadow`
* `--pf-c-accordion--PaddingTop`
* `--pf-c-accordion--PaddingBottom`
* Removes `.pf-m-no-box-shadow` variation
> fix(accordion): updated spacing, removed box shadow and shadow variation

- src/patternfly/components/ModalBox/examples/ModalBox.md
- src/patternfly/components/ModalBox/modal-box.scss
Part of the updates for https://github.com/patternfly/patternfly-next/issues/2653. This is a breaking change so shouldn't be merged to master.
@lboehling I also reduced the spacers used with the new "description" element. The space between the title -> description changed from sm (8px) to xs (4px), and the space between the description and body changed from lg (24px) to md (16px). Let me know if that works.
* Reduces default spacing:
* outer padding from `--pf-global--spacer--xl` to `--pf-global--spacer--lg`
* space between title and description from `--pf-global--spacer--sm` to `--pf-global--spacer--xs`
* space between description and body from `--pf-global--spacer--lg` to `--pf-global--spacer--md`
* space between title and body from `--pf-global--spacer--lg` to `--pf-global--spacer--md` …
> fix(modal): reduced spacing

- src/patternfly/components/Page/page.scss
part of https://github.com/patternfly/patternfly-next/issues/2653
* removes `--pf-c-page__main-nav--PaddingBottom`
* removes `--pf-c-page__main-breadcrumb--md--PaddingTop`
* removes `--pf-c-page__main-nav--main-breadcrumb--PaddingTop`
* reduced spacer between breadcrumb and page section that is below it to `var(--pf-global--spacer--md)`
> fix(page): reduce space between tertiary nav, breadcrumbs, main section

- src/patternfly/components/Card/card.scss
- src/patternfly/components/Card/examples/Card.md
Part of https://github.com/patternfly/patternfly-next/issues/2653.
Per @mceledonia we're going to leave this component as-is, and just make sure the documentation is clear that - Dashboards = compact, Larger content = regular
preview url is https://patternfly-pr-2759.surge.sh/documentation/core/components/card
* renames `--pf-c-card--m-compact__header--not-last-child--PaddingBottom` to `--pf-c-card--m-compact__header--not--last-child--PaddingBottom`
* renames `--pf-c-card__header--not-last-child--PaddingBottom` to `--pf-c-card__header--not--last-child--PaddingBottom`
* renames `--pf-c-card__header--not-last-child--PaddingBottom` to `--pf-c-card__header--not--last-child--PaddingBottom`
> fix(card): renamed vars, updated docs

- src/patternfly/components/FormControl/form-control.scss
fixes https://github.com/patternfly/patternfly-next/issues/2752
* Removes
*  `--pf-c-form-control--success--check--Background`
*  `--pf-c-form-control--success--Background`
*  `--pf-c-form-control__select--arrow--Background`
*  `--pf-c-form-control__select--Background`
*  `--pf-c-form-control__select--invalid--Background`
*  `--pf-c-form-control__select--success--Background`
> fix(form-control): enabled success/invalid states for readonly controls

- src/patternfly/components/Table/table.scss
fixes https://github.com/patternfly/patternfly/issues/2850
* removes `--pf-c-table__expandable-row--m-expanded--BoxShadow`
* replaces expanded content box shadow with border
> fix(table): replaced expanded content box shadow with border

- src/patternfly/components/Tooltip/tooltip.scss
fixes https://github.com/patternfly/patternfly/issues/2847
* adds medium box shadow to tooltip
> fix(tooltip): added box shadow

- src/patternfly/_variables.scss
- src/patternfly/sass-utilities/scss-variables.scss
- src/patternfly/utilities/BoxShadow/box-shadow.hbs
- src/patternfly/utilities/BoxShadow/box-shadow.scss
- src/patternfly/utilities/BoxShadow/examples/BoxShadow.css
- src/patternfly/utilities/BoxShadow/examples/BoxShadow.md
fixes https://github.com/patternfly/patternfly/issues/2845
@lboehling looks like these shadows are built from absolute black. We don't use black anywhere else in patternfly. The previous shadows were built from `$pf-color-black-1000` (`#151515`). Will these shadows work using `$pf-color-black-1000` as the color used in the `rgba()` function?
PR Preview: https://patternfly-pr-2854.surge.sh/
* Any component that uses the existing box-shadow global variables will be updated in this preview.
* Link to the box-shadow utility class examples: https://patternfly-pr-2854.surge.sh/documentation/core/utilities/boxshadow
> fix(box-shadow): update global shadows, add xl, update shadow utility

- package.json
- parseHbs.js
- src/patternfly/components/AppLauncher/app-launcher-group-title.hbs
- src/patternfly/components/AppLauncher/app-launcher-group.hbs
- src/patternfly/components/AppLauncher/app-launcher-menu-item-icon.hbs
- src/patternfly/components/AppLauncher/app-launcher-menu-item.hbs
- src/patternfly/components/AppLauncher/app-launcher-menu-wrapper.hbs
- src/patternfly/components/ClipboardCopy/examples/ClipboardCopy.md
- src/patternfly/components/DataToolbar/data-toolbar-item-separator.hbs
- src/patternfly/components/Dropdown/dropdown-menu-item-icon.hbs
- src/patternfly/components/Dropdown/dropdown-toggle-button.hbs
- src/patternfly/components/FormControl/examples/FormControl.md
- src/patternfly/components/List/examples/List.md
- src/patternfly/components/Login/examples/Login.md
- src/patternfly/components/NotificationBadge/notification-badge.hbs
- src/patternfly/components/Select/select-checkbox-checked.hbs
- src/patternfly/components/Select/select-checkbox-groups-checked.hbs
- src/patternfly/components/Select/select-checkbox-groups.hbs
- src/patternfly/components/Select/select-checkbox.hbs
- src/patternfly/components/Select/select-menu-search-input.hbs
- src/patternfly/components/Select/select-typeahead.hbs
- src/patternfly/demos/AboutModal/examples/AboutModal.md
- src/patternfly/utilities/Flex/examples/Flex.md
This adds a handlebars parser that is used to create snippet and fragment files for the VSCode pfsnippets extension. 
As a side effect, since it uses prettier to format the HTML, it will error if the resultant hbs -> HTML conversion has issues which is how I found most of the issues in the hbs files fixed in this PR.
The script is currently not run by default but invoked manually.
> feat(infrastructure): parse hbs files

- src/patternfly/components/Wizard/examples/Wizard.css
- src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly/issues/2849
* changes wizard box shadow from lg to xl. This is a visual breaking change only. No further action required to consume this change.
* removes box shadow from mobile nav toggle when expanded, replaces with border. This is a visual breaking change only. No further action required to consume this change.
* replaces desktop nav box shadow with border. This is a visual breaking change only. No further action required to consume this change.
* Removes the following variables. Any references to them will need to be removed as they are no longer used in patternfly.
* `--pf-c-wizard__nav--lg--BoxShadow`
* `--pf-c-wizard--m-in-page__nav--lg--BoxShadow`
* `--pf-c-wizard--m-in-page__nav--lg--BorderRightWidth`
* …
> fix(wizard): updates to shadows and borders

- src/patternfly/components/ModalBox/modal-box.scss
fixes https://github.com/patternfly/patternfly/issues/2848
* changes box shadow from lg to xl. This is a visual breaking change only. No further action required to consume this change.
> fix(modal): updated box shadow size

- src/patternfly/components/ClipboardCopy/clipboard-copy.scss
fixes https://github.com/patternfly/patternfly/issues/2846
* removes `--pf-c-clipboard-copy__expandable-content--BorderWidth`
* removes `--pf-c-clipboard-copy__expandable-content--BoxShadow`
* replaces expandable content box-shadow with border
> fix(clipboard-copy): replaced expandable box-shadow with border

- src/patternfly/components/ModalBox/examples/ModalBox.md
- src/patternfly/components/ModalBox/modal-box.scss
- src/patternfly/demos/Modal/examples/Modal.md
- src/patternfly/demos/Table/examples/Table.md
fixes https://github.com/patternfly/patternfly/issues/2620
* Buttons in the modal footer are now left-aligned by default. No further updates are needed to consume this change.
* `.pf-m-align-left` has been removed as it is no longer needed. It can be removed from any modal footer elements it is currently applied to.
* Removed `--pf-c-modal-box__footer__c-button--first-of-type--MarginLeft`. Please remove any instances of it in your application.
> fix(modal): left aligned footer actions, removed pf-m-align-left

- src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly/issues/2240
* Changes `--pf-c-page--BackgroundColor` from `--pf-global--BackgroundColor--dark-100` to `--pf-global--BackgroundColor--light-300`. This is just a visual change, no code updates are needed to consume it.
* Adds a background-color of `--pf-global--BackgroundColor--dark-100` to `.pf-c-page__header`. This is just a visual change, no code updates are needed to consume it.
> fix(page): updated page and page header background colors

- src/patternfly/components/Table/table.scss
fixes #2325 
1. Changes `word-break` to `overflow-wrap`
> fix(table-td-wrapping): added to overflow-wrap

- src/patternfly/components/Card/card.scss
- src/patternfly/components/Card/examples/Card.md
fixes https://github.com/patternfly/patternfly/issues/2852
@mcarrano @lboehling I named this `.pf-m-border`. Is that OK or is there a more meaningful description for the variation name in case, for example, in the future we decide to style this variation differently in a way that doesn't involve a border?
> feat(card): added flat variation

- src/patternfly/components/EmptyState/empty-state-content.hbs
- src/patternfly/components/EmptyState/empty-state.hbs
- src/patternfly/components/EmptyState/empty-state.scss
- src/patternfly/components/EmptyState/examples/EmptyState.md
fixes https://github.com/patternfly/patternfly/issues/2568
fixes https://github.com/patternfly/patternfly/issues/2857
* Introduces a new element `.pf-c-empty-state__content` that wraps the contents of the empty state content. The `max-width` used for the size variations applies to `.pf-c-empty-state__content` instead of `.pf-c-empty-state`, and `.pf-c-empty-state__content` is centered horizontally and vertically in its parent, reducing the need for using a `.pf-l-bullseye` layout to center empty state content. If you're using the bullseye layout to center the empty state horizontally, you can remove that, though there is likely no harm in continuing to use it.
* Adds `--pf-c-empty-state__content--MaxWidth` that is overridden with `.pf-m-sm` and `.pf-m-lg` via …
> fix(empty-state): center content, fix vars, adjust secondary margin

- src/patternfly/components/Drawer/drawer.scss
- src/patternfly/components/Drawer/examples/Drawer.md
fixes https://github.com/patternfly/patternfly/issues/2853
@lboehling from the issue
> add variation that replaces shadow with grey border for use on white backgrounds when drawer expands inline with page content.
The non-inline drawers have a shadow by default and can have a border instead with use of a `pf-m-border` variation. You can see that here https://www.patternfly.org/v4/documentation/core/components/drawer
Is that already done, or did you want a different update?
> small left shadow to be used on drawer that expand inline with content that is placed on a grey background
When the panel displays inline with the content, the drawer changed the shadow to a border. In this PR, I disabled that behavior, so that the panel has a shadow by default, and you can set a border instead by …
> fix(drawer): removed m-border, enabled m-no-border on inline/static

- src/patternfly/components/Button/button-text.hbs
- src/patternfly/components/Button/button.scss
- src/patternfly/components/Button/examples/Button.md
- src/patternfly/components/InlineEdit/inline-edit-dl.hbs
- src/patternfly/components/Table/examples/Table.md
- src/patternfly/demos/Table/table-compound-expansion-table.hbs
closes #2574 
* Adds the modifiers `pf-m-start` and `pf-m-end` to position `pf-c-button__icon` in the button component depending on whether it comes before or after text. We made this change so that we could safely position the icon before or after text, without needing to introduce a new class that wraps the text.
* Removes `  --pf-c-button__icon--MarginRight` and `--pf-c-button__text--icon--MarginLeft`. These are no longer in use, and to modify the right margin on an icon at the beginning of the button, use `--pf-c-button__icon--m-start--MarginRight` now and `--pf-c-button__icon--m-end--MarginLeft` to modify the left margin of an icon at the end of a button.
* Removes the `.pf-c-button__text` element as it is no longer necessary. Any instance of this element or styling using this …
> fix(button): add modifiers to position icon in button

- src/patternfly/components/DataList/data-list.scss
fixes https://github.com/patternfly/patternfly/issues/2851
* Replaces the box shadow on the expandable content element with a bottom border
* Removes `--pf-c-data-list__expandable-content--BoxShadow`,  `--pf-c-data-list__item--before--Height`, and `--pf-c-data-list__item-item--before--Height`. Any instances of these variables in your application should be removed as they are no longer used.
* Replaces `--pf-c-data-list__item--m-expanded__expandable-content--BorderTopWidth` with `--pf-c-data-list__expandable-content--BorderTopWidth`. Any instances of the old variable should be updated to the new variable.
> fix(data-list): changed expanded content shadow to a border

- src/patternfly/components/Page/examples/Page.md
- src/patternfly/components/Page/page-header.hbs
- src/patternfly/components/Page/page-main.hbs
Removes "required" from accessibility attributes `role="banner"` and `role="main"` for Page component documentation.
> feat(page doc): removes "required" for issue 2651

- src/patternfly/components/Radio/radio.scss
fixes https://github.com/patternfly/patternfly/issues/2911
Adds a `1px` right margin to a radio component's input element when it comes after the label. This is a visual change only and no further updates are needed to consume this change.
> fix(radio): fixed issue where radio is cut off when comes after label

- src/patternfly/components/AppLauncher/app-launcher-menu-item-external-icon.hbs
- src/patternfly/components/AppLauncher/examples/AppLauncher.md
Fixes https://github.com/patternfly/patternfly/issues/2523
Updated `.pf-c-app-launcher__menu-item-external-icon` so that it is a <span> that wraps the icon used inside instead of applying it directly to the icon.
Moves the class `.pf-c-app-launcher__menu-item-external-icon` from the external link icon itself to a `<span>` that wraps the external link icon. Any instances of the external link icon should be wrapped in a `<span>` and the `.pf-c-app-launcher__menu-item-external-icon` class should be moved from the icon to the `<span>`.
> fix(app launcher): applied external link icon class to icon wrapper

- src/patternfly/components/DataList/data-list.scss
closes #2029
* Removes `--pf-c-data-list__item-action--not-last-child--MarginBottom` all instances of it should be removed from your application.
* Removes `flex-wrap: wrap` from the data list actions. When the list of buttons get too long you should use the overflow menu to hide buttons, instead of flex-wrap, as we don't support this anymore.
> fix(datalist): remove flex wrap for action button

- src/patternfly/components/Wizard/examples/Wizard.md
- src/patternfly/components/Wizard/wizard.scss
closes #1715 
* Moves `pf-m-no-padding` from `.pf-c-wizard__main` to `.pf-c-wizard__main-body` . The same styling will occur to the wizard main body. If you want to remove padding in the wizard main body you should add `pf-m-no-padding` to `.pf-c-wizard__main-body` now.
> fix(wizard): move modifier to body

- src/patternfly/components/Tabs/__tabs-item.hbs
- src/patternfly/components/Tabs/examples/Tabs.md
- src/patternfly/components/Tabs/tabs-button.hbs
- src/patternfly/components/Tabs/tabs-link.hbs
- src/patternfly/components/Tabs/tabs.scss
closes #2594 
* Renames the class `pf-c-tabs__button` to be `pf-c-tabs__link`. Any instances of the old class should be updated to the new class.
* Updates any tabs CSS variable with a reference to the BEM element `__button` to `__link`. Any references to tabs variables with `__button` should be replaced with `__link`.
E.g. `--pf-c-tabs--m-box__button--BackgroundColor` becomes `--pf-c-tabs--m-box__link--BackgroundColor`
> fix(tabs): Update class name for tabs button to be tabs link

- src/patternfly/_variables.scss
- src/patternfly/components/Nav/examples/Nav.css
- src/patternfly/components/Nav/examples/Nav.md
- src/patternfly/components/Nav/nav-link.hbs
- src/patternfly/components/Nav/nav-toggle-icon.hbs
- src/patternfly/components/Nav/nav.scss
- src/patternfly/components/Page/page.scss
- src/patternfly/demos/Page/examples/Page.md
- src/patternfly/demos/Page/page-demo-default.hbs
- src/patternfly/demos/Page/page-demo-expandable-nav.hbs
- src/patternfly/sass-utilities/scss-variables.scss
closes #1849 
closes #2196
closes #2650 
**Nav component preview**
https://patternfly-pr-2884.surge.sh/documentation/core/demos/page
The nav component's css was refactored, see the file list for details on what changed 
https://github.com/patternfly/patternfly/pull/2884/files
This PR:
1. Applies stylistic updates to css variables rather than redefining component elements.
2. Updates `--pf-c-nav__c-nested-component--Property` to `--pf-c-nav--c-nested-component--Property`. Any instances of the old variable should be updated to the new variable.
3. Updates visual style of navigation only, no HTML updates are necessary.
> style(vertical-nav): refactored css structure

- src/patternfly/components/Breadcrumb/breadcrumb.scss
- src/patternfly/components/Breadcrumb/examples/Breadcrumb.md
- src/patternfly/demos/Page/page-template-breadcrumb.hbs
fixes https://github.com/patternfly/patternfly/issues/2915
@mcarrano curious what you think of this. Here is the previous behavior:
A breadcrumb item that breaks to multiple lines has it's arrow vertically centered to the right of the item link.
An item that is a very long string won't break and just overflows whatever it is inside of.
----
And here is the updated behavior. Is this preferred?
A side effect of that is that when the container is wide enough to fit the item, but not the arrow, the arrow will break to the next line separately like this
This PR changes the visual appearance of breadcrumbs when they break to multiple lines.
* The text will now break if there is a long string in an item link that is wider than the viewport
* The divider is displayed before the link text, instead …
> fix(breadcrumb): add word-break, display link and icon inline, move divider

- src/patternfly/components/OptionsMenu/options-menu.scss
fixes https://github.com/patternfly/patternfly/issues/2905
Adds a `color` declaration for `.pf-c-options-menu__menu-item` items so that the color will always match the default text color (`--pf-global--Color--100)`. Since this wasn't defined previously, if applications were using `<a>` elements as menu items, the item color would have been the default blue link color. This is a visual change only, no further updates are needed to consume this change.
> fix(optionsmenu): added color declaration to menu items

- src/patternfly/components/Select/examples/Select.md
- src/patternfly/components/Select/select-toggle-button.hbs
- src/patternfly/components/Select/select-toggle-typeahead.hbs
Adds a disabled typeahead example to the Select Component.
> feat(example): add select-disabled-typeahead-example.hbs

- src/patternfly/components/Form/examples/Form.md
- src/patternfly/components/Form/form-helper-text-icon.hbs
- src/patternfly/components/Form/form.scss
- src/patternfly/components/Login/examples/Login.md
- src/patternfly/components/Login/login.scss
fixes https://github.com/patternfly/patternfly/issues/1959
This PR moves the form helper text icon feature from the login component back into the form component.
* The `.pf-c-form__helper-text-icon` styles have moved from the login component stylesheet to the form component stylesheet
* Removes the following variables from the login component and replaces the variables in the form component. If you're overriding any of these using the `.pf-c-login` component selector, you will need to update the selector to `.pf-c-form`.
* `--pf-c-login__main-body--c-form__helper-text-icon--FontSize` has been renamed to `--pf-c-form__helper-text-icon--FontSize`
* `--pf-c-login__main-body--c-form__helper-text-icon--MarginRight` has been renamed to `--pf-c-form__helper-text-icon--MarginRight`
> fix(form): moved helper text icon from login to form component

- src/patternfly/sass-utilities/colors.scss
fixes https://github.com/patternfly/patternfly/issues/2939
This PR changes `$pf-color-green-50` to `#f3faf2`. This is a visual change only. No further updates are needed to consume this change.
> fix(global vars): updated pf-color-green-50

- src/patternfly/components/Chip/chip.scss
- src/patternfly/components/Chip/examples/Chip.css
- src/patternfly/components/Chip/examples/Chip.md
- src/patternfly/components/ChipGroup/examples/ChipGroup.md
closes #2657 
* The read-only modifier: `.pf-m-read-only` was removed as you can achieve the same result with the plain chip. With this the following variables were removed, all instances of them should be removed from your application:
* `--pf-c-chip--m-read-only--PaddingTop`
* `--pf-c-chip--m-read-only--PaddingRight`
*  `--pf-c-chip--m-read-only--PaddingBottom`
* The following variables were removed from the overflow chip component, all instances of them should be removed from your application:
* `--pf-c-chip--m-overflow--BackgroundColor`
* `--pf-c-chip--m-overflow--PaddingLeft`
* ` --pf-c-chip--m-overflow--BorderWidth`
* `--pf-c-chip--m-overflow--c-button--BorderRadius`
* `--pf-c-chip--m-overflow--c-button--BorderWidth`
* ` --pf-c-chip--m-overflow--c-button--PaddingLeft`
* …
> fix(chip): refactor styles

- src/patternfly/components/InputGroup/input-group.scss
fixes https://github.com/patternfly/patternfly/issues/2298
This PR removes button component styles from the input group. Patternfly now recommends using the `.pf-m-control` variation of the button component in the input group.
The following variables have been removed and any reference to them should be removed as they are no longer used in patternfly.
* `--pf-c-input-group--BorderRadius`
* `--pf-c-input-group--c-button--BorderRadius`
> fix(inputgroup): remove legacy button styles

- src/patternfly/components/Wizard/examples/Wizard.md
- src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly/issues/1737
This PR changes the wizard nav width (`--pf-c-wizard__nav--lg--Width`) from 300px to 250px on desktop. A 250px width was previously achieved using the `.pf-m-compact-nav` modifier, however since the nav width is now 250px by default, the `.pf-m-compact-nav` modifier has been removed and any reference to that class should be removed as it is no longer in patternfly.
The following variables have also been removed and any reference to them should be removed as they are no longer used in patternfly.
* `--pf-c-wizard--m-compact-nav__nav--lg--Width`
* `--pf-c-wizard--m-in-page__nav--lg--Width`
> fix(wizard): made desktop nav 250px, remove compact modifier

- src/patternfly/components/DataList/data-list.scss
- src/patternfly/components/Nav/nav.scss
- src/patternfly/components/Page/page.scss
- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Table/table.scss
- src/patternfly/components/Tabs/tabs.scss
- src/patternfly/components/Toolbar/toolbar.scss
- src/patternfly/components/Wizard/wizard.scss
- src/patternfly/demos/Table/table-simple-table.hbs
- src/patternfly/layouts/Gallery/gallery.scss
- src/patternfly/layouts/Grid/grid.scss
- src/patternfly/layouts/Level/level.scss
- src/patternfly/layouts/Split/split.scss
- src/patternfly/layouts/Stack/stack.scss
fixes https://github.com/patternfly/patternfly/issues/2907
Testing notes:
The components that changed: data-list, nav, page, table, tabs (removed the top/bottom padding change that happened at 768px), wizard. We just need to test the spacing in these components in general, but specifically to make sure the horizontal spacing aligns with the overall page chrome so that when they're used in a page main section, their horizontal padding aligns with the page chrome. For example...
desktop table
mobile table
This PR changes the CSS breakpoint at which the page component's sidebar shows and hides. This used to be defined at `$pf-global--breakpoint--md` (768px) and is now defined at `$pf-global--breakpoint--xl` (1200px). This change results in a wider main content area of the page, so this may …
> fix(global): hid vertical nav at 1200px, updated component spacing

- src/patternfly/components/AppLauncher/app-launcher.scss
- src/patternfly/components/ContextSelector/context-selector.scss
- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/ModalBox/modal-box.scss
- src/patternfly/components/OptionsMenu/options-menu.scss
- src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly/issues/2019
This PR removes a transparent border from a handful of components that was used to serve as a border in Windows high contrast mode. We no longer support specific styling for high contrast mode.
This PR removes the following variables. Any references to them should be removed as they are no longer used in patternfly:
* `--pf-c-app-launcher__menu--BorderWidth`
* `--pf-c-context-selector__menu--BorderWidth`
* `--pf-c-dropdown__menu--BorderWidth`
* `--pf-c-modal-box--BorderColor`
* `--pf-c-modal-box--BorderSize`
* `--pf-c-options-menu__menu--BorderWidth`
* `--pf-c-select__menu--BorderWidth`
> fix(components): removed transparent borders

- src/patternfly/components/ModalBox/examples/ModalBox.md
- src/patternfly/components/ModalBox/modal-box-header.hbs
- src/patternfly/components/ModalBox/modal-box-title.hbs
- src/patternfly/components/ModalBox/modal-box.scss
- src/patternfly/demos/Modal/examples/Modal.md
- src/patternfly/demos/Table/examples/Table.md
fixes https://github.com/patternfly/patternfly/issues/2967
@tlabaj I think it would be more consistent for the modal component title to be it's own element of the modal component (ie, `pf-c-modal-box__title`), instead of using the title component. It looks like the react modal title is built in the component from a `title` prop on the component. How do you feel about removing the dependency on the title component in the modal, and wrapping the title in a new element (`pf-c-modal-box__title`) instead? Would there be much (or any) impact to the consumer? If that's OK I will update this PR.
This PR moves the outer padding on the modal from the `.pf-c-modal-box` container to the modal box elements that are children of the modal. To better achieve this spacing, we have dropped the use of the …
> fix(modal): added header, moved padding from container to elements

- src/patternfly/components/Nav/examples/Nav.md
- src/patternfly/components/Nav/nav.hbs
- src/patternfly/components/Nav/nav.scss
- src/patternfly/components/Page/page.scss
- src/patternfly/components/Tabs/examples/Tabs.md
- src/patternfly/demos/DataList/data-list-main-section-nav.hbs
- src/patternfly/demos/Page/examples/Page.md
- src/patternfly/demos/Table/table-main-section-nav.hbs
Closes #1839
Closes #1848
Closes #2435
This PR modifies the nav behavior to display inline with navigational elements rather than being absolutely positioned above them.  
The following classes have been removed. Any reference to them should be removed as they are no longer used in patternfly:
* `.pf-m-start`
* `.pf-m-end`
The following variables have been removed. Any reference to them should be removed as they are no longer used in patternfly:
* `--pf-c-nav__scroll-button--Display`
* `--pf-c-nav__scroll-button--Visibility`
* `--pf-c-nav__scroll-button--ZIndex`
* `--pf-c-nav__scroll-button--Height`
* `--pf-c-nav__scroll-button--lg--Height`
* `--pf-c-nav__scroll-button--PaddingRight`
* `--pf-c-nav__scroll-button--PaddingLeft`
* `--pf-c-nav__scroll-button--nth-of-type-1--BoxShadow`
* …
> style(nav-scroll): updated nav buttons to inline

- src/patternfly/components/Content/content.scss
closes #1844 #2096 #1842
* If you are using `pf-c-content` in your application you may need to check to see if this change impacts the UI. The margin-bottom may now be removed if using h1-h6, and the margin-bottom may now be removed if using `<ol>` and `<ul>`.
* Removes the margin-bottom from `h1-h6` if its the last child. 
* Removes the margin-top from `<ol>` and `<ul>` if its the first-child.
> fix(content): margin should not be on first-child or last-child

- src/patternfly/components/Label/examples/Label.css
- src/patternfly/components/Label/examples/Label.md
- src/patternfly/components/Label/label-content.hbs
- src/patternfly/components/Label/label-icon.hbs
- src/patternfly/components/Label/label-text.hbs
- src/patternfly/components/Label/label.hbs
- src/patternfly/components/Label/label.scss
fixes https://github.com/patternfly/patternfly/issues/2656
The label component has been redesigned and refactored. This PR introduces breaking visual and code changes. At a minimum to update to the new label component, the `.pf-c-label` component now requires `.pf-c-label__text` element to wrap the label text. And the label will be grey by default now, so to achieve the previous blue styling, the closest match visually would be using the new `.pf-m-blue` modifier. However, reference the new component documentation and the PR changeset for more info regarding the changes https://github.com/patternfly/patternfly/pull/2943/files
> feat(label): refactored label component

- src/patternfly/components/ModalBox/modal-box.scss
- src/patternfly/components/Wizard/examples/Wizard.md
- src/patternfly/components/Wizard/wizard.scss
- src/patternfly/demos/Modal/examples/Modal.md
- src/patternfly/demos/Table/examples/Table.md
- src/patternfly/demos/Wizard/examples/Wizard.md
fixes https://github.com/patternfly/patternfly/issues/2046
@tlabaj @mcarrano this is pretty straight forward except for one thing. The wizard when used in a modal needs a defined height, otherwise the height will be defined by the wizard contents and will change as a user progresses through the wizard. There are a couple of ways we can do this.
1) Assign a height to the wizard for use when it's in a modal, then modify that height when the wizard is used in context of the page (the "in page" variation). This seems to work just fine and allows us to define a specific height for the wizard (that the user can override), but it means that we need to maintain separate variations of the wizard for use in the page and in a modal. The user impact is that the user has to specify the modal width …
> fix(wizard): reworked wizard so it can be used in modal

- src/patternfly/components/Table/examples/Table.css
- src/patternfly/components/Table/examples/Table.md
- src/patternfly/components/Table/table-button-content.hbs
- src/patternfly/components/Table/table-button.hbs
- src/patternfly/components/Table/table-cell-content.hbs
- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Table/table-sort-indicator.hbs
- src/patternfly/components/Table/table-td.hbs
- src/patternfly/components/Table/table-text.hbs
- src/patternfly/components/Table/table-th.hbs
- src/patternfly/components/Table/table.scss
- src/patternfly/demos/Table/table-compound-expansion-table.hbs
**Preview:** https://patternfly-pr-2965.surge.sh/documentation/core/components/table
fixes #2869 
fixes #2265 
fixes #2261
fixes #2205 
fixes #1948 
- removed `.pf-m-expanded` from compound expansion table example.
This PR fixes multiple table issues. 
* Adds dedicated table button `.pf-c-table__button`: this button relies on `::after` pseudo element to define clickable area, as previous height hacks cause cross browser bugs. `focus-ring` is disabled on this button and applied to the parent table cell.
* Hover, focus, active and selected states `.pf-c-table__sort` and `.pf-c-table__compound-expansion-toggle`: updates border discrepancies using `::before` and `::after` pseudos and negative offsets.
* Adds text wrapping control `.pf-m-truncate`, `.pf-m-wrap`, `.pf-m-no-wrap`, …
> fix(table-row-height): fixed borders, row height, focus

- src/patternfly/components/Nav/nav.scss
fixes https://github.com/patternfly/patternfly/issues/3005
Adds `display: flex; flex-direction: column;` to `.pf-c-nav__list`. This is a CSS only change and does not require any further updates to consume. However if applications have custom CSS for `.pf-c-nav__list`, the spacing and behavior may change with this update.
> fix(nav): made nav__list a flex parent

- src/patternfly/components/Card/card-head-main.hbs
- src/patternfly/components/Card/card-head.hbs
- src/patternfly/components/Card/card-header-main.hbs
- src/patternfly/components/Card/card-header.hbs
- src/patternfly/components/Card/card.scss
- src/patternfly/components/Card/examples/Card.md
- src/patternfly/demos/CardView/card-view-demo-template-gallery.hbs
- src/patternfly/demos/MasterDetail/master-detail-card-view.hbs
fixes https://github.com/patternfly/patternfly/issues/3034
This PR renames the `.pf-c-card__header` element to `.pf-c-card__title`, and removes the dependency of `.pf-c-title` from `.pf-c-card__title`. And that allows us to rename `.pf-c-card__head` to `.pf-c-card__header`.
The following elements' classes have changed. Any reference to the old class should be updated to reference the new class instead.
* `.pf-c-card__header` has been renamed to `.pf-c-card__title`.  Also `.pf-c-title` and the title size modifiers should be removed from `.pf-c-card__title`.
* `.pf-c-card__head` has been renamed to `.pf-c-card__header`. 
* `.pf-c-card__head-main` has been renamed to `.pf-c-card__header-main`.
The following variables were renamed. Any reference to the old variable name should be updated to …
> fix(card): moved __header to __title, __head to __header

- src/patternfly/components/Backdrop/backdrop.scss
fixes https://github.com/patternfly/patternfly/issues/3003
This PR removes the blur from the backdrop component. This is a visual change only and no further updates are needed to consume this change.
The variable `--pf-c-backdrop--BackdropFilter` was removed. Any reference to it should be removed as it is no longer used in patternfly.
The variable `--pf-c-backdrop--Color` was renamed to `--pf-c-backdrop--BackgroundColor`. Any reference to the old variable name should be updated to reference the new variable name.
> fix(backdrop): removed blur, renamed var

- src/patternfly/components/AppLauncher/app-launcher.scss
closes #2617 
* Removes the following variables. All instances of them should be removed from your application:
* `--pf-c-app-launcher__group--PaddingTop`
* `--pf-c-app-launcher__group--first-child--PaddingTop`
> fix(applauncher): clean up variables

- src/patternfly/components/OptionsMenu/options-menu.scss
closes #1971
* Renames the following variables:
* `--pf-c-options-menu__toggle--Background` to `--pf-c-options-menu__toggle--BackgroundColor`
* `--pf-c-options-menu__toggle-button--Background` to `--pf-c-options-menu__toggle-button--BackgroundColor`
* `--pf-c-options-menu__menu-item--Background` to `--pf-c-options-menu__menu-item--BackgroundColor`
> fix(optionsmenu): clean up vars

- src/patternfly/components/Wizard/wizard.scss
closes #2217 
* Removes `--pf-c-wizard__toggle-icon--MarginTop` all instances should be removed from your application.
> fix(wizard): cleanup vars

- src/patternfly/components/Tabs/examples/Tabs.css
- src/patternfly/components/Tabs/examples/Tabs.md
- src/patternfly/components/Tabs/tabs.scss
Fixes `.pf-c-tabs.pf-m-box.pf-m-vertical .pf-c-tabs__item:first-child.pf-m-current` border top
and `.pf-c-tabs.pf-m-vertical` right border position
> fix(tabs-box-border-top): fixed box vertical border top

- src/patternfly/components/Pagination/examples/Pagination.md
- src/patternfly/components/Pagination/pagination-options-menu.hbs
- src/patternfly/components/Pagination/pagination.scss
fixes https://github.com/patternfly/patternfly/issues/3010
This PR removes the `.pf-c-pagination__menu-text` element from the pagination options menu items. The options menu item text should just be normal text.
Any use of the class `.pf-c-pagination__menu-text` or the vars `--pf-c-pagination__menu-text--PaddingLeft`, `--pf-c-pagination__menu-text--FontSize` and `--pf-c-pagination__menu-text--Color` should be removed as they are no longer used in patternfly.
> fix(pagination): removed options menu per page text styling

- src/patternfly/components/DataList/data-list.scss
closes #2616, #2305
TBD
@mcoker do you know what causes `pf-c-data-list__item .pf-m-selectable` to show the border-bottom? I see it on master, but I don't see it on v4 , do you know if it was removed purposely?
v4:
master:
> fix(datalist): clean up vars

- src/patternfly/components/Button/button.scss
- src/patternfly/components/Button/examples/Button.md
- src/patternfly/components/FileUpload/file-upload.scss
- src/patternfly/components/FormControl/form-control.scss
fixes https://github.com/patternfly/patternfly/issues/2701
This PR updates the visuals of the control button disabled state.
* The following variables were removed. All references to them should be removed as they are no longer used in patternfly.
* `--pf-c-button--m-control--disabled--after--BorderTopColor`
* `--pf-c-button--m-control--disabled--after--BorderRightColor`
* `--pf-c-button--m-control--disabled--after--BorderBottomColor`
* `--pf-c-button--m-control--disabled--after--BorderLeftColor`
* `--pf-c-form-control--readonly--focus--BackgroundColor` was renamed to `--pf-c-form-control--readonly--BackgroundColor`. All references to the old variable name should be updated to reference the new variable name instead.
* `--pf-c-form-control--readonly--focus--PaddingBottom` was removed. Any …
> fix(button): updated control variation disabled state

- src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly/issues/2615
The CSS var `--pf-c-page__header-sidebar-toggle__c-button--xl--MarginLeft` was removed. All instances of this should be removed as it is no longer used in patternfly.
> fix(page): removed unnecessary vars

- src/patternfly/components/ModalBox/examples/ModalBox.md
- src/patternfly/components/ModalBox/modal-box-header.hbs
- src/patternfly/components/ModalBox/modal-box.scss
fixes https://github.com/patternfly/patternfly/issues/3081
This PR adds a new element `header.pf-c-modal-box__header` that wraps the `.pf-c-modal-box__title` and `.pf-c-modal-box__description` elements. All instances of `.pf-c-modal-box__title` and `.pf-c-modal-box__description` should be wrapped in `.pf-c-modal-box__header`
The following variables were renamed. Any reference to the old name should be updated to reference the new name.
* `--pf-c-modal-box__title--PaddingTop` renamed to `--pf-c-modal-box__header--PaddingTop`
* `--pf-c-modal-box__title--PaddingRight` renamed to `--pf-c-modal-box__header--PaddingRight`
* `--pf-c-modal-box__title--PaddingLeft` renamed to `--pf-c-modal-box__header--PaddingLeft`
* `--pf-c-modal-box__title--last-child--PaddingBottom` renamed to …
> fix(modal-box): added __header element

- src/patternfly/components/DataList/data-list.scss
fixes https://github.com/patternfly/patternfly/issues/3063
The way shadows should work is the selected row has a top/bottom shadow by default, and if you hover/focus over a selectable row, that row should also have a top/bottom shadow, and if you hover/focus over a selectable row that is adjacent to a selected row, the hover shadow should take precedence over the selected row's shadow.
TBD
> fix(datalist): fix shadows on selected rows

- src/patternfly/components/Table/examples/Table.css
- src/patternfly/components/Table/table.scss
Found an inconsistency in truncation string length because `--pf-c-table__text` and `--pf-c-table__sort--MinWidth` don't factor in changing padding left/right values. 
Also, @redallen found an unused variable: `--pf-c-table--cell--Width: var(--pf-c-table--thead--cell--Width);`
The following variables have been removed. Any reference to them should be removed as they are no longer used in patternfly:
* `--pf-c-table--thead--cell--Width`
> fix(table-vars): updated min-width vars, removed unused

- src/patternfly/components/EmptyState/empty-state.scss
fixes https://github.com/patternfly/patternfly/issues/3085
This PR removes `--pf-c-empty-state--Padding`. Any reference to that variable should be removed as it is no longer used.
To change the empty state outer padding, use `--pf-c-empty-state--PaddingTop`, `--pf-c-empty-state--PaddingRight`, `--pf-c-empty-state--PaddingBottom`, and `--pf-c-empty-state--PaddingLeft` instead.
> fix(emptystate): split single padding var to top/right/bottom/left

- src/patternfly/components/Tabs/examples/Tabs.md
- src/patternfly/components/Tabs/tabs-link.hbs
- src/patternfly/components/Tabs/tabs.scss
closes #2920 
relates to #2893 
This PR updates tab `:focus` and `:active` states to reflect hover state. It also resizes the tab `::after` pseudo element to not consume the entirety of the button. 
The following variables have been removed. Any reference to them should be removed as they are no longer used in patternfly:
* `--pf-c-tabs--before--BorderStyle`
* `--pf-c-tabs__link--before--BorderStyle`
* `--pf-c-tabs__link--after--BorderStyle`
* `--pf-c-tabs__scroll-button--BorderStyle`
* `--pf-c-tabs__link--child--MarginRight`
* `--pf-c-tabs--m-vertical--m-box__link--after--Top`
> Fix tab focus 2

- src/patternfly/components/Page/examples/Page.md
- src/patternfly/components/Page/page.scss
- src/patternfly/demos/Page/page-template-header-tools-elements.hbs
fixes https://github.com/patternfly/patternfly/issues/3108
This PR moves the `.pf-m-selected` class in the masthead toolbar from the `.pf-c-button` component to the `.pf-c-page__header-tools-item` element. Any instance of `.pf-m-selected` on a `.pf-c-button` in the masthead should be moved to its containing `.pf-c-page__header-tools-item` element.
> fix(page): move masthead selected button mod to header-tools-item

- src/patternfly/components/ChipGroup/chip-group.scss
fixes https://github.com/patternfly/patternfly/issues/3083
This stems from `line-height: 1` on the chip-group__list-item elements, which was needed so that those elements are the same height in Firefox and other browsers (they're 0.5px taller in FF for some reason). I tried to figure out the root cause of that and couldn't track it down, though it seems to have something to do with font rendering. Changing the font family to `sans-serif` fixes that 0.5px discrepancy.
Making the list items a flex parent also solves it, which is better than setting the `line-height`,  so I did that and removed the `line-height`.
> fix(chipgroup): fix cut off chip text

- src/patternfly/components/Table/examples/Table.md
- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Table/table.scss
This PR moves `::before` borders to `::after` borders to prevent the following hidden label (`[data-label]::before`)
This PR updates `.pf-c-table` borders to use `::after` pseudos to draw borders, rather than `::before` pseudos. 
The following variables have been removed. Any reference to them should be removed as they are no longer used in patternfly:
* `--pf-c-table__expandable-row--before--BorderRightWidth`
* `--pf-c-table-cell-th--responsive--PaddingTop`
The following variables have been renamed. Any reference to the old variable should be updated to use the new variable:
* `--pf-c-table-tbody--responsive—BorderWidth` has changed to `--pf-c-table-tbody--responsive--border-width—base`
* `--pf-c-table--tbody--after—BorderWidth` has changed to …
> fix(table-grid): move borders to ::after

- package.json
Now that we've committed to v4 this will prevent v3 from publishing directly to `latest`.
> chore(npm): publish v3 branch to v3 tag

- src/patternfly/components/Alert/alert.scss
- src/patternfly/components/Alert/examples/Alert.md
- src/patternfly/components/NotificationDrawer/examples/NotificationDrawer.md
- src/patternfly/components/NotificationDrawer/notification-drawer-basic-list.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer.scss
- src/patternfly/sass-utilities/mixins.scss
fixes https://github.com/patternfly/patternfly/issues/3144
This PR enables long strings when used as title of a notification in the notification drawer to wrap:
----
It also enables the same behavior in the alert component for consistency:
----
And the way notification drawer group/section title/toggle wraps currently isn't ideal, so I updated it to truncate when the title text exceeds the width of the toggle (to be consistent with the accordion) - @mcarrano wdyt of this?
----
Alternatively, we could allow that text to wrap - it would look like this.
> fix(notificationdrawer/alert): improved title wrapping

- src/patternfly/components/NotificationDrawer/notification-drawer.scss
fixes https://github.com/patternfly/patternfly/issues/3148
This was a problem any time the last item in a group was unread. The problem is with this `calc()`:
https://github.com/patternfly/patternfly/blob/555bd56d753317b9ee72e7d944d0289548c161d5/src/patternfly/components/NotificationDrawer/notification-drawer.scss#L30
`--pf-c-notification-drawer__list-item--BorderBottomWidth` is normally a negative value, but reset on the item `.pf-c-notification-drawer__list-item:last-child` to be `0` here:
https://github.com/patternfly/patternfly/blob/555bd56d753317b9ee72e7d944d0289548c161d5/src/patternfly/components/NotificationDrawer/notification-drawer.scss#L259-L262
The calc fails with `calc(0 * -1)` though, so the declaration doesn't do anything, leaving the negative `bottom` position.
Another way …
> fix(notificationdrawer): fixed last item's color line position

- src/patternfly/components/Drawer/drawer.scss
- src/patternfly/sass-utilities/mixins.scss
fixes #3129 
closes #2779 
Added `pf-animate-remove-tab-focus` which sets a delay on css properties to hide element from tab focus.
> fix(drawer-focus): added tab focus fix

- UPGRADE-GUIDE.md
Closes #3194 
This PR updates the Upgrade Guide to reflect RedHatDisplay font removal being reverted in https://github.com/patternfly/patternfly/pull/3188
> fix(docs): updated upgrade guide RedHatDisplay text

- build/gulp/copy.js
This is how patternfly-org consumes the UPGRADE-GUIDE.md.
I'll just copy it over manually for now.
> fix(build): copy UPGRADE-GUIDE.md

- RELEASE-NOTES.md
`s/(@patternfly/patternfly@v?(.*))/[$1](https://www.npmjs.com/package/@patternfly/patternfly/v/$2)/gi`
> fix(release-notes): updated release versions to npm links

- src/patternfly/components/Breadcrumb/breadcrumb.scss
- src/patternfly/components/Breadcrumb/examples/Breadcrumb.md
Towards patternfly/patternfly-react#4422
> fix(breadcrumb): always use divider and hide first

- src/patternfly/components/Alert/alert-title.hbs
- src/patternfly/components/Alert/examples/Alert.md
- src/patternfly/demos/Page/page-template-title.hbs
Closes #3199
Alerts can appear in many contexts, so a `<span>` instead of `<h4>` makes more sense.
> fix(alert): fix heading order

- src/patternfly/components/ChipGroup/chip-group-close.hbs
- src/patternfly/components/ChipGroup/examples/ChipGroup.md
closes #3247 
@maryshak1996 @mceledonia I noticed the removable action doesn't have the same spacing as in the design kit. Do you know the actual px for the padding ?
> fix(chipgroup): update removable action icon

- src/patternfly/components/ModalBox/examples/ModalBox.md
- src/patternfly/components/ModalBox/modal-box.scss
- src/patternfly/demos/Modal/examples/Modal.md
fixes https://github.com/patternfly/patternfly/issues/2979
Noticed the modal demos were broken, so went ahead and added this, too.
@mattnolting @christiemolloy wdyt about this change? Since the size modifiers were applied at breakpoints before, the point at which the size modifier applies needs to be 32px below whatever the breakpoint is in order for the modal to resize smoothly between the size modifier and adjusting with the width of the browser. So the existing small and large modifiers jerk a little right at the point where the modifier is applied. That also meant this medium modifier would need to apply at 736px to not jerk when the modifier is applied, and design wanted that width to be 840px.
The changes I made don't break the variable name API, and the react component's `width` …
> fix(modal): added medium, adjusted maxwidths for better responsiveness

- .circleci/config.yml
- scripts/gulp/codeTransformer.js
- scripts/sizeReport/sizeReport.js
Fixes:
```sh
➜  patternfly npm run dev:lite
> @patternfly/patternfly@0.0.0-development dev:lite /home/redallen/src/patternfly
> gulp develop
[15:41:47] Using gulpfile ~/src/patternfly/gulpfile.js
[15:41:47] Starting 'develop'...
[15:41:47] Starting 'compileSrcSASS'...
[15:41:47] Starting 'copyWorkspaceAssets'...
[15:41:47] Starting 'compileSrcHBS'...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[15:41:56] Finished 'compileSrcSASS' after 8.56 s
[15:41:57] Finished 'copyWorkspaceAssets' after 9.81 s
[15:41:57] Finished 'compileSrcHBS' after 9.85 s
[15:41:57] Starting 'compileSrcMD'...
[15:41:58] 'compileSrcMD' errored after 743 ms
[15:41:58] TypeError: Cannot read property 'match' of null
at visitor (/home/redallen/src/patternfly/scripts/gulp/codeTransformer.j …
```
> fix(dev-lite): parse new h3 example titles

- src/patternfly/sass-utilities/scss-variables.scss
https://github.com/patternfly/patternfly/issues/3314
The places success-200 is used
```
components/Form/form.scss:  --pf-c-form__helper-text--m-success--Color: var(--pf-global--success-color--200);
components/Alert/alert.scss:  --pf-c-alert--m-success__title--Color: var(--pf-global--success-color--200);
components/Label/label.scss:  --pf-c-label--m-green__content--Color: var(--pf-global--success-color--200);
```
> fix(global-var): updated success-200 to be a shade lighter

- src/patternfly/components/AlertGroup/examples/AlertGroup.md
For the underway org redesign, metastrings should now be [valid JSX attributes.](https://www.reactenlightenment.com/react-nodes/4.4.html)
Examples:
- `prop="string value"`
- `prop={jsExpression}`
- `prop` (which is equivalent to `prop={true}`)
> fix(alertgroup): removed misformed metastring

- src/patternfly/sass-utilities/mixins.scss
fixes https://github.com/patternfly/patternfly/issues/3318
This fixes a problem found in the notification drawer. One option to fix that is to just apply this change in the notification drawer. That said, a lot of the sr-only classes use positioning like `top: -9999px; left: -9999px;` or some variant of that, so it doesn't seem like the positioning plays a role in how the content is read. https://webaim.org/techniques/css/invisiblecontent/
This will simply contain the element within the bounding box of its closest ancestor with a coordinate system instead of placing it wherever it is in the document flow, which triggers this bug in chrome.
> fix(global): positioned sr-only class to top/left 0 to avoid overflow

- .github/stale.yml
Closes #3335 
This adds Stalebot config to the repo, which will activate the Stalebot app to begin running.
> chore(repo): added .github directory with stalebot configuration file

- src/patternfly/components/Drawer/drawer.scss
fixes https://github.com/patternfly/patternfly/issues/3260
I took the approach of traditional style overrides using selectors and properties instead of overriding variables. There are cases where overriding a variable would work, but to be consistent, I kept the styling changes consistent. It may be a better approach to define something like - a nested drawer can only exist in the drawer__content element, so applying var overrides to elements in the drawer__panel element is fine, but this way, a nested drawer can exist anywhere inside of the drawer component and it should work fine*.
Another consideration was using the `*` selector in place of `__main` (and maybe `__body`, or maybe `.pf-c-drawer > * (main) > * (panel) > * (body) > * (head) > .pf-c-drawer__close` as a means to style the …
> fix(drawer): scoped drawer styles to improve behavior of nested drawers

- src/patternfly/base/_chart-globals.scss
Victory changed the way padding is applied to chart tooltips. With the latest Victory packages, the tooltip appears too large.
Fixes https://github.com/patternfly/patternfly/issues/3346
**Before**
**After**
> fix(charts): Adjust chart tooltip padding

- src/patternfly/components/NotificationDrawer/notification-drawer.scss
fixes https://github.com/patternfly/patternfly/issues/3285
> fix(notificationdrawer): wrapped long item description, group title

- src/patternfly/components/Drawer/drawer.scss
> fix(drawer-full-page): scoped drawer__body >  page__main

- src/patternfly/components/Skeleton/examples/Skeleton.css
- src/patternfly/components/Skeleton/skeleton.scss
https://github.com/patternfly/patternfly/issues/3375
found a bug where safari renders `transparent` as `rgba(0,0,0,0)`, a transparent based on black (`rgb(0,0,0)`) and the gradient was the wrong color. https://stackoverflow.com/questions/38391457/linear-gradient-to-transparent-bug-in-latest-safari
> fix(skeleton): added width var, safari fix bug w/ transparent

- src/patternfly/components/Page/examples/Page.md
fixes https://github.com/patternfly/patternfly/issues/1997
We already have a demo at https://www.patternfly.org/v4/documentation/core/demos/page/tertiary-nav
Opened a react issue to create a demo at https://github.com/patternfly/patternfly-react/issues/4676, and will create a react issue to add the section examples to https://www.patternfly.org/v4/documentation/react/components/page once this PR is merged.
> chore(page): added main section element examples

- src/patternfly/components/Form/form.scss
- src/patternfly/demos/BasicForms/examples/BasicForms.md
fixes https://github.com/patternfly/patternfly/issues/3391
You can verify this by adding `overflow: auto;` to one of the basic forms demos. The presence of the `.pf-c-form__group.pf-m-action` element with buttons will trigger the overflow. Also verified it should be safe to hide overflow on this element, as it was already hidden on `__actions`, and you can't put anything other than the buttons in `__actions` in the react [ActionGroup](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/components/Form/ActionGroup.tsx) component, so this shouldn't hide any tooltips or other things that created overflow that wouldn't have been hidden already.
> fix(form): hide negative margin overflow from __actions

- src/patternfly/components/Button/button.scss
- src/patternfly/components/Button/examples/Button.md
> feat(button): add warning modifier to buttons

- src/patternfly/components/AppLauncher/app-launcher.scss
- src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly/issues/3429
This also adds `:focus-within` support in the app launcher to match the select, so that when you focus on an element in a favorite menu item, the whole item's background changes. This will change the current keyboard navigation style in the app launcher from:
to:
This makes the app launcher match the select, and the general style of navigating any of these types of menus by keyboard.
> fix(select): added pf-m-focus support for favorite __menu-items

- RELEASE-NOTES.md
- package.json
While node>=12 is required to build and develop the workspace, the `"engines"` section limits what versions of node consumers must use to consume the `dist` folder. It's best to let consumers use whatever versions they want and instead rely on the version listed in the README for development (which is currently Node 12).
> fix(package): downgrade engines

- src/patternfly/components/DatePicker/date-picker-calendar.hbs
- src/patternfly/components/DatePicker/date-picker-helper-text.hbs
- src/patternfly/components/DatePicker/date-picker-input.hbs
- src/patternfly/components/DatePicker/date-picker.hbs
- src/patternfly/components/DatePicker/date-picker.scss
- src/patternfly/components/DatePicker/examples/DatePicker.css
- src/patternfly/components/DatePicker/examples/DatePicker.md
- src/patternfly/components/FormControl/examples/FormControl.md
- src/patternfly/components/FormControl/form-control.hbs
- src/patternfly/components/FormControl/form-control.scss
- src/patternfly/components/_all.scss
- src/patternfly/patternfly-date-picker.scss
fixes https://github.com/patternfly/patternfly/issues/180
to test the flatpickr styles, you can import the compiled `patternfly-date-picker.css` in the root into this POC page http://datepicker-in-progress.surge.sh/documentation/react/components/datepicker
@nicolethoen right now I'm just styling the flatpickr classes directly. We'll want to scope these styles so that we only style our date picker instance of flatpickr, in case someone uses flatpickr on their site for some other purpose. Can we add a class to the `.flatpickr-calendar` element, or wrap it in a container so I can target the styles to the class we add?
> feat(date-picker): added date-picker, flatpickr styles

- src/patternfly/components/InputGroup/input-group.scss
closes #2732 
@mcoker can this be positioned as a bug so that I can remove the block and variable ?
> fix(inputgroup): fix double line in invalid

- src/patternfly/components/NotificationBadge/notification-badge.scss
- src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly/issues/3450
@mcarrano @mceledonia this works, and the color changes applies to the notification badge in a dark area (masthead) and light area (the example page). Though I'll note that we've traditionally made things lighter on hover/focus in dark theme, and this makes them darker. Just want to make sure I got that right?
> fix(notification-badge): added hover/focus styles for unread/attention

- src/patternfly/components/ModalBox/modal-box.scss
https://github.com/patternfly/patternfly/issues/3480
yay `min()` and `max()`! 
refactored this a bit to
* use `top` instead of `margin-top` since percentage based values for `margin-top` will not work as intended.
* set smart values for min/max-width so that, if the top-aligned spacer is < the default left/right/bottom gutter for a modal, the gutters will match the spacer, creating equal space around the modal. But if the spacer is > the default gutter sizes, the default gutters are applied.
> fix(modal): refactored the top aligned variation so it works better

- src/patternfly/components/ModalBox/examples/ModalBox.md
- src/patternfly/components/ModalBox/modal-box-title-icon.hbs
- src/patternfly/components/ModalBox/modal-box-title.hbs
- src/patternfly/components/ModalBox/modal-box.hbs
- src/patternfly/components/ModalBox/modal-box.scss
fixes https://github.com/patternfly/patternfly/issues/3374
> feat(modal-box): added support for title icon, modal alert states

- .circleci/config.yml
Speeds up builds ~1m20s. We upload them to surge and no longer need to upload them in CI since they're rather large now.
> chore(build): don't upload artifacts

- src/patternfly/components/ModalBox/modal-box.scss
fixes https://github.com/patternfly/patternfly/issues/3587
Verified this is correct in the react component. Core component is a little off since the icon isn't 16px wide.
Before
After
> fix(modal): increased space between close button and what preceedes it

- src/patternfly/components/ModalBox/modal-box.scss
fixes https://github.com/patternfly/patternfly/issues/3602
With https://github.com/patternfly/patternfly/issues/3587, the help and close buttons should be adjacent to one another.
The help button is taller than the close button, but that's because of the pficons and there is an issue to address that here - https://github.com/patternfly/patternfly/issues/3536. The react implementation doesn't have that issue.
> fix(modal): right aligned help button, aligned with close button

- src/patternfly/components/FormControl/form-control.scss
fixes https://github.com/patternfly/patternfly/issues/3578
@mcarrano @mceledonia the css we had in place to change the placeholder text to black-600 wasn't working. This PR fixes that so the color is now black-600.
> fix(form-control): updated placeholder block so the color change applies

- src/patternfly/components/Table/table.scss
fixes https://github.com/patternfly/patternfly/issues/3119
@christiemolloy I'm not seeing that, but I am seeing an `:active` border that doesn't seem to match any other interactive styles we have on elements like this. WDYT?
> fix(table): removed compound expansion active border

- src/patternfly/components/NotificationDrawer/notification-drawer-basic-list.hbs
- src/patternfly/demos/NotificationDrawer/examples/NotificationDrawer.md
- src/patternfly/demos/Page/page-template-header-tools-notification-badge.hbs
fixes https://github.com/patternfly/patternfly/issues/3371
@mceledonia @mcarrano this adds a read notification drawer demo, attention demo, and updates the other demo notification badges to unread. WDYT, does this look like you would expect? Also in the drawer demos, since there is no notification drawer in the drawer, should we update the header icon that toggles the drawer open/closed to be something other than the bell icon?
> chore(notification-drawer): updated demos so badge reflects drawer items

- src/patternfly/components/Alert/examples/Alert.md
fixes https://github.com/patternfly/patternfly/issues/3257
@mcarrano there are no changes in core outside of adding the examples. Any icon can be dropped into any of the alert variations and it will take on the properties of the existing supported icons. Was there anything else we need to support with custom icons?
> feat(alert): added examples to support custom alert icon

- src/patternfly/components/CalendarMonth/calendar-month.scss
part of https://github.com/patternfly/patternfly/issues/3668
* Removes default browser focus outline
* Fixes adjacent month selected styling
> fix(calendar-month): removed focus outline, fixed selected styling

- src/patternfly/components/Pagination/examples/Pagination.md
- src/patternfly/components/Pagination/pagination.scss
closes #3561 
Caveat: the new modifiers DO NOT apply to `.pf-c-pagination.pf-m-bottom` as `.pf-m-bottom` has a unique and specific, presentation. 
@mcoker removed the `isFullscreen` tag as the examples are difficult to scan in component context.
> feat(pagination): added layout mods

- src/patternfly/components/CalendarMonth/calendar-month-date.hbs
- src/patternfly/components/CalendarMonth/calendar-month-dates-cell.hbs
- src/patternfly/components/CalendarMonth/calendar-month-day.hbs
- src/patternfly/components/CalendarMonth/calendar-month-days-row.hbs
- src/patternfly/components/CalendarMonth/calendar-month-header-month.hbs
- src/patternfly/components/CalendarMonth/calendar-month.scss
- src/patternfly/components/CalendarMonth/examples/CalendarMonth.md
- src/patternfly/components/DatePicker/date-picker.hbs
- src/patternfly/components/DatePicker/date-picker.scss
- src/patternfly/components/DatePicker/examples/DatePicker.md
fixes https://github.com/patternfly/patternfly/issues/3679
> if a cell has .pf-m-selected applied you cannot tell when its button has :focus applied since the borders overlap
@mcarrano do you want to do something about this? We could use a blue shadow on focus or something like that?
> fix(calendar-month): updated a11y per the react component

- src/patternfly/components/JumpLinks/jump-links.scss
fixes #3683 .
Now when you set the top-level item as current, it will no longer mark the whole subsection under this item as current.
> fix(jump-links): mark only top-level item as current

- src/patternfly/components/Table/examples/Table.md
- src/patternfly/components/Table/table-tr.hbs
- src/patternfly/components/Table/table.hbs
- src/patternfly/components/Table/table.scss
**Previews start here:** https://patternfly-pr-3691.surge.sh/components/table#borderless
I added `.pf-c-table__control-row` for compound expandable table control rows, that allows for a border below that works with hover/active styles:
I think we may want to keep some borders on `.pf-m-expandable` tables. 
@mceledonia @mcarrano Here are SS:
> feat(table): extended borderless to expandable

- src/patternfly/components/Form/examples/Form.md
- src/patternfly/components/Form/form-field-group-body.hbs
- src/patternfly/components/Form/form-field-group-header-actions.hbs
- src/patternfly/components/Form/form-field-group-header-description.hbs
- src/patternfly/components/Form/form-field-group-header-main.hbs
- src/patternfly/components/Form/form-field-group-header.hbs
- src/patternfly/components/Form/form-field-group-title-text.hbs
- src/patternfly/components/Form/form-field-group-title.hbs
- src/patternfly/components/Form/form-field-group-toggle-button.hbs
- src/patternfly/components/Form/form-field-group-toggle-icon.hbs
- src/patternfly/components/Form/form-field-group-toggle.hbs
- src/patternfly/components/Form/form-field-group.hbs
- src/patternfly/components/Form/form.scss
fixes https://github.com/patternfly/patternfly/issues/3557
> feat(form): added field groups

- src/patternfly/components/Progress/examples/Progress.md
- src/patternfly/components/Progress/progress-measure.hbs
- src/patternfly/components/Progress/progress.scss
fixes https://github.com/patternfly/patternfly/issues/3529
@kmcfaul adding you to see if the variation works with what you'd expect in the react component. Adds `pf-m-fixed-width` to the `__measure` element that fits any `0-100%` value. And that width is overridable if someone is using a non-percentage value for the measure and wants a custom width by setting `pf-m-fixed-width` and defining `--pf-c-progress__measure--m-fixed-width--Width: 25%` (where 25% is any size unit).
> fix(progress): enabled static width for measure value

- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/Dropdown/examples/Dropdown.css
- src/patternfly/components/Dropdown/examples/Dropdown.md
closes #3069 .
Now it's not only support `pf-m-align-right-on-[breakpoint]` but also support `pf-m-align-left-on-[breakpoint]`, so you can set your style like `pf-m-align-right-on-md pf-m-align-left-on-xl`.
> fix(dropdown): support dropdown menu alignment on different breakpoint

- src/patternfly/components/DescriptionList/description-list-order.scss
- src/patternfly/components/DescriptionList/description-list.scss
- src/patternfly/components/Divider/divider.scss
- src/patternfly/components/Drawer/drawer.scss
- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/Page/page.scss
- src/patternfly/components/Pagination/pagination.scss
- src/patternfly/components/Tabs/tabs.scss
- src/patternfly/components/Toolbar/toolbar.scss
- src/patternfly/layouts/Flex/flex.scss
- src/patternfly/sass-utilities/mixins.scss
closes #3751 .
`$breakpoint-map` is not needed and I have removed it from the function and anywhere we call the function.
> refactor(mixins): remove breakpoint map in pf-apply-breakpoint function

- src/patternfly/components/Card/card.scss
- src/patternfly/components/List/examples/List.md
- src/patternfly/components/List/list.scss
- src/patternfly/demos/Card/examples/CardView.md
fixes https://github.com/patternfly/patternfly/issues/3555
fixes https://github.com/patternfly/patternfly/issues/1635
Along with adding the card demos, I needed to update 2 things:
* Added a plain list variant. This removes the bullet and left padding of a list. The demo shows a top level plain list with a nested regular list. That was filed in a separate issue - https://github.com/patternfly/patternfly/issues/1635
* Fixed a bug where - if the card title is a child of pf-c-card__header, we remove all padding. There was a bug where if the title was the first-child in __header, it was assigned a padding-top, and if it was not the last child, it got a padding-bottom.
> feat(card-demo): added demos for horizontal cards

- src/patternfly/components/Menu/examples/Menu.md
- src/patternfly/components/Menu/menu-item-action.hbs
- src/patternfly/components/Menu/menu-item-description.hbs
- src/patternfly/components/Menu/menu-item-main.hbs
- src/patternfly/components/Menu/menu-item.hbs
- src/patternfly/components/Menu/menu-list-item.hbs
- src/patternfly/components/Menu/menu.scss
fixes https://github.com/patternfly/patternfly/issues/3675
* Clean up hbs/examples
* Add disabled examples under actions and favorites
* Change item-main and item-description to spans
* Disable item action if parent item is disabled
* Clean up external icon var names
* Use proper global vars
* Update disabled item action, toggle icon colors
@mcarrano can you verify that if an item is disabled that any children actions should also be disabled? I added some new disabled examples to review under expanded toggle, links, actions, and favorites.
> fix(menu): cleaned up examples, code

- src/patternfly/components/Form/examples/Form.md
- src/patternfly/components/Form/form-section-title.hbs
- src/patternfly/components/Form/form.scss
- src/patternfly/demos/Form/examples/BasicForms.md
fixes https://github.com/patternfly/patternfly/issues/3380
Adds a `pf-m-stack` variation to control groups (similar to `pf-m-inline`) that creates a stacking layout and space between children in form control groups.
Added section titles.
Updated and added forms from #3380.
> feat(form): added demos, section title, stack control group mod

- src/patternfly/components/DataList/data-list-grid.scss
- src/patternfly/components/Pagination/pagination-nav.hbs
- src/patternfly/components/Toolbar/examples/Toolbar.css
- src/patternfly/components/Toolbar/examples/Toolbar.md
- src/patternfly/components/Toolbar/toolbar--template--content.hbs
- src/patternfly/components/Toolbar/toolbar--template--filter-group.hbs
- src/patternfly/components/Toolbar/toolbar--template.hbs
- src/patternfly/components/Toolbar/toolbar-item-context-selector.hbs
- src/patternfly/components/Toolbar/toolbar.hbs
- src/patternfly/demos/Card/examples/CardView.md
- src/patternfly/demos/DataList/data-list--action-buttons.hbs
- src/patternfly/demos/DataList/data-list--icon-text.hbs
- src/patternfly/demos/DataList/data-list-actionable-data-list.hbs
- src/patternfly/demos/DataList/data-list-content-1.hbs
- src/patternfly/demos/DataList/data-list-content-2.hbs
- src/patternfly/demos/DataList/data-list-content-4.hbs
- src/patternfly/demos/DataList/data-list-content-5.hbs
- src/patternfly/demos/DataList/data-list-expandable-data-list.hbs
- src/patternfly/demos/DataList/data-list-simple-data-list.hbs
- src/patternfly/demos/DataList/examples/DataList.md
- src/patternfly/demos/PrimaryDetail/examples/PrimaryDetail.md
- src/patternfly/demos/PrimaryDetail/primary-detail-panel-body.hbs
- src/patternfly/demos/Table/examples/Table.md
- src/patternfly/demos/Table/table-compound-expansion-table.hbs
- src/patternfly/demos/Table/table-expandable-table.hbs
closes #3040 
**Previews:**
- `data-list` - https://patternfly-pr-3753.surge.sh/components/data-list/html-demos
- `table` - https://patternfly-pr-3753.surge.sh/components/table/html-demos
- `primary-detail` - https://patternfly-pr-3753.surge.sh/demos/primary-detail
- `card-view` - https://patternfly-pr-3753.surge.sh/components/card/html-demos
This PR includes a configurable `toolbar` template. It is usable across all components and demos.
> feat(toolbar-demos): added toolbar back to demos

- src/patternfly/components/Drawer/drawer.scss
- src/patternfly/components/Drawer/examples/Drawer.md
fixes https://github.com/patternfly/patternfly/issues/3787
This adds a var `--pf-c-drawer__panel--m-resizable--FlexBasis` that can be used anywhere we want it to be able to override the panel `flex-basis`. It also moves the inline var from the panel to the parent drawer.
> fix(drawer): limited drawer resize to desktop breakpoint

- src/patternfly/demos/Card/card-view-demo-template-gallery.hbs
closes #3687 .
Thanks @mmenestr ! We have a fourth variation for the empty state card here https://marvelapp.com/prototype/f869h61/screen/74368154. It contains the title and removes the empty state body.
> fix(card-demo): add empty state card into the demo

- src/patternfly/components/Card/card.scss
- src/patternfly/components/Card/examples/Card.md
> fix(card): introduce large card variant

- src/patternfly/components/Drawer/drawer.scss
- src/patternfly/components/Drawer/examples/Drawer.md
fixes https://github.com/patternfly/patternfly/issues/3804
Introduces these vars as a means to control the drawer width:
| Class | Applied to | Outcome |
| -- | -- | -- |
| `--pf-c-drawer__panel--md--FlexBasis--min` | `.pf-c-drawer__panel` | Defines the drawer panel minimum size. |
| `--pf-c-drawer__panel--md--FlexBasis` | `.pf-c-drawer__panel` | Defines the drawer panel size. |
| `--pf-c-drawer__panel--md--FlexBasis--max` | `.pf-c-drawer__panel` | Defines the drawer panel maximum size. |
These are all applied > the medium breakpoint, so they do not apply to the mobile layout, and they're applied via `flex-basis: clamp(--pf-c-drawer__panel--md--FlexBasis--min, --pf-c-drawer__panel--md--FlexBasis, --pf-c-drawer__panel--md--FlexBasis--max)`. 
The var `--pf-c-drawer__panel--FlexBasis` still …
> fix(drawer): changes to vars used to redefine panel flex-basis

- src/patternfly/utilities/Flex/examples/Flex.css
- src/patternfly/utilities/Sizing/examples/Sizing.css
- src/patternfly/utilities/Spacing/examples/Spacing.css
Closes #3823 
This PR fixes workspace selectors for flex, spacing, & sizing utilities examples to restore missing outlines.
Note: this was originally file as a PF-Org issue but the change was required here & will update in Org when it bumps the PF version at next release.
> fix(docs): fixed missing outlines for utilities examples

- src/patternfly/components/Check/check.scss
- src/patternfly/components/Check/examples/Check.md
- src/patternfly/components/DataList/data-list.scss
- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/DualListSelector/dual-list-selector-item-check.hbs
- src/patternfly/components/Radio/examples/Radio.md
- src/patternfly/components/Radio/radio.scss
- src/patternfly/components/Table/table.scss
- src/patternfly/components/TreeView/tree-view-node-check.hbs
- src/patternfly/demos/Card/card-view-demo-template-gallery.hbs
- src/patternfly/demos/PrimaryDetail/primary-detail-card-view.hbs
fixes https://github.com/patternfly/patternfly/issues/3288
fixes https://github.com/patternfly/patternfly/issues/3311
@mcarrano @mattnolting @mceledonia this adds a "pf-m-standalone" variation to the check and radio components for use when the radio/check is just a single input with no label/description. Previously, the components required a label. This PR updates our beta components that use a regular checkbox (tree view, dual list selector) and card view demo checkboxes to use the standalone variation of the checkbox component instead of regular checkboxes.
I tested using the standalone checkbox/radio components in our existing non-beta components (table, data list, split button dropdown toggles) and it works fine, though you could argue it might be breaking if users are relying on the …
> feat(radio, check): added standalone variation, cursor styles

- src/patternfly/components/Drawer/drawer.scss
- src/patternfly/components/Drawer/examples/Drawer.md
fixes https://github.com/patternfly/patternfly/issues/3813
@mcarrano @mceledonia I added this variation as `pf-m-light-200`. I'd like to be consistent as we use a variation like this going forward. Our page sections are `--pf-global--BackgroundColor-200` by default, and we use `pf-m-light` as the variation name to turn it white, so we have that precedent to work with. I'm thinking we can keep `pf-m-light` to represent white/`--pf-global--BackgroundColor-100`, and use `pf-m-light-200` for `--pf-global--BackgroundColor-200`. That will also allow us to apply this to other components in the same way. Sound OK?
> fix(drawer): added light-200 variation for grey background

- src/patternfly/components/Page/examples/Page.md
- src/patternfly/components/Page/page.scss
- src/patternfly/components/Wizard/__wizard-form.hbs
- src/patternfly/components/Wizard/examples/Wizard.md
- src/patternfly/components/Wizard/wizard.scss
- src/patternfly/demos/Wizard/examples/Wizard.md
fixes https://github.com/patternfly/patternfly/issues/3255
@mcarrano this adds a top box-shadow to the wizard footer when the wizard is 1) used in a modal, 2) used in the special page component section currently needed to add the wizard to the page. Those are the places where we should be able to guarantee the wizard footer remains sticky, so a shadow seems appropriate. I didn't add it globally to any wizard footer since, if the footer doesn't remain sticky as it should, the shadow will look out of place. So this means we may end up with some wizard footers that have a shadow, and ones that don't, even if the wizard footer is sticky since the wizard wasn't used in a modal or the special page section. That seems like a fair compromise since the wizard footers don't have a shadow currently, …
> fix(wizard): set in page wizard page section to shrink so footer/nav are sticky

- src/patternfly/components/Drawer/drawer.scss
Closes #3851 
This PR replaces `clamp` used in the resizable drawer with `min/max` functions [as described here](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()) to increase browser support for Safari 13.
> fix(drawer): replace clamp in resizable drawer for browser support

- src/patternfly/components/Drawer/drawer.scss
fixes https://github.com/patternfly/patternfly/issues/3857
`flex-basis: 100%` on `__content` isn't working in a vertical layout because its parent `__main` doesn't have a height.
> fix(drawer): fixed bottom variant issues in safari

- patternfly-a11y.config.js
fixes https://github.com/patternfly/patternfly/issues/3861
just temporarily ignoring this attr and we can enable next sprint once we sort out why it's failing.
> fix(build): set a11y test to temporarily ignore aria-allowed-attr

- RELEASE-NOTES.md
Label update now reads: Updated colors and add non-transparent border to work better on a gray background
> fix(release-notes): clarify update to Label

- src/patternfly/components/ContextSelector/context-selector.scss
fixes https://github.com/patternfly/patternfly/issues/3872
> fix(context-selector): hid menu scroll unless there is overflow

- src/patternfly/components/Login/examples/Login.md
Small bug from last sprint. Fixes https://github.com/patternfly/patternfly/issues/3876
> chore(login): added aria-hidden to hide/show password example fa icons

- src/patternfly/components/Switch/switch.scss
fixes https://github.com/patternfly/patternfly/issues/3880
Looks like this was a bug introduced in https://github.com/patternfly/patternfly/pull/3749/
> fix(switch): adjust space between switch and label

- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/OptionsMenu/options-menu.scss
This makes the plain toggles match the plain button size.
fixes https://github.com/patternfly/patternfly/issues/3437
> fix(options-menu, dropdown): normalized plain toggle size

- src/patternfly/components/FormControl/form-control.scss
fixes https://github.com/patternfly/patternfly/issues/3837
Allows textarea to be resized via `--pf-c-form-control--textarea--Width` and `--pf-c-form-control--textarea--Height`
@tlabaj can you let me know if this is enough to support autosize/resize?
> fix(form-control): added vars for textarea width/height for resizing

- src/patternfly/components/Accordion/accordion-expanded-content.hbs
- src/patternfly/components/Accordion/accordion-toggle.hbs
- src/patternfly/components/Accordion/accordion.scss
- src/patternfly/components/Accordion/examples/Accordion.md
fixes https://github.com/patternfly/patternfly/issues/3865
* Adds web/marketing variation
* Moves the pseudo elements around a little to support the border overlap
* Adds support for multiple `__expanded-content-body` elements
@ajacobs21e @mcarrano can you also verify the spacing between adjacent sections is correct in the regular/fixed example? https://patternfly-pr-3888.surge.sh/components/accordion#fixed
> feat(accordion): added display-lg, support multiple bodies

- src/patternfly/components/SearchInput/examples/SearchInput.css
- src/patternfly/components/SearchInput/examples/SearchInput.md
- src/patternfly/components/SearchInput/search-input-menu-body.hbs
- src/patternfly/components/SearchInput/search-input-menu-item-text.hbs
- src/patternfly/components/SearchInput/search-input-menu-item.hbs
- src/patternfly/components/SearchInput/search-input-menu-list-item.hbs
- src/patternfly/components/SearchInput/search-input-menu-list.hbs
- src/patternfly/components/SearchInput/search-input-text-input.hbs
- src/patternfly/components/SearchInput/search-input-text.hbs
- src/patternfly/components/SearchInput/search-input.scss
fixes https://github.com/patternfly/patternfly/issues/3863
@mcarrano 
* This does not add the hint/grey text that finishes the search term in the text input when there is a single option in the autocomplete box. That part isn't obvious how to implement since the text there is a regular text input and you can't style text like that in a text input. If that feature is a requirement, I'd like to have a follow-up issue to investigate how to best do that.
* We have the option to use the menu component here. I didn't implement it that way, and just made this list a feature of the search input component since we wouldn't be able to promote the search input component until we promoted the menu component. If that's OK, or we anticipate wanting to support features of the menu component in this list …
> feat(search-input): added autocomplete

- src/patternfly/components/Select/examples/Select.md
- src/patternfly/components/Select/select-toggle-status-icon.hbs
- src/patternfly/components/Select/select-toggle.hbs
- src/patternfly/components/Select/select.hbs
- src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly/issues/3874
> feat(select): added invalid state

- src/patternfly/components/CodeBlock/code-block-actions-item.hbs
- src/patternfly/components/CodeBlock/code-block-actions.hbs
- src/patternfly/components/CodeBlock/code-block-code.hbs
- src/patternfly/components/CodeBlock/code-block-content.hbs
- src/patternfly/components/CodeBlock/code-block-header.hbs
- src/patternfly/components/CodeBlock/code-block-pre.hbs
- src/patternfly/components/CodeBlock/code-block.hbs
- src/patternfly/components/CodeBlock/code-block.scss
- src/patternfly/components/CodeBlock/examples/CodeBlock.md
- src/patternfly/components/CodeEditor/code-editor-code.hbs
- src/patternfly/components/ExpandableSection/examples/ExpandableSection.md
- src/patternfly/components/ExpandableSection/expandable-section-content.hbs
- src/patternfly/components/ExpandableSection/expandable-section-toggle.hbs
- src/patternfly/components/ExpandableSection/expandable-section.hbs
- src/patternfly/components/ExpandableSection/expandable-section.scss
- src/patternfly/components/_all.scss
fixes https://github.com/patternfly/patternfly/issues/3907
> feat(code-block): added code block component

- src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly/issues/3987
this will allow us to remove the toggle button in a typeahead select and the select toggle height will remain the same height (36px)
> fix(select): updated typeahead text input height to match form control

- .github/stale.yml
Should fix the bot which I don't think is running. Not sure why it was [added](https://probot.github.io/apps/stale/) on Probot's side.
> fix(stalebot): add closeComment

- src/patternfly/components/Button/button.scss
fixes https://github.com/patternfly/patternfly/issues/3996
From https://github.com/patternfly/patternfly/pull/3932/files
* changes the variations back to defining `color` and `background-color`
* removes the initial `--pf-c-button--Color/BackgroundColor` vars that were added in #3932
* moves the danger variation to come after link
* nests the danger variations together
> fix(button): reverted variations to regular property declarations

- src/patternfly/components/ClipboardCopy/examples/ClipboardCopy.md
Renaming the examples per https://github.com/patternfly/patternfly-react/pull/5629#discussion_r611918535
> chore(copy-clipboard): renamed inline examples to inline compact

- src/patternfly/components/Menu/examples/Menu.md
Docs for `pf-m-load`, `pf-m-loading` and `pf-c-menu__footer` from https://github.com/patternfly/patternfly/pull/3968
> docs(menu): added docs for load, loading, footer

- src/patternfly/components/Drawer/drawer.scss
fixes https://github.com/patternfly/patternfly/issues/4051
> fix(drawer): made panel main/body elements fill height on mobile

- src/patternfly/components/Card/card.scss
- src/patternfly/components/Card/examples/Card.md
fixes https://github.com/patternfly/patternfly/issues/3959
There is an obvious problem with the way the actions element's negative margin 1) uses the wrong vars and 2) doesn't work in a lot of cases, like the problem in #3959. We have an issue to clean this up (https://github.com/patternfly/patternfly/issues/3924) but it will be a breaking change.
> feat(card): added variation to remove actions negative margin offset

- src/patternfly/components/Menu/menu.scss
> refactor(menu): changed translate to left

- src/patternfly/components/HelperText/examples/HelperText.md
- src/patternfly/components/HelperText/helper-text-item-icon.hbs
- src/patternfly/components/HelperText/helper-text-item-text.hbs
- src/patternfly/components/HelperText/helper-text-item.hbs
- src/patternfly/components/HelperText/helper-text.hbs
- src/patternfly/components/HelperText/helper-text.scss
- src/patternfly/components/_all.scss
fixes https://github.com/patternfly/patternfly/issues/4017
Preview - https://patternfly-pr-4089.surge.sh/components/helper-text
Adds 2 types of helper texts:
This is the default helper text. With static helper text, the text color and icon color are the same. By default the text and optional icon are black. Indeterminate is grey, warning is yellow, success is green, invalid is red.
This is an opt in to the helper text component. By default a dynamic helper text and icon are black. Intermediate is grey, warning has yellow icon and grey text, success has green icon and grey text, and invalid has red icon and black text.
A helper text component is a block made up of helper text items. There can be one or more items, and if there are multiple items in a helper text block, there is a `xs` …
> feat(helper-text): added helper text component

- src/patternfly/components/Wizard/examples/Wizard.md
- src/patternfly/components/Wizard/wizard-nav-link-toggle.hbs
- src/patternfly/components/Wizard/wizard-nav-link.hbs
- src/patternfly/components/Wizard/wizard.scss
- src/patternfly/demos/CardView/examples/CardView.md
fixes https://github.com/patternfly/patternfly/issues/4111
just separates the icon element that rotates from the toggle element that has padding for the toggle icon
> fix(wizard): fixed expandable nav item toggle rotation/padding issue

- src/patternfly/components/Content/content.scss
- src/patternfly/components/Content/examples/Content.md
fixes https://github.com/patternfly/patternfly/issues/4131
also wrapped the link in a `<p>` to improve the spacing and removed the value from `href`, which is how [MDN does it](https://developer.mozilla.org/en-US/docs/Web/CSS/:visited)
> fix(content): changed visited to declare color property

- src/patternfly/components/LogViewer/examples/LogViewer.md
- src/patternfly/components/LogViewer/log-viewer.scss
fixes https://github.com/patternfly/patternfly/issues/4079
This just implements our basic dark theme var overrides for the `__main` element (where the log text is output).
> feat(log-viewer): added dark variation

- src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly/issues/4053
Uses the z-index higher than our menus, but lower than overlays (backdrop, modal, etc)
> fix(page): increase sticky page section z-index

- src/patternfly/components/OverflowMenu/examples/overflow-menu.md
- src/patternfly/components/OverflowMenu/overflow-menu-action-group-example.hbs
- src/patternfly/components/OverflowMenu/overflow-menu-control.hbs
- src/patternfly/components/OverflowMenu/overflow-menu.hbs
- src/patternfly/components/Toolbar/toolbar--template.hbs
- src/patternfly/components/Toolbar/toolbar-icon-button-group-example.hbs
- src/patternfly/components/Toolbar/toolbar-overflow-menu-example.hbs
- src/patternfly/demos/Tabs/templates/tabs--table-overflow-menu.hbs
fixes #3773 
also added aria-expanded to the toolbar and tabs examples that use overflow menus
> fix(overflow-menu): added aria-expanded to examples

- src/patternfly/components/Form/examples/Form.md
- src/patternfly/components/Form/form-group-label-info.hbs
- src/patternfly/components/Form/form-group-label-main.hbs
- src/patternfly/components/Form/form-group-label.hbs
- src/patternfly/components/Form/form.scss
This adds an optional main and info element within the form-group-label to position the contents of the info opposite the current label text. See it as the "Label with additional info" example on the form component.
Fixes #4171
> feat(form): added info text to group label

- src/patternfly/assets/fonts/overpass-mono-webfont/overpass-mono.css
- src/patternfly/assets/fonts/overpass-webfont/overpass.css
- src/patternfly/assets/pficon/pficon.scss
- src/patternfly/base/_fa-icons.scss
- src/patternfly/base/_fonts.scss
Removes the `?#iefix` suffix for loading `.eot` fonts, this is a workaround for Internet Explorer 8 and older to load [ensure fonts are loaded properly](https://stackoverflow.com/questions/14207425/css-font-face-iefix). This is no longer needed as this browser is not supported by Patternfly.
The motivation for removing this is that it causes [issues](https://github.com/evanw/esbuild/issues/826) with more modern bundlers such as Snowpack (which uses `esbuild` under the hood.
> feat: drop '?#iefix' for font face definitions

- src/patternfly/components/Form/examples/Form.md
- src/patternfly/components/Form/form-helper-text.hbs
- src/patternfly/components/Login/examples/Login.md
- src/patternfly/demos/PasswordStrength/examples/PasswordStrength.md
Adds an example login page showing interactive password strength using helper text
Fixes #4018
> feat(login): adds a password strength demo

- src/patternfly/components/Spinner/spinner.scss
fixes https://github.com/patternfly/patternfly/issues/4207
--
reproduce the issue by applying `overflow: auto;` to `ul.pf-c-select__menu` on https://patternfly-pr-4208.surge.sh/components/select#loading
> fix(spinner): hid overflow from rotating elements

- src/patternfly/components/Popover/examples/Popover.md
- src/patternfly/components/Popover/popover.scss
This adds modifiers `.pf-m-start` and `.pf-m-end` to the popover in order to adjust the arrow when the position of the popover is at the start (top for left and right; left for top and bottom) and the end (bottom for left and right; right for top and bottom). 
Fixes #3930
> feat(popover): add position options

- src/patternfly/components/NotificationBadge/examples/NotificationBadge.md
fixes https://github.com/patternfly/patternfly/issues/4185
No code changes needed, just new examples with a different icon.
> docs(notification-badge): updated examples to show tasks icon

- src/patternfly/components/Form/examples/Form.md
- src/patternfly/components/Form/form-group-label.hbs
- src/patternfly/components/Form/form-group.hbs
- src/patternfly/components/Form/form-label.hbs
- src/patternfly/components/Login/examples/Login.md
- src/patternfly/components/SearchInput/examples/SearchInput.md
- src/patternfly/demos/Alert/examples/horizontal-form.hbs
- src/patternfly/demos/Alert/examples/stacked-form.hbs
- src/patternfly/demos/Form/examples/BasicForms.md
fixes #4124 
Fix based on the guidance provided here: [associating-related-controls-with-wai-aria](https://www.w3.org/WAI/tutorials/forms/grouping/#associating-related-controls-with-wai-aria)
Using the `<fieldset>` element with grid worked for formatting, although I'm not sure if it loses semantic value in doing so. It looks like, based on [this description](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#styling_with_css), that it's acceptable to use. What didn't work well was the `<legend>` element, which is only display block. Using this breaks the `required` and/or `helper` concept layouts.
> fix(form-group): updated form group role

- src/patternfly/components/HelperText/examples/HelperText.md
- src/patternfly/demos/HelperText/examples/HelperText.md
- src/patternfly/demos/PasswordStrength/examples/PasswordStrength.md
fixes #4205 
updated static demo icons to match dynamic demo icons (specifically default and indeterminate)
> fix(helper-text): updated static and dynamic to use same icons

- src/patternfly/components/Alert/alert.scss
- src/patternfly/components/Alert/examples/Alert.md
Adds a plain variation on the inline alert.
Fixes #4220
> feat(alert): add plain inline alert

- src/patternfly/components/NumberInput/number-input.scss
This adjusts the vertical alignment of the number input. Screen shot shows old and new alignment in Chrome and Firefox.
@KKoukiou does this look better to you?
Fixes #4189
> fix(number-input): adjust alignment

- src/patternfly/components/Alert/alert-description.hbs
- src/patternfly/components/Alert/alert-title.hbs
- src/patternfly/components/Alert/alert-toggle-icon.hbs
- src/patternfly/components/Alert/alert-toggle.hbs
- src/patternfly/components/Alert/alert.hbs
- src/patternfly/components/Alert/alert.scss
- src/patternfly/components/Alert/examples/Alert.md
fixes https://github.com/patternfly/patternfly/issues/4056
with the usage docs changes, all I really did was add `__toggle`, `__toggle-icon`, and `.pf-m-expand[ed/able]`. The rest of the edits were just whitespace edits around the double-askerisks.
> feat(alert): added expandable variation

- src/patternfly/layouts/Split/examples/Split.md
Adds a demo for a wrappable split layout.
Fixes #4167
> chore(split): added wrappable demo

- src/patternfly/components/Card/examples/Card.md
- src/patternfly/components/ClipboardCopy/examples/ClipboardCopy.md
- src/patternfly/components/DatePicker/examples/DatePicker.md
- src/patternfly/components/FileUpload/examples/FileUpload.md
- src/patternfly/components/Form/examples/Form.md
- src/patternfly/components/InputGroup/examples/InputGroup.md
- src/patternfly/components/Select/__select-menu-footer.hbs
- src/patternfly/components/Select/__select-single.hbs
- src/patternfly/components/Select/select-menu.hbs
- src/patternfly/components/Wizard/examples/Wizard.md
- src/patternfly/demos/Alert/examples/horizontal-form.hbs
- src/patternfly/demos/Alert/examples/stacked-form.hbs
- src/patternfly/demos/CardView/examples/CardView.md
- src/patternfly/demos/Form/examples/BasicForms.md
- src/patternfly/demos/Page/page-template-title.hbs
- src/patternfly/demos/Skeleton/examples/Skeleton.md
- src/patternfly/demos/Table/examples/Table.md
- src/patternfly/demos/Table/table-main-section-content.hbs
Closes #4023 
Closes #4290 
This PR updates microcopy across many Core examples & demos, per the notes in the original issue (further discussion in [this doc](https://docs.google.com/document/d/1Lqa8turRxmYNn05hDUPykM-q4vQDoWyuVfy3qasXlGU/edit)).
This PR also removes the date variation from the input group examples.
> docs(examples): updated example/demo microcopy

- src/patternfly/components/BackToTop/back-to-top.hbs
- src/patternfly/components/BackToTop/back-to-top.scss
- src/patternfly/components/BackToTop/examples/BackToTop.css
- src/patternfly/components/BackToTop/examples/BackToTop.md
- src/patternfly/components/_all.scss
- src/patternfly/demos/BackToTop/examples/BackToTop.md
fixes https://github.com/patternfly/patternfly/issues/4255
example: https://patternfly-pr-4291.surge.sh/components/back-to-top
demo: https://patternfly-pr-4291.surge.sh/components/back-to-top/html-demos/basic/
* The demo just shows the button placement in context of the page. Doesn't show any sort of interaction, which will all likely be handled via JS in the react component. 
Some questions:
* Will there be some kind of show/hide fade animation?
* It's easy to add this to a simple page that has a single scrollbar for the main content area with a bunch of content on it that scrolls - the button is just positioned at the bottom/right of the main content area. It's more difficult to add it to these types of pages:
* [overflow scroll](https://www.patternfly.org/v4/components/page/html-demos/o …
> feat(back-to-top): added back to top component

- src/patternfly/components/ClipboardCopy/clipboard-copy.scss
fixes https://github.com/patternfly/patternfly/issues/3966
examples - https://patternfly-pr-4296.surge.sh/components/clipboard-copy#inline-compact-in-sentence
This only changes the default inline variation with text that wraps inline with other text. It does not change the block variation of inline clipboard copy - that variation looks like it will need a breaking change to rework the html/css to allow for gaps between wrapping lines. Likely something like this:
```
div.pf-c-clipboard-copy.pf-m-inline // set to block
div.pf-c-clipboard-copy__main // set to inline with styles .pf-c-clipboard-copy.pf-m-inline has now (bgcolor, left/right padding, white-space, etc)
span.pf-c-clipboard-copy__text
span.pf-c-clipboard-copy__actions
...
```
> fix(clipboard-copy): allowed gap b/w wrapping lines in inline variation

- src/patternfly/components/AboutModalBox/examples/AboutModalBox.md
- src/patternfly/components/ChipGroup/examples/ChipGroup.md
- src/patternfly/components/DataList/examples/DataList.md
- src/patternfly/components/FormControl/examples/FormControl.md
- src/patternfly/components/InputGroup/examples/InputGroup.md
- src/patternfly/components/LabelGroup/examples/LabelGroup.md
- src/patternfly/components/ModalBox/examples/ModalBox.md
- src/patternfly/components/Popover/examples/Popover.md
- src/patternfly/components/Select/examples/Select.md
- src/patternfly/components/SkipToContent/examples/SkipToContent.md
- src/patternfly/components/TabContent/examples/TabContent.md
- src/patternfly/components/Tabs/examples/Tabs.md
- src/site/pages/contribution.md
Fixes #4293 
Updates links to use  `/components/component-id` and `/accessibility/product-development-guide`
Updates the list given in the issue, with the following exceptions:
- Spinner, Breadcrumb, and AlertGroup were ok as is
- Added a fix in contribution.md pointing to the table component
> fix(documentation): fix broken links

- src/patternfly/components/SkipToContent/examples/SkipToContent.md
- src/patternfly/components/Tabs/examples/Tabs.md
- src/patternfly/utilities/BackgroundColor/examples/BackgroundColor.md
- src/patternfly/utilities/Text/examples/Text.md
Fixes #4345 
Note that in the core workspace, the `/guidelines` links won't point to the right thing, but they will in patternfly.org.
> Update some documentation links to be relative

- src/patternfly/demos/Masthead/examples/Masthead.md
closes #4303
Adds `.pf-c-toolbar__content` to basic masthead example.
> fix(masthead): added content wrapper to demo

- src/patternfly/components/Form/examples/Form.md
- src/patternfly/components/FormControl/form-control.scss
fixes https://github.com/patternfly/patternfly/issues/4288
Not sure if I want to make this change now or in a breaking change. It seems like a safe enough change, I just wonder if it could cause some unexpected issue - and the form control elements are commonly used. Beyond fixing the extra space from the original issue, it fixes this inconsistency that currently exists under the element between firefox and either chrome or safari.
wdyt @mattnolting @srambach 
chrome
safari
firefox
> fix(form-control): removed extra space under textarea

- src/patternfly/components/ProgressStepper/examples/ProgressStepper.md
- src/patternfly/components/ProgressStepper/progress-stepper-step-title.hbs
- src/patternfly/components/ProgressStepper/progress-stepper.scss
This adds in styling for the `.pf-m-help-text` to be added to the step title so that it can be used for initiating a popover.
Fixes #4372
> feat(progress-stepper): added help text for popover

- src/patternfly/components/Check/check.scss
- src/patternfly/components/Form/form.scss
- src/patternfly/components/Radio/radio.scss
This does some math to calculate the distance from the top of the element to the baseline so that the horizontal form labels and also the checkbox/radio button labels can be properly aligned vertically.
Sadly, in Firebox, aligning the label/input to "baseline" doesn't give the desired behavior on multi-line inputs.
Old and new alignment here:
Fixes #3868
> fix(radio,checkbox,form): Correct label alignment

- src/patternfly/components/LogViewer/log-viewer-string.hbs
- src/patternfly/components/LogViewer/log-viewer.scss
- src/patternfly/components/LogViewer/templates/__log-viewer-dynamic-data.hbs
fixes https://github.com/patternfly/patternfly/issues/4396
@redallen when you have an html element in an example block, it renders a new line before the element. Is there a way we can fix that? It's messing up the formatting in some of these examples.
> fix(log-viewer): preserved white space in log viewer text

- src/patternfly/components/FormControl/form-control.scss
- src/patternfly/components/Select/examples/Select.md
- src/patternfly/components/Select/select-toggle-typeahead.hbs
- src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly/issues/4263
I noticed some differences between core & react's invalid states:
* **Core**: has `aria-invalid` on the toggle `<button>`
* **React**: has `aria-invalid` on the `.pf-c-select` component container
* **Core**: now has `aria-invalid` on the text input
* **React*: has `aria-invalid` on the `.pf-c-select` component container
* **Core**: has `aria-invalid` on the text input
* **React**
* has `aria-invalid` on the `.pf-c-select` component container
* has `aria-invalid` on the text input
@jessiehuff just wanted to verify any follow up changes needed by core and react after this PR?
> fix(select): removed double invalid icon on invalid typeahead

- src/patternfly/components/Banner/banner.scss
- src/patternfly/components/Banner/examples/Banner.md
This adds styles for inline links in the banner.
@mceledonia @lboehling I don't know if we want to show all these examples or not, but I put them there for you to take a look at. Thanks!
Fixes #4360
> feat(banner): add link style

- src/patternfly/utilities/BackgroundColor/examples/BackgroundColor.md
- src/patternfly/utilities/Text/examples/Text.md
Fixes #3702 
Adds documentation about breakpoints to the text and background color utilities and consolidates some repeated options.
> chore(utilities): add breakpoint options to docs

- src/patternfly/components/Tooltip/examples/Tooltip.md
- src/patternfly/components/Tooltip/tooltip.scss
Fixes #4382 
Adds diagonal positioning with the same modifiers currently used in the popover.
> feat(tooltip): diagonal positioning

- src/patternfly/components/Nav/nav.scss
fixes https://github.com/patternfly/patternfly/issues/4485
@mattnolting I think ideally we would handle the icon rotation by redefining vars instead of setting the `transform` property like we're doing now, but since we're treating changing properties as breaking changes, this seemed like the easiest fix. Lemme know what you think!
> fix(nav): fixed toggle icon rotation

- src/patternfly/components/TextInputGroup/examples/TextInputGroup.md
- src/patternfly/components/TextInputGroup/text-input-group-text-input.hbs
- src/patternfly/components/TextInputGroup/text-input-group.hbs
- src/patternfly/components/TextInputGroup/text-input-group.scss
> feat(TextInputGroup): added disabled styling

- src/patternfly/components/Card/card.scss
- src/patternfly/components/Card/examples/Card.md
- src/patternfly/demos/Card/templates/card-demo--template-gallery.hbs
fixes https://github.com/patternfly/patternfly/issues/4359
* Adds a `pf-m-non-selectable-raised` variant
* Updates the card view demo to use the new selectable-raised variant instead of the old hoverable variant, and add a selected and non selectable card
example - https://patternfly-pr-4500.surge.sh/components/card#non-selectable
card view demo - https://patternfly-pr-4500.surge.sh/demos/card-view/html-demos/card-view/
FYI, here is what the card view demo looks like with flat cards:
> feat(card): added non-selectable card, updated card view demo

- src/patternfly/components/Table/table.scss
- src/patternfly/components/Table/templates/table--scrollable--tbody--tr.hbs
- src/patternfly/components/Table/templates/table--scrollable--td.hbs
- src/patternfly/components/Table/templates/table--scrollable--th.hbs
- src/patternfly/components/Table/templates/table--scrollable--thead--tr.hbs
- src/patternfly/components/Table/templates/table--scrollable.hbs
closes #4488 
Using `pf-l-flex` as a child of table cells, in conjunction with `.pf-m-truncate` and icons prohibits the cell from restricting width. This PR
- Removes `pf-l-flex` 
- Add support for vertical alignment of icons in `pf-m-truncate`
- Allows for text to truncate when width is set
> fix(table): fix pf-m-truncate alignment

- src/patternfly/components/FormControl/form-control.scss
This adjusts the padding on the form component select so that it matches the PatternFly select component.
Screen shot of Chrome, FF, and Safari below. @garrett I didn't find that the same values you provided gave me the correct alignment (but the selector was very helpful), so if you could check this out that would be great. 
To see this, you'll need to inspect and put width:auto on the select form elements.
One other note: the placeholder text doesn't seem to respect the padding when using width: auto. If you put `&nbsp;` in the placeholder you can fake it... 😬
fixes #4387
> fix(form-select): match padding with select

- src/patternfly/components/MenuToggle/menu-toggle.scss
> fix(menu-toggle): added rounded corners to primary

- patternfly-a11y.config.js
- src/patternfly/components/DualListSelector/dual-list-selector-item.hbs
- src/patternfly/components/DualListSelector/dual-list-selector-list-item.hbs
- src/patternfly/components/DualListSelector/dual-list-selector-list.hbs
- src/patternfly/components/DualListSelector/dual-list-selector-status-text.hbs
- src/patternfly/components/DualListSelector/dual-list-selector.scss
- src/patternfly/components/DualListSelector/examples/DualListSelector.md
Fixes #4413 and also a few more inconsistencies not mentioned in the issue. 
Important notes:
This PR is currently failing A11y checks due to a nested interactive component where it's not allowed in the draggable version. 
The React component currently has a span there instead of a button for the drag handle - but this was a stop gap measure and the plan is to put it back. I could remove the button temporarily here, but changing it to a span (as the React component has) means that other a11y issues arise such as `aria-label` and `aria-labeledby` is not allowed on a span.
> fix(dual-list-selector): align a11y to react

- src/patternfly/components/Toolbar/toolbar.scss
Fixes #4284
See #4284 for before and after.
> fix(toolbar): Do not hide labels in collapsed state

- src/patternfly/components/Table/table.scss
Closes #4475 
Updated selector to no longer apply `cursor: pointer` to checkboxes with `disabled` attribute.
> fix(table): removed cursor pointer on disabled checkboxes

- src/patternfly/demos/PasswordGenerator/examples/PasswordGenerator.md
- src/patternfly/demos/PasswordStrength/examples/PasswordStrength.md
This adds a new demo showing a form input field in combination with a menu to show a suggested password and button to regenerate a new password.
Mockup here: https://marvelapp.com/prototype/c7j2b6b/screen/79266406
Fixes #4340
> feat(demos): adds a password generator demo

- src/patternfly/base/_globals.scss
fixes https://github.com/patternfly/patternfly/issues/4524
These custom focus styles were to fix a problem with buttons being different sizes in firefox, however that has since been fixed. This restores the default focus styles for buttons. @mcarrano @mceledonia do you see this as a breaking change? It's definitely a bug fix as far as I'm concerned, but it will change the default focus style for buttons in FF so it could result in an unexpected visual change for FF users.
> fix(global): removed custom firefox focus styles

- src/patternfly/components/Table/examples/Table.md
This rearranges some examples and documentation in the table component to better group examples with documentation. 
Fixes #4463
> chore(table): reorganize documentation

- src/patternfly/components/Truncate/examples/Truncate.md
- src/patternfly/components/Truncate/truncate-end.hbs
- src/patternfly/components/Truncate/truncate-start.hbs
- src/patternfly/components/Truncate/truncate-text.hbs
- src/patternfly/components/Truncate/truncate.hbs
- src/patternfly/components/Truncate/truncate.scss
- src/patternfly/components/_all.scss
closes #4129 
A couple of notes: 
- Only firefox currently supports `text-overflow: <string>`, all other browser hide overflow text regardless of character placement (characters could be hidden in the middle). We could control this programmatically, but could result in performance issues. 
- No modifiers are needed, the css recognizes `start` and `end` elements and logically controls where truncation occurs. 
- Text strings are scalable ie there's no `width` control other than that included by container.
> feat(truncate): added truncate component

- src/patternfly/components/Truncate/truncate.scss
react build is failing because `--pf-c-truncate--FontSize` is referenced but not defined
> fix(truncate): fixed fontsize var value

- src/patternfly/components/Label/examples/Label.md
- src/patternfly/components/Label/label-content.hbs
- src/patternfly/components/Label/label-editable-text.hbs
- src/patternfly/components/Label/label.hbs
- src/patternfly/components/Label/label.scss
This fixes the styling of the editable label, but the structure is in the inline edit component and will be addressed in a future PR.
#4469 
[design](https://docs.google.com/document/d/1ReoW10DzrrWxdAnzwuXbeTMdGXpFfiIAE9JHu-43o4U/edit)
[React PR](https://github.com/patternfly/patternfly-react/pull/6472)
> fix(label): adjust style of editable

- src/patternfly/components/NotificationBadge/examples/NotificationBadge.css
- src/patternfly/components/NotificationBadge/examples/NotificationBadge.md
Fixes #4563 
Changes background of the examples to dark. Also clarifies in the documentation that the selected (notification/task drawer open) state is handled by the page component.
> fix(notification badge): change example to dark

- src/patternfly/components/Login/login.scss
Closes #4540 
This PR sets `align-self: start` on `.pf-c-login__main` to avoid it stretching to fill height if the content beside it is taller than it is.
> fix(login page): aligned login box to top

- src/patternfly/components/Table/table.scss
closes #4535 
@mcarrano Looks like this issue applies to all sortable table `th`s, not just nested `th`s. `max-width` should be `none` rather than `fit-content`. Update tested in FF, Chrome and Safari.
> fix(table): fixed sort/fit-content width

- src/patternfly/components/Table/examples/Table.md
Closes #4584 
Removes col/colgroups references from examples
> fix(table): removed cols/colgroups

- src/patternfly/components/Truncate/examples/Truncate.css
- src/patternfly/components/Truncate/examples/Truncate.md
- src/patternfly/components/Truncate/truncate-end.hbs
- src/patternfly/components/Truncate/truncate-start.hbs
- src/patternfly/components/Truncate/truncate-text.hbs
- src/patternfly/components/Truncate/truncate.scss
[React issue 6713](https://github.com/patternfly/patternfly-react/pull/6713) raises several questions about the truncate component. There is only one way to truncate with CSS per character, and that is with `text-overflow: ellipsis` or `text-overflow: {string}` (currently only supported in FF). Calculating string widths per non-monospace font character is a heavy JS lift alone, and the truncate component will appear multiple times in tables, data lists, etc those browser calcs will be exponential and lead to performance issues. 
The current implementation takes advantage of `text-overflow: ellipsis` by setting the font size of the duplicate ellipsis to `0` which essentially hides it. `display: flex` doesn't respond to truncated text when it occurs at the beginning of a string and …
> fix(truncate): resolved spacing issues

- src/patternfly/components/DescriptionList/description-list-icon.hbs
- src/patternfly/components/DescriptionList/description-list-term.hbs
- src/patternfly/components/DescriptionList/description-list.scss
- src/patternfly/components/DescriptionList/description-list__example-with-icons.hbs
- src/patternfly/components/DescriptionList/description-list__example.hbs
- src/patternfly/components/DescriptionList/examples/DescriptionList.md
This adds support for an icon in the term of a description list. 
Note that per design, at the smallest width, the text wraps under the icon, but at the small breakpoint the text changes to be indented past the icon.
Fixes #4353
> feat(DescriptionList): add icon variant

- src/patternfly/components/Dropdown/dropdown.hbs
- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/Masthead/masthead.scss
- src/patternfly/components/Toolbar/examples/Toolbar.md
- src/patternfly/components/Toolbar/toolbar.scss
- src/patternfly/demos/Masthead/examples/Masthead.md
- src/patternfly/demos/Masthead/templates/masthead-demo--drilldown.hbs
- src/patternfly/demos/Masthead/templates/masthead-demo--icon-group.hbs
- src/patternfly/demos/Masthead/templates/masthead-demo--page.hbs
closes #4522 
@mcarrano @mceledonia can you please review [Masthead with horizontal nav](https://patternfly-pr-4617.surge.sh/components/masthead/html-demos#horizontal-nav)? A couple of things in question, bearing in mind that space becomes much more limited in this iteration. 
* Do we want to show this demo with context selector included? It has to live in the same container as `__brand` to be accommodated. 
* Should the nav be full height?
* Any design details that I've missed...
> feat(masthead): added horizontal nav demo

- src/patternfly/components/BackToTop/examples/BackToTop.md
- src/patternfly/components/JumpLinks/examples/JumpLinks.md
- src/patternfly/demos/BackToTop/examples/BackToTop.md
- src/patternfly/demos/JumpLinks/examples/JumpLinks.md
Closes: #4604
For reference:
The only open issues for jumplinks are to build a new demo: [jump links issues](https://github.com/orgs/patternfly/projects/7/views/5?filterQuery=is%3Aopen+jump+links+)
The only issues open for Back to top are the typescript conversion and design guidelines: [back to top issues](https://github.com/orgs/patternfly/projects/7/views/5?filterQuery=is%3Aopen+back+to+top+
)
> chore(docs): promote beta components

- src/patternfly/components/TextInputGroup/examples/TextInputGroup.md
- src/patternfly/components/TextInputGroup/text-input-group-text-input.hbs
Closes #4558 
This PR adds a new example for text input group using the existing `--pf-c-text-input-group__text-input--m-hint--Color` variable to show ghosting for autocomplete suggestion.
> feat(Text input group): added autocomplete ghosting

- src/patternfly/components/ContextSelector/context-selector.scss
- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/MenuToggle/menu-toggle.scss
- src/patternfly/components/OptionsMenu/options-menu.scss
- src/patternfly/components/Select/select.scss
Fixes #4552 
This changed the toggle icon to be darker on hover for dropdown, options menu, select, menu toggle, context selector, and pagination.
> Fix hover state for all plain variant icons

- src/patternfly/demos/DataList/data-list-expandable-compact-table.hbs
- src/patternfly/demos/Table/table-compact-table.hbs
- src/patternfly/demos/Table/table-expandable-table.hbs
- src/patternfly/demos/Table/table-simple-table.hbs
- src/patternfly/demos/Table/table-sortable-table.hbs
Fixes #4598 
This also replaces a couple of empty THs with TDs to fix an accessibility error (empty THs are not allowed).
https://patternfly-pr-4640.surge.sh/components/table/html-demos#basic
Bulk selector removed from the header of  the basic, sortable, expandable, compact, static bottom pagination, column management modal, and sticky header demos.
The data list example just changes the empty TH to a TD for a11y, but I believe should still have the bulk selector in the table header since it's a selector for the secondary table. https://patternfly-pr-4640.surge.sh/components/data-list/html-demos#expandable-demo
> fix(TableDemo): remove bulk selector from header

- src/patternfly/components/NumberInput/number-input.scss
- src/patternfly/components/Pagination/pagination.scss
- src/patternfly/sass-utilities/placeholders.scss
Closes: #4224
To test, navigate to the Pagination examples and verify when focusing on any page select input box that up/down arrows are not visible and you are still able to use keyboard up/down arrows to increment/decrement the count.
> feat(pagination): remove number input arrow visibility

- src/patternfly/components/Table/examples/Table.md
fixes https://github.com/patternfly/patternfly/issues/4643
> chore(table): removed unnecessary class from striped tr example

- UPGRADE-GUIDE.md
Closes #4677 
This PR adds additional context to the upgrade guide, clarifying that it details upgrading from V3 to V4 and linking to the relevant release notes.
> chore(docs): added version details to upgrade guide

- src/patternfly/components/Nav/examples/Navigation.css
- src/patternfly/components/Nav/examples/Navigation.md
- src/patternfly/components/Nav/nav.scss
fixes #4602 
@mcarrano @mceledonia I added a divider between sections to separate them and an `aria-label` to sections without titles. Lmk if you this presentation is what you expect.
> feat(nav): added variation to fix section spacing

- src/patternfly/demos/ContextSelector/examples/ContextSelector.md
- src/patternfly/demos/Page/page-demo-masthead-component.hbs
fixes the context selector demos after an include was removed from https://github.com/patternfly/patternfly/pull/4683/
> chore(context-selector): fixed broken include paths

- src/patternfly/components/Spinner/examples/Spinner.md
fixes https://github.com/patternfly/patternfly/issues/4679
> chore(spinner): rename examples is SVG is default, non-SVG is legacy

- src/patternfly/demos/Tabs/examples/Tabs.md
- src/patternfly/demos/Tabs/templates/tabs--page-grid-view.hbs
Closes #4615 
This PR:
- Replaces `.pf-m-no-border-bottom` with secondary tabs in the Grey tabs demo
- Removes unncessary `.pf-m-no-border-bottom` class from secondary tabs in Modal tabs demo
- Removes the `.pf-u-font-weight-light` class from the body card headers in the Gray tabs demo
- Removes the `.pf-u-mt-md` manual margin-top from the main h1 in the Nested tabs & Gray tabs demos
> chore(tabs): update tabs demos to use secondary tabs and standard styles

- src/patternfly/components/Wizard/examples/Wizard.md
- src/patternfly/components/Wizard/wizard-description.hbs
fixes https://github.com/patternfly/patternfly/issues/4688
The plan is to add a `component` prop in the react component that will let it be either a `<p>` (default) or a `<div>` - then update it to be a `<div>` by default in our next breaking change.
> chore(wizard): update docs/hbs for description to allow div

- src/patternfly/components/Table/examples/Table.md
fixes https://github.com/patternfly/patternfly/issues/4646
Is this too wordy? I imagine we'll want to add something like this to the react docs, too.
> docs(table): added docs around z-index conflicts with use of sticky columns/headers

- src/patternfly/components/MenuToggle/menu-toggle.scss
Closes #4630 
This PR fixes the active/hover/focus/expanded/disabled states of the plain menu toggle:
- Declare these styles within the `.pf-c-menu-toggle.pf-m-plain:not(.pf-m-text)` scope to resolve specificity issues.
- Removed three unused variables (which all match `--pf-c-menu-toggle--m-plain--hover--Color`:
- `--pf-c-menu-toggle--m-plain--focus--Color`
- `--pf-c-menu-toggle--m-plain--active--Color`
- `--pf-c-menu-toggle--m-plain--m-expanded--Color`
> fix(menu toggle): fixed plain menu toggle state

- src/patternfly/demos/DescriptionList/description-list-template-complex-content.hbs
- src/patternfly/demos/DescriptionList/description-list-template.hbs
- src/patternfly/demos/DescriptionList/examples/DescriptionList.md
- src/patternfly/demos/Masthead/templates/masthead-template-application-launcher.hbs
- src/patternfly/demos/Page/page-template-drawer-panel-tab-content.hbs
- src/patternfly/demos/Page/page-template-drawer-panel-tabs.hbs
- src/patternfly/demos/Page/page-template-drawer-panel.hbs
- src/patternfly/demos/Page/page-template-drawer.hbs
- src/patternfly/demos/Page/page-template.hbs
closes #1921 
@mcarrano Inline edit isn't yet available via React outside of `pf-c-table`, so I think it's best to add those demo features when it's available globally.
> feat(description-list): added description list demo

- src/patternfly/components/Check/check-input.hbs
- src/patternfly/components/Check/check-label.hbs
- src/patternfly/components/MenuToggle/examples/MenuToggle.md
- src/patternfly/components/MenuToggle/menu-toggle--check.hbs
- src/patternfly/components/MenuToggle/menu-toggle-button.hbs
- src/patternfly/components/MenuToggle/menu-toggle.hbs
- src/patternfly/components/MenuToggle/menu-toggle.scss
closes #4612 
There are some differences between this and dropdown.
- The target are for `pf-c-menu-toggle__button` is larger than that of `pf-c-dropdown`. Ideally, it would be at least `44px` wide, but that looks a bit odd. 
- `pf-c-dropdown` doesn't support `pf-m-secondary`, `menu-toggle` does and presents an example.
- The interactions are the same
> feat(menu-toggle): added split button

- src/patternfly/components/ModalBox/examples/ModalBox.md
- src/patternfly/components/Page/examples/Page.md
- src/patternfly/components/Wizard/examples/Wizard.md
- src/patternfly/components/Wizard/wizard-main.hbs
- src/patternfly/demos/Modal/examples/Modal.md
- src/patternfly/demos/Page/examples/Page.md
- src/patternfly/demos/Page/page-template-gallery.hbs
fixes https://github.com/patternfly/patternfly/issues/4733
fixes https://github.com/patternfly/patternfly/issues/4734
fixes https://github.com/patternfly/patternfly/issues/4735
@nicolethoen also added this to our modal example with long content, that scrolls when the viewport is short enough.
> chore(page/modal/wizard): made scrollable regions keyboard focusable

- src/patternfly/components/Form/examples/Form.md
- src/patternfly/components/Form/form-group-label-help.hbs
- src/patternfly/demos/Form/examples/BasicForms.md
- src/patternfly/demos/Modal/examples/Modal.md
- src/patternfly/demos/PasswordGenerator/examples/PasswordGenerator.md
- src/patternfly/demos/PasswordStrength/examples/PasswordStrength.md
Fixes #4453 
This adds `aria-described` by on the form field "more info" buttons  and improves the `aria-label` text so that core matches patternfly-react.
> chore(form): improve accessible label on form elements in examples/demos

- gulpfile.js
- scripts/gulp/copy.js
Closes #4700 
This PR makes the build process aware of the new `themes` directory so it is included in the `dist` directory to be shipped as part of the package.
> fix(build): updated build to include themes directory

- src/patternfly/components/Form/form.scss
Allowing PatternFly users to customize the cursor shown when hovering a
form label.
Refs: https://github.com/patternfly/patternfly/issues/4777
> fix(form): use CSS vars for defining label cursor

- src/patternfly/base/_globals.scss
fixes https://github.com/patternfly/patternfly/issues/4763
> fix(global): updated code and pre elements to use PF mono font stack

- src/patternfly/components/FormControl/examples/FormControl.md
- src/patternfly/components/FormControl/form-control.scss
fixes https://github.com/patternfly/patternfly/issues/4772
When a form select has the placeholder modifier to turn the selected item text grey in a collapsed select menu, in chrome on linux (and FF on mac, probably other places, too), the placeholder color is applying to the items in the expanded menu, too, and they should not.
These screenshots are from FF on https://www.patternfly.org/v4/components/form-select
> fix(form-control): fixed placeholder variation menu item color

- src/patternfly/components/Card/card.scss
fixes https://github.com/patternfly/patternfly/issues/4770
@wise-king-sullyman this is a fun one! There are certain properties in CSS that create a thing called a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). In short, an element with a stacking context is basically the base z-layer for "positioned" (the `position` property being set to anything other than the default, which is `static) elements. The property here that is creating a new stacking context is `transform` on `.pf-c-card.pf-m-selectable-raised`. It's the property that moves the selected card up a bit to "raise" it. https://github.com/patternfly/patternfly/blob/6e04cbd09b4e9bc7f09fc9a39831ca9d64f773d7/src/patternfly/components/Card/card.scss#L201 …
> fix(card): fix stacking context issue with selectable raised cards

- src/patternfly/components/Tabs/__tabs-item.hbs
- src/patternfly/components/Tabs/__tabs-list.hbs
- src/patternfly/components/Tabs/examples/Tabs.md
- src/patternfly/components/Tabs/tabs-add.hbs
- src/patternfly/components/Tabs/tabs-item-close-icon.hbs
- src/patternfly/components/Tabs/tabs-item-close.hbs
- src/patternfly/components/Tabs/tabs-item-icon.hbs
- src/patternfly/components/Tabs/tabs-item.hbs
- src/patternfly/components/Tabs/tabs.scss
- src/patternfly/demos/PrimaryDetail/primary-detail-template-panel-tabs.hbs
- src/patternfly/demos/Tabs/examples/Tabs.md
- src/patternfly/demos/Tabs/tabs--page-grid-view.hbs
- src/patternfly/demos/Tabs/tabs-template-pod-tab-list.hbs
fixes https://github.com/patternfly/patternfly/issues/4757
There is currently no styling or anything associated with the "add new tab" tab - it's just a regular tab with an icon. @mcarrano @mmenestr wdyt?
> feat(tabs): added close button and add new tab

- src/patternfly/components/DescriptionList/description-list.scss
Fixes #4768 
Fixes text overflowing in data list text (when there are no spaces in the text).
> fix(description-list): fix text wrap

- src/patternfly/components/Menu/menu.scss
Fixes #4748 
I think this fixes it without breaking the scrollable menu but it is difficult to test within core. Here's a codepen with the fix, and the animation speed has been slowed so that you can see it. You can also remove a comment in index.tsx to test with the menu scrollable. https://codesandbox.io/s/drilldown-menu-phantom-scrollbar-fix-s674xf?file=/styles.css
This PR also removes an extra transition duration that was probably left in accidentally during development.
> Remove phantom scrollbar in drilldown menu

- src/patternfly/components/Spinner/spinner.scss
Fixes #3803 to make the legacy CSS spinner go clockwise, as the newer SVG spinner does.
> chore(spinner): reverse the spin of legacy spinner

- src/patternfly/components/Chip/chip.scss
- src/patternfly/components/ChipGroup/chip-group.scss
Fixes #4685 
The overlap in the select shown in the related issue is caused by the chips not ellipsing when the width of the container is too narrow to fit them. This is caused by flex objects having a default min-width of auto rather than 0.
The overflow would also happen to all chip groups besides in the typeahead select (if they were too narrow) and this fixes that as well.
To test, look at chip groups and typeahead select and manually set a max-width on the container to be very narrow.
> fix(chip group): fixes an overflow problem

- src/patternfly/utilities/Text/examples/Text.md
- src/patternfly/utilities/Text/text.scss
Adds utility classes for font families san serif, heading san serif, and monospace, and variable fonts of each of those. Breakpoint modifiers are not included.
Fixes #4764
> feat(utilities): add font family utilities

- src/patternfly/components/FormControl/examples/FormControl.md
Fixes #4858 
Adds documentation relating to #2702, which will be fixed in a future breaking change.
Adds a note on form field component saying that form fields with status icons should turn off autocomplete or use dynamic helper text to indicate status because of a bug/limitation in webkit.
> chore(form field): note autocomplete limitation

- src/patternfly/components/Form/examples/Form.md
- src/patternfly/components/LabelGroup/label-group.scss
- src/patternfly/demos/Form/examples/BasicForms.md
Simplifies the existing [nested field group example](https://patternfly-pr-4865.surge.sh/components/form#expandable-and-nested-field-groups) to scope it to just nested field groups, and moves and expands the existing demo to the [HTML demos](https://patternfly-pr-4865.surge.sh/components/form/html-demos#complex-form).
Fixes #4148
> chore(form): add complex form demo

- src/patternfly/components/ChipGroup/chip-group.scss
closes #4874 
Looks like the `max-width` on `.pf-c-chip-group__list` is the issue. 
**Before:** 
**After:**
**Very narrow:** The list still remains confined by the wrapper without the need for `max-width`.
> fix(chip-group): fixed premature wrapping

- src/patternfly/demos/Table/table-empty-state-table.hbs
- src/patternfly/demos/Table/table-loading-table.hbs
Removed reference to bullseye handle bar code
> Fixes #4872 fix(tabledemo): fixes removal of bullseye layouts

- src/patternfly/components/Menu/menu.scss
Closes #4871 
It looks like PR #4807 fix for the drilldown variant affected the flyout variant. I moved the fix introduced in that PR so that it only applies to the `pf-m-drilldown` class. Using the Codepen linked in this previous PR, I tweaked it a little to show how this fix *should* work (as I also don't believe I can test this solely in Core).
[Drilldown/flyout overflow fix codepen](https://codesandbox.io/s/drilldown-flyout-overflow-fix-s6k07v?file=/styles.css:50-127)
One point I could use clarification on is whether we would still need `overflow-x: hidden;` on line 245. If not, then I could instead replace that with `overflow: hidden` for the same result of this proposed solution it looks like.
> fix(Menu): fix scrollbar on flyout variant

- src/patternfly/components/Card/card.scss
- src/patternfly/components/Card/themes/dark/card.scss
Override the card box shadow in dark theme to provide enough contrast when the card is on the "light" background.
Fixes #4889
> fix(card): fix dark theme card, light bg contrast

- src/patternfly/base/_variables.scss
- src/patternfly/components/Page/examples/Page.md
- src/patternfly/components/Page/page.scss
- src/patternfly/demos/Page/examples/Page.md
- src/patternfly/sass-utilities/functions.scss
- src/patternfly/sass-utilities/mixins.scss
- src/patternfly/sass-utilities/scss-variables.scss
This adds a set of vertical breakpoints that are used for sticky top and bottom modifiers on page components. [Demo for a sticky breadcrumb](https://patternfly-pr-4905.surge.sh/components/page/html-demos#sticky-breadcrumb-on-medium)
Fixes #3660 
As part of this, the functions and mixins for creating utilities were updated to allow creation of vertical breakpoint utilities.
There was previous discussion about whether to try to create two-dimensional media queries. After some thought working through it with this [codepen](https://codepen.io/srambach/pen/dydKQaV?editors=0100), I feel that it's a lot of overhead for not that much advantage. There are some cases that can't really be handled with separate height and width media queries, but I honestly think that would be a sign of a …
> Adds height breakpoints for sticky top and bottom modifiers

- src/patternfly/components/Card/themes/dark/card.scss
- src/patternfly/sass-utilities/themes/dark/placeholders.scss
Previous PR #4889 changed the box shadow of cards on dark background. However, design would like all cards on a dark section to have the same background. 
@mceledonia In some cases, the pf-m-non-selectable-raised card is a different color. Is this the desired result? They are a different color in the normal (light) theme.
> fix(card): force dk theme dk section card bg color

- src/patternfly/components/MenuToggle/examples/MenuToggle.md
- src/patternfly/components/MenuToggle/menu-toggle.scss
Follow-up to #4673, where the hierarchy of elements has been changed in split button and typeahead variants to be `controls -> button -> icon` versus what was previously `button -> controls -> icon`. Padding and margins were adjusted accordingly.
Associated issue: #4666
React issue that needs typeahead toggle: https://github.com/patternfly/patternfly-react/issues/6888
> feat(menu-toggle): updated typeahead variant layout/spacing

- src/patternfly/components/TreeView/examples/TreeView.md
- src/patternfly/components/TreeView/templates/tree-view--base.hbs
- src/patternfly/components/TreeView/tree-view-node-container.hbs
- src/patternfly/components/TreeView/tree-view-node-content.hbs
- src/patternfly/components/TreeView/tree-view-node-text.hbs
- src/patternfly/components/TreeView/tree-view-node-toggle.hbs
- src/patternfly/components/TreeView/tree-view-node.hbs
- src/patternfly/components/TreeView/tree-view-text.hbs
- src/patternfly/components/TreeView/tree-view.scss
fixes https://github.com/patternfly/patternfly/issues/4724
fixes https://github.com/patternfly/patternfly/issues/4725
Makes the node a `div` when the node is selectable (including nodes with checkboxes), and makes the toggle a `button`. This will require a react update to only allow a selectable node to expand when clicking on the node-toggle, otherwise clicking on the node will select it.
This also changes the icon color on hover/focus/active when clicking will expand the node
* hover/focus/active anywhere on a non-selectable node
* hover/focus/active on the toggle on a selectable node
In the original issue, we said that clicking anywhere to the left of a selectable/expandable toggle would also toggle the row, but decided against that since it isn't necessarily intuitive, and it would …
> feat(tree-view): add selectable/expandable, improve click areas

- patternfly-docs/patternfly-docs.config.js
Enables the switch for the dark theme from patternfly-org. Depends on https://github.com/patternfly/patternfly-org/pull/3014 being merged.
Fixes #4936
> [blocked] Enable dark theme switch

- src/patternfly/utilities/BackgroundColor/BackgroundColor.scss
- src/patternfly/utilities/BackgroundColor/themes/dark/BackgroundColor.scss
- src/patternfly/utilities/Text/text.scss
- src/patternfly/utilities/Text/themes/dark/text.scss
Adds dark theme overrides for text color and background color utility classes.
Fixes #4929
> fix(utilities): adjust utility colors in dark theme

- src/patternfly/components/FormControl/examples/FormControl.md
- src/patternfly/components/FormControl/form-control.scss
fixes https://github.com/patternfly/patternfly/issues/4987
fixed the root issue by passing the form control base text color - also updated the disabled state to set `color` so it isn't overridden by other states currently setting `color`.
> fix(form-control): fixed disabled text color

- src/patternfly/components/Popover/popover.scss
Fixes #4781 
applied following:
`--pf-c-popover--c-button--Right: calc(var(--pf-c-popover__content--PaddingRight) - var(--pf-global--spacer--md));`
Initially tried using
`var(--pf-c-button--PaddingRIght) but did not work, in its place I used var(--pf-global--spacer--md)`
> fix(popover): aligned edge of close button icon with content

- src/patternfly/components/Timestamp/examples/Timestamp.md
- src/patternfly/components/Timestamp/timestamp-text.hbs
- src/patternfly/components/Timestamp/timestamp.hbs
- src/patternfly/components/Timestamp/timestamp.scss
- src/patternfly/components/_all.scss
Closes #4801 
[Timestamp preview build](https://patternfly-pr-4996.surge.sh/components/timestamp)
Some notes/items to get feedback on:
- I noticed I still need to remove the CSS variable for textalign; depending on whether there are suggested changes I can lump that in with making those updates
- Originally I had used the `<time>` element for the timestamp text, but per MDN's [time element documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time), if the `datetime` attribute is not provided then the <time> element cannot have any child elements (and must be one of the valid date/time formats on the page). Based on the design docs it seems like the timestamp usage might not really require the time element, but it might be worth looking into offering as an opt-in down …
> feat(Timestamp): create component

- src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly/issues/5009
@mmenestr @mcarrano 
This happens when the section switches between sticky and not. It happened before (a sticky section had more padding than it would if it was not sticky), but it wasn't as visible since the sticky modifier was either on or off - it didn't change dynamically as the viewport height changed.
I wanted to check to see if you think this is an issue. If so, I think we could solve it a couple of ways...
1) Change the padding on the breadcrumb and nav sections so that there is top/bottom padding all of the time (regardless of whether it's sticky or not) that looks appropriate both when the section is sticky and not. That's likely a breaking change as who knows how that might interfere with ways users are using these …
> fix(page): fixed sticky-on section padding

- src/patternfly/components/Avatar/avatar.hbs
- src/patternfly/components/Avatar/examples/Avatar.md
- src/patternfly/components/Dropdown/dropdown.hbs
- src/patternfly/components/MenuToggle/examples/MenuToggle.md
- src/patternfly/demos/Masthead/masthead-template-content-icon-group.hbs
- src/patternfly/demos/Page/page-template-header-tools-elements.hbs
fixes https://github.com/patternfly/patternfly/issues/5023
* Updates the `alt` description in the docs - https://patternfly-pr-5026.surge.sh/components/avatar#accessibility
* Dropdown toggle avatar - https://patternfly-pr-5026.surge.sh/components/dropdown#dropdown-with-image-and-text
* Menu toggle avatar - https://patternfly-pr-5026.surge.sh/components/menu-toggle#with-avatar-and-text
* Masthead menu toggle avatar in full page demo template - https://patternfly-pr-5026.surge.sh/components/page/html-demos/basic/
Also updates the avatar handlebars template logic to simplify things a bit and use the right image by default, so checking the avatar component page would be good - https://patternfly-pr-5026.surge.sh/components/avatar
> chore(avatar): use correct avatar image, simplify hbs

- src/patternfly/components/ContextSelector/context-selector.scss
- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/Dropdown/examples/Dropdown.md
- src/patternfly/components/Select/select.scss
closes #4861 
Possible approach. When popper is used, a duplicate component is added to the DOM. By using an adjacent sibling combinator, we can target non-popper menus.
> fix(dropdown): added menu position combinator

- src/patternfly/components/Menu/menu.scss
fixes https://github.com/patternfly/patternfly/issues/5006
Putting this up for review. We added that bottom border when we created the plain variation of the menu in this PR - https://github.com/patternfly/patternfly/pull/4392. The problem is that the bottom border seems unnecessary in both the default component (when the menu has a box shadow) and the plain variation (box shadow is removed), and creates a double border if you put the menu in something with a border, like a flat card - https://codesandbox.io/s/agitated-sanderson-xjy56g?file=/index.html
> fix(menu): removed footer bottom border when scrollable

- src/patternfly/components/Button/button-count.hbs
- src/patternfly/components/Button/button.scss
- src/patternfly/components/Button/examples/Button.md
- src/patternfly/components/Button/themes/dark/button.scss
This adds a count as an optional component of the button. Design feels this should only be used with the link button (and so only that variant is shown as an example), but for completeness we've made sure the other variants display adequately. 
Direct link: https://patternfly-pr-5029.surge.sh/components/button#link-button-with-a-count
The other variants are shown here:
Other decisions per @mmenestr and @mceledonia:
- The badge color does not change on hover
- Disabling the button causes the badge (even if blue/unread) to display as read/gray.
Fixes #5012
> feat(button): adds a count to the link button

- src/patternfly/components/Page/examples/Page.md
- src/patternfly/components/Page/page.scss
- src/patternfly/demos/Page/examples/Page.md
This adds a modifier to the page component that sets the height using viewport units to eliminate the need to ensure that all elements above the page are set to 100% height.
Fixes #4822
> feat(page): adds full-height modifier

- src/patternfly/base/_base.scss
- src/patternfly/base/_common.scss
- src/patternfly/base/_fonts.scss
fixes https://github.com/patternfly/patternfly/issues/5028
This PR allows you to set a custom `font-size` with this rule that was added to PF4 to override PF3's `font-size` on `html`
https://github.com/patternfly/patternfly/blob/9ab78a81b9d6d63cd7795fa82b1ff673abba5332/src/patternfly/base/_common.scss#L12-L21
An issue with updating this rule is that it's so fundamental, if we introduce a change that inadvertently causes an issue with the way someone is using PF now, it would likely impact the entire site/app.
The solution in this PR is probably the simplest approach, though it does require a value passed for the `font-size`, which may be a limitation since you can't allow `html` to `inherit` its `font-size` from some other dynamic/unknown style. To override the `font-size` with this PR, …
> fix(global): added custom property to override root font-size

- src/patternfly/components/Table/table-scrollable.scss
> feat(table): added max-height to outerscroll

- src/patternfly/components/Button/button.hbs
- src/patternfly/components/Masthead/masthead.scss
- src/patternfly/components/NotificationBadge/examples/NotificationBadge.md
- src/patternfly/components/NotificationBadge/notification-badge.hbs
- src/patternfly/components/NotificationBadge/notification-badge.scss
- src/patternfly/components/NotificationBadge/themes/dark/notification-badge.scss
- src/patternfly/demos/Masthead/masthead-template-content-icon-group.hbs
- src/patternfly/demos/NotificationDrawer/examples/NotificationDrawer.md
- src/patternfly/demos/NotificationDrawer/notification-drawer-template.hbs
> feat(notification-badge): added expanded state

- src/patternfly/components/Page/page.scss
This adds `max-height: 100%;` to the `pf-m-full-height` page modifier to ensure that if a full height page is contained within another container, it does not grow larger than the available space.
To test, go to the [Banner Top/Bottom HTML demo](https://patternfly-pr-5066.surge.sh/components/banner/html-demos/topbottom/) and add `.pf-m-full-height` to the `pf-c-page` element.
> fix(page): set max-height on full height page

- src/patternfly/components/LogViewer/examples/LogViewer.md
- src/patternfly/components/LogViewer/log-viewer.scss
fixes https://github.com/patternfly/patternfly/issues/5067
@DaoDaoNoCode I created a new class for this so we don't change or break the existing line number column width/padding or the existing vars. If you think it's fine just to update, I can remove the need for the class.
Also do you see any issue with moving the font-family/size properties from the index + text elements up to the parent list?
> feat(log-viewer): support for custom line number col size

- src/patternfly/components/ProgressStepper/progress-stepper.scss
Fixes #5024 
This sets `min-width:0` so that the steps will maintain even widths, and allows wrapping of long words without spaces.
Screen shots of all examples with long text for convenience:
> fix(progress-stepper): fix width and long words wrap

- src/patternfly/components/Slider/slider.scss
Fixes #5053 
This fixes excessive (every character) wrapping resulting from an absolutely positioned element within another.
However, note that 
- long words without breaks won't break, and could cause horizontal overlap.
- normal word breaks could cause vertical overlap if there's something directly below
- There are ways to fix this ([more info here](https://codesandbox.io/s/slider-word-wrap-fl44nh?file=/style.css)) but require a fixed min or max width.
> fix(slider): fixed excessive wrapping of labels

- src/patternfly/components/TreeView/examples/TreeView.md
- src/patternfly/components/TreeView/tree-view-node.hbs
- src/patternfly/components/TreeView/tree-view.scss
Makes the text element a `<button>` when a node is selectable and expandable.
convenience link - https://patternfly-pr-5107.surge.sh/components/tree-view#with-selectable-expandable-nodes
---
fixes https://github.com/patternfly/patternfly/issues/5106
> fix(tree-view): made selectable node text a button to fix keyboard a11y

- src/patternfly/components/TextInputGroup/examples/TextInputGroup.md
- src/patternfly/components/TextInputGroup/text-input-group.scss
This removes the rule preventing the chip group from wrapping within a text input group, and changes the min-width from 0 to fit-content so that the chips don't get too small to read. This isn't foolproof at extremely small widths but mostly alleviates the problem.
Also fixed a duplicate id in the example causing an axe error.
Fixes #4885
> fix(text-input-group): fix chip/filter wrapping

- src/patternfly/components/Accordion/examples/Accordion.md
- src/patternfly/components/Alert/examples/Alert.md
- src/patternfly/components/Card/examples/Card.md
- src/patternfly/components/Tabs/examples/Tabs.md
- src/patternfly/components/Tooltip/examples/Tooltip.md
> chore(a11y docs): removed a11y section from example pages

- src/patternfly/components/Tabs/examples/Tabs.md
- src/patternfly/components/Tabs/tabs.hbs
- src/patternfly/components/Tabs/tabs.scss
- src/patternfly/demos/Tabs/examples/Tabs.md
- src/patternfly/demos/Tabs/tabs--page-grid-view.hbs
> fix(tabs): added default border to secondary, cleaned up modifiers

- src/patternfly/components/AppLauncher/app-launcher.scss
- src/patternfly/components/AppLauncher/examples/application-launcher.md
- src/patternfly/components/DatePicker/date-picker.scss
- src/patternfly/components/DatePicker/examples/DatePicker.md
- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/Dropdown/examples/Dropdown.md
- src/patternfly/components/OptionsMenu/examples/options-menu.md
- src/patternfly/components/OptionsMenu/options-menu.scss
- src/patternfly/components/SearchInput/examples/SearchInput.md
- src/patternfly/components/SearchInput/search-input.scss
- src/patternfly/components/Select/examples/Select.md
- src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly/issues/5188
@thatblindgeye this disables the dropdown's `.pf-m-top` modifier from doing anything with the dropdown menu when `.pf-m-static` is set. That was probably just an oversight when we added `.pf-m-static`. You can test it by adding the classes manually in the core workspace.
> fix(dropdown): disabled top positioning when using static variation

- src/patternfly/components/Button/button.hbs
- src/patternfly/components/Tabs/__tabs-all.hbs
- src/patternfly/components/Tabs/__tabs-list.hbs
- src/patternfly/components/Tabs/examples/Tabs.md
- src/patternfly/components/Tabs/tabs-item-action-icon.hbs
- src/patternfly/components/Tabs/tabs-item-action.hbs
- src/patternfly/components/Tabs/tabs-item-close-icon.hbs
- src/patternfly/components/Tabs/tabs-item-close.hbs
- src/patternfly/components/Tabs/tabs-item.hbs
- src/patternfly/components/Tabs/tabs.scss
fixes https://github.com/patternfly/patternfly/issues/5139
Convenience link - https://patternfly-pr-5213.surge.sh/components/tabs#tab-item-actions
* refactors the close and help buttons to be generic tab actions - so we can add more things like this, or open it up to users to add their own actions. Renames the close class and vars, but this is beta in both core and react so should be OK. I can rework that if needed and build help as its own class w/ vars.
* Decreases the spacing a bit after the tab text if it has an action. This lets me easier adjust the spacing between the help button and tab text to be less than the close button and help text. I can rework this if needed.
* before
* after
* updates the examples page a bit to add titles for the sections and groups a bunch of common …
> feat(tabs): added help popover, refactored tab action

- src/patternfly/components/AboutModalBox/about-modal-box.hbs
- src/patternfly/components/AboutModalBox/about-modal-box.scss
- src/patternfly/components/AboutModalBox/examples/AboutModalBox.md
- src/patternfly/demos/AboutModal/about-modal-template.hbs
> refactor(about-modal): moved to modal-box

- src/patternfly/components/FormControl/themes/dark/form-control.scss
Closes #5215 
Previously we were hard coding the incorrect icon in for `--pf-c-form-control__select--BackgroundUrl` in dark theme, but the icon does not change - only the color needs to change.  This PR uses the same `pf-bg-svg` SASS function in dark theme but passes in the third argument (`$svg-color`) to override the color.
Note: The color looks correct now, but I'm unclear of if there's a better variable to use (or new one to create) for this usage.
> fix(formcontrol): fixed form control select dark theme icon

- src/patternfly/components/Button/examples/Button.md
- src/patternfly/demos/Button/examples/Button.md
Removes some hbs test code that was committed in https://github.com/patternfly/patternfly/pull/5135/. Used `git checkout [prev commit hash]` on `[components/demos]/button`
> chore(button): removed test code from #5135

- src/patternfly/components/Dropdown/dropdown-toggle-check.hbs
- src/patternfly/components/Dropdown/dropdown-toggle-progress.hbs
- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/Dropdown/examples/Dropdown.md
fixes https://github.com/patternfly/patternfly/issues/4926
disables the checkbox while in progress to keep the check/label from accepting events while the spinner is shown.
> feat(dropdown): adds loading state for split button checkbox

- src/patternfly/components/Menu/menu.scss
Closes #5241
cc @kmcfaul
I had tracked down what selectors would need to be set to `visibility: hidden` without causing anything else to become visually hidden/cause other bugs. Both Jessie and Nicole were able to confirm that this works with their VoiceOver; I was running into a bug where when drilling out of a menu, the visual VO focus indicator was on the correct menu item, but it would jump to the TS code toggle when trying to navigate to the next item. JAWS and NVDA did not have this issue, though.
@mcoker, in trying to look at other drilldown implementations, I came across [Foundations drilldown menu](https://get.foundation/sites/docs/drilldown-menu.html). The markup looks pretty similar to what we have, though one difference I wanted to mention was their use of an `is-active` class …
> fix(Menu): prevented hidden drilldown items from being focusable

- src/patternfly/components/CalendarMonth/calendar-month.scss
fixes https://github.com/patternfly/patternfly/issues/5222
You can see the year truncate if you set the year to "0000" in chrome. This just bumps the size a bit for cases where that might trigger.
> fix(calendar-month): updated year width to not truncate

- scripts/gulp/html.js
- src/patternfly/components/Select/select.hbs
- src/patternfly/components/Toolbar/examples/Toolbar.md
- src/patternfly/components/Toolbar/toolbar-item-search-filter.hbs
- src/patternfly/components/Toolbar/toolbar.scss
- src/patternfly/demos/Toolbar/examples/Toolbar.md
closes #5030 
This PR adds:
- `.pf-m-align-items-center` to `.pf-c-toolbar__content-section` and `.pf-c-toolbar__group`
- `.pf-m-align-self-center` to `.pf-c-toolbar__group` and `.pf-c-toolbar__item`
- `.pf-m-align-self-baseline` to `.pf-c-toolbar__group` and `.pf-c-toolbar__item`
> fix(toolbar): added center and baseline alignments

- src/patternfly/components/ChipGroup/chip-group.scss
Fixes #5289 
Removes margins within chip group in favor of using gap for spacing.
Some comments included to mark items that can be removed if legacy chip group (without the main container) is removed.
I left a slight difference in spacing between category label and the chips when they wrap because I suspect it was due to lack of row spacing or just oversight? @mceledonia can you let me know which is preferred?
> chore(ChipGroup): use gap instead of item margins

- src/patternfly/components/EmptyState/empty-state-actions.hbs
- src/patternfly/components/EmptyState/empty-state-footer.hbs
- src/patternfly/components/EmptyState/empty-state-header.hbs
- src/patternfly/components/EmptyState/empty-state-icon.hbs
- src/patternfly/components/EmptyState/empty-state-primary.hbs
- src/patternfly/components/EmptyState/empty-state-secondary.hbs
- src/patternfly/components/EmptyState/empty-state-title-text.hbs
- src/patternfly/components/EmptyState/empty-state-title.hbs
- src/patternfly/components/EmptyState/empty-state.scss
- src/patternfly/components/EmptyState/examples/EmptyState.md
Fixes #5138 
[Empty state page](https://patternfly-pr-5307.surge.sh/components/empty-state)
- Body text font size is properly controlled with variables
- The icon must be contained in the icon container
- Title size is driven by the modifier on the title rather than empty state overrides
- Button size is determined by the button modifier rather than empty state overrides
- __primary/__secondary containers are now required if there are primary/secondary actions
- __primary and __secondary containers use flex/gap to space contents
- Rearranged variables for clarity
- Removed Patternfly "4" from example text
> fix(empty-state): cleaned up CSS

- src/patternfly/components/Card/card.scss
- src/patternfly/components/Card/examples/Card.md
- src/patternfly/demos/Card/examples/Card.md
Fixes #4958 by making the `.pf-c-card__header-main` required if there is a `.pf-c-card__header`.
This creates a container so that other items and layouts can be within the header without disturbing the expand icon and actions. Some styling that was specific to title in the header was moved to header-main.
Fixes #3924 by using the correct margin variables.
Pending a design change, it does not directly address having actions wrap below the header main content as requested in #3714, but that would be possible by placing the actions into a layout as desired in the header main.
> feat(card): improve card header

- src/patternfly/components/CodeBlock/examples/CodeBlock.md
fixes https://github.com/patternfly/patternfly/issues/5348
> chore(code-block): updated incorrect class names in docs

- src/patternfly/components/LabelGroup/label-group.scss
Fixes #5294 
Removes margins within label group in favor of using gap for spacing.
Like in the [chip group PR](https://github.com/patternfly/patternfly/pull/5293), there is a slight change to the space between category and label when it wraps - @mceledonia please let me know what spacing is to spec.
> fix(label-group): use gap instead of item margins

- src/patternfly/components/Check/check-input.hbs
- src/patternfly/components/Check/check.hbs
- src/patternfly/components/Check/examples/Check.md
- src/patternfly/components/DataList/data-list-check.hbs
- src/patternfly/components/Dropdown/dropdown-toggle-check.hbs
- src/patternfly/components/Table/Tree-table/table-tr--tree.hbs
- src/patternfly/components/Table/table-check.hbs
- src/patternfly/components/Table/templates/table--radio.hbs
- src/patternfly/demos/DataList/data-list-actionable-data-list.hbs
- src/patternfly/demos/DataList/data-list-expandable-compact-table.hbs
- src/patternfly/demos/DataList/data-list-expandable-data-list.hbs
- src/patternfly/demos/Skeleton/table-skeleton.hbs
- src/patternfly/demos/Table/table-compact-table.hbs
- src/patternfly/demos/Table/table-empty-state-table.hbs
- src/patternfly/demos/Table/table-expandable-table.hbs
- src/patternfly/demos/Table/table-loading-table.hbs
- src/patternfly/demos/Table/table-manage-cols-data-list.hbs
- src/patternfly/demos/Table/table-simple-table.hbs
- src/patternfly/demos/Table/table-sortable-table.hbs
- src/patternfly/demos/Tabs/tabs--table.hbs
> chore: updated components to use standalone checkbox/radio

- src/patternfly/components/AlertGroup/alert-group.hbs
- src/patternfly/components/AppLauncher/app-launcher-menu.hbs
- src/patternfly/components/AppLauncher/examples/application-launcher.md
- src/patternfly/components/Breadcrumb/breadcrumb-list.hbs
- src/patternfly/components/ContextSelector/context-selector-menu-menu.hbs
- src/patternfly/components/DataList/data-list.scss
- src/patternfly/components/Divider/examples/Divider.md
- src/patternfly/components/HelperText/examples/HelperText.md
- src/patternfly/components/HelperText/helper-text-item.hbs
- src/patternfly/components/HelperText/helper-text.hbs
- src/patternfly/components/JumpLinks/jump-links-list.hbs
- src/patternfly/components/List/examples/List.md
- src/patternfly/components/List/list.hbs
- src/patternfly/components/Login/login-main-footer-links.hbs
- src/patternfly/components/MultipleFileUpload/multiple-file-upload-status-list.hbs
- src/patternfly/components/Nav/nav-list.hbs
- src/patternfly/components/NotificationDrawer/notification-drawer-list.hbs
- src/patternfly/components/ProgressStepper/progress-stepper.hbs
- src/patternfly/components/SimpleList/simple-list-list.hbs
- src/patternfly/components/Wizard/wizard-nav-list.hbs
- src/patternfly/demos/Masthead/masthead-template-application-launcher.hbs
Closes #5262 
Some notes:
- Did not update `log-viewer-list` as it doesn't seem to be used anywhere -- There's a template file called `__log-viewer-dynamic-data` that is used in the HTML examples and which the markup matches React examples. 
- Unrelated to this issue, but related to some usage of lists in Core code, the following components needs to be updated to use the applicable role + match React:
- Tabs
- Dropdown
- OptionsMenu
- SearchInput (the list for autocomplete examples)
- OverflowMenu
> fix(lists): added list role to list elements

- src/patternfly/components/Progress/progress.hbs
- src/patternfly/components/Progress/progress.scss
> fix(Progress): prevented empty desc and status from rendering

- src/patternfly/components/Table/table.scss
closes [#4716](https://github.com/patternfly/patternfly/issues/4716)
Preview: 
- https://patternfly-pr-4717.surge.sh/components/table#overflow-menu-usage-mobile 
To view update, remove one of the overflow menu buttons
> fix(table): right align table action cells

- src/patternfly/components/ModalBox/examples/ModalBox.md
- src/patternfly/components/ModalBox/modal-box-close.hbs
- src/patternfly/components/ModalBox/modal-box.scss
- src/patternfly/demos/Modal/examples/Modal.md
- src/patternfly/demos/Table/examples/Table.md
- src/patternfly/demos/Tabs/examples/Tabs.md
Fixes #5362 
Breaking change:
- Adds the `pf-c-modal-box__close` wrapper around the close button. Associated CSS variables are renamed.
> fix(modal): add wrapper to close button

- src/patternfly/components/Table/table.scss
Reverts patternfly/patternfly#4717
#4717 was an old PR and accidentally opened against main, needs to come out since this is a breaking change intended for v5
> fix(table): reverts "right align table action cells"

- src/patternfly/components/LogViewer/examples/LogViewer.md
- src/patternfly/components/Popover/examples/Popover.md
- src/patternfly/components/Popover/popover-close.hbs
- src/patternfly/components/Popover/popover-title-text.hbs
- src/patternfly/components/Popover/popover-title.hbs
- src/patternfly/components/Popover/popover.scss
- src/patternfly/demos/Card/templates/card-demo--popover.hbs
Fixes #4123 
Breaking changes:
- Adds `pf-c-popover__close` around the close button (required if there is a close button)
- Adds `pf-c-popover__header` and `pf-c-popover__title` to all variations (was previously only on icon/alert variations)
- Moves h1 from `pf-c-popover__title` to the `pf-c-popover__title-text`
- Moves the screen reader text in the alert variant to within `pf-c-popover__title-text`
Also removes and renames corresponding css variables.
> feat(popover): add header, title, close elements

- src/patternfly/components/Popover/examples/Popover.md
- src/patternfly/components/Popover/popover-title-text.hbs
Fixes #5404 
Uses screen reader partial
Removes unnecessary documentation of button in popover
Clarifies a11y documentation for screenreader element in popover alert
> docs(popover): update a11y nits

- src/patternfly/components/FormControl/themes/dark/form-control.scss
- src/patternfly/sass-utilities/themes/dark/scss-variables.scss
fixes https://github.com/patternfly/patternfly/issues/5361
@mceledonia @lboehling this updates the form control/text input. What about other things - buttons (specifically control buttons, which match form control styles), menu toggles - anything else? 
FWIW here is a readonly and disabled text input after our disabled buttons:
And some menu toggles, with a readonly and disabled text input after the disabled menu toggle example
> fix(form-control): updated readonly, disabled colors

- src/patternfly/components/Table/examples/Table.css
- src/patternfly/components/Table/examples/Table.md
- src/patternfly/components/Table/table-scrollable.scss
- src/patternfly/components/Table/table-th.hbs
- src/patternfly/components/Table/table.scss
- src/patternfly/components/Table/templates/table--scrollable--tbody--tr.hbs
- src/patternfly/components/Table/templates/table--scrollable--thead--tr.hbs
- src/patternfly/demos/Table/examples/Table.md
closes #5391
This PR adds `right: var(--pf-c-table__sticky-column--Right, revert);` to support righthand sticky column. If the table cell is the first child, `--pf-c-table__sticky-column--Left` is set to `0`. If the table cell is the last child, `--pf-c-table__sticky-column--Right` is set to `0`. There are no other instances in which either value should be `0`.
> feat(table): added support for sticky column on right

- src/patternfly/components/Sidebar/examples/Sidebar.md
- src/patternfly/components/Sidebar/sidebar-main.hbs
- src/patternfly/components/Sidebar/sidebar.scss
> feat(sidebar): added padding and border to sidebar

- src/patternfly/components/Chip/chip.scss
- src/patternfly/components/Toolbar/toolbar-item-search-filter.hbs
- src/patternfly/components/Toolbar/toolbar.scss
closes #3348 
The original request was to add `row-gap` to toolbar, _WITH_ modifiers. I don't think we need modifiers as the original intent was to prevent visual breakages when items/groups wrap and have no spacing. Once [5243](https://github.com/patternfly/patternfly/pull/5243) and [5270](https://github.com/patternfly/patternfly/pull/5270) are finalized and merged, that model will need to be applied to toolbar.
> feat(toolbar): added row-gap to items/content-section

- src/patternfly/components/ContextSelector/context-selector.scss
- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/OptionsMenu/options-menu.scss
Closes #4894
Also updates styling in ContextSelector and OptionsMenu in case.
This approach shouldn't really require any markup changes. The alternative would be doing something more similar to Select/Menu Toggle and place some sort of wrapper inside the toggle button and either apply the styling in this PR to it (like MenuToggle), or remove the styling here and just wrap everything but the arrow icon in a wrapper so that `space-between` doesn't cause spacing issues (similar to Select).
> fix(Dropdown): updated styling to resolve unexpected spacing

- src/patternfly/components/Chip/chip.scss
- src/patternfly/components/DataList/data-list-item.hbs
- src/patternfly/components/DataList/data-list.scss
- src/patternfly/components/DataList/examples/DataList.md
- src/patternfly/components/Table/examples/Table.md
- src/patternfly/components/Table/table-tbody.hbs
- src/patternfly/components/Table/table-tr.hbs
- src/patternfly/components/Table/table.scss
Closes #5347 
- Updated "hoverable"/"selectable" verbiage to "clickable". This includes class names, example text, etc. (several updates made will simply be lines with this update)
- To provide the additional ask of the border for indented datalist items, I removed some left padding and then added a left margin to the `pf-c-data-list` element instead.
Question regarding these components scss files: would the `*-grid.scss` files also need to be updated? It didn't look like the files were interfering with updates made in the `<component>.scss` file, but wanted to double check
> feat(Table/DataList): refactored visual affordances

- scripts/gulp/html.mjs
Fixes #5491 
The `ifEquals` handlebars helper wasn't working with `else if isEquals` as shown in the comment.
This construct is being used in masthead to apply `pf-m-light-200` so you can check that to see that this is working now.
> fix(handlebars): fix ifEquals

- gulpfile.mjs
- scripts/gulp/html.mjs
- scripts/helpers.mjs
Closes #5509
Also refactors helpers to be exported from their own file, with a utility that handles helper registration in their previous location. This has the additional benefit of helping to separate concerns a bit and tries make the approach to helpers a little cleaner.
> build(dev-server): enable hot reloads of helpers

- src/patternfly/components/Page/examples/Page.md
- src/patternfly/components/Page/page.scss
- src/patternfly/demos/Page/examples/Page.md
Fixes #5448 
Removes `.pf-m-full-height` for a page in lieu of defaulting the page to be 100vh/dvh with a max-height so it doesn't overrun the space it's allocated if it's within another layout.
This will need a follow-on issue on .org to limit the width of all the page examples (this is currently done just for a couple of the examples).
> chore(page): default page to full viewport height

- src/patternfly/components/Wizard/wizard.scss
Fixes #4794 
Adjusts z-indexes of wizard components as demonstrated in https://codesandbox.io/s/elated-jerry-1xl9m5?file=/fonts.css
> fix(wizard): adjust z-indexes so menus show with overflow

- src/patternfly/components/Icon/icon.scss
- src/patternfly/sass-utilities/scss-variables.scss
fixes https://github.com/patternfly/patternfly/issues/5265
----
@mceledonia @andrew-ronaldson @mmenestr @lboehling 
A couple of questions
* By default, SVGs and font-based icons (font awesome, pficons in core) will inherit their size based on whatever the text size is where the icon is used. So their default size is `1em` basically. **What is the use case for these icon specific sizes?** As in, when would you want to use an icon-specific size versus making the icon match whatever the text size is? I can see if you have a standalone icon in a thing like a big icon in a card, or like the empty state icon. But if you have an icon beside a title (or any other kind of text)... would you ever want that icon to be a different size than the title? Should it be an option for the icon to match …
> fix(icons): update global icon font sizes

- src/patternfly/components/AboutModalBox/about-modal-box-hero.hbs
- src/patternfly/components/AboutModalBox/about-modal-box.hbs
- src/patternfly/components/AboutModalBox/about-modal-box.scss
- src/patternfly/components/AboutModalBox/examples/AboutModalBox.md
- src/patternfly/components/BackgroundImage/background-image.hbs
- src/patternfly/components/BackgroundImage/background-image.scss
- src/patternfly/components/BackgroundImage/examples/BackgroundImage.md
- src/patternfly/components/FormControl/form-control.scss
- src/patternfly/sass-utilities/scss-variables.scss
fixes https://github.com/patternfly/patternfly/issues/5529, fixes https://github.com/patternfly/patternfly/issues/4930
* No longer shipping the PF logo as the default for about modal and background image in the CSS, with approval from @mceledonia 
* Updated docs for ^ to note the var needed to set the background images
* Removed `$pf-global--image-path` as it's no longer necessary
* Updated form control sprite paths to no longer use the global var path so the SCSS will compile - those paths will be removed in https://github.com/patternfly/patternfly/issues/5469
> fix(about-modal, background-image): updated to not ship default background image

- src/patternfly/layouts/Flex/flex.scss
- src/patternfly/sass-utilities/functions.scss
fixes https://github.com/patternfly/patternfly/issues/5560
this update just reverts the change to `build-spacer-map()` in https://github.com/patternfly/patternfly/pull/5516/files#diff-2c8ba30b3fb18dba9e1c5a24069960a79c0e98016bb4409d5c98821a139af90a, and updates the way spacers are passed to `$pf-v5-l-flex--gap-map` in the flex layout.
> fix(functions): fixed bug with argument order in build-spacer-map

- src/patternfly/sass-utilities/functions.scss
fixes https://github.com/patternfly/patternfly/issues/5577
@mattnolting I just removed the conditional that checks to see if the the spacer passed to `build-spacer-map()` exists in the global spacer map, since that will create an unusable item in that map saying it's an invalid spacer. That seems more like a debug statement, since the map should never be used that way. Removing it will add any non-global-spacer value passed to `build-spacer-map()` with a value of `null`, which is what I'm looking for. Below is a `@debug` of the flex map with "base" in that list. WDYT?
```
Debug: ("base": null, "none": 0, "sm": "var(--pf-v5-global--spacer--sm)", "md": "var(--pf-v5-global--spacer--md)", "lg": "var(--pf-v5-global--spacer--lg)", "xl": "var(--pf-v5-global--spacer--xl)", "2xl": …
```
> fix(sass): allow non-spacers to be added to a spacer map

- src/patternfly/components/Nav/nav.scss
Closes #5406 
Looks like styles for `.pf-c-nav__item` are being applied twice, which is pre-existing behavior. From the Core v5 surge:
From this PR's surge:
> feat(Nav): added top and bottom padding to nav list

- src/patternfly/components/Table/Tree-table/table-tree-view--basic.hbs
- src/patternfly/components/Table/table.scss
closes #5576 
@mcoker 
> Tree with no children or indentation example 
Fix: https://patternfly-pr-5579.surge.sh/components/table#tree-with-no-children-or-indentation
> Compact example - thead is taller than it needs to be due to an issue with the checkbox td cell in the thead.
Fix: https://patternfly-pr-5579.surge.sh/components/table#compact-example
> fix(table): updated table paddings and templates

- src/patternfly/components/Masthead/masthead.scss
- src/patternfly/components/Toolbar/examples/Toolbar.md
- src/patternfly/components/Toolbar/toolbar.scss
closes #5532 closes #5612
Apparently Firefox calculates baseline differently than other browsers. 
Here's an example including this update: https://codesandbox.io/s/relaxed-smoke-qfxw7r?file=/index.html
> fix(toolbar): fixed vertical alignment issue

- src/patternfly/components/ClipboardCopy/examples/ClipboardCopy.md
- src/patternfly/components/DatePicker/examples/DatePicker.md
- src/patternfly/components/FileUpload/examples/FileUpload.md
- src/patternfly/components/Form/examples/Form.md
- src/patternfly/components/FormControl/examples/FormControl.md
- src/patternfly/components/FormControl/form-control.scss
- src/patternfly/components/InlineEdit/examples/InlineEdit.md
- src/patternfly/components/InputGroup/examples/InputGroup.md
- src/patternfly/components/InputGroup/input-group.scss
- src/patternfly/components/Login/examples/Login.md
- src/patternfly/components/NumberInput/examples/NumberInput.md
- src/patternfly/components/NumberInput/number-input.scss
- src/patternfly/components/Pagination/pagination-nav-content.hbs
- src/patternfly/components/Pagination/pagination.scss
- src/patternfly/components/Select/select-toggle-typeahead.hbs
- src/patternfly/components/Wizard/__wizard-form.hbs
- src/patternfly/demos/Alert/alert-template-horizontal-form.hbs
- src/patternfly/demos/Alert/alert-template-stacked-form.hbs
- src/patternfly/demos/Button/button-template-form.hbs
- src/patternfly/demos/Form/examples/BasicForms.md
- src/patternfly/demos/HelperText/examples/HelperText.md
- src/patternfly/demos/Modal/examples/Modal.md
- src/patternfly/demos/PasswordGenerator/examples/PasswordGenerator.md
- src/patternfly/demos/PasswordStrength/examples/PasswordStrength.md
- src/patternfly/demos/Toolbar/examples/Toolbar.md
Fixes #5566
Form control height was previously removed, but is necessary in some cases - however this causes a slight difference elsewhere. 
Alert horizontal and stacked forms
Calendar - no update needed
Clipboard copy
Datepicker
File upload - must set form control option (readonly) with the form-element hbs parameter
Form
Inline edit - also removed a large block of commented code that is no longer needed
Input group
Login
Number input
Pagination
Select
Slider - fixed in https://github.com/patternfly/patternfly/pull/5590
Text input group - no change necessary
Basic forms
Helper text
Modal
Password generator
Password strength
Toolbar
Wizard form
> fix(form-control): update form-control in other components

- src/patternfly/components/MenuToggle/menu-toggle.scss
Closes #5604
@mcarrano Updated some styling for the MenuToggle. You can copy+paste the following code into an example to compare a FormSelect against a MenuToggle typeahead (the markup of a MenuToggle typeahead should be similar to React's Select typeahead)
<details>
<summary>Code to copy</summary>
```
<div class="pf-v5-c-form-control pf-m-placeholder">
<select
class
id="select-selectable-placeholder"
name="select-selectable-placeholder"
aria-label="Selectable placeholder select example"
>
<option value selected>Selectable placeholder</option>
<option value="Mr">Mr</option>
<option value="Miss">Miss</option>
<option value="Mrs">Mrs</option>
<option value="Ms">Ms</option>
<option value="Dr">Dr</option>
<option value="Other">Other</option>
</select>
<div …
```
> fix(MenuToggle): updated spacing of toggle icon

- src/patternfly/components/FormControl/form-control.scss
- src/patternfly/components/FormControl/themes/dark/form-control.scss
Updates the form control to move the borders to pseudo elements, remove all of the custom height and padding `calc()`s that were needed to offset the borders since they were part of the component layout.
> fix(form-control): move borders to pseudo element, remove extra css

- src/patternfly/components/Nav/examples/Navigation.md
- src/patternfly/components/Nav/nav.scss
Closes #5592 
@mcoker @andrew-ronaldson Tried comparing examples/demos that had screenshots in the previous PR to the local build for this update. Seemed like the local build matched what was expected visually, but some spacing between screenshots was pretty close to call for me.
It seems like the issue was more tied to a section that also had `pf-m-no-title`, so the following also seemed to work:
```
&.pf-m-no-title {
--#{$nav}__list--PaddingTop: 0;
--#{$nav}__section--MarginTop: 0;
}
```
> fix(Nav): updated spacing for grouped nav

- src/patternfly/components/Masthead/masthead.scss
- src/patternfly/components/Toolbar/toolbar-item-search-filter.hbs
- src/patternfly/components/Toolbar/toolbar.scss
closes #5557 
The layout shift was caused by adding `row-gap` https://github.com/patternfly/patternfly/blame/13ed13afc9c20557d88d90533b2fdb9af646ca71/src/patternfly/components/Toolbar/toolbar.scss#L383
So I moved the expandable content background to a `::before` pseudo.
> fix(toolbar): updated positioning of expanded content

- src/patternfly/components/Switch/examples/Switch.md
- src/patternfly/components/Switch/switch-toggle-icon-disabled.hbs
- src/patternfly/components/Switch/switch.scss
- src/patternfly/components/Switch/themes/dark/switch.scss
Adjusted the disabled switch in dark mode so that the colors match the other dark mode switches. Also added extra switches to include option with check.
Closes https://github.com/patternfly/patternfly/issues/5622
> fix(core): darkened circle icon to match dark theme

- src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly/issues/5697
screenshots - I just added a select component to a demo with a toolbar in dev tools to validate.
before
after
> fix(select): fixed typeahead form control border styles

- src/patternfly/components/FormControl/examples/FormControl.md
- src/patternfly/components/FormControl/form-control-icon.hbs
- src/patternfly/components/FormControl/form-control-select.hbs
- src/patternfly/components/FormControl/form-control-utilities.hbs
- src/patternfly/components/FormControl/form-control.hbs
Fixes #5701 
Changes all the divs in a form control to be spans to allow a form control to be inside phrasing content.
> fix(form-control): change divs to spans

- src/patternfly/components/Toolbar/toolbar.scss
fixes https://github.com/patternfly/patternfly/issues/5767
This just reverts the alignment to what it was before. The label alignment isn't great, but we don't have any open issues against that, so I don't think it's something we need to fix for this release. Assuming it reverts the layout properly, we shouldn't need to test it extensively or worry about inadvertent side effects.
> fix(toolbar): revert alignment of chip/filter layout

- src/patternfly/components/Badge/examples/Badge.md
closes: [#5230](https://github.com/patternfly/patternfly/issues/5230)
> chore(badge): added screenreader to unread badges

- src/patternfly/components/Menu/menu.scss
fixes https://github.com/patternfly/patternfly/issues/5786
> fix(menu): keep description from wrapping mid-word

- src/patternfly/components/Button/examples/Button.md
- src/patternfly/components/Select/__select-menu-descriptive.hbs
- src/patternfly/components/Select/deprecated/Select.css
- src/patternfly/components/Select/deprecated/Select.md
- src/patternfly/components/Select/select-toggle-typeahead.hbs
- src/patternfly/components/Select/select.hbs
Fixed some of the hidden labels in the HTML examples on Select page. Some were saying to choose one when multiple could be selected. Adjusted to reflect that.
Closes: [#5653](https://github.com/patternfly/patternfly/issues/5653)
> chore(select): fixed text in HTML example to show multiple checks can be selected

- src/patternfly/components/Dropdown/dropdown.scss
- src/patternfly/components/Label/label-group.scss
- src/patternfly/components/ProgressStepper/progress-stepper.scss
- src/patternfly/components/Sidebar/sidebar.scss
The element it looks like autoprefixer is warning about was introduced in v5, but it looks like we have the same issue in a few other components, too. autoprefixer likely isn't catching them, I'm guessing, because either they aren't using/processing those component styles and/or the offending values are used in custom properties (css vars) and I don't know if autoprefixer can go as far as to trace the value of vars back through the CSS and see if the value is used on/in a flex layout.
IMO this isn't a showstopper since it's pre-existing in other places, and AFAIK no one has flagged it on any of the other components. But we should at least update it for good measure since it is also in violation of the browser support we currently have documented - Safari only supports the current value in …
> fix: updated use of flex start/end to be more compatible

- src/patternfly/components/Chip/chip.scss
fixes https://github.com/patternfly/patternfly/issues/5842
I copied the markup from the [react chip example with a badge](https://www.patternfly.org/components/chip/#chip-variants) into the core workspace for this PR
> fix(chip): add margin for badge when used in text element

- src/patternfly/base/_common.scss
- src/patternfly/base/_variables.scss
- src/patternfly/components/Chip/examples/Chip.md
- src/patternfly/components/DragDrop/examples/DragDrop.css
- src/patternfly/components/DualListSelector/dual-list-selector.scss
- src/patternfly/components/Label/examples/Label.md
- src/patternfly/components/Pagination/pagination.scss
- src/patternfly/components/Switch/switch.scss
- src/patternfly/components/Wizard/examples/Wizard.md
- src/patternfly/components/Wizard/wizard.scss
- src/patternfly/sass-utilities/mixins.scss
fixes https://github.com/patternfly/patternfly/issues/5839
fixes https://github.com/patternfly/patternfly/issues/5840
----
* Adds a `pf-v5-rtl($transform)` mixin that manages 2 things so far:
* Handles selector(s) we'll use to wrap RTL styles.
* Currently works on `.ws-dir-rtl, .#{$pf-prefix}m-dir-rtl, [dir="rtl"]`.
* Can return helpful, common blocks of CSS with a preferred way of doing some RTL transform by passing a `$transform`. 
* Added a "flip-inline" transform that applies `scale: -1 1`
* Adds `.pf-v5-m-rtl-flip-inline` as a helper class to flip something horizontally (inline), and gets its code from ^ `pf-v5-rtl($transform: "flip-inline")`
* Adds `.pf-v5-m-dir-rtl` to apply `direction: rtl;` to something
* Adds `.pf-v5-m-dir-ltr` to apply `direction: ltr;` to something if you …
> fix: added base, wizard, pagination RTL styles

- src/patternfly/demos/Card/examples/Card.md
fixes https://github.com/patternfly/patternfly/issues/5850
should help with the screenshot tool generating false positives since the screenshot sometimes fires before the image has finished downloading
> chore(card): updated horiz demo image

- src/patternfly/components/Alert/alert.scss
- src/patternfly/components/NotificationDrawer/notification-drawer.scss
Closes #5817 
closes #5818 
For both Alert and Notification drawer, the truncation is slightly different between Chromium and Firefox when viewing an example in a new window (viewing the examples normally on the component page things like fine). In Chromium a line clamp of 1 seems to cause the first word to be cut off, while a line clamp greater than 1 seems to truncate okay (same screenshot from the alert/hint issue linked above):
In Firefox, it seems to be the reverse; line clamp of 1 truncates okay, while line clamp greater than 1 causes the first word of the last line to be cut off:
Since it seems to more have this affect if the Alert is wide enough it may not be a huge issue. This could also just be an issue with the Core examples, as applying `dir="rtl"` to the `html` tag in the …
> chore(Alert,NotificationDrawer): added additional rtl styling

- src/patternfly/components/Menu/menu.scss
- src/patternfly/components/Nav/nav.scss
Fixes up carets on navigation and scrollable navigation buttons. Fixed menu as part of drilldown navigation.
Navigation demos appear broken but should be fixed by Sidebar RTL fixes.
No fixes needed for masthead(?)
Fixes #5761
> chore(Nav, Menu): apply RTL fixes

- src/patternfly/components/Popover/examples/Popover.css
- src/patternfly/components/Popover/examples/Popover.md
- src/patternfly/components/Popover/popover.scss
- src/patternfly/components/Tooltip/examples/Tooltip.css
- src/patternfly/components/Tooltip/examples/Tooltip.md
- src/patternfly/components/Tooltip/tooltip.scss
fixes https://github.com/patternfly/patternfly/issues/5829
Adds support for the top/left/right/bottom/etc modifiers as logical equivalents since those are a little more clear. Uses `:is()` so it should actually decrease the size of those stylesheets with the additional modifiers. Also adds support for `.pf-m-text-align-start` on tooltip content.
I think we'll want these modifiers eventually, though we don't have to add them, or add prop vals for them in react as part of this release, but we could. And if we keep them, we could also update our examples to use them by default, as the preferred way to set the popover/tooltip direction. Thoughts?
> fix(popover, tooltip): added rtl styles

- src/patternfly/components/Table/examples/Table.md
- src/patternfly/components/Table/table-scrollable.scss
- src/patternfly/components/Table/table-tree-view.scss
- src/patternfly/components/Table/table.scss
Closes #5826 
Added logical class names for left/right modifiers for the sticky table as well. If we want to keep them, I wasn't sure how best to rewrite the class description. "Initiates a sticky table cell along the ending/starting side of a table" was about all else I could think of.
> chore(Table): added additional RTL styling

- src/patternfly/components/ModalBox/examples/ModalBox.css
Changes centering of the modal in the examples from grid to flex. Now matches how bullseye centers.
Fixes #5900
> fix(ModalBox): fix centering on mobile

- src/patternfly/components/Popover/examples/Popover.css
fixes https://github.com/patternfly/patternfly/issues/5901
the pagination examples are fine, the result of fixing the pagination markup in a toolbar demo from a previous PR.
> chore(popover): center examples

- src/patternfly/components/Nav/examples/Navigation.css
Fixes #5899 
• Looks like the [third level expandable example](https://www.patternfly.org/components/navigation/html#expandable-third-level) had an [explicit background color set](https://github.com/patternfly/patternfly/commit/447630c3449372332ee1628268397f16f5ffa965#diff-c0c17bbec61392998ccf9e8532dc141d0f007e6bc152355119b66317925f671cR1). I'm not entirely sure how backstop is drawing and comparing examples, but it doesn't seem to be appearing in localhost. Added the example css declaration back to navigation.css.
• Tabs are fine. Backstop seems to be throwing an error bc of scroll position. 
**.org**
**localhost**
> fix(nav): updated example css

- src/patternfly/components/DualListSelector/dual-list-selector--actions.hbs
- src/patternfly/components/DualListSelector/examples/DualListSelector.md
- src/patternfly/components/OptionsMenu/deprecated/options-menu.md
- src/patternfly/demos/Toolbar/toolbar-template.hbs
fixes https://github.com/patternfly/patternfly/issues/5918
Updates icons you can see in these examples:
/components/dual-list-selector
/components/table/html-demos/basic - there are separate icons for mobile and desktop to verify
/components/menus/options-menu#plain
> chore: mirror fa-sort icon

- src/patternfly/components/CodeEditor/code-editor-code.hbs
- src/patternfly/components/CodeEditor/code-editor.scss
This updates the `__code` element to use `dir="ltr"` so it will always be LTR. Everything else adapts to RTL as normal.
fixes https://github.com/patternfly/patternfly/issues/5927
> fix(code-editor): make code box and header LTR

- src/patternfly/sass-utilities/themes/dark/mixins.scss
fixes https://github.com/patternfly/patternfly/issues/5932
Looks like this mixin was meant to mimic the light theme mixins that have a conditional for the arg that gets passed
https://github.com/patternfly/patternfly/blob/c2db12236403508c577fc7c3cc524e29961f9dca/src/patternfly/sass-utilities/mixins.scss#L170-L182
> fix(banner): fixed invalid dark theme color declaration

- src/patternfly/components/Button/button.scss
- src/patternfly/components/Button/examples/Button.md
Closes #5351 
@mceledonia @mcoker This draft currently only extends inline support to the plain button. I did try seeing what similar styling might look like for other button variants, for example the primary variant:
One thing to note is that with the Tabs component's action buttons (close and help), the icon becomes a little bigger than it currently is (can be fixed by adding a font size CSS var for pf-v5-c-tabs__item-action), and the outline on focus gets a little overlapped on the top and bottom:
We could use the current outline offset in the Tabs css (-0.1875rem), though that might make it feel cramped using `--pf-v5-global--FontSize--xs` (worse if the font size is custom and smaller than this):
This is also assuming we'd want to move the button styling out of the Tabs scss. If not, …
> feat(Button): extended inline styling

- src/patternfly/components/Popover/examples/Popover.md
- src/patternfly/components/Popover/popover.scss
- src/patternfly/components/Tooltip/examples/Tooltip.md
- src/patternfly/components/Tooltip/tooltip.scss
fixes https://github.com/patternfly/patternfly/issues/5951
This also simplifies the CSS a bit, makes everything a variable, and makes everything's `top`, `right`, `bottom`, and `left` position provide the actual position for where the arrow should be. Previously a couple of variations were using the arrow's width as the values for some of those position properties. What that will allow is better control of the arrow position via setting CSS vars for a feature it looks like we want to introduce in popper - [overflow prevention](https://codesandbox.io/s/github/floating-ui/popper.js.org/tree/master/examples/overflow-prevention). That allows the popper element to act as if it's sticky to an overflow edge as overflow is scrolling, and the arrow's position updates dynamically as you scroll …
> fix(popover/tooltip): revert arrow logical prop positioning

- src/patternfly/components/Switch/switch.scss
Closes #5481 
Question for @andrew-ronaldson and/or @lboehling: I did a quick check of some of our other components, and curious whether you think a similar update should/could be made to our Slider and Toggle Group styles. For the Slider, when you click the thumb the focus style remains:
For Toggle Group, a clicked item that isn't selected and a selected item are fairly similar in look. In the following screen shot, Option 2 was clicked to select it, then Option 1 was clicked to deselect it (but it still retains focus after clicking). The styling is more similar in light theme (to me), and would be even more most likely to a user with some form of color blindness:
Unrelated to the above, but I did some basic testing using [Talon](https://talonvoice.com/) to see how an interaction works …
> fix(Switch): updated focus style to focus-visible

- src/patternfly/components/Accordion/accordion.hbs
- src/patternfly/components/Accordion/accordion.scss
- src/patternfly/components/Accordion/examples/Accordion.md
Closes #5426 
For context, I went with a medium spacer since it looked closer to the spacing between the toggle icon and toggle text when the text is truncated:
Opted to place the modifier on the top level `pf-v5-c-accordion` element since having that modifier on the individual `pf-v5-c-accordion__toggle` elements, there's the possibility to mix and match left and right aligned accordion toggles within the same accordion which isn't ideal. Having it on the top level element would sort of prevent that as the styling wouldn't be correct for the default accordion toggle positioning (the toggle icon would no longer be positioned at the end of the toggle)
> feat(Accordion): added left-aligned toggle variant

- src/patternfly/base/tokens/_tokens-font.scss
- src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly/issues/6034
the beans:
> fix(box-shadow): typo in box shadow token names

- src/patternfly/components/Page/page.scss
The nav component will provide the spacing on the left edge of the page, so this removes the padding on the page sidebar that contains the nav. Added a margin to the page sidebar title to compensate.
fixes #6052
> feat(page): remove padding on nav sidebar

- src/patternfly/base/tokens/_tokens-font.scss
- src/patternfly/components/Alert/alert.scss
- src/patternfly/components/Page/page.scss
Result of a discussion with @lboehling
Bold body font weight should be 500.
Heading font weight - for now keep both base tokens at 700. They might adjust in the future.
Remove any uses of the semantic bold heading token to date in favor of the (regular) heading font weight token.
> fix(tokens): adjust font-weight base for headings

- src/patternfly/base/_common.scss
- src/patternfly/base/tokens/_tokens-font.scss
fixes https://github.com/patternfly/patternfly/issues/6072
I didn't add any base vars for the legacy font families/weights. It's a global opt-in, design should never need to use it - it's just for products if they aren't ready to change their font-weights to use VF, and imagine we'll drop this support with the next major release so I don't think we need to make room for it outside of overriding the existing vars. LMK if that sounds alright!
This probably won't look right until https://github.com/patternfly/patternfly/pull/6070/ goes in, since #6070 updates the bold body text token to use `500`. @lboehling if https://github.com/patternfly/patternfly/pull/6070/ looks OK, we can merge that and rebase this PR so you can see the change.
> fix(font): use variable font, add opt-in for legacy font

- src/patternfly/base/_globals.scss
- src/patternfly/base/tokens/_tokens-font.scss
- src/patternfly/components/Accordion/accordion.scss
- src/patternfly/components/Alert/alert.scss
- src/patternfly/components/Banner/banner.scss
- src/patternfly/components/Button/button.scss
- src/patternfly/components/Content/content.scss
- src/patternfly/components/Hint/hint.scss
- src/patternfly/components/Login/login.scss
- src/patternfly/components/MenuToggle/menu-toggle.scss
- src/patternfly/components/ModalBox/modal-box.scss
- src/patternfly/components/Nav/nav.scss
- src/patternfly/components/Table/table.scss
- src/patternfly/components/Title/title.scss
This builds on the update of the font tokens coming from Figma. It removes font size tokens from the non-generated font token file, except for heading sizes xs-2xl, which haven't been added to figma. These are still used in a few components when it's not clearly a particular heading level (h tag).
> chore(tokens): updating usage of new font tokens

- src/patternfly/components/Card/card--check.hbs
- src/patternfly/components/Card/card--radio.hbs
- src/patternfly/components/Card/card.scss
- src/patternfly/components/Check/examples/Check.md
- src/patternfly/components/MenuToggle/menu-toggle.scss
- src/patternfly/components/Radio/examples/Radio.md
fixes https://github.com/patternfly/patternfly/issues/6007
Fixes everything except https://core-staging.patternfly.org/components/card/#clickable-and-selectable
Looking at that, here are some issues aside from the misalignment:
* The presence of the checkbox is changing the layout/spacing compared with a card without it (delete the checkbox and watch the layout change)
* The checkbox is using the standalone variation, but the label element is present - the standalone variant should only have the checkbox input as a child.
In those examples, probably the simplest way to fix that is to remove `.pf-m-standalone`? That isn't ideal, but it addresses the issues mentioned above. 
Longer term, I wonder if those checkboxes (in all of the selectable/clickable card variants) can be updated to the …
> fix(card/menu-toggle/check): alignment bugs

- src/patternfly/components/Divider/divider.scss
- src/patternfly/components/Divider/examples/Divider.css
- src/patternfly/components/Divider/examples/Divider.md
closes #6136 
Couple of things to note
• Added `// * {Component}` to `:root` variable comments to make them searchable by `{Component}` or `* {Component}`
• Added `// - {Component}` to component/elements comments to make them searchable by `{Component}` or `- {Component}`
• Removed unnecessary `::after` styling and breaking change comments
• Simplified implementation
> chore(divider): added tokens, fixed breaking change comments

- src/patternfly/components/DragDrop/drag-drop.scss
- src/patternfly/components/DragDrop/examples/DragDrop.css
- src/patternfly/components/DragDrop/themes/dark/drag-drop.scss
Closes #5740
As design for penta drag and drop is still in flight (for both the current and new implementations) this PR updates the current styling to use the new tokens. A follow up may be required later if the design changes.
> feat(DragDrop): use tokens

- src/patternfly/base/tokens/_tokens-default.scss
- src/patternfly/components/ToggleGroup/toggle-group.scss
This addresses the adjacent borders in #6202 (but not the mobile is too-wide and cut off problems)
This adds a token that has already been added in Figma, and fixes the block comment on that file that lint complains about.
It splits the border into parts so that the left side can be set to the right color to divide two blocks of the same color. Fallbacks are used so that if the individual border colors aren't set, it falls back to the overall border color.
> feat(ToggleGroup): add border between like toggles

- src/patternfly/components/Button/button.scss
[convenience link to button preview](https://patternfly-pr-6256.surge.sh/components/button)
fixes https://github.com/patternfly/patternfly/issues/6224
* adds back mix-blend-mode that was accidentally removed in https://github.com/patternfly/patternfly/pull/6057/files#diff-5c706547718d6a7568e1ac13d2effe9bea08a57effb763ab9ec373d2dab9b450
* Updates mix-blend-mode to only apply to hover/focus/clicked
* Unsets mix-blend-mode for inline links
* Fixes clicked control button icon style (had a dupe `--Color` var instead of `__icon--Color`)
* Reorganizes the vars a little
> fix(button): update plain disabled, fix mix blend mode

- src/patternfly/components/Pagination/pagination.scss
> fix(Pagination): updated width logic for page selection

- src/patternfly/components/Button/button.scss
Somehow this is fine for the react build, but the integration build is failing from the missing semicolon.
> fix(Button): add missing semicolon

- src/patternfly/base/tokens/_tokens-charts.scss
- src/patternfly/base/tokens/_tokens-dark.scss
- src/patternfly/base/tokens/_tokens-default.scss
- src/patternfly/base/tokens/_tokens-font.scss
- src/patternfly/base/tokens/_tokens-palette.scss
- src/patternfly/components/Accordion/accordion.scss
- src/patternfly/components/Button/button.scss
- src/patternfly/components/Label/label.scss
- src/patternfly/components/Menu/menu.scss
- src/patternfly/components/MenuToggle/menu-toggle.scss
- src/patternfly/components/SimpleList/simple-list.scss
- src/patternfly/components/Tabs/tabs.scss
- src/patternfly/components/Wizard/wizard.scss
Tokens updated
- Box shadow tokens from figma added
- Box shadows built from constituent tokens
- Clicked changed to use opacity rather than blend mode
- Some additional color changes
Components:
- Mix blend mode removed
- Accordion `--selected` token changed to `--clicked`
- Fixed some missing semicolons in button
> feat(tokens): update tokens, add opacity, box-shadow tokens

- src/patternfly/components/ModalBox/modal-box.scss
Fixes #6380 
Hardcoded v5 variable left in erroneously.
> fix(modal): remove erroneous v5 variable in close button

- src/patternfly/components/Check/check.scss
- src/patternfly/components/Radio/radio.scss
- src/patternfly/components/Table/Tree-table/table-tr--tree.hbs
- src/patternfly/components/Table/table-check.hbs
- src/patternfly/components/Table/table-td.hbs
- src/patternfly/components/Table/table.scss
- src/patternfly/components/Table/templates/table--check.hbs
- src/patternfly/components/Table/templates/table--radio.hbs
- src/patternfly/demos/DataList/data-list-expandable-compact-table.hbs
- src/patternfly/demos/Page/examples/Penta.md
- src/patternfly/demos/Skeleton/table-skeleton.hbs
- src/patternfly/demos/Table/table-compact-table.hbs
- src/patternfly/demos/Table/table-empty-state-table.hbs
- src/patternfly/demos/Table/table-expandable-table.hbs
- src/patternfly/demos/Table/table-loading-table.hbs
- src/patternfly/demos/Table/table-simple-table.hbs
- src/patternfly/demos/Table/table-sortable-table.hbs
- src/patternfly/demos/Tabs/tabs--table.hbs
Applies to #6294 
This PR fixes standalone padding vertical alignment. The standalone variant lacks consideration in context. This code takes a line height and font size to calculate a height, then uses default alignment of center to position vertically, but will respond to alternative alignments.
> fix(check): update standalone styling

- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Table/table-scrollable.scss
- src/patternfly/components/Table/table-tree-view.scss
- src/patternfly/components/Table/table.scss
relates to #6324 
This updates makes variables and selectors searchable by updating them to match BEM names. Prefixing with `*` results in variable definitions, prefixing with `-` results in selector definitions. Omitting prefix results in either/both.
> chore(table): updated code comments, made searchable

- src/patternfly/components/FormControl/form-control.scss
Towards https://github.com/patternfly/patternfly/issues/5695 and #5751 
Need to test this update in other OS/browser combos to ensure nothing visually breaks.
Would most likely need a v6 update as well if we go forward with this.
> fix(FormControl): updated select styling in light and dark themes

- src/patternfly/components/Table/table.scss
references #6293 
This PR 
- Adjusts table text truncate `min-width`
- Adjusts nested table header sort buttons
Before:
After:
Before: 
After:
> chore(table): updated truncate width, nested button

- src/patternfly/components/Label/examples/Label.md
- src/patternfly/components/Label/label-content.hbs
- src/patternfly/components/Label/label-template-variants.hbs
- src/patternfly/components/Label/label.hbs
- src/patternfly/components/Label/label.scss
fixes https://github.com/patternfly/patternfly/issues/6055
* Moves the template hbs file to the root label component dir since the workspace doesn't auto-compile-n-reload on files nested in subdirs.
* Sets the close button color in a disabled label to the same color as the disabled text, since by default a disabled close button color is the same color as the disabled label background.
* Just setup to work on regular (filled/outline) labels - not the overflow or add. It's easy enough to add support for those, or we could add that support if/when it comes up. wdyt @lboehling @andrew-ronaldson?
> fix(label): added support for disabled labels

- src/patternfly/base/tokens/_tokens-charts.scss
- src/patternfly/base/tokens/_tokens-dark.scss
- src/patternfly/base/tokens/_tokens-default.scss
- src/patternfly/base/tokens/_tokens-palette.scss
Fixes #6472 
NOTE: This also updates the selector for the dark tokens to v6, so the dark theme switcher will not work until it filters through everywhere. @nicolethoen
> chore(tokens): add semantic spacers, update dark selector

- src/patternfly/base/tokens/_tokens-font.scss
- src/patternfly/components/Alert/alert.scss
- src/patternfly/components/Breadcrumb/breadcrumb.scss
- src/patternfly/components/Card/card.scss
- src/patternfly/components/DataList/data-list.scss
- src/patternfly/components/Drawer/drawer.scss
- src/patternfly/components/FormControl/form-control.scss
- src/patternfly/components/Hint/hint.scss
- src/patternfly/components/JumpLinks/jump-links.scss
- src/patternfly/components/Popover/popover.scss
Closes #6363 
Only updated TODOs/existing form element vars to tokens. Started to update instances of t-shirt spacers, but that may depend on naming (for example, plain buttons would need a new token added, but does `--pf-t--global--spacer--button--plain--default`/`--pf-t--global--spacer--button--plain--compact` make sense?). Also using the same spacer on different components could cause different spacing than possibly intended (had placed a spacer on the Text Input Group left/right padding as well as a Drawer close button's padding or margin, and it results in one of them having significant difference than current spacing; couldn't really think of a good name for a new token other than maybe "--enlarged" or "--extra-compact" and such)
> chore(tokens): updated form element spacers to tokens

- src/patternfly/demos/Card/examples/Card.md
- src/patternfly/utilities/Text/examples/Text.md
Replaces some utility class use with the timestamp component and icon component. Also removes an un-supported light font weight.
Fixes #6496
> fix(card): clean up utility classes in demos

- src/patternfly/components/Select/select-chip-group-collapsed.hbs
- src/patternfly/components/Select/select-chip-group-expanded.hbs
- src/patternfly/components/TextInputGroup/examples/TextInputGroup.md
- src/patternfly/components/TextInputGroup/text-input-group--chip-group.hbs
- src/patternfly/components/Toolbar/examples/Toolbar.md
- src/patternfly/components/Toolbar/templates/toolbar--chip-group.hbs
- src/patternfly/components/Toolbar/templates/toolbar--item-chip-group.hbs
- src/patternfly/demos/DescriptionList/examples/DescriptionList.md
- src/patternfly/demos/Toolbar/examples/Toolbar.css
- src/patternfly/demos/Toolbar/examples/Toolbar.md
Closes #5345 & #5346
LMK if I should change all references to chips in the examples, for now I've just replaced the usages of the chip component itself (so did not convert things like `text-input-group--chip-group` to `text-input-group--label-group`).
> feat(misc): convert chip to label in examples

- src/patternfly/components/LogViewer/log-viewer.scss
fixes https://github.com/patternfly/patternfly/issues/6367
Updates the log viewer styling. The menus at the top should be updated in https://github.com/patternfly/patternfly/pull/6566
One thing I didn't see called out in the design was the "matched" highlight. Is the text color in light theme OK? Highlight text is just using the default text color.
The highlight color with text in dark theme isn't accessible though. I see there is a mix-blend-mode in figma for the highlight color. WDYT @lboehling? Should I make an update to the CSS? I'm wondering if we should have text color tokens for use with the highlight background colors?
> fix(log-viewer): add tokens

- src/patternfly/components/DataList/data-list.scss
Closes #6555 
This PR updates the default DataList and DataListItem borders from `--pf-t--global--spacer--sm` to `--pf-t--global--border--width--strong`
> chore(datalist): reduce mobile borders to 2px

- src/patternfly/components/Hint/hint.scss
closes #6570 
This PR adds `align-self: start` to the hint actions to keep them from filling available space.
> fix(hint): top-align hint actions

- src/patternfly/base/tokens/tokens-charts-dark.scss
- src/patternfly/base/tokens/tokens-charts.scss
- src/patternfly/base/tokens/tokens-dark.scss
- src/patternfly/base/tokens/tokens-default.scss
- src/patternfly/base/tokens/tokens-palette.scss
- src/patternfly/sass-utilities/scss-variables.scss
This adds back css variables for breakpoints as tokens. They should match the scss variables, but the scss variables are still required for use in media queries. 
Fixes #6613
> fix(breakpoints): add css variables for breakpoints

- src/patternfly/patternfly-charts.scss
fixes https://github.com/patternfly/patternfly/issues/5949
There is an issue with some of the charts tokens not being generated because of their "string" type not supported in the exporter, but that should be fixed soon. This PR only references tokens that are generated, so we'll need a follow up once those tokens are available.
I don't know that there is much to verify for now<sup>[1]</sup> since I don't believe we can pull this change into react yet. Here is the original PR that took out the charts scss/global vars if anyone wants to reference that - https://github.com/patternfly/patternfly/pull/6533/files
1. Just to clarify, this PR and core should be good to pull into react as-is, but I believe pulling into react is currently blocked by …
> fix(charts): add tokens

- src/patternfly/base/tokens/tokens-charts-dark.scss
- src/patternfly/base/tokens/tokens-charts.scss
- src/patternfly/base/tokens/tokens-dark.scss
- src/patternfly/base/tokens/tokens-default.scss
- src/patternfly/base/tokens/tokens-palette.scss
fixes https://github.com/patternfly/patternfly/issues/6685
~~@lboehling just want to make sure the changes to the hex values in the palette token file are intentional? Looks to just change a handful of shorter hex values to the long/full value (eg `#06c` to `#0066cc`)~~ nevermind, core has a linter rule that complains about long hex values that can be shorter. Let the linter fix it for now, we may consider aligning on that format in the future
> fix(charts): update dark label color token

- src/patternfly/patternfly-charts.scss
Included screenshots since the changes are only visible in the react codebase. Screenshots are from my local react dev server with the core npm package linked to this branch's dist build.
fixes https://github.com/patternfly/patternfly/issues/6681
* dark theme labels 
* cyan charts (also in ^)
* bullet charts
* threshold
> fix(charts): color/token updates

- src/patternfly/components/Nav/examples/Navigation.md
- src/patternfly/components/Nav/nav-link-icon.hbs
- src/patternfly/components/Nav/nav-link-text.hbs
- src/patternfly/components/Nav/nav-link.hbs
- src/patternfly/components/Nav/nav.scss
fixes https://github.com/patternfly/patternfly/issues/6527
fixes https://github.com/patternfly/patternfly/issues/6703
@andrew-ronaldson there is an "xs" spacer between the icon and text in figma, but because of the "icon component" in figma (the 21x21 box around the icon), the visual space between the icon and text is about 8px, so I used the small spacer instead.
> fix(nav): add support for icon, text

- src/patternfly/components/Card/card.scss
Closes #6575 
This PR updates the `flex` to `flex-grow` on the Card's `header__main` to prevent it from shrinking in favor of the Card actions.
> fix(card): update header-main vs actions width

- src/patternfly/components/Tabs/tabs.scss
Closes https://github.com/patternfly/patternfly/issues/6254
Removed the extra borders on the first/last child of the box tabs. This better aligns with the design.
Added the
> chore(box tabs): remove before after border

- src/patternfly/components/Hint/examples/Hint.md
- src/patternfly/components/Hint/hint.scss
Closes #6116 
This PR mirrors the negative margin-start on hint actions to the margin-bottom, to remove extra spacing added in the hint by the hint actions.
> fix(hint): remove extra hint actions space

- src/patternfly/components/ModalBox/modal-box.scss
Closes #6304 
This PR splits the 16px top padding from the modal body into 8px top padding and moves the remaining 8px to bottom padding on the modal header.
> fix(modal): split padding between header & body

- src/patternfly/components/Breadcrumb/breadcrumb.scss
- src/patternfly/components/Breadcrumb/examples/Breadcrumb.md
- src/patternfly/components/Menu/templates/menu-breadcrumbs--dropdown.hbs
- src/patternfly/components/MenuToggle/examples/MenuToggle.md
- src/patternfly/components/MenuToggle/menu-toggle.scss
Closes #6463 
Currently I'm applying some additional styling to a `pf-m-small` MenuToggle rather than only when it's inside a breadcrumb dropdown. I can update to only change that styling when the MenuToggle is inside the breadcrumb dropdown, but was curious if it would make sense to adjust other styling for a `pf-m-small` Menu Toggle rather than only the top/bottom padding.
Also note that the `pf-m-text` modifier on MenuToggle no longer actually does anything, but we've kept it on the React component.
> chore(Badge/MenuToggle): updated styling

- src/patternfly/components/Nav/examples/Navigation.md
- src/patternfly/components/Nav/nav-item.hbs
- src/patternfly/components/Nav/nav-link.hbs
- src/patternfly/components/Nav/nav-subnav.hbs
- src/patternfly/components/Nav/templates/nav--drilldown--nav-item-submenu.hbs
- src/patternfly/components/Nav/templates/nav--drilldown-bu.hbs
- src/patternfly/components/Nav/templates/nav--flyout.hbs
- src/patternfly/demos/DataList/data-list-page-nav.hbs
- src/patternfly/demos/Page/page-demo-expandable-nav.hbs
- src/patternfly/demos/Page/page-template-expandable-nav.hbs
fixes https://github.com/patternfly/patternfly/issues/6248
* removes `.pf-m-expandable`
* removes `nav-item--expandable` - it's never used
* removes dupes of `nav-item--IsExpandable`
* removes `nav-item--IsExpanded` - this is never set, it's only checked for
* renames `nav-item--expanded` to `nav-item--IsExpanded` - more consistent with the other attributes
> chore(nav): remove references to pf-m-expandable

- src/patternfly/components/Icon/icon.scss
Fixes #6674 
Uses icon status colors instead of the test status colors.
> fix(icon): use icon status color tokens

- src/patternfly/base/_index.scss
- src/patternfly/base/normalize.scss
- src/patternfly/base/patternfly-variables.scss
- src/patternfly/base/tokens/_index.scss
- src/patternfly/base/tokens/workspace-overrides.scss
fixes https://github.com/patternfly/patternfly/issues/6747
fixes https://github.com/patternfly/patternfly/issues/6679
@srambach @mattnolting changes discussed from today's working session, except I also moved reset.scss to come before normalize.scss. Seems like a change we would want to make - wdyt? I'll also run visual regression tests to make sure nothing unexpected changed from that.
> fix(global): base stylesheets cleanup

- src/patternfly/components/Alert/alert-group.scss
- src/patternfly/components/Brand/brand.scss
- src/patternfly/components/Button/button.scss
- src/patternfly/components/CalendarMonth/calendar-month.scss
- src/patternfly/components/Card/card.scss
- src/patternfly/components/DataList/data-list.scss
- src/patternfly/components/FormControl/form-control.scss
- src/patternfly/components/HelperText/helper-text.scss
- src/patternfly/components/InlineEdit/inline-edit.scss
- src/patternfly/components/List/list.scss
- src/patternfly/components/LogViewer/log-viewer.scss
- src/patternfly/components/Page/page.scss
- src/patternfly/components/Popover/popover.scss
- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Wizard/wizard.scss
closes #6751
Looks like we missed a few `:where(:root, .selector)` and closures. This PR addresses those.
> fix(css): added :where(:root, .selector)

- src/patternfly/components/Truncate/examples/Truncate.css
- src/patternfly/components/Truncate/truncate.scss
`min-width` value of `pf-c-truncate` is too large. 
Closes #6261 
Because the `ch` unit [is measured as the width of “0” in the prescribed font](https://www.w3.org/TR/css3-values/#ch), `min-width` for `pf-c-truncate` should be no greater than `pf-c-truncate__start`. This is because `pf-c-truncate__end` has no `min-width` value by default as it contains a discrete charset via `trailingNumChars={foo}` and its css is defined as `white-space: nowrap; overflow: visible`. Thusly, `pf-c-truncate__end` will never shrink. 
`min-width` for `pf-c-truncate` could be removed altogether if not for the `start` variant, which uses the `pf-c-truncate__end` container to create an ellipsis at the beginning of the applicable string. In order to prevent `pf-c-truncate` from shrinking to `0`, we need to apply …
> fix(truncate): updated min-widths to match

- src/patternfly/components/Card/card.scss
Closes #6234 
This PR:
- Moves Card borders to `::before` pseudoelement
- Removes two unneeded `revert` rules
> fix(card): move borders to pseudoelement

- src/patternfly/components/Menu/menu.scss
Adds transitions for the menu items, and for the menu itself. Note that for the menu as a whole, popper is controlling it being shown and hidden, so this PR uses !important to override the settings of Popper. Also note that the current implementation of Popper doesn't allow for the menu to slide, but simply transitions opacity.
A [follow-on issue](https://github.com/patternfly/patternfly/issues/6739) should address the motion currently happening in the drill-down menu.
Implements part of #6590
> feat(menu): add transitions for menu and items in menu

- src/patternfly/components/MenuToggle/examples/MenuToggle.md
- src/patternfly/components/MenuToggle/menu-toggle--check.hbs
- src/patternfly/components/MenuToggle/menu-toggle-button.hbs
- src/patternfly/components/MenuToggle/menu-toggle.scss
Closes #6534.
Adds `pf-m-split-toggle-button` modifier, for use when a split action checkbox toggle has toggle text (not a checkbox label).
> feat(MenuToggle): split action toggle button modifier

- src/patternfly/components/ProgressStepper/progress-stepper.scss
fixes https://github.com/patternfly/patternfly/issues/6730
scoped this to `__step-title.pf-m-help-text` (when we make the title a `<button>`) so it has less of a chance of impacting any existing user overrides.
> fix(progress-stepper): remove padding from help-text title button

- src/patternfly/components/Page/examples/Page.css
- src/patternfly/components/Page/examples/Page.md
- src/patternfly/components/Page/page-main-section.hbs
- src/patternfly/components/Page/page.scss
- src/patternfly/components/Toolbar/toolbar.scss
Fixes #6631 
Moves padding/margin from the page__main-body to the page__main-section.
This requires page__main-body to be required.
Refactors the side margin spacing that had a TODO on it.
Also decreases the height of the examples when they are on the example page so that each one isn't taking up 100vh!
NOTE: To see what it looks like, it currently has 16px (md spacer) in as the space between rather than the 24 that was spec'd.
Backstop report with 24px: https://drive.google.com/file/d/1or9X7tbWaN3TFv41rKexfmS1oV_invdi/view?usp=sharing
> fix(page): fix section spacing

- src/patternfly/components/ClipboardCopy/clipboard-copy.scss
- src/patternfly/components/ClipboardCopy/examples/ClipboardCopy.md
fixes https://github.com/patternfly/patternfly/issues/6762
@andrew-ronaldson is there a formula for when we use the subtle icon color by default and regular color on hover? I know we've added that in a few places, but it currently exists as overrides in components where that style exists. I'm wondering if this should be a variation or something instead. Should the "no padding" icon button have this style by default?
FWIW here are all of the places in the CSS we're using that token. I can provide more info if that's helpful
```
ClipboardCopy/clipboard-copy.scss:  --#{$clipboard-copy}__actions-item--button--Color: var(--pf-t--global--icon--color--subtle);
DataList/data-list.scss:  --#{$data-list}__item-draggable-button-icon--Color: var(--pf-t--global--icon--color--subtle); …
```
> fix(clipboard-copy): adjust inline icons

- src/patternfly/components/Panel/examples/Panel.md
- src/patternfly/components/Panel/panel-menu.hbs
- src/patternfly/components/Panel/panel.scss
- src/patternfly/demos/Panel/Panel.md
Closes #6732 
Worth noting that the scrollable example currently looks off. I can apply similar styling as the [scrollable menu example](https://pf6.patternfly.org/components/menus/menu#scrollable) (to make the scrollbar look like it has a curve to it), but may ultimately depend on how we want to proceed re: https://github.com/patternfly/patternfly/issues/6045
> feat(Panel): added Penta styles

- src/patternfly/components/Badge/badge.hbs
- src/patternfly/components/Button/button--variations.hbs
- src/patternfly/components/Button/button-count.hbs
- src/patternfly/components/Button/button-icon.hbs
- src/patternfly/components/Button/button-text.hbs
- src/patternfly/components/Button/button.hbs
- src/patternfly/components/Button/button.scss
- src/patternfly/components/Button/examples/Button.md
- src/patternfly/demos/Button/button-template-form.hbs
fixes https://github.com/patternfly/patternfly/issues/5944
fixes https://github.com/patternfly/patternfly/issues/6245
~~[BackstopJS Report-6.18.24.pdf](https://github.com/user-attachments/files/15891164/BackstopJS.Report-6.18.24.pdf)~~
Backstop visual regression report - [backstop-new-new-6.18.24.pdf](https://github.com/user-attachments/files/15892839/backstop-new-new-6.18.24.pdf)
[First commit](https://github.com/patternfly/patternfly/pull/6806/commits/ff4c7e2822c0298283b10dc4333a9b1788050338) is the CSS change if you want to look at just that. [Second commit](https://github.com/patternfly/patternfly/pull/6806/commits/1ee915881aa07f924420c4040ea39cbeea83641e) is the hbs updates.
I only updated the button component examples/demos (not in any of the other  but the backstop report looks …
> fix(button): add icon/text wrapper

- src/patternfly/components/Alert/alert-group.scss
- src/patternfly/components/Alert/alert.scss
This add animation on the alert group item when adding/removing an item.
For expediency, for now there are no additional component variables - motion tokens are used directly in the transitions.
One other TODO remains: a toast alert that times out should leave in the same way, but have a slower duration than an alert that is dismissed.
To test, go to the [toast alert full page example](https://patternfly-pr-6804.surge.sh/components/alert/html/toast-alert-group/). Add `.pf-m-offstage-top` to simulate the starting condition. Remove it to see the alert appear (slide in from the top). To simulate removal, add the `.pf-m-offstage-right` class and see it slide to the right.
To test reduced motion, turn on "Reduce motion" in the Display settings (MacOS). When this option is on, only opacity …
> feat(alert-group): animate addition and removal of alerts

- src/patternfly/components/Page/examples/Page.md
- src/patternfly/components/Page/page.scss
- src/patternfly/demos/Page/examples/Page.css
- src/patternfly/demos/Page/examples/Page.md
- src/patternfly/demos/Page/page-template-context-selector.hbs
- src/patternfly/demos/Page/page-template-sidebar.hbs
This adds an example for a context selector in the page sidebar, and another with it expanded.
It adds a container in the sidebar modified to hold a context selector.
Fixes #5776
> feat(page): add context selector container in sidebar and add examples

- src/patternfly/components/Table/table-grid.scss
Closes #6556 
This PR removes the bottom border on collapsed expandable rows on mobile, which is causes a double border to appear.
> fix(Table): remove duplicate bottom border on mobile collapsed expandable rows

- src/patternfly/components/Table/table-grid.scss
- src/patternfly/components/Table/table-tree-view.scss
closes #6283 
@rebeccaalpert bordered cells paint a border in mobile view. This PR prevents that from happening. Does this address you issue fully?
> fix(tree-table): fixed cell border mobile positioning

- src/patternfly/base/patternfly-fonts.scss
- src/patternfly/base/tokens/tokens-local.scss
Fixes #6790 
Updates font names to match tokens (include spaces)
Also removes font tokens from the local token file since they are now in the default token file from Figma.
Note: There are two local tokens for font weight that are used but not in Figma - `--pf-t--global--font--weight--body--bold` and `--pf-t--global--font--weight--heading--bold`. These point to base tokens that also don't exist. (see diff for details) @lboehling should these semantic font weight tokens exist and should they point to existing base font weigh tokens?
> chore(fonts): update font names and remove extra tokens

- src/patternfly/layouts/Flex/flex.scss
- src/patternfly/layouts/Gallery/gallery.scss
- src/patternfly/layouts/Grid/grid.scss
- src/patternfly/layouts/Level/level.scss
- src/patternfly/layouts/Split/split.scss
- src/patternfly/layouts/Stack/stack.scss
Closes https://github.com/patternfly/patternfly/issues/6771
One question I have is the Flex layout update. Not sure if this is intended @lboehling ?
`  --#{$flex}--spacer--column--base: var(--pf-t--global--spacer--gutter--default); // default spacer/gap for columns`
That trickles down as the base for other spacers. It was using `spacer--lg` before the update.
> fix(layouts): updating gutters tokens

- src/patternfly/components/Page/examples/Page.css
- src/patternfly/components/Page/examples/Page.md
- src/patternfly/components/Page/page.scss
Closes #6653 
This changes the main container not to fill unless it either a) has `.pf-m-fill` or b) it contains a section with `.pf-m-fill` 
Note: I'm not sure we really need `.pf-m-no-fill` now but I left it because it might be useful in some instances?
Also, I removed the flex-grow on last child because that causes it to take space even if another section has fill. I don't think the last section should automatically fill. There's one case I see that might have to be adjusted:
```
pf-c-main-container.pf-m-fill
pf-c-main-section 
pf-c-main-section pf-m-secondary
```
Here the secondary section wouldn't fill the space, but a `.pf-m-fill` could be added to that section.
Alternatively, if we automatically fill the last section, if you didn't want it to take extra space when another section …
> feat(page): add fill modifier for page container

- .stylelintrc
- src/patternfly/base/tokens/tokens-charts-dark.scss
- src/patternfly/base/tokens/tokens-charts.scss
- src/patternfly/base/tokens/tokens-dark.scss
- src/patternfly/base/tokens/tokens-default.scss
- src/patternfly/base/tokens/tokens-palette.scss
- src/patternfly/components/Card/card.scss
fixes https://github.com/patternfly/patternfly/issues/6894
* Pulls in latest tokens
* Adds stylelint rules to
* unset [color-hex-length](https://stylelint.io/user-guide/rules/color-hex-length/) (allow for `#000000` instead of failing in favor of `#000`)
* Add the capitalized font-names as ignored values for [value-keyword-case](https://stylelint.io/user-guide/rules/value-keyword-case/) - references https://github.com/liubich/weather-vue/pull/154 and https://github.com/vicompany/stylelint-config-vi/issues/3
* Updates an instance of `--pf-t--global--spacer--action--horizontal--plain` to `--pf-t--global--spacer--action--horizontal--plain--default`
> fix(tokens): pull in updates to semantic tokens

- src/patternfly/components/Masthead/masthead.scss
- src/patternfly/components/Toolbar/toolbar.scss
- src/patternfly/demos/CardView/examples/CardView.md
- src/patternfly/demos/Masthead/examples/Masthead.md
- src/patternfly/demos/Masthead/masthead-template-content-icon-group.hbs
- src/patternfly/demos/PrimaryDetail/examples/PrimaryDetail.md
- src/patternfly/demos/Tabs/examples/Tabs.md
- src/patternfly/demos/Toolbar/examples/Toolbar.md
- src/patternfly/demos/Toolbar/toolbar-template-content.hbs
- src/patternfly/demos/Toolbar/toolbar-template-filter-group.hbs
- src/patternfly/demos/Toolbar/toolbar-template.hbs
closes #6889 
* updated `toolbar-group--modifier="pf-m-icon-button-group"` to `toolbar-group--IsActionGroupPlain=true`
* updated `toolbar-group--modifier="pf-m-filter-group"` to `toolbar--IsFilterGroup=true`
* updated `toolbar-group--modifier="pf-m-icon-button-group"` to `toolbar-group--IsActionGroupPlain=true`
* removed `page-main-section--modifier='pf-m-no-padding` from demos/examples
* updated demo padding
* set toolbar padding inline to zero
> fix(toolbar): changed toolbar `inline-padding` default to zero, updated toolbar demo examples

- src/patternfly/components/MenuToggle/examples/MenuToggle.md
- src/patternfly/components/MenuToggle/menu-toggle--check.hbs
- src/patternfly/components/MenuToggle/menu-toggle-button.hbs
- src/patternfly/components/MenuToggle/menu-toggle.scss
Closes #6778.
Same changes as https://github.com/patternfly/patternfly/pull/6668 but for v6 branch.
> feat(MenuToggle): split action toggle text modifier

- src/patternfly/base/normalize.scss
- src/patternfly/base/tokens/tokens-charts-dark.scss
- src/patternfly/base/tokens/tokens-charts.scss
- src/patternfly/base/tokens/tokens-dark.scss
- src/patternfly/base/tokens/tokens-default.scss
- src/patternfly/base/tokens/tokens-local.scss
- src/patternfly/base/tokens/tokens-palette.scss
- src/patternfly/components/Breadcrumb/breadcrumb.scss
- src/patternfly/components/Button/button.scss
- src/patternfly/components/Content/content.scss
- src/patternfly/components/DescriptionList/description-list-term.hbs
- src/patternfly/components/DescriptionList/description-list-text.hbs
- src/patternfly/components/DescriptionList/description-list.scss
- src/patternfly/components/DescriptionList/examples/DescriptionList.md
- src/patternfly/components/JumpLinks/jump-links.scss
- src/patternfly/components/Label/label.scss
- src/patternfly/components/ProgressStepper/progress-stepper.scss
- src/patternfly/components/SimpleList/simple-list.scss
- src/patternfly/components/Tabs/tabs.scss
- src/patternfly/components/Timestamp/timestamp.scss
- src/patternfly/components/ToggleGroup/toggle-group.scss
fixes https://github.com/patternfly/patternfly/issues/6869
fixes https://github.com/patternfly/patternfly/issues/6900
For testing, I verified the styles are showing up as intended, then pasted this into the dev tools console to make sure I was using the right tokens and the hover/focus styles were working as expected, since the hover/focus styles match the default styles, it's hard to validate that part was working.
```
document.documentElement.style.setProperty("--pf-t--global--text-decoration--editable-text--line--default", "underline green");
document.documentElement.style.setProperty("--pf-t--global--text-decoration--editable-text--style--default", "dotted");
document.documentElement.style.setProperty("--pf-t--global--text-decoration--editable-text--line--hover", "overline green"); …
```
> fix(global): use tokens for links/help-text/editable-text

- src/patternfly/patternfly-charts.scss
Towards: https://github.com/patternfly/patternfly-react/issues/10582
The red charts tokens were removed for v6, the red-orange tokens are now meant to be used for danger statuses in charts.
> feat(charts): remove deleted red tokens

- src/patternfly/components/MenuToggle/examples/MenuToggle.md
- src/patternfly/components/MenuToggle/menu-toggle--check.hbs
Closes #6776 
Also updated some labeling in examples. We should also update other examples/demos (post v6) so that any dynamic text inside a split toggle isn't tied to the checkbox input itself. Otherwise it runs into a similar issue that we had to fix for the Switch, where the dynamic labeling will cause confusion. 
For example, the [Bulk Select React example](https://patternfly-react-v6.surge.sh/components/table/react-demos/bulk-select/) updates the input's labeling to "Deselect all cards" when at least 1 item is selected; if all items are selected, the labeling conveys that all cards are already deselected ("deselect all cards, checked checkbox"), when the opposite is actually true (all cards are selected, but clicking the checkbox will cause all cards to be deselected). 
Likewise, if …
> fix(MenuToggle): removed nested label elements

- src/patternfly/components/Content/content--element.hbs
- src/patternfly/components/Content/content.hbs
- src/patternfly/components/Content/content.scss
- src/patternfly/components/Content/examples/Content.md
fixes https://github.com/patternfly/patternfly/issues/6951
Adds `font-size/line-height/color` to all of the `.pf-v6-c-content--[element]` classes, since they were previously only set on `.pf-v6-c-content` before.
Adds `.pf-m-editorial` as a modifier that can go on on `.pf-v6-c-content` or `.pf-v6-c-content--[element]` and
* Changes the default font-size from `body--default` to `body--lg`
* Changes the `<small>` from `body--sm` to `body--default`
> fix(content): added editorial styling

- src/patternfly/components/Card/card--actionable.hbs
- src/patternfly/components/Card/card.scss
- src/patternfly/components/Card/examples/Card.md
fixes https://github.com/patternfly/patternfly/issues/6948
Ran visual regressions and only the new/renamed examples failed (lack of a reference image to compare against)
Changes:
* Updates the selectors in the existing selectable/clickable blocks to group the radio/check stuff in `:is()` so they're in a single selector instead of multiple (should be no visual change from that)
* Adds the new button/link element class (`.#{$card}__clickable-action`) in the `:is()` groups where it's needed, just a couple of them
To test this in a local react dev environment:
* Check this branch out in a clone of the core repo somewhere
* Run `yarn build-patternfly`
* This builds the dist package that we put on npm for `@patternfly/patternfly` at `./dist` in the core repo
* Rename the existing …
> fix(card): update clickable to use button and anchor

- src/patternfly/components/MenuToggle/examples/MenuToggle.md
- src/patternfly/components/MenuToggle/menu-toggle.hbs
- src/patternfly/components/MenuToggle/menu-toggle.scss
fixes https://github.com/patternfly/patternfly/issues/6962
* adds `.pf-m-placeholder` on the menu toggle, which changes the text color to the placeholder color token
* Icon colors were mostly set to `inherit` (matched text color), so this wires up/fixes vars to use icon color tokens 
Backstop report has no failures other than this random one, which looks like a viewport size/timing glitch
[BackstopJS Report.pdf](https://github.com/user-attachments/files/16606725/BackstopJS.Report.pdf)
> fix(menu-toggle): added support for placeholder, fixed disabled icon color

- src/patternfly/base/tokens/tokens-charts-dark.scss
- src/patternfly/base/tokens/tokens-charts.scss
- src/patternfly/base/tokens/tokens-dark.scss
- src/patternfly/base/tokens/tokens-default.scss
- src/patternfly/base/tokens/tokens-palette.scss
- src/patternfly/components/Slider/examples/Slider.md
- src/patternfly/components/Slider/slider.scss
fixes https://github.com/patternfly/patternfly/issues/6977 and pulls in the latest tokens from https://github.com/patternfly/design-tokens/pull/82
@lboehling  the only difference I see in the between what's in the PR and in the referenced issue is the disabled/unfilled tick color (updated to `--pf-t--global--icon--color--on-disabled`). In the design screenshot, the tick color is lighter than the background, but `--pf-t--global--icon--color--on-disabled` is a darker color. Not sure if anything needs to be updated there?
> fix(slider): adjust styles

- src/patternfly/components/TextInputGroup/text-input-group.scss
Closes #6930 
Couple of notes;
- The gap between the status icon and utilities is slightly larger now.
This PR: 
Staging:
- Did we want padding at the end of the utilities, to create more of a visual gap? Right now when the close button is hovered there's not much of a gap:
But if we used the same spacing as the icons it may create too much of a visual gap when the button isn't focused:
> fix(TextInputGroup): updated inline padding of icons

- src/patternfly/components/Table/table.scss
Closes #6782.
Adjusts padding so it applies padding-block-start to compound expandable rows (and still removes padding for all other types of expandable row).
> feat(Table): add padding except for clickable expandable rows

- src/patternfly/components/Toolbar/toolbar.scss
fixes https://github.com/patternfly/patternfly/issues/6918
[BackstopJS Report.pdf](https://github.com/user-attachments/files/16641892/BackstopJS.Report.pdf) with `filter="toolbar|masthead"`
The 3 failures are the last 3 in the report, and seem to match the layout I see for these examples v5
> fix(toolbar): fix expanded content position in masthead

- src/patternfly/components/Progress/progress.scss
This should take care of the only issue not addressed in another issue on https://github.com/patternfly/patternfly/issues/5476
This PR changes the progress measure to be tabular numbers.
> feat(progress): display progress measure as tabular numbers

- src/patternfly/components/Toolbar/toolbar.scss
Allows label groups to wrap within the header rather than flexing them onto one line and having the labels within wrap down excessively.
Here are some examples of the new wrapping with longer label groups
Before:
After:
fixes #6967
> fix(toolbar-group): let label groups wrap within the toolbar

- src/patternfly/components/ExpandableSection/examples/ExpandableSection.md
- src/patternfly/components/ExpandableSection/expandable-section-toggle-text.hbs
- src/patternfly/components/ExpandableSection/expandable-section-toggle.hbs
- src/patternfly/components/ExpandableSection/expandable-section.scss
fixes https://github.com/patternfly/patternfly/issues/6998
Visual regression report - [expandable-section.pdf](https://github.com/user-attachments/files/16702893/expandable-section.pdf)
Just a draft to see if it's something we want to get in this sprint. Cleans up some styles, too.
The react changes would be:
* Make `__toggle` a `<div>` instead of a custom button
* Use a link `<Button>` in `__toggle` and update old `__toggle` logic to apply to the `<Button>` instead
> fix(expandable-section): use link button, update styles

- src/patternfly/base/tokens/tokens-local.scss
Fixes #7003 
I disabled the linter for the token pattern - I could alter the pattern instead but thought this was better for this 1-off.
@wise-king-sullyman @kmcfaul
> feat(tokens): add temporary color token for debugging use

- scripts/helpers.mjs
- src/patternfly/components/Check/check-input.hbs
- src/patternfly/components/Check/check.hbs
- src/patternfly/components/DataList/data-list-check.hbs
- src/patternfly/components/Menu/menu-item.hbs
- src/patternfly/components/MenuToggle/menu-toggle.hbs
- src/patternfly/components/Table/TableCells/table-cell-action.hbs
- src/patternfly/components/Table/TableCells/table-cell-check.hbs
- src/patternfly/components/Table/TableCells/table-cell-empty.hbs
- src/patternfly/components/Table/TableCells/table-cell-overflow-menu.hbs
- src/patternfly/components/Table/TableCells/table-cell-radio.hbs
- src/patternfly/components/Table/TableCells/table-cell-toggle.hbs
- src/patternfly/components/Table/TableCells/table-cell.hbs
- src/patternfly/components/Table/Tree-table/table-tree-view--basic.hbs
- src/patternfly/components/Table/examples/Table.md
- src/patternfly/components/Table/table-tbody.hbs
- src/patternfly/components/Table/table-th.hbs
- src/patternfly/components/Table/table-thead.hbs
- src/patternfly/components/Table/table-tr.hbs
- src/patternfly/components/Table/table.scss
- src/patternfly/components/Toolbar/toolbar-toggle.hbs
- src/patternfly/demos/Table/table-compact-table.hbs
- src/patternfly/demos/Table/table-empty-state-table.hbs
- src/patternfly/demos/Table/table-expandable-table.hbs
- src/patternfly/demos/Table/table-simple-table.hbs
- src/patternfly/demos/Table/table-sortable-table.hbs
- src/patternfly/demos/Toolbar/toolbar-template.hbs
closes #6272 
closes https://github.com/patternfly/patternfly/issues/6643
[Backstop Report](https://drive.google.com/file/d/1X98JYLHM_U5YtSaLwGvrg-8aX6j4krD-/view?usp=sharing)
**Header shift is due to `pf-v6-c-table__cell-empty` and is expected**
[Backstop report](https://drive.google.com/file/d/11u1r8QELIo1m9e2a5Y8AAiFoKYNW5Wwz/view?usp=sharing)
Favorites example shouldn't be sorted, this diff is expected
This PR creates a partial container for special table cells. The internals of the partials remain unchanged while the wrapping element detects `IsThead` and returns `th` if true, `td` if false. Empty cells' default screen reader text is set to "Action" (the most common use case) and optionally updated text via `table-cell--text`. 
This shift is due to updating action empty `th` to …
> fix(table): updated thead td to th

- src/patternfly/components/JumpLinks/jump-links-header.hbs
- src/patternfly/demos/Drawer/examples/drawer-jump-links.hbs
fixes https://github.com/patternfly/patternfly/issues/7021
Convenience link from the issue - https://patternfly-pr-7024.surge.sh/components/drawer/html-demos/collapsed-drawer-with-jump-links/
* The expandable toggle is now visible on small screens
> fix(jumplinks): fixed outdated hbs for jump link toggle in demo

- src/patternfly/components/Nav/nav.scss
- src/patternfly/components/Sidebar/sidebar.scss
- src/patternfly/components/Table/table.scss
- src/patternfly/components/TextInputGroup/text-input-group.scss
- src/patternfly/sass-utilities/mixins.scss
- src/patternfly/utilities/Sizing/sizing.scss
- src/patternfly/utilities/Text/text.scss
Fixes #6991 
Removes remaining hardcoded `--pf-v6-` instances and replaces them with the appropriate sass variable for the prefix.
Visual regression tests for nav, sidebar, table, utilities, and text show the same number of failures (9, 5, 15, 0, and 5 respectively) as when I ran it before changes, and all are indistinguishable.
> feat(various): remove hardcoded namespace

- src/patternfly/components/Button/button.scss
- src/patternfly/components/ClipboardCopy/clipboard-copy.scss
fixes https://github.com/patternfly/patternfly/issues/7034
[backstop-button-min-width.pdf](https://github.com/user-attachments/files/16882480/backstop-button-min-width.pdf)
There is a sub-pixel size difference with the clipboard copy buttons for some reason when adding the `min-width`. Not sure why, but not concerned about it either 🐸
> fix(button): add min-width

- src/patternfly/components/Button/button.scss
- src/patternfly/components/Check/check.scss
- src/patternfly/components/MenuToggle/menu-toggle.scss
- src/patternfly/components/Pagination/pagination.scss
- src/patternfly/components/Radio/radio.scss
- src/patternfly/components/Slider/slider.scss
As noted by @srambach, removing `:root` from the component var selectors drastically improves dev tools performance in Firefox. This PR makes that update, and fixes a handful of places we've cross-referenced component vars in other components since vars were previously available from the `:root` scope. 
Here is the backstop report - [backstop-remove-root.pdf](https://github.com/user-attachments/files/16971491/backstop-remove-root.pdf)
Everything is from `.pf-v6-c-radio.pf-m-standalone` now having a `min-height` because those were previously referencing `--#{$check}--Height` for their height, which didn't exist. They now reference `--#{$radio}--m-standalone--MinHeight`. It looks like the presence of a standalone check or radio is making a single line of regular content taller than it would …
> fix(global): removed root selector from component vars, fix var refs

- src/patternfly/components/Content/content--element.hbs
- src/patternfly/components/Content/content--kitchen-sink.hbs
- src/patternfly/components/Content/content.scss
- src/patternfly/sass-utilities/mixins.scss
Looks like I forgot to commit removing `:root` in https://github.com/patternfly/patternfly/pull/7060 🤦‍♂️ And there was an update to the content component I was still working out, so made that, too. 
Here's the [backstop report](https://github.com/user-attachments/files/16987350/BackstopJS.Report.pdf). From what I can tell, everything is a false positive or related to previous updates.
> fix(content): actually remove root, update content selector

- src/patternfly/components/Pagination/pagination-menu-toggle.hbs
- src/patternfly/components/Pagination/pagination.scss
- src/patternfly/components/Toolbar/toolbar.scss
- src/patternfly/demos/Table/table-pagination-footer-static.hbs
- src/patternfly/demos/Table/table-pagination-footer.hbs
fixes https://github.com/patternfly/patternfly/issues/7057
Visual regression report - [backstop-toolbar-pagination-padding.pdf](https://github.com/user-attachments/files/16970719/backstop-toolbar-pagination-padding.pdf)
This updates both the toolbar's bottom padding and the bottom pagination's top padding to use `var(--pf-t--global--spacer--gap--group--vertical)`
> fix(pagination): adjust block padding

- src/patternfly/components/Alert/alert.scss
Closes #7054 
Toggle before update:
Toggle after update:
Close button before update:
Close button after update:
Do we ever intend for consumers to ever be able to have multiple actions in an Alert, not just a close button? Wondering if having the action button be larger would cause issues if that's the case.
> chore(Alert): updated toggle and close styling per audit

- src/patternfly/components/MenuToggle/examples/MenuToggle.md
- src/patternfly/components/MenuToggle/menu-toggle-toggle-icon.hbs
- src/patternfly/components/MenuToggle/menu-toggle.scss
fixes https://github.com/patternfly/patternfly/issues/6458, possibly https://github.com/patternfly/patternfly/issues/6632
I left comments explaining most of the changes. ~~If we can merge https://github.com/patternfly/patternfly/pull/7108, we can run visual regressions in this PR.~~
Backstop reports
* Error report (PDF) - https://drive.google.com/file/d/17EDi0xivLI04ly_HZgpAlT-tBSUunsol/view?usp=sharing
* Full report - https://drive.google.com/file/d/1I53w8gUdvmvZEX7K-6IVNlvyXv58cn7e/view?usp=sharing
* You'll need to download, unzip, open `backstop_data -> html_report -> indx.html`
> fix(menu-toggle): adjust toggle icon spacing, split toggle border

- src/patternfly/components/FormControl/examples/FormControl.md
- src/patternfly/components/FormControl/form-control.hbs
- src/patternfly/components/FormControl/form-control.scss
Closes #7013
Overrides padding styles for formcontrol textareas, to account for the outline offset. I put the new values into variables, but they could be calc'd inline in the modifier as well, so LMK which place would be preferred.
> feat(FormControl): refine textarea styles

- src/patternfly/components/MenuToggle/examples/MenuToggle.md
- src/patternfly/components/MenuToggle/menu-toggle-icon.hbs
- src/patternfly/components/MenuToggle/menu-toggle.scss
closes #6975 
`.#{$menu-toggle}__icon` should not be `display: flex`.
> fix(menu-toggle): fixed alignment, remove display: flex from __icon

- src/patternfly/components/Button/button.scss
Fixes #7095 
Icon color on a plain no padding button should be subtle icon color (#707070)
When hovered, it should be the regular icon color (#1f1f1f)
> fix(Button): adjust plain no padding icon color

- src/patternfly/components/Page/page.scss
Fixes #7126 
Sidebar area did not collapse on a page with a full height drawer (i.e. notification drawer)
Backstop report for ["drawer"](https://drive.google.com/file/d/1cP67ZM66Rc2b9w9cdj9fb2v2YKIUYqTm/view?usp=sharing)
> fix(Page): fixes drawer grid area when sidebar is collapsed

- src/patternfly/components/MenuToggle/menu-toggle.scss
fixes https://github.com/patternfly/patternfly/issues/6933
The V5 dark theme Menu toggle secondary variant `background-color` was incorrect. This sets it to transparent
> fix(menu-toggle): sets secondary menu-toggle background-color transparent, except for disabled state

- src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly/issues/7145
Convenience links:
* [sticky breadcrumb](https://patternfly-pr-7152.surge.sh/components/page/html-demos/sticky-breadcrumb/)
* [sticky horizontal subnav](https://patternfly-pr-7152.surge.sh/components/page/html-demos/sticky-horizontal-subnav/)
**After**
> fix(page): apply bottom padding to page breadcrumb and horizontal subnav elements

- src/patternfly/components/Table/examples/Table.md
- src/patternfly/components/Table/table-tr.hbs
- src/patternfly/components/Table/templates/table-tbody--expandable.hbs
- src/patternfly/demos/Card/examples/Card.css
- src/patternfly/demos/Card/templates/card-demo--popover-table.hbs
addresses following a11y issues flagged by patternfly-a11y upgrade:
- card demo has invalid aria-controls values (the aria-controls on a table's expandable row toggle does not match the id of the expandable content)
- multiple table examples have invalid aria-controls values (the aria-controls on a table's expandable row toggle does not match the id of the expandable content)
Also cleans up:
- the styles on the card demo - status card expanded with popover example
- `role="row"` always being rendered (rather than only conditionally rendered), preventing a lot of `[Object, object]` appearing in the rendered html markup in table examples.
> fix: address early a11y issues + clean up

- src/patternfly/components/MenuToggle/examples/MenuToggle.md
- src/patternfly/components/MenuToggle/menu-toggle.hbs
We removed `pf-m-action` from the menu toggle but missed removing it from the hbs and docs, so this cleans that up.
Fixes #7135
> chore(menu-toggle): remove reference to pf-m-action

- src/patternfly/components/MenuToggle/menu-toggle.scss
Fixes https://github.com/patternfly/patternfly/issues/7137
The react `MenuToggle` component uses an `<svg>` for the `menu toggle` icon, instead of an `<i>` used by core.
Removing `display: flex` from `pf-v6-c-menu-toggle__toggle-icon` because it causes a bug  where the `svg` `CaretDownIcon` is misaligned with the text and the button height to grow taller.
Before and after
https://patternfly-pr-7213.surge.sh/components/menus/menu-toggle#split-toggle
> fix(menu toggle): correct spacing for split menu-toggle__toggle-icon that contains svg for icon

- src/patternfly/components/Table/table.scss
closes #7132 
`table__check` cells are supposed to be set as `max-width: none`. In this case, `max-width` is being overridden by [`.pf-v6-c-table tr:where(.pf-v6-c-table__tr) > :where(th, td)`](https://github.com/patternfly/patternfly/blob/main/src/patternfly/components/Table/table.scss#L322)
Convenience links:
https://patternfly-pr-7134.surge.sh/components/table/html-demos/loading-state-demo/
https://patternfly-pr-7134.surge.sh/components/table/html-demos/empty-state/
> fix(table): fixed thead checkbox fitting

- src/patternfly/components/Content/content--element.hbs
- src/patternfly/components/Content/content--kitchen-sink.hbs
- src/patternfly/components/Content/content.scss
- src/patternfly/components/Content/examples/Content.md
- src/patternfly/components/Title/examples/Title.md
- src/patternfly/components/Title/title.hbs
- src/patternfly/components/Title/title.scss
- src/patternfly/demos/Page/page-template-title.hbs
fixes https://github.com/patternfly/patternfly/issues/7072
* Adds `.pf-m-page-title` to the content component and title component
* Can be applied to any heading level/size and it will override the font-weight
* Updates our standard full-page demo template to add the page title modifier to the main heading
* Some demos may not use that template and would need to be updated manually
* We could add the page-title modifier to the "Hello world" heading in main content component examples - wdyt @lboehling @andrew-ronaldson?
Links:
https://patternfly-pr-7212.surge.sh/components/content
https://patternfly-pr-7212.surge.sh/components/title#page-title
https://patternfly-pr-7212.surge.sh/components/page/html-demos/basic/
https://patternfly-pr-7212.surge.sh/components/data-list/html-demos/basic/
> feat(title/content): add page title variation

- src/patternfly/components/DataList/data-list-item-action.hbs
- src/patternfly/components/DataList/data-list.hbs
- src/patternfly/components/DataList/data-list.scss
- src/patternfly/components/DataList/examples/DataList.md
- src/patternfly/demos/Table/table-manage-cols-data-list.hbs
fixes https://github.com/patternfly/patternfly/issues/7105
- Update DataList compact examples to use small buttons
- Add top and bottom padding to small buttons
Backstop tests
https://drive.google.com/drive/folders/1aKh3N42bPbMjsfkTTbGOrQr8zUO_YHYn?usp=sharing
**Before**
**After**
**Before**
**After**
> fix(data-list): add spacing to compact data-list buttons

- src/patternfly/components/Table/examples/Table.md
- src/patternfly/components/Table/table.scss
- src/patternfly/components/Table/templates/table-tr--nested-column-header.hbs
fixes #7172 
`max(var(--#{$table}--m-truncate__text--MinWidth), var(--#{$table}--m-truncate--cell--MaxWidth));` sets `table__text.m-truncate` to accept larger of the two values, assuring that truncated text is always at least `5ch` long and at max `100%`. 
Link: https://patternfly-pr-7175.surge.sh/components/table
[BackstopJS Report table text.pdf](https://github.com/user-attachments/files/17510300/BackstopJS.Report.table.text.pdf)
> fix(table-text): updated truncate value

- src/patternfly/components/Page/examples/Page.css
- src/patternfly/components/Page/examples/Page.md
- src/patternfly/components/Page/page-main-container.hbs
- src/patternfly/components/Page/page.scss
`.pf-m-limit-width` was not working at XL viewport because there was a calc() involving `auto`. Instead of a calc, I manually set the max-width value for the XL breakpoint. EDIT: in light of #7216, I kept the calc but changed `auto` to be the same width for XL as it was for the other breakpoints. This means the sidebar no longer stretches, and so the items will now wrap properly.
Added the main-subnav page section to the sections that can be width limited.
The `.pf-m-fill` example wasn't showing the effect because `.pf-m-fill` wasn't added to the page main container, so this has been fixed and documented.
The sidebar example didn't have the correct modifier for insets/no inset and the footer section was preventing the fill section from filling.
Changed the selector in the local css to …
> fix(Page): limit width on section and example cleanup

- src/patternfly/components/Button/button.scss
- src/patternfly/components/Button/examples/Button.md
- src/patternfly/components/MenuToggle/examples/MenuToggle.md
- src/patternfly/components/MenuToggle/menu-toggle.scss
fixes https://github.com/patternfly/patternfly/issues/7197
This was originally in https://github.com/patternfly/patternfly/pull/7138, but I closed that PR since it needed more work to fix a separate issue and @sg00dwin is taking the lead on that.
From https://github.com/patternfly/patternfly/pull/7138#pullrequestreview-2341771216, this is the idea behind this fix
> This was just targeting the wrong element. Needs to look for `__controls` as an only child (meaning no `__text` sibling). It's effectively the same style as this one, but in `:not()` to target the inverse https://github.com/patternfly/patternfly/blob/689a71891bac6823c3dc2bd1406ea713f7037e3d/src/patternfly/components/MenuToggle/menu-toggle.scss#L486
> fix(menu-toggle): fix split button inline padding

- src/patternfly/components/Table/table.scss
Closes #7220 
Quick fix for table sort buttons in nested tables. Eventually we'll need to address the issues detailed in #7244 and #7050, but this will solve our immediate issue.
> fix(table): isolated sort button negative margins to thead
