README.md, package-lock.json, package.json
Adds the required node version to the setup instructions and the engines field in the package.json
Issue: https://github.com/patternfly/patternfly-next/issues/40
=> Add supported node version

src/pages/layouts/split/index.js, src/pages/layouts/stack/index.js, src/patternfly/layouts/Stack/docs.md, src/patternfly/layouts/Stack/index.js, src/patternfly/layouts/Stack/styles.scss, src/workspace.scss
A stack layout is when the children stack vertically, and one of the elements (the main) will expand as needed.
Preview: https://deploy-preview-78--pf-next.netlify.com/layouts/stack/
Issue: https://github.com/patternfly/patternfly-next/issues/72
=> Add the Stack layout

src/patternfly/components/Button/styles.scss, src/patternfly/utilities/variables.scss
Adds global variables for BoxShadow and removes the active state shadow on buttons.
=> BoxShadow global variables

src/pages/layouts/bullseye/index.js, src/patternfly/layouts/Bullseye/docs.md, src/patternfly/layouts/Bullseye/index.js, src/patternfly/layouts/Bullseye/styles.scss, src/workspace.scss
A bullseye layout is when there is a single child element, and that child is centered both vertically and horizontally in the parent.
resolves: #73
=> Add the Bullseye layout

src/pages/layouts/level/index.js, src/patternfly/layouts/Level/docs.md, src/patternfly/layouts/Level/index.js, src/patternfly/layouts/Level/styles.scss, src/workspace.scss
A Level is a layout that distributes the space between children evenly and it centers children on the x-axis. By default it positions the children horizontally, but on smaller devices it will position the children vertically.
resolves #76
=> Add Level layout

src/pages/layouts/gallery/index.js, src/patternfly/layouts/Gallery/docs.md, src/patternfly/layouts/Gallery/index.js, src/patternfly/layouts/Gallery/styles.scss, src/workspace.scss
A Gallery layout is a layout where all of the children are a uniform size, the children are displayed horizontally, and they wrap as needed. It's really just a grid, but the name is already taken.
resolve #74
=> Add Gallery layout

blueprints/component-html/files/src/patternfly/components/__moduleName__/styles.scss, blueprints/component/files/src/patternfly/components/__moduleName__/styles.scss, blueprints/pattern/files/src/patternfly/patterns/__moduleName__/styles.scss, package-lock.json, patternfly_old/pf-c-button/pf-c-button.scss, patternfly_old/pf-c-card/pf-c-card.scss, patternfly_old/pf-c-content/pf-c-content.scss, patternfly_old/pf-c-secondary-nav/pf-c-secondary-nav.scss, patternfly_old/pf-c-vertical-nav/pf-c-vertical-nav.scss, src/pages/guidelines.md, src/patternfly/_base.scss, src/patternfly/_fonts.scss, src/patternfly/components/Alert/styles.scss, src/patternfly/components/Button/styles.scss, src/patternfly/components/Content/styles.scss, src/patternfly/patterns/SecondaryNav/styles.scss, src/patternfly/utilities/bs-variables.scss, src/patternfly/utilities/functions.scss, src/patternfly/utilities/variables.scss
Global variables now follow this syntax `$global--concept--PropiertyCamelCase--modifier--state`
This is a global change in every file to reflect that.
This PR will destroy #68 but I think we should merge this and do the turn variables from CSS to SASS before fixing it.
resolves #125
=> Global variables new syntax

src/pages/components/content/index.js, src/patternfly/_base.scss, src/patternfly/components/Content/docs.md, src/patternfly/components/Content/styles.scss, src/patternfly/utilities/variables.scss
This PR cherry picks and closes #68 to accommodate to the new global variable syntax
=> Rebases and cleans up typography

build/blueprints/component/files/src/patternfly/components/__moduleName__/examples/index.js, src/patternfly/components/Button/examples/index.js, src/site/_site/GeneratedSource/index.js, src/site/_site/Preview/index.js
To allow for proper handling of the new Handlebars components, we needed to update the GeneratedSource and Preview site components.
resolves #143
=> Refactor site components to use handlebars input

src/patternfly/components/Alert/styles.scss, src/patternfly/components/Button/examples/buttonTypes.hbs, src/patternfly/components/Button/styles.scss, src/patternfly/components/Content/styles.scss, src/patternfly/components/SecondaryNav/styles.scss, src/patternfly/utilities/variables.scss
=> Converts css variables to sass variables

gatsby-config.js, gatsby-node.js
Fixed links in top right for guidelines, getting-started, and react-reference.
=> fix(site/pages): Fixed missing links for site pages

gatsby-config.js, gatsby-node.js, patternfly-cli/package-lock.json, plugins/gatsby-plugin-page-creator/gatsby-node.js, src/layouts/demo.js, src/patternfly/_base.scss, src/patternfly/components/Alert/styles.scss, src/patternfly/components/Button/styles.scss, src/patternfly/components/Content/styles.scss, src/patternfly/components/SecondaryNav/styles.scss, src/patternfly/utilities/variables.scss, src/site/layouts/demo.js, src/site/layouts/index.js
This is still a work in progress but I want to get some thoughts on the approach for naming. 
In #58 the background themes show a need for at least three shades of the light background. 
This naming could work if we can limit it to three, which seems reasonable.
I am also pulling this into the text colours b/c the same principle should apply there as well.
=> Add theme colors

src/patternfly/_base.scss
This PR adds an important because we don't know if pf3 will be loaded after pfnext
=> Adds an important to font size unset

build/blueprints/layout/files/src/patternfly/layouts/__moduleName__/docs/code.md, src/site/workspace.scss
Adds some styles to the workspace to make the existing markdown documentation a little more readable.
=> Reformats markdown documentation

src/site/pages/accessibility-guide.md, src/site/workspace.scss
This adds the first version of the a11y guide.
Link: https://deploy-preview-196--pf-next.netlify.com/accessibility-guide
Note: additional css is needed to handle how .md files present lists and nested lists.
=> Add first version of the a11y guide

.travis.yml
This configuration will build create a `gh-pages` branch off of master, using the `public' directory as the source.
=> fix(travis): Add Travis build config

build/blueprints/component/files/src/patternfly/components/__moduleName__/docs/code.md, build/blueprints/layout/files/src/patternfly/layouts/__moduleName__/docs/code.md, build/blueprints/pattern/files/src/patternfly/patterns/__moduleName__/docs/code.md, src/patternfly/components/Alert/docs/code.md, src/patternfly/components/Button/docs/code.md, src/patternfly/components/Content/docs/code.md, src/patternfly/components/SecondaryNav/docs/code.md, src/patternfly/layouts/Bullseye/docs/code.md, src/patternfly/layouts/Gallery/docs/code.md, src/patternfly/layouts/Grid/docs/code.md, src/patternfly/layouts/Level/docs/code.md, src/patternfly/layouts/Page/docs/code.md, src/patternfly/layouts/Split/docs/code.md, src/patternfly/layouts/Stack/docs/code.md, src/site/workspace.scss
This PR closes #209 and improves the CSS documentation template.
=> Changes the doc template

.stylelintrc
Update the `.stylelintrc` configuration file with improved error messages and update preferences.
Closes https://github.com/patternfly/patternfly-next/issues/117
=> fix(stylelint): update stylelint config

.travis.yml, build/blueprints/component/files/src/patternfly/components/__moduleName__/docs/code.md, build/blueprints/layout/files/src/patternfly/layouts/__moduleName__/docs/code.md, build/blueprints/pattern/files/src/patternfly/patterns/__moduleName__/docs/code.md, gatsby-config.js, package-lock.json, package.json, src/patternfly/components/Alert/docs/code.md, src/patternfly/components/Button/docs/code.md, src/patternfly/components/Button/styles.scss, src/patternfly/components/Content/docs/code.md, src/patternfly/components/Content/styles.scss, src/patternfly/components/SecondaryNav/docs/code.md, src/patternfly/layouts/Bullseye/docs/code.md, src/patternfly/layouts/Bullseye/styles.scss, src/patternfly/layouts/Gallery/docs/code.md, src/patternfly/layouts/Gallery/styles.scss, src/patternfly/layouts/Grid/docs/code.md, src/patternfly/layouts/Level/docs/code.md, src/patternfly/layouts/Level/styles.scss, src/patternfly/layouts/Page/docs/code.md, src/patternfly/layouts/Page/styles.scss, src/patternfly/layouts/Split/docs/code.md, src/patternfly/layouts/Split/styles.scss, src/patternfly/layouts/Stack/docs/code.md, src/patternfly/layouts/Stack/styles.scss, src/patternfly/utilities/variables.scss, src/site/workspace.scss
This PR closes #222 and removes support for IE11
=> Removes support for IE11

src/patternfly/components/Title/docs/code.md, src/patternfly/components/Title/docs/design.md, src/patternfly/components/Title/examples/index.js, src/patternfly/components/Title/examples/titleTypes.hbs, src/patternfly/components/Title/styles.scss, src/patternfly/components/Title/title.hbs
adding styles for titles outside of content component.
@andresgalante @srambach @jgiardino is this the right way to do margins?
as per #211 this addresses titles
closes #211
=> adds title component

patternfly_old/pf-c-button/pf-c-button.scss, src/patternfly/utilities/colors.scss
This updates the value of pf-blue-400 to pass AA requirements.
closes #241
=> updates pf-blue-400 value

src/patternfly/components/Dropdown/examples/index.js
remove unwanted text from description of expanded dropdown
=> docs(dropdown): update description for expanded dropdown

src/patternfly/layouts/Gallery/styles.scss
=> fix(gallery): fixes grid on gallery

src/patternfly/components/Button/docs/code.md, src/patternfly/components/Button/styles.scss
fix https://github.com/patternfly/patternfly-next/issues/258
verified in chrome, firefox, edge, safari, opera
=> refactor(Button): change button borders to inset box-shadows

gulpfile.js, package-lock.json, package.json, src/patternfly/_icons.scss, src/patternfly/patternfly.scss, src/patternfly/utilities/variables.scss, src/site/layouts/demo.js, src/site/layouts/index.js, static/assets/icons/fontawesome.css
This PR introduces the Font Awesome 5 icons (solid only) and completes https://github.com/patternfly/patternfly-next/issues/137.
A separate issue has been created (https://github.com/patternfly/patternfly-next/issues/304) to address the simplification of icons in PatternFly-Next.
=> feat(icons): Add Font Awesome 5 solid icons

src/patternfly/components/Button/docs/code.md, src/patternfly/components/Button/examples/buttonStates.hbs, src/patternfly/components/Button/examples/buttonTypes.hbs, src/patternfly/components/Button/styles.scss
The link button will in many cases include an icon, which is represented by {placeholder icon}. The action button will typically be used in isolation, modal close, list expand, etc.
Closes #256
=> feat(button): adds link and action buttons

gulpfile.js
=> fix(package): add basic and full css output for patternfly

src/patternfly/components/Alert/docs/code.md
After speaking further with @jgiardino the alerts docs needed further refinement around their a11y guidance. 
Closes #321
=> fix(alert):a11y doc update

src/patternfly/components/Button/styles.scss, src/patternfly/utilities/placeholders.scss
=> fix(themes): Fixes the btn component when its nested on a dark background

build/resolveAliases.js, gatsby-node.js, src/site/layouts/index.js, src/site/pages/contribution.md, src/site/pages/guidelines.md, src/site/pages/patterns/index.js
=> chore(patterns): remove patterns from site

src/site/pages/upgrade-guide.md
Adds the beginnings of an Upgrade Guide to PatternFly 4.
related to https://github.com/patternfly/patternfly-next/issues/300
=> feat(guide): Add Upgrade Guide

.eslintrc.js, build/blueprints/template/files/src/patternfly/__typeDirectory__/__namePascalized__/examples/index.js, build/patternfly-cli/pf.js, package-lock.json, package.json, src/patternfly/components/Alert/examples/index.js, src/patternfly/demos/Modal/examples/index.js, src/site/_site/Example/index.js, src/site/_site/Example/styles.scss, src/site/_site/GeneratedSource/index.js, src/site/_site/Handlebars/index.js, src/site/_site/Handlebars/styles.scss
=> chore(preview): add handlebars preview ability for the workspace

src/patternfly/components/Alert/docs/design.md
This adds a design.md starter file to the directory tree for he Alerts component that can be later populated with content.
=> Add design.md starter file to Alert/docs

build/blueprints/template/files/src/patternfly/__typeDirectory__/__namePascalized__/styles.scss, src/site/pages/guidelines.md
=> chore(guidelines): Fixes guidelines and blueprints to follow the changes done for themes

README.md, package.json
Also removes alpha tag from release so running npm install gives latest now
=> fix(release): move semantic release to master branch

build/blueprints/template/files/src/patternfly/__typeDirectory__/__namePascalized__/styles.scss, patternfly_old/pf-c-button/pf-c-button.scss, patternfly_old/pf-c-content/pf-c-content.scss, patternfly_old/pf-c-vertical-nav/pf-c-vertical-nav.scss, src/patternfly/components/Content/styles.scss, src/patternfly/components/ModalBox/styles.scss, src/patternfly/components/Title/docs/code.md, src/patternfly/components/Title/examples/titleTypes.hbs, src/patternfly/components/Title/styles.scss, src/patternfly/demos/Modal/examples/modal-example.hbs, src/patternfly/demos/Modal/examples/modal-lg-example.hbs, src/patternfly/demos/Modal/examples/modal-scroll-example.hbs, src/patternfly/demos/SimpleFormDemo/styles.scss, src/patternfly/utilities/bs-variables.scss, src/patternfly/utilities/variables.scss, src/site/pages/contribution.md, src/site/pages/guidelines.md
This PR changes the global sizes that used repeated letters (such as xxxxl) to 4xl.
Fixes https://github.com/patternfly/patternfly-next/issues/312
=> fix(global-sizes): rename global sizes to use numbers

src/patternfly/components/Form/styles.scss, src/patternfly/utilities/variables.scss
this cleans up some variables that were not needed in the global variables.
=> removes variables from global variables

src/patternfly/layouts/Grid/examples/grid-nested-example.hbs
=> fixes varying case in grid

src/site/pages/guidelines.md
This PR adds utilities to the guidelines, and clarifies what should and shouldn't be in a demo.
Fixes #340
=> fix(guidelines): Adds utilities and clarifies demos

src/patternfly/components/VerticalNav/docs/code.md, src/patternfly/components/VerticalNav/examples/vertical-nav-basic-example.hbs, src/patternfly/components/VerticalNav/styles.scss, src/patternfly/components/VerticalNav/vertical-nav-link-text.hbs, src/patternfly/components/VerticalNav/vertical-nav-link.hbs
fix https://github.com/patternfly/patternfly-next/issues/475
@mattnolting can you think of a better way to write the SCSS for the text bottom border to support those states?
=> fix(VerticalNav): make sure component css is scoped, introduce text bottom border on active/hover states

src/patternfly/components/Form/styles.scss
fix https://github.com/patternfly/patternfly-next/issues/495
=> fix(form): remove unused pf-m-align-right class

src/patternfly/components/FormControls/docs/code.md, src/patternfly/components/FormControls/styles.scss
fix https://github.com/patternfly/patternfly-next/issues/497
=> fix(FormControls): add .pf-m-disabled css, document .pf-m-form-control-alt

src/patternfly/demos/CardUpgradeExamples/docs/code.md, src/patternfly/demos/CardUpgradeExamples/examples/card-upgrade-examples-example2.hbs, src/patternfly/demos/SimpleFormDemo/examples/simple-form-demo-example.hbs
fix https://github.com/patternfly/patternfly-next/issues/511
=> fix(demos): change .pf-m-gutters to .pf-m-gutter and use double-quotes to wrap attribute vals

src/patternfly/components/SecondaryNav/docs/code.md, src/patternfly/components/SecondaryNav/examples/secondary-nav-example.hbs, src/patternfly/components/SecondaryNav/styles.scss
fix https://github.com/patternfly/patternfly-next/issues/514
=> refactor(secondaryNav): change pf-m-active to pf-m-current, small style and docs updates

package-lock.json, src/patternfly/components/Backdrop/styles.scss, src/patternfly/components/BackgroundImage/styles.scss, src/patternfly/components/Card/styles.scss, src/patternfly/demos/PageTest/docs/code.md, src/patternfly/demos/PageTest/docs/design.md, src/patternfly/demos/PageTest/examples/index.js, src/patternfly/demos/PageTest/examples/page-test-example1.hbs, src/patternfly/demos/PageTest/examples/page-test-example2.hbs, src/patternfly/demos/PageTest/page-test.hbs, src/patternfly/demos/PageTest/styles.scss, src/patternfly/layouts/Page/docs/code.md, src/patternfly/layouts/Page/examples/page-layout-example.hbs, src/patternfly/layouts/Page/page-section.hbs, src/patternfly/layouts/Page/page.hbs, src/patternfly/layouts/Page/styles.scss, src/patternfly/sass-utilities/variables.scss
This PR introduces improvements to the page layout. Things to keep in mind:
1- Even though it moved the parts of the header to the right places following the mockups, it doesn't add spacers between each part since we don't have the selector, brand and nav components yet.
2- The parts of the header have class names that are very use case specific. 
3- I am probably screwing things up with handlebars 😝
4- @mattnolting I've creates a PageTest demo to preview this PR, it'll good to have it as we create the different navigation parts 
5- There are changes on the size of the gutters and paddings around cards too. This is part of a global change that @kybaker and @mceledonia want to do to make the interface look more condensed. @LHinson THis might trigger new stories to accommodate other …
=> Improves page layout

patternfly_old/SecondaryNav/styles.scss, patternfly_old/VerticalNav/styles.scss, patternfly_old/pf-c-secondary-nav/pf-c-secondary-nav.scss, patternfly_old/pf-c-vertical-nav/pf-c-vertical-nav.scss, src/patternfly/components/Button/styles.scss, src/patternfly/components/Dropdown/styles.scss, src/patternfly/components/Form/styles.scss, src/patternfly/components/FormControls/styles.scss, src/patternfly/sass-utilities/bs-variables.scss, src/patternfly/sass-utilities/placeholders.scss, src/patternfly/sass-utilities/variables.scss
fix https://github.com/patternfly/patternfly-next/issues/364
=> reafactor(variables): remove property name from state variables

src/site/pages/guidelines.md
This PR fixes a comment on the guidelines on global variables and adds more example of global variables.
=> fix(guidelines): improves code guielines for global variables

src/patternfly/components/Dropdown/docs/code.md, src/patternfly/components/Dropdown/examples/dropdown-align-right-example.hbs, src/patternfly/components/Dropdown/examples/dropdown-dropup-example.hbs, src/patternfly/components/Dropdown/examples/dropdown-kebab-align-right-example.hbs, src/patternfly/components/Dropdown/examples/dropdown-kebab-right-aligned-example.hbs, src/patternfly/components/Dropdown/examples/dropdown-right-aligned-example.hbs, src/patternfly/components/Dropdown/examples/dropdown-top-example.hbs, src/patternfly/components/Dropdown/examples/index.js, src/patternfly/components/Dropdown/styles.scss, src/site/workspace.scss
fix https://github.com/patternfly/patternfly-next/issues/542
=> Update dropdown modifier classes

src/patternfly/components/Title/docs/code.md, src/patternfly/components/Title/examples/title-types-example.hbs, src/patternfly/components/Title/styles.scss
fix https://github.com/patternfly/patternfly-next/issues/546
=> refactor(title): remove pf-m-margin and add default margin for title size modifiers

src/patternfly/components/AboutModalBox/examples/about-modal-box-example.hbs, src/patternfly/components/AboutModalBox/styles.scss, src/patternfly/components/Button/docs/code.md, src/patternfly/components/Button/examples/button-types-example.hbs, src/patternfly/components/Button/styles.scss, src/patternfly/components/Dropdown/docs/code.md, src/patternfly/components/Dropdown/examples/dropdown-kebab-example.hbs, src/patternfly/components/Dropdown/examples/dropdown-kebab-right-aligned-example.hbs, src/patternfly/components/Dropdown/styles.scss, src/patternfly/components/ModalBox/examples/modal-box-basic-example.hbs, src/patternfly/components/ModalBox/examples/modal-box-lg-example.hbs, src/patternfly/components/ModalBox/examples/modal-box-no-header-example.hbs, src/patternfly/components/Popover/popover.hbs, src/patternfly/demos/AboutModal/examples/about-modal-example.hbs, src/patternfly/demos/Modal/examples/modal-example.hbs, src/patternfly/demos/Modal/examples/modal-lg-example.hbs, src/patternfly/demos/Modal/examples/modal-scroll-example.hbs, src/patternfly/demos/SimpleFormDemo/examples/simple-form-demo-example.hbs
fix https://github.com/patternfly/patternfly-next/issues/550
=> refactor(pf-m-action): change to pf-m-plain

src/patternfly/components/Form/docs/code.md, src/patternfly/components/Form/styles.scss, src/patternfly/demos/SimpleFormDemo/examples/simple-form-demo-example.hbs
fix https://github.com/patternfly/patternfly-next/issues/555
=> chore(form): remove .pf-m-subsection-title

src/patternfly/components/Form/docs/code.md, src/patternfly/components/Form/styles.scss
fix https://github.com/patternfly/patternfly-next/issues/575
=> chore(form): remove .pf-m-right

src/patternfly/components/Alert/docs/code.md, src/patternfly/components/Alert/examples/alert-danger-example.hbs, src/patternfly/components/Alert/examples/alert-info-example.hbs, src/patternfly/components/Alert/examples/alert-success-example.hbs, src/patternfly/components/Alert/examples/alert-warning-example.hbs, src/patternfly/components/Form/docs/code.md, src/patternfly/components/Form/form-label.hbs, src/patternfly/components/Form/styles.scss, src/patternfly/components/InputGroup/docs/code.md, src/patternfly/demos/SimpleFormDemo/examples/simple-form-demo-example.hbs, src/site/pages/accessibility-guide.md
fix https://github.com/patternfly/patternfly-next/issues/548
=> refactor(accessibility): replace .sr-only and .pf-m-visually-hidden with .pf-u-sr-only

src/patternfly/components/Popover/styles.scss
variable in popover (Line 48) has been removed
=> removed variable in popover

src/patternfly/components/Button/styles.scss, src/patternfly/components/Dropdown/styles.scss, src/patternfly/sass-utilities/variables.scss
fix https://github.com/patternfly/patternfly-next/issues/426
=> feat(a11y): add min-width/height for target size, update buttons

src/patternfly/demos/AboutModal/examples/index.js, src/patternfly/demos/AboutModal/styles.scss, src/patternfly/demos/Modal/docs/code.md, src/patternfly/demos/SimpleFormDemo/examples/index.js, src/patternfly/demos/SimpleFormDemo/simple-form-demo.hbs, src/patternfly/demos/dashboard/index.js
Closes https://github.com/patternfly/patternfly-next/issues/463
=> fix(demos): remove css from demos

package-lock.json, src/patternfly/components/Form/examples/form-input-group-example.hbs, src/patternfly/components/InputGroup/docs/code.md, src/patternfly/components/InputGroup/examples/input-group-example.hbs, src/patternfly/components/InputGroup/input-group-action.hbs, src/patternfly/components/InputGroup/input-group-text.hbs, src/patternfly/components/InputGroup/styles.scss, test-a11y/index.js
This updates the input group to better use handlebars. I've also added icons. These are different from `pf-c-input-group__text` because they are styled differently and are actionable. I'm not sure if the name is the best so feedback there would be great too.
closes #536 
This also deals with some of the issues that were raised in the accessibility audit. Specifically :
#618 
#617 
#616 
Thanks!
=> feat:adds icons to input group

src/patternfly/components/ModalBox/styles.scss
fix https://github.com/patternfly/patternfly-next/issues/601
=> fix(modalBox): use global vars for modal box title line height and font weight/size

src/patternfly/components/Dropdown/examples/dropdown-kebab-align-right-example.hbs, src/patternfly/components/Dropdown/styles.scss
Fixes #633 
This also removes the `.pf-m-action` from the kebab that is right aligned and adds the `pf-m-plain` class. @jgiardino please let me know if I missed something and that should have remained.
=> fix(dropdown):update border colour

src/site/pages/contribution.md
=> chore(guidelines): add pr review guidelines to the contribution guide

test-a11y/config.js
fix addresses issue with revisions made recently.
=> fix(a11y):update config script

.stylelintrc, src/patternfly/_variables.scss, src/patternfly/components/Content/styles.scss, src/patternfly/sass-utilities/scss-variables.scss
fix https://github.com/patternfly/patternfly-next/issues/668
=> feature(stylelint): add rule to match pattern for custom properties

src/patternfly/components/Card/examples/card-basic-example.hbs, src/patternfly/components/Card/examples/card-content-only-example.hbs, src/patternfly/components/Card/examples/card-no-footer-example.hbs, src/patternfly/components/Card/examples/card-no-header-example.hbs, src/patternfly/components/Card/styles.scss, src/patternfly/components/ModalBox/docs/code.md, src/patternfly/components/ModalBox/examples/modal-box-basic-example.hbs, src/patternfly/components/ModalBox/examples/modal-box-lg-example.hbs, src/patternfly/components/ModalBox/examples/modal-box-no-header-example.hbs, src/patternfly/components/ModalBox/styles.scss
fixes https://github.com/patternfly/patternfly-next/issues/672
=> refactor(card,modalbox): rewrite spacing modifiers for first/last children, whitespace formatting, doc updates for modalbox

src/patternfly/components/Popover/examples/popover-example.hbs, src/patternfly/components/Popover/popover.hbs, src/patternfly/components/Tooltip/examples/tooltip-example.hbs, src/patternfly/components/Tooltip/tooltip.hbs, src/patternfly/demos/AboutModal/examples/about-modal-example.hbs, test-a11y/index.js
this keeps the errors below 14, but color contrast checking is now enabled and will be running from now on
=> fix(reporter): turn back on color contrast a11y test and fix issues

package-lock.json, src/patternfly/demos/PageLayout/examples/page-layout-grouped-nav-example.hbs, src/patternfly/demos/PageLayout/examples/page-layout-horizontal-nav-example.hbs, src/patternfly/layouts/Page/docs/code.md, src/patternfly/layouts/Page/examples/page-layout-nav-horizontal-example.hbs, src/patternfly/layouts/Page/examples/page-layout-nav-vertical-example.hbs, src/patternfly/layouts/Page/styles.scss
This PR closes #683 and adds a darker section on the page layout
**Heads up!** this is a breaking change, the class `pf-m-dark` was replaced by `pf-m-dark-100`
=> feat(dark page layout section): adds a darker section on the page layout

src/patternfly/layouts/Toolbar/examples/index.js, src/patternfly/utilities/Accessibility/examples/index.js, src/patternfly/utilities/Alignment/examples/index.js, src/patternfly/utilities/Display/examples/index.js, src/patternfly/utilities/Flex/examples/index.js, src/patternfly/utilities/Spacing/examples/index.js, src/site/workspace.scss
Closes: https://github.com/patternfly/patternfly-next/issues/682
=> fix(layout): create appropriate utility class for workspace

package-lock.json, src/patternfly/sass-utilities/functions.scss
=> perf(functions): removes unused yiq function

build/blueprints/template/files/src/patternfly/__typeDirectory__/__namePascalized__/__nameDasherized__.hbs, build/blueprints/template/files/src/patternfly/__typeDirectory__/__namePascalized__/styles.scss, build/patternfly-cli/pf.js, src/patternfly/layouts/Grid/examples/grid-base-example.hbs, src/patternfly/layouts/Grid/examples/grid-gutter-example.hbs, src/patternfly/layouts/Grid/examples/grid-nested-example.hbs, src/patternfly/layouts/Grid/examples/grid-offsets-example.hbs, src/patternfly/layouts/Grid/examples/grid-responsive-example.hbs, src/patternfly/layouts/Grid/examples/grid-rowspan-example.hbs, src/patternfly/layouts/Grid/examples/grid-smart-grid-example.hbs, src/patternfly/layouts/Grid/examples/grid-smart-grid-overrides-example.hbs, src/patternfly/layouts/Grid/grid-item.hbs, src/patternfly/layouts/Grid/grid.hbs, src/patternfly/layouts/Grid/styles.scss, src/site/pages/contribution.md
Closes #694 
Closes #500 
Closes #499
=> chore(update blueprints): Updates contribution guidelines and code generator 

src/patternfly/components/Card/styles.scss
=> fix(card): fixes card background

src/patternfly/components/Check/check.scss, src/patternfly/components/Check/docs/code.md
fixes font size for check label and spelling mistake 🤦‍♂️
=> fix(check):updates font size, variable spelling

src/site/_site/Documentation/index.js, src/site/_site/Documentation/styles.scss, src/site/workspace.scss
=> fix(bleedingcss): no longer set any h2 styles globally from workspace

src/patternfly/components/AboutModalBox/about-modal-box.scss, src/patternfly/components/ModalBox/modal-box.scss, src/patternfly/layouts/Page/page.scss
fixes https://github.com/patternfly/patternfly-next/issues/795
=> fix(scss): interpolate scss vars assigned to css custom properties

src/patternfly/components/Backdrop/backdrop.scss, src/patternfly/components/Backdrop/docs/code.md
=> fix(backdrop body scroll): Adds class `pf-c-backdrop__open` to backdrop component. Sets body to `overflow: hidden;`

src/patternfly/components/Nav/nav.scss
=> Increase specificity of expandable nav toggle 

src/site/pages/contribution.md
Updating to provide guidance on doc formatting
closes #816
=> fix(docs): Update guidelines

src/patternfly/components/Switch/docs/code.md, src/patternfly/components/Switch/examples/switch-disabled-example.hbs, src/patternfly/components/Switch/examples/switch-example.hbs, src/patternfly/components/Switch/examples/switch-no-label-example.hbs, src/patternfly/components/Switch/switch.scss
=> enhancement(switch): Update the Switch to reflect the latest design

src/patternfly/components/Nav/nav.scss, src/patternfly/layouts/Page/page.scss
This is based on the redesign that @kybaker put together to offer a more condensed side navigation.
fixes #891
=> fix(nav): update spacing for nav system

src/patternfly/layouts/Page/page.scss
fixes https://github.com/patternfly/patternfly-next/issues/907
=> fix(page): fix padding var order, update dark attr selector

src/patternfly/components/Brand/examples/index.js
=> fix(brand): remove min-height in example

src/patternfly/layouts/Page/page.scss, src/patternfly/utilities/Spacing/spacing.scss
fixes https://github.com/patternfly/patternfly-next/issues/780
=> fix(page): create stacking context of page layout elements with header over the sidebar over the main area

src/patternfly/components/Brand/examples/index.js, src/patternfly/components/Nav/nav.scss
=> Update horizontal nav spacers

src/site/pages/guidelines.md
fixes https://github.com/patternfly/patternfly-next/issues/943
=> docs(guidelines): add more complex css var example

src/patternfly/_variables.scss, src/patternfly/components/EmptyState/docs/code.md, src/patternfly/components/EmptyState/docs/design.md, src/patternfly/components/EmptyState/empty-state-action.hbs, src/patternfly/components/EmptyState/empty-state-body.hbs, src/patternfly/components/EmptyState/empty-state-icon.hbs, src/patternfly/components/EmptyState/empty-state.hbs, src/patternfly/components/EmptyState/empty-state.scss, src/patternfly/components/EmptyState/examples/empty-state-complex-example.hbs, src/patternfly/components/EmptyState/examples/empty-state-simple-example.hbs, src/patternfly/components/EmptyState/examples/index.js, src/patternfly/sass-utilities/scss-variables.scss
* The icon size should be 54px. I suspect this is a one-off, as any other icons will be significantly smaller.
* In my mockups I am using a max-width of 400px, let's try that and see how it works.
* 24px between icon and title
* 16px between title and body
* 32px between body (or title, if body not present) and actions
* 8px between buttons
fixes https://github.com/patternfly/patternfly-next/issues/293
=> feat(EmptyState): adds empty state component

src/patternfly/components/Nav/docs/code.md, src/patternfly/components/Nav/nav.scss, src/patternfly/demos/PageLayout/examples/page-layout-default-nav-header-example.hbs, src/patternfly/layouts/Page/docs/code.md
fixes https://github.com/patternfly/patternfly-next/issues/1011
=> chore(Nav/Page): remove pf-m-tall artifacts

src/patternfly/demos/PageLayout/examples/page-layout-horizontal-nav-example.hbs, src/patternfly/layouts/Page/page.scss
adding some adjustments to the page layout to accommodate horizontal nav.
Also fixed the negative margin that wasn't working before :)
Updated the horizontal page layout demo to not hide the brand on small screens.
=> fix(nav): fix spacers, add min height for horizontal nav

src/patternfly/layouts/Page/page.scss
removes bug that shows scroll bar on vertical nav.
=> fix(page): scroll bug

src/patternfly/components/Nav/nav.scss
=> fix(page): update spacers

src/patternfly/components/Label/styles.scss
=> refactor(Label): refactor css

src/patternfly/components/Login/examples/login-simple-example.hbs, src/patternfly/demos/Toolbar/examples/toolbar-complex-example.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1043
=> fix(Login/Toolbar): remove redundant .pf-c-button from modifier

src/patternfly/components/Dropdown/dropdown-toggle.hbs, src/patternfly/components/Dropdown/dropdown.scss, src/patternfly/layouts/Page/page.scss
Update the handlebars to not pull in the toggle text if it's just a kebab dropdown.
Fixes hover/active/default colour for plain dropdown modifier
adds max-width to dropdown in page layout toolbar for username.
This closes
#1053
#1054
#1055
=> fix(dropdown): adds max-width, fixes dropdown handlebars

src/patternfly/components/Table/examples/table-compact-example.hbs, src/patternfly/components/Table/examples/table-expandable-example.hbs, src/patternfly/components/Table/examples/table-simple-with-checkboxes-example.hbs, src/patternfly/components/Table/examples/table-width-example.hbs, src/patternfly/components/Table/table.scss
=> Table updates

src/patternfly/components/Content/content.hbs, src/patternfly/components/Dropdown/dropdown-multi-select.hbs, src/patternfly/components/Dropdown/dropdown-select.hbs, src/patternfly/components/Dropdown/dropdown.hbs, src/patternfly/components/Table/examples/table-expandable-example.hbs, src/patternfly/components/Table/table-td.hbs
=> fix(content,dropdown,table): fix hbs attributes typos

src/patternfly/components/Card/card.scss
This issue closes #986 
- consolidated padding variables
=> refactor(card): consolidate variables(#986)

src/patternfly/components/DataList/styles.scss
fixes https://github.com/patternfly/patternfly-next/issues/989
=> refactor(datalist): refactor css vars

src/patternfly/components/ChipGroup/examples/chip-group-select-collapsed-example.hbs, src/patternfly/components/ChipGroup/examples/chip-group-select-expanded-example.hbs, src/patternfly/components/ChipGroup/examples/chip-group-toolbar-collapsed-example.hbs, src/patternfly/components/ChipGroup/examples/chip-group-toolbar-expanded-example.hbs, src/patternfly/components/Form/examples/form-help-text-example.hbs, src/patternfly/components/Form/examples/form-horizontal-align-labels-example.hbs, src/patternfly/components/Form/examples/form-vertical-align-labels-example.hbs, src/patternfly/components/Form/form-helper-text.hbs, src/patternfly/components/InputGroup/examples/input-group-example.hbs, src/patternfly/demos/BasicForms/examples/horizontal-form-demo-example.hbs, src/patternfly/demos/BasicForms/examples/simple-form-demo-example.hbs, src/patternfly/demos/PageLayout/examples/page-layout-default-nav-header-example.hbs, src/patternfly/demos/PageLayout/examples/page-layout-expandable-nav-example.hbs, src/patternfly/demos/PageLayout/examples/page-layout-grouped-nav-example.hbs, src/patternfly/demos/PageLayout/examples/page-layout-horizontal-nav-example.hbs, src/patternfly/demos/PageLayout/examples/page-layout-simple-nav-example.hbs, src/patternfly/demos/PageLayout/page-template-header-brand-elements.hbs, src/patternfly/demos/PageLayout/page-template-header-tools-elements.hbs, src/patternfly/demos/Toolbar/examples/toolbar-complex-example.hbs, src/patternfly/demos/Toolbar/examples/toolbar-simple-example.hbs, src/patternfly/layouts/Page/examples/page-layout-nav-horizontal-example.hbs, src/patternfly/layouts/Page/examples/page-layout-nav-vertical-example.hbs, src/patternfly/layouts/Page/page.hbs, src/patternfly/layouts/Toolbar/examples/toolbar-section-example.hbs, test-a11y/config.js
fixes https://github.com/patternfly/patternfly-next/issues/616
=> fix(a11y): ensure id attributes are unique

src/patternfly/upgrade-examples/LoginUpgradeExamples/docs/code.md, src/patternfly/upgrade-examples/LoginUpgradeExamples/examples/index.js, src/patternfly/upgrade-examples/LoginUpgradeExamples/examples/login-upgrade-examples-pf3-login.hbs, src/patternfly/upgrade-examples/LoginUpgradeExamples/examples/login-upgrade-examples-pf4-login.hbs, src/patternfly/upgrade-examples/LoginUpgradeExamples/login-upgrade-examples.hbs
fixes #420 
Comparing PF3 and PF4 login page examples. 
**NOTE:**
The CSS code isn't exact correct as of right now. Some PF3 styling are not transferring over correctly. But the markup for PF3 and PF4 are correct.
=> feat(LoginUpgradeExamples): Adding login upgrade migration example

src/patternfly/layouts/Gallery/gallery.scss
fixes https://github.com/patternfly/patternfly-next/issues/1005
=> refactor(gallery): rename grid-gap var

src/patternfly/components/InputGroup/input-group.scss
=> refactor(InputGroup): refactor css

src/patternfly/_variables.scss, src/patternfly/components/Alert/alert.scss, src/patternfly/components/Alert/docs/code.md, src/patternfly/components/EmptyState/empty-state.scss, src/patternfly/sass-utilities/scss-variables.scss
fixes https://github.com/patternfly/patternfly-next/issues/981
fixes https://github.com/patternfly/patternfly-next/issues/1021
=> refactor(Alert/EmptyState): redefine css vars instead of properties for alert, add icon size range vars and update empty state and alert

src/patternfly/_base.scss, src/patternfly/components/Breadcrumb/breadcrumb.scss, src/patternfly/demos/PageLayout/page-template-header-brand-elements.hbs
=> refactor(breadcrumb): redefine css variables

src/patternfly/components/Badge/badge.scss, src/patternfly/components/Badge/docs/code.md
fixes https://github.com/patternfly/patternfly-next/issues/983
=> refactor(badge): redefine CSS vars instead of properties

src/patternfly/components/Button/button.scss
fixes https://github.com/patternfly/patternfly-next/issues/985
=> refactor(button): refactor CSS vars

src/patternfly/layouts/Grid/grid.scss
fixes https://github.com/patternfly/patternfly-next/issues/1006
=> refactor(grid): refactor css vars

src/patternfly/components/BackgroundImage/background-image.scss
fixes https://github.com/patternfly/patternfly-next/issues/982
=> refactor(BackgroundImage): refactor CSS vars

src/patternfly/components/Switch/docs/code.md, src/patternfly/components/Switch/switch.scss
=> refactor(switch): refactor css vars

src/patternfly/components/Login/login.scss
fixes https://github.com/patternfly/patternfly-next/issues/1092
=> fix(login): remove custom check styling

src/patternfly/components/BackgroundImage/background-image.scss
closes #1116 
Didn't remove the corresponding images but I think we probably could.
=> fix(backgroud-image): reduces media query count

src/patternfly/components/AboutModalBox/about-modal-box.scss, src/patternfly/layouts/Grid/grid.scss
fixes https://github.com/patternfly/patternfly-next/issues/1133
=> fix(vars): interpolate scss vars

src/patternfly/_base.scss
fixes https://github.com/patternfly/patternfly-next/issues/1169
=> refactor(base.scss): update pf shield to allow pf-[cul] anywhere in the class list

src/patternfly/components/Check/check.scss
fixes https://github.com/patternfly/patternfly-next/issues/1154
=> fix(check): rename css var

src/patternfly/components/Switch/switch.scss
fixes https://github.com/patternfly/patternfly-next/issues/1158
=> refactor(switch): separate css vars

src/patternfly/components/Badge/badge.scss
fixes https://github.com/patternfly/patternfly-next/issues/1156
=> refactor(badge): separate css vars

src/patternfly/components/Card/card.scss
fixes https://github.com/patternfly/patternfly-next/issues/1152
=> refactor(card): Separate css vars

src/patternfly/components/Content/content.scss, src/patternfly/components/Content/examples/content-template-example.hbs
fixes https://github.com/patternfly/patternfly-next/issues/988
=> refactor(content): refactor css vars

src/patternfly/components/Page/examples/page-component-nav-vertical-example.hbs, src/patternfly/components/Tooltip/tooltip.scss
fixes https://github.com/patternfly/patternfly-next/issues/1004
=> refactor(tooltip): refactor css vars

src/patternfly/components/Form/form.scss, src/patternfly/components/Login/examples/index.js, src/patternfly/components/Login/examples/login-invalid-example.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1017
=> feature(login): add error state to login page component

src/patternfly/components/InputGroup/input-group.scss
fixes https://github.com/patternfly/patternfly-next/issues/1164
=> refactor(inputgroup): separate css vars

src/patternfly/components/Alert/alert.scss
fixes https://github.com/patternfly/patternfly-next/issues/1162
=> refactor(alert): separate css vars

src/patternfly/components/Button/button.scss
fixes https://github.com/patternfly/patternfly-next/issues/1160
=> refactor(button): separate css vars

src/patternfly/components/DataList/styles.scss
fixes https://github.com/patternfly/patternfly-next/issues/1166
=> refactor(datalist): separate css vars

src/patternfly/_base.scss, src/patternfly/components/Nav/docs/code.md, src/patternfly/components/Nav/examples/nav-simple-list-example.hbs, src/patternfly/components/Nav/nav.scss, src/patternfly/components/Page/page-sidebar.hbs, src/patternfly/demos/Page/examples/page-component-expandable-nav-example.hbs
=> fix(nav): add separator modifier for sub nav items

src/patternfly/components/Check/check-label.hbs, src/patternfly/components/Check/check.hbs, src/patternfly/components/Check/docs/code.md, src/patternfly/components/Check/examples/check-checkbox-example.hbs, src/patternfly/components/Check/examples/check-radio-example.hbs, src/site/workspace.scss, test-a11y/config.js
fixes https://github.com/patternfly/patternfly-next/issues/1210
=> refactor(check): update docs, allow for label to wrap input

src/patternfly/_base.scss
fixes https://github.com/patternfly/patternfly-next/issues/1245
=> refactor(shield): apply box-sizing, padding, margin, background-color to all descendents

src/patternfly/components/Login/login.scss
Closes #996 and #1008 . Refactor CSS.
=> refactor(LoginBox): refactor CSS

src/patternfly/components/Chip/chip.scss, src/patternfly/components/ChipGroup/chip-group.scss
=> refactor(chip&chipGroup): refactor css vars

src/patternfly/components/Alert/alert-body.hbs, src/patternfly/components/Alert/alert-checkcircle-icon.hbs, src/patternfly/components/Alert/alert-close.hbs, src/patternfly/components/Alert/alert-description.hbs, src/patternfly/components/Alert/alert-exclamationcircle-icon.hbs, src/patternfly/components/Alert/alert-exclamationtriangle-icon.hbs, src/patternfly/components/Alert/alert-icon.hbs, src/patternfly/components/Alert/alert-infocircle-icon.hbs, src/patternfly/components/Alert/alert.scss, src/patternfly/components/Alert/docs/code.md, src/patternfly/components/Alert/examples/alert-types-example.hbs, src/patternfly/components/Alert/examples/alert-variations-example.hbs, src/patternfly/components/AlertGroup/docs/alert-group.md, src/patternfly/components/AlertGroup/docs/design.md, src/patternfly/components/AlertGroup/docs/toast-group.md, src/patternfly/components/AlertGroup/examples/alert-group-example.hbs, src/patternfly/components/AlertGroup/examples/toast-group-example.hbs, src/patternfly/demos/Page/page-template-header-tools-elements.hbs, src/patternfly/upgrade-examples/AlertUpgradeExamples/examples/alert-upgrade-example-pf4-alert.hbs, src/patternfly/upgrade-examples/AlertUpgradeExamples/examples/alert-upgrade-example-pf4-notification.hbs, src/site/pages/accessibility-guide.md
closes #1226
This required a new way to build the alerts using grid. I've also updated the alert/alert group to have proper a11y based on #1226 as well as conversations with @jgiardino and @seanforyou23
=> fix(alerts): accessibility updates

src/patternfly/_variables.scss, src/patternfly/sass-utilities/placeholders.scss, src/patternfly/sass-utilities/scss-variables.scss
fixes https://github.com/patternfly/patternfly-next/issues/1199
=> refactor(base): update link colors

src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly-next/issues/1009
=> refactor(page): refactor css

src/patternfly/components/AboutModalBox/about-modal-box.scss
fixes #980 
This is a redo of https://github.com/patternfly/patternfly-next/pull/1014
=> refactor(AboutModalBox): refactor CSS, redefine vars instead of redefining properties

src/patternfly/components/Badge/badge.scss
=> fix(Badge): set a minimum width for badge and align text to center

src/patternfly/components/List/docs/code.md, src/patternfly/components/List/examples/index.js, src/patternfly/components/List/examples/list-grid-example.hbs, src/patternfly/components/List/examples/list-inline-example.hbs, src/patternfly/components/List/examples/list-ordered-example.hbs, src/patternfly/components/List/examples/list-simple-example.hbs, src/patternfly/components/List/examples/list-unordered-example.hbs, src/patternfly/components/List/list.hbs, src/patternfly/components/List/list.scss, src/patternfly/components/Login/examples/login-invalid-example.hbs
=> List Component Update

src/patternfly/components/Tooltip/tooltip.scss
closes #1224 
//cc @mceledonia
=> fix(Tooltip): visual changes to spacing, text and shadow

src/patternfly/components/Popover/examples/popover-bottom-example.hbs, src/patternfly/components/Popover/examples/popover-left-example.hbs, src/patternfly/components/Popover/examples/popover-no-header-example.hbs, src/patternfly/components/Popover/examples/popover-right-example.hbs, src/patternfly/components/Popover/examples/popover-top-example.hbs, src/patternfly/upgrade-examples/PopoverUpgradeExamples/examples/popover-upgrade-examples-example2.hbs
=> fix(popover): change close icon

src/patternfly/components/Nav/nav.scss, src/patternfly/components/Page/page.scss
closes #998 
We could condense hover, active, focus, current but not sure it's the best approach. They aren't cut and dry but we could save some lines. What do you think @mcoker ?
=> fix(nav): updates variables

src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly-next/issues/1275
cc @jschuler
=> bug(page): add height:100% to page section

src/patternfly/_variables.scss, src/patternfly/components/FormControl/form-control.scss, src/patternfly/sass-utilities/scss-variables.scss
This closes #1237 
Need to confirm these styles changes with @kybaker
=> fix(inputgroup): updates disabled/readonly states

src/patternfly/components/Form/form.scss, src/patternfly/components/FormControl/form-control.scss
=> refactor(Form & FormControl): refactor css variables

src/patternfly/_base.scss, src/patternfly/components/AppLauncher/app-launcher.scss, src/patternfly/components/Dropdown/dropdown.scss, src/patternfly/components/OptionsMenu/docs/code.md, src/patternfly/components/OptionsMenu/docs/design.md, src/patternfly/components/OptionsMenu/examples/index.js, src/patternfly/components/OptionsMenu/examples/options-menu-align-right-example.hbs, src/patternfly/components/OptionsMenu/examples/options-menu-multiple-example.hbs, src/patternfly/components/OptionsMenu/examples/options-menu-plain-example.hbs, src/patternfly/components/OptionsMenu/examples/options-menu-plain-text-example.hbs, src/patternfly/components/OptionsMenu/examples/options-menu-single-example.hbs, src/patternfly/components/OptionsMenu/examples/options-menu-top-example.hbs, src/patternfly/components/OptionsMenu/options-menu-menu.hbs, src/patternfly/components/OptionsMenu/options-menu-multiple.hbs, src/patternfly/components/OptionsMenu/options-menu-single.hbs, src/patternfly/components/OptionsMenu/options-menu-toggle-button.hbs, src/patternfly/components/OptionsMenu/options-menu-toggle.hbs, src/patternfly/components/OptionsMenu/options-menu.hbs, src/patternfly/components/OptionsMenu/options-menu.scss, src/patternfly/components/Select/select.scss, src/site/workspace.scss, test-a11y/config.js
fixes https://github.com/patternfly/patternfly-next/issues/1088
Also added a small fix for the expanded color on the app launcher @matthewcarleton
=> feat(OptionsMenu): adds options menu

src/patternfly/_variables.scss, src/patternfly/components/EmptyState/empty-state.scss, src/patternfly/components/Form/form.scss, src/patternfly/components/Login/docs/code.md, src/patternfly/components/Login/examples/login-invalid-example.hbs, src/patternfly/components/Login/examples/login-simple-example.hbs, src/patternfly/components/Login/login-main-footer-band-item.hbs, src/patternfly/components/Login/login-main-footer-band.hbs, src/patternfly/components/Login/login-main-footer-grid-item.hbs, src/patternfly/components/Login/login-main-footer-grid.hbs, src/patternfly/components/Login/login-main-footer-link-text.hbs, src/patternfly/components/Login/login-main-footer-link.hbs, src/patternfly/components/Login/login-main-footer-links-item-link.hbs, src/patternfly/components/Login/login-main-footer-links-item.hbs, src/patternfly/components/Login/login-main-footer-links.hbs, src/patternfly/components/Login/login.scss, src/patternfly/sass-utilities/scss-variables.scss
This closes #1256, closes #1189, closes #1069, Closes #1063
i've added some icon updates too. You'll see new scss vars for dark, light which then need to be updated in the Empty state.
I've added the helper text modifier `pf-m-hidden` to allow us to keep it on the page for spacing but not have it visible to sighted users/screen readers.
The social login links will need a tooltip when bumped to React
=> fix(login): new login layout

src/patternfly/_base.scss, src/patternfly/components/Page/page.scss, src/site/workspace.scss
=> bug(page): change 100vh to 100%

src/patternfly/components/Page/docs/code.md, src/patternfly/components/Page/examples/page-component-nav-vertical-example.hbs, src/patternfly/demos/Page/page-template-header-brand-elements.hbs
=> fix(page): updates toggle to use aria-expanded

src/patternfly/components/Dropdown/docs/code.md, src/patternfly/components/Dropdown/dropdown-basic.hbs, src/patternfly/components/Dropdown/dropdown-menu-basic.hbs, src/patternfly/components/Dropdown/dropdown-menu-split-button.hbs, src/patternfly/components/Dropdown/dropdown-toggle-button.hbs, src/patternfly/components/Dropdown/dropdown-toggle-check.hbs, src/patternfly/components/Dropdown/dropdown-toggle.hbs, src/patternfly/components/Dropdown/dropdown.hbs, src/patternfly/components/Dropdown/dropdown.scss, src/patternfly/components/Dropdown/examples/dropdown-split-button-example.hbs, src/patternfly/components/Dropdown/examples/index.js
fixes https://github.com/patternfly/patternfly-next/issues/1259
=> feat(dropdown): adds split button dropdown

src/patternfly/components/AboutModalBox/docs/code.md, src/patternfly/components/ModalBox/docs/code.md, src/patternfly/components/Popover/docs/code.md, src/patternfly/demos/AboutModal/about-modal.hbs, src/patternfly/demos/Modal/modal.hbs, src/site/pages/accessibility-guide.md, src/site/workspace.scss
=> fix(a11y): updates docs

src/patternfly/_base.scss
fixes https://github.com/patternfly/patternfly-next/issues/1304
=> fix(shield): remove shield styles from children of .pf- elements

src/patternfly/components/Content/content.scss
fixes https://github.com/patternfly/patternfly-next/issues/1311
=> fix(content): don't overwrite color for every element

src/patternfly/_base.scss, src/patternfly/sass-utilities/scss-variables.scss
fixes https://github.com/patternfly/patternfly-next/issues/1313
=> fix(_base.scss): move pf3 cdn imports to _base.scss

src/patternfly/components/ModalBox/docs/code.md, src/patternfly/components/ModalBox/examples/index.js, src/patternfly/components/ModalBox/examples/modal-box-sm-example.hbs, src/patternfly/components/ModalBox/modal-box.scss, src/patternfly/demos/Modal/examples/modal-example.hbs, src/patternfly/demos/Modal/examples/modal-lg-example.hbs, src/patternfly/demos/Modal/examples/modal-scroll-example.hbs, test-a11y/config.js
fixes https://github.com/patternfly/patternfly-next/issues/1202
=> refactor(modalbox): modal full width by default, add pf-m-sm

src/patternfly/components/Nav/examples/nav-example.hbs, src/patternfly/components/Nav/examples/nav-expandable-example.hbs, src/patternfly/components/Nav/examples/nav-expandable-subnav-titles-example.hbs, src/patternfly/components/Nav/examples/nav-horizontal-list-example.hbs, src/patternfly/components/Nav/examples/nav-list-grouped-example.hbs, src/patternfly/components/Nav/examples/nav-mixed-example.hbs, src/patternfly/components/Nav/examples/nav-simple-list-example.hbs, src/patternfly/components/Nav/examples/nav-tertiary-list-example.hbs, src/patternfly/components/Nav/nav.hbs, src/patternfly/components/Page/examples/page-component-nav-vertical-example.hbs, src/patternfly/components/Tabs/docs/tabs-primary.md, src/patternfly/demos/Page/page-template-header-brand-elements.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1127
=> fix(nav): Consistent labels for <nav> elements

src/patternfly/components/DataList/data-list.scss, src/patternfly/components/DataList/examples/index.js
fixes https://github.com/patternfly/patternfly-next/issues/1038
fixes https://github.com/patternfly/patternfly-next/issues/1039
fixes https://github.com/patternfly/patternfly-next/issues/989
=> refactor(DataList): remove utility classes, refactor CSS, rename stylesheet

src/patternfly/components/ModalBox/examples/modal-box-sm-example.hbs
=> fix(modalbox): duplicate id a11y violation

src/patternfly/components/Login/examples/login-invalid-example.hbs
=> chore(login): update demo ids

src/patternfly/components/ContextSelector/examples/context-selector-example.hbs
=> chore(context-selector): update demo ids

src/patternfly/components/Table/examples/table-expandable-example.hbs, src/patternfly/components/Table/examples/table-simple-with-checkboxes-example.hbs
=> fix(table): fix table id in examples

src/patternfly/_base.scss
fixes https://github.com/patternfly/patternfly-next/issues/1324
=> chore(_base.scss): update component list in shield

src/patternfly/components/Label/docs/code.md, src/patternfly/components/Label/examples/index.js, src/patternfly/components/Label/label.scss
=> fix(label): remove hover state

src/patternfly/_base.scss
verified it doesn't break my local version of OpenShift console.
fixes https://github.com/patternfly/patternfly-next/issues/1336
=> fix(base.scss): Update shield to replicate base SCSS styles for .pf- class elements

src/patternfly/components/Login/docs/code.md, src/patternfly/components/Login/examples/login-invalid-example.hbs, src/patternfly/components/Login/examples/login-simple-example.hbs, src/patternfly/components/Login/login-footer-link.hbs, src/patternfly/upgrade-examples/LoginUpgradeExamples/examples/login-upgrade-examples-pf4-login.hbs
=> fix(login): removes unused classes

src/patternfly/_base.scss
fixes https://github.com/patternfly/patternfly-next/issues/1352
=> fix(base.scss): revert shield scss to apply inheritable properties to component/layout classes, and non-inheritable properties to .pf-[cul] elements

src/patternfly/components/Dropdown/dropdown.scss, src/patternfly/components/OptionsMenu/options-menu.scss
fixes https://github.com/patternfly/patternfly-next/issues/1349
=> fix(dropdown): fix z-index issue with toggle border appearing on top of buttons in toggle

README.md, gatsby-config.js, gatsby-node.js, package-lock.json, package.json, src/patternfly/components/DataList/docs/code.md, src/patternfly/components/Tabs/docs/code.md, src/site/_site/CodepenButton/index.js, src/site/_site/FullPageExampleLayout/index.js, src/site/_site/Layout/index.js, src/site/pages/upgrade-guide.md
Closes #1121
This is a major milestone for us - great job everybody!
=> feat(beta): change to @patternfly/patternfly for beta release

commitlint.config.js, package-lock.json, package.json
closes #1122 -- adds commit linting & forces users to stick to this pattern for commit messages:
type(scope?): subject  #scope is optional
=> feat(devx): add commitlint husky pre commit hook

src/patternfly/components/Form/form.scss
fixes https://github.com/patternfly/patternfly-next/issues/1364
=> fix(form): update horizontal margin between action buttons

src/patternfly/components/Toolbar/examples/toolbar-filter-expanded-checked-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-mobile-filter-checked-example.hbs
=> fix(toolbar): update total items text in checked toolbar demos

src/site/pages/guidelines.md
fixes https://github.com/patternfly/patternfly-next/issues/1388
=> docs(guidelines): avoid nested calc() functions

src/patternfly/_base.scss
fixes https://github.com/patternfly/patternfly-next/issues/1382
fixes https://github.com/patternfly/patternfly-next/issues/1368
=> fix(base.scss): add trailing hyphen, remove pf-u from attr selectors

src/patternfly/components/ModalBox/modal-box.scss
fixes https://github.com/patternfly/patternfly-next/issues/1385
=> fix(modalbox): remove max-height from body

src/patternfly/components/TabContent/docs/code.md, src/patternfly/components/TabContent/docs/design.md, src/patternfly/components/TabContent/examples/index.js, src/patternfly/components/TabContent/examples/tab-content-example.hbs, src/patternfly/components/TabContent/tab-content.hbs, src/patternfly/components/Tabs/docs/code.md, src/patternfly/components/Tabs/docs/tabs-primary.md, src/patternfly/components/Tabs/examples/index.js, src/patternfly/components/Tabs/examples/tabs-primary.hbs, src/patternfly/components/Tabs/tabs-section.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1093
=> feat(tabcontent): adds tab content component

src/patternfly/components/Table/table-grid.scss, src/patternfly/components/Table/table.scss
=> fix(table): remove scroll from desktop

src/patternfly/components/DataList/data-list-check.hbs, src/patternfly/components/DataList/examples/data-list-check-action-example.hbs, src/patternfly/components/DataList/examples/data-list-expandable-example.hbs, src/patternfly/components/DataList/examples/data-list-width-example.hbs
=> fix(datalist): remove pf-c-check__input class

src/patternfly/components/Table/examples/table-compact-example.hbs, src/patternfly/components/Table/examples/table-expandable-example.hbs, src/patternfly/components/Table/examples/table-simple-with-checkboxes-example.hbs, src/patternfly/components/Table/examples/table-width-example.hbs
closes #1271 
//cc @jgiardino @mcoker
=> fix(Table): Remove pf-c-check__input class from the check-all input

src/patternfly/components/ModalBox/modal-box.scss
fixes https://github.com/patternfly/patternfly-next/issues/1425
=> fix(modal): update space between title and body

src/patternfly/components/ContextSelector/context-selector.scss
fixes https://github.com/patternfly/patternfly-next/issues/1422
=> fix(contextselector): fix background color in dark theme

src/patternfly/components/Select/select.scss
=> fix(select): fixes spacing within select toggle

src/patternfly/components/Nav/nav.scss
=> refactor(nav): update color variable

src/patternfly/patternfly-no-reset.scss
fixes https://github.com/patternfly/patternfly-next/issues/1415
=> feat(patternfly-no-reset.css): add patternfly.css without reset

src/patternfly/components/Progress/docs/code.md, src/patternfly/components/Progress/docs/progress-dynamic.md, src/patternfly/components/Progress/examples/index.js, src/patternfly/components/Progress/examples/progress-dynamic-example.hbs, src/patternfly/components/Progress/examples/progress-failure-example.hbs, src/patternfly/components/Progress/examples/progress-finite-step-example.hbs, src/patternfly/components/Progress/examples/progress-inside-example.hbs, src/patternfly/components/Progress/examples/progress-inside-success-example.hbs, src/patternfly/components/Progress/examples/progress-large-example.hbs, src/patternfly/components/Progress/examples/progress-no-measure-example.hbs, src/patternfly/components/Progress/examples/progress-no-measure-failure-example.hbs, src/patternfly/components/Progress/examples/progress-outside-example.hbs, src/patternfly/components/Progress/examples/progress-outside-failure-example.hbs, src/patternfly/components/Progress/examples/progress-simple-example.hbs, src/patternfly/components/Progress/examples/progress-small-example.hbs, src/patternfly/components/Progress/examples/progress-step-instruction-example.hbs, src/patternfly/components/Progress/examples/progress-step-integer-example.hbs, src/patternfly/components/Progress/examples/progress-success-example.hbs, src/patternfly/components/Progress/progress-indicator.hbs, src/patternfly/components/Progress/progress.hbs, src/patternfly/components/Progress/progress__measure.hbs
fixes #1128 
- Adding new progress bar updates to reflect different use cases
- Adjusted handlebar configuration to better reflect dynamic aria values
- Replaced documentation instructions
=> feat(ProgressBarUpdate): aria update for progress bar component

src/patternfly/patternfly.scss
fixes https://github.com/patternfly/patternfly-next/issues/1370
=> fix(patternfly.scss): add extension to import for patternfly-base.scss

src/patternfly/_base.scss, src/patternfly/components/Accordion/accordion.scss, src/patternfly/components/Accordion/examples/index.js, src/patternfly/components/Badge/examples/index.js
fixes https://github.com/patternfly/patternfly-next/issues/1432
=> fix(base): add missing components to base, remove unnecessary imports

src/patternfly/components/Table/table-nested.hbs, src/patternfly/components/Toolbar/examples/toolbar-expanded-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-filter-expanded-checked-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-filter-expanded-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-mobile-filter-checked-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-mobile-filter-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-pagination-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-simple-example.hbs, test-a11y/config.js
Fixes duplicate IDs on the table and toolbar components. This fixes part of #1439. The duplicate IDs on SVG filters will be addressed separately.
This fix allows the tolerance to be reduced by 3.
=> Unique ids

src/patternfly/components/Tooltip/tooltip.scss
=> fix(width): tooltip

src/patternfly/components/Toolbar/toolbar.scss
=> fix(toolbar): reduce padding to 16px at mobile

src/patternfly/components/Dropdown/docs/code.md, src/patternfly/components/Dropdown/dropdown-menu-groups.hbs, src/patternfly/components/Dropdown/dropdown.hbs, src/patternfly/components/Dropdown/dropdown.scss, src/patternfly/components/Dropdown/examples/dropdown-expanded-example.hbs, src/patternfly/components/Dropdown/examples/dropdown-groups-example.hbs, src/patternfly/components/Dropdown/examples/index.js
fixes https://github.com/patternfly/patternfly-next/issues/1436
@jgiardino how does this look?
=> feat(dropdown): add support for groups

src/patternfly/components/Form/docs/code.md, src/patternfly/components/Form/examples/form-help-text-example.hbs
=> fix(form): replace aria-errormessage with aria-describedby

src/patternfly/components/Wizard/docs/code.md, src/patternfly/components/Wizard/examples/wizard-example.hbs, src/patternfly/components/Wizard/examples/wizard-expanded-example.hbs, src/patternfly/components/Wizard/wizard-body.hbs, src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly-next/issues/1501
=> fix(wizard): adjust padding, var names

src/patternfly/components/Page/docs/code.md, src/patternfly/components/Page/page.scss
=> fix(page): add modifier to page main section

src/patternfly/components/Select/select-checkbox-checked.hbs, src/patternfly/components/Select/select-checkbox-groups-checked.hbs, src/patternfly/components/Select/select-checkbox-groups.hbs, src/patternfly/components/Select/select-checkbox.hbs
=> fix(select menu): include fieldset around checkbox groups

src/patternfly/components/Accordion/docs/code.md, src/patternfly/components/Accordion/examples/accordion-fixed-example.hbs, src/patternfly/components/Accordion/examples/accordion-fluid-example.hbs
=> fix(accordion): remove aria-expanded from dd

src/patternfly/components/DataList/data-list.scss, src/patternfly/components/DataList/examples/data-list-width-example.hbs
Fix #1327
Currently, the data list doesn't support three columns of content in its row, thats why the action kebab is overflowing to the next line.  
Two fixes: larger breakpoint or remove the third column from the "Flex Modifiers - Example 3".
I wonder if it should support three columns without breaking though?
=> Fix Data List w Modifiers Example

src/patternfly/components/Table/examples/table-simple-example.hbs, src/patternfly/components/Table/table-caption.hbs, src/patternfly/components/Table/table.scss
fixes https://github.com/patternfly/patternfly-next/issues/1494
=> feat(table): add support for caption

src/patternfly/components/InputGroup/input-group.scss
=> fix(inputGroup): background is all white now

src/patternfly/components/Table/examples/table-compound-expansion-example.hbs, src/patternfly/components/Table/examples/table-expandable-example.hbs, src/patternfly/components/Table/examples/table-width-example.hbs, src/patternfly/components/Table/table-nested.hbs, src/patternfly/components/Table/table.hbs
=> fix(table): fix a11y

src/patternfly/components/Chip/chip.scss, src/patternfly/components/Chip/docs/code.md, src/patternfly/components/Chip/examples/chip-example.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1553
=> feat(chip): add read-only variation

src/patternfly/components/AlertGroup/docs/alert-group.md, src/patternfly/components/AlertGroup/examples/alert-group-example.hbs, src/patternfly/components/AlertGroup/examples/toast-group-example.hbs, src/patternfly/demos/Alert/examples/alert-toast-example.hbs, test-a11y/config.js
=> fix(alertGroup): fix a11y

src/patternfly/components/Table/examples/table-compact-example.hbs, src/patternfly/components/Table/examples/table-simple-example.hbs, src/patternfly/components/Table/examples/table-simple-with-checkboxes-example.hbs, src/patternfly/components/Table/examples/table-sortable-example.hbs, src/patternfly/components/Table/examples/table-width-example.hbs, src/patternfly/components/Table/table.scss, src/site/workspace.scss
fixes https://github.com/patternfly/patternfly-next/issues/1520
You'll need to test in Firefox on windows to verify the borders no longer disappear. Also updated a bunch of workspace styles so they don't bleed into the examples.
=> fix(table): fix disappearing borders in firefox, workspace styles

src/patternfly/components/Progress/docs/code.md, src/patternfly/components/Progress/progress-bar.hbs, src/patternfly/components/Progress/progress-status.hbs, src/patternfly/components/Progress/progress.hbs
=> fix(progress): moves aria attributes to improve screenreader results

src/patternfly/components/Login/docs/code.md, src/patternfly/components/Login/examples/login-invalid-example.hbs, src/patternfly/components/Login/examples/login-simple-example.hbs, src/patternfly/components/Login/login-main-header-desc.hbs, src/patternfly/components/Login/login.scss
fixes https://github.com/patternfly/patternfly-next/issues/1487
=> feat(login): add main header description

src/patternfly/components/Tabs/docs/tabs-nav.md, src/patternfly/components/Tabs/docs/tabs-primary.md, src/patternfly/components/Tabs/examples/index.js, src/patternfly/components/Tabs/examples/tabs-filled.hbs, src/patternfly/components/Tabs/examples/tabs-nav.hbs, src/patternfly/components/Tabs/examples/tabs-primary.hbs, src/patternfly/components/Tabs/examples/tabs-scroll.hbs, src/patternfly/components/Tabs/examples/tabs-secondary.hbs, src/patternfly/components/Tabs/tabs-list.hbs, src/patternfly/components/Tabs/tabs.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1537
=> chore(tabs): remove aria-label from examples

src/patternfly/components/Table/docs/table-compact-border-rows.md, src/patternfly/components/Table/docs/table-compact.md, src/patternfly/components/Table/examples/index.js, src/patternfly/components/Table/examples/table-compact-border-rows-example.hbs, src/patternfly/components/Table/examples/table-compact-example.hbs, src/patternfly/components/Table/examples/table-compound-expansion-example.hbs, src/patternfly/components/Table/examples/table-expandable-example.hbs, src/patternfly/components/Table/examples/table-simple-example.hbs, src/patternfly/components/Table/examples/table-simple-with-checkboxes-example.hbs, src/patternfly/components/Table/examples/table-sortable-example.hbs, src/patternfly/components/Table/examples/table-width-example.hbs, src/patternfly/components/Table/table.scss
fixes https://github.com/patternfly/patternfly-next/issues/1540
=> feat(table): add support for borders in compact table

src/patternfly/components/Pagination/docs/code.md, src/patternfly/components/Pagination/docs/pagination-top-example.md, src/patternfly/components/Pagination/examples/pagination-bottom-example.hbs, src/patternfly/components/Pagination/examples/pagination-top-example.hbs, src/patternfly/components/Pagination/examples/pagination-top-expanded-example.hbs
=> fix(pagination): removes aria-label from divs

src/patternfly/components/OptionsMenu/options-menu-multiple.hbs, src/patternfly/components/OptionsMenu/options-menu-single.hbs, src/patternfly/components/Toolbar/examples/toolbar-expanded-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-filter-expanded-checked-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-filter-expanded-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-mobile-filter-checked-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-mobile-filter-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-pagination-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-simple-example.hbs
fixes: #617 
**ISSUE:**
Below are the three listed issues from ticket #617. I ran `npm run a11y` and it was not able to detect issues for `/components/Pagination/examples-full/`. However, when I fixed issue three `/components/Toolbar/examples-full/`, I guess the first think on the list fixed issue two.
**ARIA VIOLATIONS:**
1. `/components/OptionsMenu/examples-full/`
```
1 error found in: /components/OptionsMenu/examples-full/
1) Elements must only use allowed ARIA attributes -- https://dequeuniversity.com/rules/axe/3.0/aria-allowed-attr -- impact: critical
-------html violation instances-------
<button class="pf-c-options-menu__menu-item pf-m-selected" aria-selected="true">
Option 2
<i class="fas fa-check pf-c-options-menu__menu-item-icon" aria-hidden="true"></i>
</button>
<button …
```
=> fix(AriaCorrection617): fixed several aria violations.

src/patternfly/components/Table/docs/table-simple.md, src/patternfly/components/Table/examples/table-expandable-example.hbs, src/patternfly/components/Table/examples/table-simple-with-checkboxes-example.hbs, src/patternfly/components/Table/examples/table-width-example.hbs, src/patternfly/components/Table/table-cell-content.hbs, src/patternfly/components/Table/table-td.hbs, src/patternfly/components/Table/table-th.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1590
=> refactor(table): remove cell-content element from table cells

src/patternfly/components/Tabs/examples/tabs-nav.hbs
=> fix(Tabs): update wording

src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly-next/issues/1603
=> fix(page): flex shorthand safari bug

src/patternfly/components/Switch/examples/switch-disabled-example.hbs, src/patternfly/components/Switch/examples/switch-example.hbs, src/patternfly/components/Table/examples/table-compound-expansion-example.hbs, src/patternfly/components/Table/examples/table-expandable-example.hbs, src/patternfly/components/Table/examples/table-simple-with-checkboxes-example.hbs, src/patternfly/components/Table/examples/table-width-example.hbs, src/patternfly/demos/AboutModal/examples/about-modal-example.hbs, test-a11y/config.js
fixes https://github.com/patternfly/patternfly-next/issues/619
There were also a bunch of table violations.
=> fix(a11y): fix switch, table, and about modal violations

src/patternfly/components/Toolbar/docs/code.md
=> fix(toolbar): move from toolbar__current to toolbar__total-items

src/patternfly/_variables.scss, src/patternfly/components/Content/content.scss, src/patternfly/components/Content/examples/content-template-example.hbs, src/patternfly/sass-utilities/scss-variables.scss
fixes https://github.com/patternfly/patternfly-next/issues/1455
=> feat(content): add support for horizontal rule

src/patternfly/components/Login/docs/code.md
=> docs(login): update required components for the login

src/patternfly/components/Table/table-grid.scss, src/patternfly/components/Table/table.scss
=> fix(table): update breakpoints for padding

src/patternfly/components/Pagination/examples/pagination-bottom-example.hbs, src/patternfly/components/Pagination/examples/pagination-top-example.hbs, src/patternfly/components/Pagination/examples/pagination-top-expanded-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-expanded-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-pagination-example.hbs, src/patternfly/demos/DataList/data-list-pagination.hbs, src/patternfly/demos/DataList/data-list-toolbar.hbs, src/patternfly/demos/DataTable/data-table-pagination.hbs, src/patternfly/demos/DataTable/data-table-toolbar-no-sort.hbs, src/patternfly/demos/DataTable/data-table-toolbar.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1536
=> chore(pagination): remove size attr from type=number input

src/patternfly/demos/DataList/examples/data-list-actionable-demo.hbs, src/patternfly/demos/DataList/examples/data-list-expandable-demo.hbs, src/patternfly/demos/DataList/examples/data-list-simple-demo.hbs, src/patternfly/demos/DataList/examples/data-list-simple-without-pagination-demo.hbs
=> fix(DataTableDemo): use page-main-nav component

src/patternfly/components/Accordion/accordion.scss, src/patternfly/components/Chip/chip.scss, src/patternfly/components/ChipGroup/chip-group.scss, src/patternfly/components/ContextSelector/context-selector.scss, src/patternfly/components/Dropdown/dropdown.scss, src/patternfly/components/ModalBox/modal-box.scss, src/patternfly/components/OptionsMenu/options-menu.scss, src/patternfly/components/Select/select.scss, src/patternfly/sass-utilities/mixins.scss
=> refactor(mixins): add mixin for text overflow and update components

src/patternfly/components/DataList/data-list.scss
=> refactor(data list): breakpoints should use sm instead of mobile

src/patternfly/components/Toolbar/docs/code.md, src/patternfly/components/Toolbar/examples/toolbar-expanded-example.hbs, src/patternfly/components/Toolbar/examples/toolbar-pagination-example.hbs, src/patternfly/demos/DataList/data-list-toolbar.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1570
=> chore(toolbar): remove references to pf-c-toolbar__pagination class

src/patternfly/demos/DataList/data-list-toolbar.hbs, src/patternfly/demos/DataTable/data-table-toolbar-no-sort.hbs, src/patternfly/demos/DataTable/data-table-toolbar.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1652
=> chore(demos): remove pf-c-toolbar__pagination from toolbar in demos

src/patternfly/components/DataList/data-list.scss
=> fix(dataList): use md breakpoint instead of sm for padding change.

src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly-next/issues/1554
=> chore(select): remove unused block

src/patternfly/components/Switch/switch.scss
fixes https://github.com/patternfly/patternfly-next/issues/1581
=> chore(switch): remove old css label styles

src/patternfly/components/Table/docs/code.md, src/patternfly/components/Table/docs/table-checkboxes-actions.md, src/patternfly/components/Table/docs/table-compound-expansion.md, src/patternfly/components/Table/docs/table-expandable.md, src/patternfly/components/Table/docs/table-simple.md, src/patternfly/components/Table/docs/table-sortable.md, src/patternfly/components/Table/docs/table-width.md, src/patternfly/components/Table/examples/table-expandable-example.hbs, src/patternfly/demos/DataTable/data-table-expandable-table.hbs, src/patternfly/demos/DataTable/data-table-simple-table.hbs, src/patternfly/demos/DataTable/data-table-sortable-table.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1637
=> fix(table): remove unnecessary aria-label

src/patternfly/components/ContextSelector/context-selector.hbs, src/patternfly/components/ContextSelector/examples/context-selector-example.hbs
Fixes https://github.com/patternfly/patternfly-next/issues/1531.
Added ids to `.pf-c-context-selector__toggle` and `.pf-c-button pf-m-tertiary`, updated the aria-label on `.pf-c-button pf-m-tertiary`, and added aria-labelledby to `.pf-c-context-selector__toggle` and `.pf-c-form-control`.
=> refactor(context-selector): aria refinements

src/patternfly/components/Table/docs/table-checkboxes-actions.md
close #1662 
@mcoker spoke with @jgiardino  and she agreed about changing the name of this.
=> docs(table): update table with checkboxes

src/patternfly/components/Wizard/docs/code.md, src/patternfly/components/Wizard/examples/index.js, src/patternfly/components/Wizard/examples/wizard-expanded-example.hbs, src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly-next/issues/1616
=> fix(wizard): update disabled step, remove right align option

src/patternfly/components/Form/docs/code.md, src/patternfly/components/Form/examples/form-vertical-align-labels-example.hbs, src/patternfly/components/Form/form-label.hbs, src/patternfly/components/FormControl/docs/code.md, src/patternfly/components/Switch/docs/code.md
fixes https://github.com/patternfly/patternfly-next/issues/769
=> fix(a11y): remove aria-required, remove required attr from labels

src/patternfly/components/Nav/docs/code.md, src/patternfly/components/Nav/examples/nav-example.hbs, src/patternfly/components/Nav/examples/nav-expandable-example.hbs, src/patternfly/components/Nav/examples/nav-simple-list-example.hbs, src/patternfly/components/Nav/nav-separator.hbs, src/patternfly/components/Nav/nav.scss
fixes https://github.com/patternfly/patternfly-next/issues/1574
=> feat(nav): add nav item separator

src/patternfly/components/Page/page.scss, src/patternfly/demos/Page/page-template-header-tools-elements.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1538
=> fix(page): address hidden elements that are visible to screen readers

src/patternfly/layouts/Flex/docs/flex-basic.md, src/patternfly/layouts/Flex/docs/flex-columns.md, src/patternfly/layouts/Flex/docs/flex-individually-spaced.md, src/patternfly/layouts/Flex/docs/flex-intro.md, src/patternfly/layouts/Flex/docs/flex-justification.md, src/patternfly/layouts/Flex/flex.scss, src/patternfly/sass-utilities/scss-variables.scss
=> refactor(flex-layout): convert device breakpoints to grid breakpoints

src/patternfly/components/Card/card.scss, src/patternfly/components/Card/docs/code.md, src/patternfly/components/Card/examples/card-grow-example.hbs, src/patternfly/components/Card/examples/card-multiple-body-example.hbs, src/patternfly/components/Card/examples/card-no-fill-example.hbs, src/patternfly/components/Card/examples/index.js, src/site/workspace.scss
WIP. This is targeted for the 4/5 release.
fixes https://github.com/patternfly/patternfly-next/issues/355
=> refactor(card): allow for multiple body, add grow modifier

src/patternfly/components/Card/card.scss
fixes https://github.com/patternfly/patternfly-next/issues/1674
=> fix(card): refactor child flex/spacing selector

src/patternfly/components/Tabs/tabs.scss, src/patternfly/sass-utilities/mixins.scss
=> Add mixin for Scrollbar Hiding

src/patternfly/components/Breadcrumb/breadcrumb.scss, src/patternfly/components/EmptyState/docs/code.md, src/patternfly/components/EmptyState/empty-state-body.hbs, src/patternfly/components/EmptyState/empty-state-icon.hbs, src/patternfly/components/Progress/progress.scss, src/patternfly/components/Wizard/docs/code.md, src/patternfly/components/Wizard/examples/index.js, src/patternfly/components/Wizard/examples/wizard-example.hbs, src/patternfly/components/Wizard/examples/wizard-expanded-example.hbs, src/patternfly/components/Wizard/examples/wizard-finished-example.hbs, src/patternfly/components/Wizard/wizard-main-body.hbs, src/patternfly/components/Wizard/wizard-main.hbs, src/patternfly/components/Wizard/wizard-toggle-divider.hbs, src/patternfly/components/Wizard/wizard-toggle-separator.hbs, src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly-next/issues/1670
=> feat(wizard): add support for finished state

src/patternfly/demos/DataList/examples/data-list-actionable-demo.hbs, src/patternfly/demos/DataList/examples/data-list-expandable-demo.hbs, src/patternfly/demos/DataList/examples/data-list-simple-demo.hbs, src/patternfly/demos/DataList/examples/data-list-simple-without-pagination-demo.hbs, src/patternfly/demos/DataTable/examples/data-table-compact-demo.hbs, src/patternfly/demos/DataTable/examples/data-table-compound-expansion-demo.hbs, src/patternfly/demos/DataTable/examples/data-table-expandable-demo.hbs, src/patternfly/demos/DataTable/examples/data-table-simple-demo.hbs, src/patternfly/demos/DataTable/examples/data-table-sortable-demo.hbs, src/patternfly/demos/Page/examples/page-component-expandable-nav-example.hbs, src/patternfly/demos/Page/examples/page-component-grouped-nav-example.hbs, src/patternfly/demos/Page/examples/page-component-horizontal-nav-example.hbs, src/patternfly/demos/Page/examples/page-component-simple-nav-example.hbs, src/patternfly/demos/Page/page-demo-default.hbs
fixes  https://github.com/patternfly/patternfly-next/issues/1679
=> chore(demos): add skip-to-content to page demos

src/patternfly/components/Login/login.scss
fixes https://github.com/patternfly/patternfly-next/issues/1683
This fixes the login component for now. It exposed a bigger issue that I've captured here - https://github.com/patternfly/patternfly-next/issues/1684
=> refactor(login): change the way we define light/dark areas

src/patternfly/layouts/Split/docs/code.md, src/patternfly/layouts/Split/examples/split-example.hbs, src/patternfly/layouts/Split/examples/split-gutters-example.hbs, src/patternfly/layouts/Split/split.hbs, src/patternfly/layouts/Split/split.scss, src/patternfly/layouts/Stack/docs/code.md, src/patternfly/layouts/Stack/examples/index.js, src/patternfly/layouts/Stack/examples/stack-example.hbs, src/patternfly/layouts/Stack/examples/stack-has-gutter-example.hbs, src/patternfly/layouts/Stack/stack.scss
fixes https://github.com/patternfly/patternfly-next/issues/1686
=> refactor(split/stack): use pf-m-fill instead of pf-m-main

src/site/workspace.scss
fixes https://github.com/patternfly/patternfly-next/issues/1691
=> chore(workspace): fix color contrast issue in page component example

src/patternfly/components/Page/docs/code.md, src/patternfly/components/Page/examples/index.js, src/patternfly/components/Page/examples/page-component-fill-example.hbs, src/patternfly/components/Page/page.scss, src/site/workspace.scss
fixes https://github.com/patternfly/patternfly-next/issues/1492
=> feat(page): add fill/no-fill modifiers for main-section elements

src/patternfly/demos/DataList/data-list-expandable-compact-table.hbs
=> fix(DataListDemo): change modifier on card

.travis.yml
Fix @dgutride 's off by one error.
=> build(travis): fix travis.yml

src/patternfly/components/Wizard/docs/code.md, src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly-next/issues/1708
=> fix(wizard): no-padding modifier should modify main-body element

src/patternfly/components/Select/docs/select-single.md, src/patternfly/components/Select/examples/select-single-typeahead-expanded-example.hbs, src/patternfly/components/Select/select-menu-item-icon.hbs, src/patternfly/components/Select/select-single.hbs, src/patternfly/components/Select/select-typeahead.hbs, src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly-next/issues/1410
=> feat(select): add selected state

src/patternfly/components/Wizard/docs/code.md, src/patternfly/components/Wizard/examples/index.js, src/patternfly/components/Wizard/examples/wizard-full-width-full-height-example.hbs, src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly-next/issues/1720
=> feat(wizard): add support for full-width and full-height wizard

src/patternfly/components/Card/card-header.hbs, src/patternfly/components/Card/card.scss
=> fix(card): update font sizes

src/patternfly/components/Card/card.scss, src/patternfly/components/Card/docs/code.md, src/patternfly/components/Card/examples/card-hover-example.hbs, src/patternfly/components/Card/examples/index.js
=> fix(card): add hoverable shadow

src/patternfly/components/Page/docs/code.md, src/patternfly/components/Page/examples/index.js, src/patternfly/components/Page/examples/page-component-fill-example.hbs, src/patternfly/components/Page/examples/page-component-main-section-modifiers.hbs, src/patternfly/components/Page/page.scss
=> fix(page): add no padding modifier to main section

src/patternfly/components/Tabs/docs/tabs-nav.md, src/patternfly/components/Tabs/examples/tabs-nav.hbs, src/patternfly/components/Tabs/tabs-button.hbs, src/patternfly/components/Tabs/tabs.scss
fixes https://github.com/patternfly/patternfly-next/issues/1585
=> fix(tabs): show tabs as links in <nav> example

src/patternfly/components/Table/examples/table-compact-expandable-example.hbs, src/patternfly/components/Table/examples/table-compound-expansion-example.hbs, src/patternfly/components/Table/table.scss, src/patternfly/demos/DataTable/data-table-compound-expansion-table.hbs, src/patternfly/demos/DataTable/data-table-expandable-table.hbs
=> fix(dataTableDemo): remove expanded class from non expanded items

src/patternfly/components/Button/button.scss, src/patternfly/components/Button/docs/code.md, src/patternfly/components/Button/examples/button-block-example.hbs, src/patternfly/components/Button/examples/button-link-example.hbs, src/patternfly/components/Button/examples/button-states-example.hbs, src/patternfly/components/Button/examples/button-types-example.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1182
=> feat(button): add inline variation

src/patternfly/components/Wizard/docs/code.md, src/patternfly/components/Wizard/examples/index.js, src/patternfly/components/Wizard/examples/wizard-compact-nav-example.hbs, src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly-next/issues/1737
=> feat(wizard): add modifier for compact nav width

src/site/pages/accessibility-guide.md
This change fixes a broken link in the accessibility guide.
=> docs(a11y): fixed a link

src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly-next/issues/1760
=> fix(wizard): allow long wizard title to wrap

.travis.yml
=> build(a11y): update chromedriver

src/patternfly/components/Content/content.scss, src/patternfly/components/Title/docs/code.md
fixes https://github.com/patternfly/patternfly-next/issues/1755
cc @kybaker
=> fix(content): change heading font-size and margin

src/patternfly/components/AboutModalBox/docs/code.md, src/patternfly/components/AboutModalBox/examples/about-modal-box-example.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1754
=> docs(aboutmodal): remove content component dependency in content area

src/patternfly/components/AboutModalBox/about-modal-box-body.hbs, src/patternfly/components/AboutModalBox/docs/code.md, src/patternfly/components/AboutModalBox/examples/about-modal-box-example.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1771
=> fix(aboutmodal): add content body wrapper

src/patternfly/components/Wizard/wizard-footer.hbs
https://github.com/patternfly/patternfly-next/issues/1802
=> fix(wizard): fix wizard closing tag

src/patternfly/components/Brand/brand.scss, src/patternfly/components/TabContent/tab-content.scss
fixes https://github.com/patternfly/patternfly-next/issues/1811
=> fix(brand,tabcontent): add blank stylesheet

src/patternfly/components/Pagination/pagination-options-menu.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1777
=> docs(pagination): update options menu aria-label

src/patternfly/components/Nav/examples/nav-example.hbs, src/patternfly/components/Nav/examples/nav-expandable-example.hbs, src/patternfly/components/Nav/examples/nav-expandable-subnav-titles-example.hbs, src/patternfly/components/Nav/examples/nav-horizontal-list-example.hbs, src/patternfly/components/Nav/examples/nav-horizontal-list-overflow-example.hbs, src/patternfly/components/Nav/examples/nav-list-grouped-example.hbs, src/patternfly/components/Nav/examples/nav-mixed-example.hbs, src/patternfly/components/Nav/examples/nav-simple-list-example.hbs, src/patternfly/components/Nav/examples/nav-tertiary-list-example.hbs, src/patternfly/components/Nav/examples/nav-tertiary-list-overflow-example.hbs, src/patternfly/demos/Page/examples/page-component-tertiary-nav-example.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1779
=> docs(nav): update aria-label in examples

src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly-next/issues/1766
=> fix(wizard): set pf-c-wizard__main to grow and fill available height

src/patternfly/components/Card/card-actions.hbs, src/patternfly/components/Card/card-head.hbs, src/patternfly/components/Card/card.hbs, src/patternfly/components/Card/card.scss, src/patternfly/components/Card/docs/code.md, src/patternfly/components/Card/examples/card-img-action.hbs, src/patternfly/components/Card/examples/index.js
=> feature(card): support img and actions

src/patternfly/components/Card/card.scss
=> fix(card): remove flex from header

src/patternfly/_variables.scss, src/patternfly/components/Table/docs/code.md, src/patternfly/components/Table/table-grid.scss, src/patternfly/layouts/Flex/flex.scss, src/patternfly/sass-utilities/bs-variables.scss, src/patternfly/sass-utilities/mixins.scss, src/patternfly/sass-utilities/scss-variables.scss
close #1640 
This is related to a fix for the table in the website: https://github.com/patternfly/patternfly-org/issues/1021
=> fix(table): add an extra breakpoint

src/patternfly/components/NotificationBadge/docs/code.md, src/patternfly/components/NotificationBadge/docs/design.md, src/patternfly/components/NotificationBadge/examples/index.js, src/patternfly/components/NotificationBadge/examples/notification-badge-simple-example.hbs, src/patternfly/components/NotificationBadge/notification-badge.hbs, src/patternfly/components/NotificationBadge/notification-badge.scss
Fixes #1789 
This adds a new component that is the blue dot on an icon showing that there are read/unread notifications.
=> feat(notificationbadge): adds notification badge

src/patternfly/components/Alert/alert.scss
fixes https://github.com/patternfly/patternfly-next/issues/1908
=> fix(alert): update inline alert icon sizes

src/patternfly/layouts/Bullseye/docs/code.md, src/patternfly/layouts/Flex/docs/flex-intro.md, src/patternfly/layouts/Gallery/docs/code.md, src/patternfly/layouts/Grid/docs/code.md, src/patternfly/layouts/Level/docs/code.md, src/patternfly/layouts/Split/docs/code.md, src/patternfly/layouts/Stack/docs/code.md
=> fix(layout): update docs

src/patternfly/components/AlertGroup/docs/code.md, src/patternfly/components/AlertGroup/examples/index.js
=> fix(alertgroup): rename example and reword docs

RELEASE-NOTES.md
=> chore(notes): format release note md

src/patternfly/components/AboutModalBox/about-modal-box-strapline.hbs, src/patternfly/components/AboutModalBox/about-modal-box.scss, src/patternfly/components/AboutModalBox/docs/code.md, src/patternfly/components/AboutModalBox/examples/about-modal-box-example.hbs
fixes https://github.com/patternfly/patternfly-next/issues/1941
=> fix(aboutmodalbox): decrease strapline font, make it a paragraph

src/patternfly/components/Table/table-grid.scss, src/patternfly/components/Table/table.scss
fixes https://github.com/patternfly/patternfly-next/issues/1947
=> fix(table): make column headers bold

src/patternfly/components/Progress/progress.scss
=> fix(progress): change the font weight on sm variation

src/patternfly/components/OptionsMenu/docs/code.md, src/patternfly/components/OptionsMenu/examples/index.js, src/patternfly/components/OptionsMenu/examples/options-menu-disabled-example.hbs, src/patternfly/components/OptionsMenu/examples/options-menu-plain-example.hbs, src/patternfly/components/OptionsMenu/options-menu-toggle.hbs, src/patternfly/components/OptionsMenu/options-menu.scss
=> feat(optionsmenu): add disabled variation

src/patternfly/_chart-globals.scss, src/patternfly/patternfly-charts.scss
Adjusted chart vars for react-charts.
fixes https://github.com/patternfly/patternfly-next/issues/2011
=> fix(charts): various updates to chart vars

src/patternfly/_chart-globals.scss, src/patternfly/patternfly-charts.scss
Need to adjust a couple chart axis vars.
Fixes https://github.com/patternfly/patternfly-next/issues/2023
=> fix(chart): adjust axis vars

src/patternfly/_fa-icons.scss
fixes https://github.com/patternfly/patternfly-next/issues/2017
=> fix(fa-icons): change selector that wraps extend for lower specificity

src/patternfly/demos/Page/examples/page-component-horizontal-nav-example.hbs
Closes #2003 
noticed this when talking about spacing in the header [here](https://github.com/patternfly/patternfly-design-kit/issues/37)
=> fix(page): removes toggle

src/patternfly/components/Tooltip/tooltip.scss
=> fix(tooltip): break words

src/patternfly/components/AppLauncher/app-launcher-menu-item.hbs, src/patternfly/components/AppLauncher/app-launcher-menu.hbs, src/patternfly/components/AppLauncher/app-launcher.hbs, src/patternfly/components/AppLauncher/app-launcher.scss, src/patternfly/components/AppLauncher/docs/code.md, src/patternfly/components/AppLauncher/examples/app-launcher-collapsed-example.hbs, src/patternfly/components/AppLauncher/examples/app-launcher-expanded-example.hbs, src/patternfly/components/AppLauncher/examples/app-launcher-sections-icons-example.hbs
closes #1944 
@mcoker @mattnolting what do you guys think about showing a `<div>` as an example in the menu. Do you know if thats a common case? I don't think we do it in the dropdown.
=> feat(applauncher): add button example to menu item

src/patternfly/components/Select/docs/select-plain.md, src/patternfly/components/Select/examples/index.js, src/patternfly/components/Select/examples/select-plain-example.hbs, src/patternfly/components/Select/examples/select-plain-expanded-example.hbs, src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly-next/issues/1987
=> feat(select): add plain variation

src/patternfly/demos/Table/table-compact-table.hbs, src/patternfly/demos/Table/table-compound-expansion-table.hbs, src/patternfly/demos/Table/table-expandable-table.hbs, src/patternfly/demos/Table/table-simple-table.hbs, src/patternfly/demos/Table/table-sortable-table.hbs
fixes https://github.com/patternfly/patternfly-next/issues/2059
=> fix(table): fix data-label attr in table demos

src/patternfly/_chart-globals.scss, src/patternfly/patternfly-charts.scss
Adding individual padding properties for donut, donut utilization, and donut threshold.
Fixes https://github.com/patternfly/patternfly-next/issues/2067
=> fix(charts): add individual padding vars for donut charts

src/patternfly/components/Dropdown/dropdown.scss, src/patternfly/components/OptionsMenu/options-menu.scss
fixes https://github.com/patternfly/patternfly-next/issues/2066
=> fix(dropdown, optionsmenu): center plain button content

src/patternfly/components/Login/login.scss, test-a11y/config.js
fixes #1907 
unsets the link color text so that its white. Looks like even when its blue at a max-width of "xl" it still doesnt pass the color-contrast test, so I made it white at all sizes @mceledonia is this ok?
=> fix(login): fix a11y

RELEASE-NOTES.md
**What**: For the next -org website update.
**Additional issues**: This should be done _before_ we promote -react next time.
=> Format RELEASE-NOTES.md

src/patternfly/demos/DataList/examples/index.js
=> fix(datalistdemo): add in header to avoid a11y issue

src/patternfly/components/Divider/divider.hbs, src/patternfly/components/Divider/examples/divider-li-example.hbs
=> fix(divider): update example

src/patternfly/demos/Page/page-template-title.hbs
fixes https://github.com/patternfly/patternfly-next/issues/2090
=> chore(page): update demo main section copy

src/patternfly/demos/Alert/examples/alert-toast-example.hbs, src/patternfly/demos/CardView/examples/card-view-demo-example.hbs
fixes https://github.com/patternfly/patternfly-next/issues/2105
=> chore(demos): use unique ID used in alert and cardview demos

src/patternfly/_chart-globals.scss
fixes https://github.com/patternfly/patternfly-next/issues/2093
=> fix(charts): add color to black range, shift vars

src/patternfly/components/Popover/popover.scss
fixes https://github.com/patternfly/patternfly-next/issues/2098
=> fix(popover): ensure content does not overlap close button

src/patternfly/components/Select/docs/select-single.md, src/patternfly/components/Select/examples/index.js, src/patternfly/components/Select/examples/select-disabled-example.hbs, src/patternfly/components/Select/select.scss
=> feat(select): add a disable modifier

RELEASE-NOTES.md
This PR updates the release notes to fix the bullet placement.
=> Updated release notes to fix bullet placement

.circleci/config.yml
Fix [errors on master](https://circleci.com/gh/patternfly/patternfly-next/334?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) uploading new docs to gh-pages.
=> fix(build): fix gh-pages deploy on master

src/patternfly/components/Select/docs/code.md, src/patternfly/components/Select/docs/select-checkbox.md, src/patternfly/components/Select/docs/select-icon.md, src/patternfly/components/Select/docs/select-multi-typeahead.md, src/patternfly/components/Select/docs/select-plain.md, src/patternfly/components/Select/docs/select-single-typeahead.md, src/patternfly/components/Select/docs/select-single.md, src/patternfly/components/Select/examples/index.js, src/patternfly/components/Select/examples/select-icon-example.hbs, src/patternfly/components/Select/examples/select-plain-example.hbs, src/patternfly/components/Select/examples/select-plain-expanded-example.hbs, src/patternfly/components/Select/select-toggle-arrow.hbs, src/patternfly/components/Select/select-toggle-badge.hbs, src/patternfly/components/Select/select-toggle-icon.hbs, src/patternfly/components/Select/select-toggle-text.hbs, src/patternfly/components/Select/select-toggle-wrapper.hbs, src/patternfly/components/Select/select-toggle.hbs, src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly-next/issues/2152
=> fix(select): add support for custom toggle icon

src/site/_site/CodepenButton/index.js
fixes https://github.com/patternfly/patternfly-next/issues/2150
=> chore(workspace): fix codepen title button

.circleci/config.yml
Second attempt to fix the master build since #2160 only partially worked :)
=> fix(build): remove github pages deploy

src/patternfly/components/Divider/divider.scss, src/patternfly/components/Page/page-main-wizard.hbs, src/patternfly/components/Page/page.scss, src/patternfly/components/Wizard/docs/code.md, src/patternfly/components/Wizard/examples/index.js, src/patternfly/components/Wizard/examples/wizard-compact-nav-example.hbs, src/patternfly/components/Wizard/examples/wizard-example.hbs, src/patternfly/components/Wizard/examples/wizard-expanded-example.hbs, src/patternfly/components/Wizard/examples/wizard-finished-example.hbs, src/patternfly/components/Wizard/examples/wizard-full-width-full-height-example.hbs, src/patternfly/components/Wizard/examples/wizard-in-page-example.hbs, src/patternfly/components/Wizard/wizard-main.hbs, src/patternfly/components/Wizard/wizard.scss, src/patternfly/demos/Wizard/examples/index.js, src/patternfly/demos/Wizard/examples/wizard-example.hbs, src/patternfly/demos/Wizard/examples/wizard-expanded-example.hbs, src/patternfly/demos/Wizard/examples/wizard-in-page-example.hbs, src/patternfly/demos/Wizard/examples/wizard-in-page-expanded-example.hbs, src/site/workspace.scss
fixes https://github.com/patternfly/patternfly-next/issues/2073
=> feat(wizard): add in-page variation

src/patternfly/components/Dropdown/docs/code.md, src/patternfly/components/Dropdown/dropdown.scss, src/patternfly/components/Dropdown/examples/dropdown-collapsed-example.hbs, src/patternfly/components/Dropdown/examples/dropdown-primary-example.hbs, src/patternfly/components/Dropdown/examples/index.js
fixes https://github.com/patternfly/patternfly-next/issues/1872
=> fix(dropdown): add primary toggle variation to dropdown

src/patternfly/components/Dropdown/docs/code.md, src/patternfly/components/Dropdown/dropdown-toggle-check.hbs, src/patternfly/components/Dropdown/dropdown.scss, src/patternfly/components/Dropdown/examples/dropdown-split-button-example.hbs
=> feat(split-button-dropdown-text): add toggle text to split button

src/patternfly/components/Dropdown/dropdown.scss
fixes https://github.com/patternfly/patternfly-next/issues/2223
=> fix(dropdown): use flex for split button check label to fix spacing

src/patternfly/components/DataToolbar/data-toolbar.scss, src/patternfly/components/DataToolbar/docs/data-toolbar-intro.md, src/patternfly/components/DataToolbar/examples/data-toolbar-selected-filters-example.hbs, src/patternfly/components/DataToolbar/examples/data-toolbar-stacked-example.hbs, src/patternfly/components/DataToolbar/examples/data-toolbar-toggle-group-example.hbs
Fixes needed for the Data Toolbar React component PR.
=> fix(data toolbar): format groups correctly inside expandable content

RELEASE-NOTES.md
fixes https://github.com/patternfly/patternfly-next/issues/2234
=> fix(notes): update release notes for 2019.07 release

src/patternfly/demos/Wizard/examples/index.js
fixes https://github.com/patternfly/patternfly-next/issues/2258
You'll have to pull this down locally to test.
=> fix(demo): re-enable wizard modal demos

src/patternfly/components/Tooltip/docs/code.md, src/patternfly/components/Tooltip/examples/index.js, src/patternfly/components/Tooltip/examples/tooltip-text-align-left-example.hbs, src/patternfly/components/Tooltip/tooltip.scss
=> feat(tooltip-alignment): add text align left

src/patternfly/components/Nav/nav.scss
fixes https://github.com/patternfly/patternfly-next/issues/2279
=> fix(nav): styling updates to dark nav

src/patternfly/components/Select/docs/select-single-top.md, src/patternfly/components/Select/examples/index.js, src/patternfly/components/Select/examples/select-single-top-expanded-example.hbs, src/patternfly/components/Select/select-multi.hbs, src/patternfly/components/Select/select-single.hbs, src/patternfly/components/Select/select-typeahead.hbs, src/patternfly/components/Select/select.scss
closes #1986 
//cc @tlabaj @mcoker
=> docs(select): add a top expanded select example

src/patternfly/components/Pagination/docs/code.md, src/patternfly/components/Pagination/examples/index.js, src/patternfly/components/Pagination/examples/pagination-compact-example.hbs, src/patternfly/components/Pagination/pagination.scss, src/patternfly/demos/DataList/data-list-actionable-data-list.hbs, src/patternfly/demos/DataList/data-list-expandable-data-list.hbs, src/patternfly/demos/DataList/data-list-simple-data-list.hbs, src/patternfly/demos/DataList/data-list-simple-no-pagination-data-list.hbs, src/patternfly/demos/DataList/data-list-toolbar.hbs, src/patternfly/demos/DataList/examples/data-list-simple-compact-pagination-demo.hbs, src/patternfly/demos/DataList/examples/index.js, src/patternfly/demos/Table/examples/index.js, src/patternfly/demos/Table/examples/table-simple-compact-pagination-demo.hbs, src/patternfly/demos/Table/table-compact-table.hbs, src/patternfly/demos/Table/table-compound-expansion-table.hbs, src/patternfly/demos/Table/table-expandable-table.hbs, src/patternfly/demos/Table/table-simple-table.hbs, src/patternfly/demos/Table/table-sortable-table.hbs, src/patternfly/demos/Table/table-toolbar.hbs
fixes https://github.com/patternfly/patternfly-next/issues/2110
=> feat(pagination): offer compact variation

src/patternfly/components/Table/examples/table-compact-example.hbs, src/patternfly/components/Table/examples/table-compact-expandable-example.hbs, src/patternfly/components/Table/examples/table-compact-no-border-rows-example.hbs, src/patternfly/components/Table/examples/table-expandable-example.hbs, src/patternfly/components/Table/examples/table-simple-with-checkboxes-example.hbs, src/patternfly/components/Table/examples/table-width-example.hbs, src/patternfly/components/Table/table-nested.hbs
=> fix(table): prefix input name attr, remove scope

src/patternfly/demos/Wizard/examples/wizard-in-page-example.hbs, src/patternfly/demos/Wizard/examples/wizard-in-page-expanded-example.hbs
fixes https://github.com/patternfly/patternfly-next/issues/2243
=> chore(wizard): update in page wizard demos to use dark sidebar/nav

src/patternfly/components/ChipGroup/chip-group.scss, src/patternfly/components/ChipGroup/examples/chip-group-toolbar-collapsed-example.hbs
=> fix(chip-group): add overflow to group

src/patternfly/components/Radio/examples/index.js, src/patternfly/components/Radio/examples/radio-checked-example.hbs, src/patternfly/components/Radio/examples/radio-disabled-example.hbs, src/patternfly/components/Radio/examples/radio-example.hbs, src/patternfly/components/Radio/examples/radio-reversed-example.hbs, src/patternfly/components/Radio/examples/radio-wrap-example.hbs
=> docs(radio): update the radio component example to single components

src/patternfly/components/DataList/data-list.scss
fixes #2185 
When reviewing, refer to #2185 for the slides that @mmenestr made!
=> Make data list consistent with table 

src/patternfly/components/AppLauncher/examples/AppLauncher.md, src/patternfly/components/Nav/examples/Nav.md
This PR resolves - https://github.com/patternfly/patternfly-next/issues/2355
and is also linked to https://github.com/patternfly/patternfly-org/issues/1486
=> docs: fixed component titles for Navigation and Application Launcher 

.circleci/upload-docs.sh, gatsby-node.js, package-lock.json, package.json, src/patternfly/components/Nav/examples/Nav.css
=> [WIP] chore(docs): bump gatsby-theme-patternfly-org

src/patternfly/components/Popover/popover.scss
fixes https://github.com/patternfly/patternfly-next/issues/2380
=> fix(popover): reduce space below title

src/patternfly/components/Nav/examples/Nav.md, src/patternfly/demos/Page/examples/Page.md
fixes https://github.com/patternfly/patternfly-next/issues/2272
=> fix(nav): update examples so simple-list is only used in expandable nav

src/patternfly/components/FormControl/examples/FormControl.md
fixes https://github.com/patternfly/patternfly-next/issues/2374
=> chore(formcontrol): update vertical/horizontal modifier descriptions

src/patternfly/components/Accordion/accordion.scss, src/patternfly/components/Accordion/examples/Accordion.md
fixes https://github.com/patternfly/patternfly-next/issues/2376
fixes https://github.com/patternfly/patternfly-next/issues/2375
=> fix(accordion): add no-box-shadow variation, refactor expanded border

RELEASE-NOTES.md
fixes https://github.com/patternfly/patternfly-next/issues/2395
=> fix(releasenotes): update release notes for 2019.09 release

gulpfile.js
=> fix(build): add /g to regex

.circleci/upload-docs.sh, static/CNAME
I've just disabled Netlify as well.
=> fix(deploy): use surge to host pf4.patternfly.org

src/patternfly/components/AboutModalBox/examples/AboutModalBox.md, src/patternfly/components/AlertGroup/examples/AlertGroup.md, src/patternfly/components/AppLauncher/examples/AppLauncher.md, src/patternfly/components/BackgroundImage/examples/BackgroundImage.md, src/patternfly/components/ChipGroup/examples/ChipGroup.md, src/patternfly/components/ClipboardCopy/examples/ClipboardCopy.md, src/patternfly/components/ContextSelector/examples/ContextSelector.md, src/patternfly/components/DataList/examples/DataList.md, src/patternfly/components/DataToolbar/examples/DataToolbar.md, src/patternfly/components/EmptyState/examples/EmptyState.md, src/patternfly/components/FormControl/examples/FormControl.md, src/patternfly/components/InputGroup/examples/InputGroup.md, src/patternfly/components/ModalBox/examples/ModalBox.md, src/patternfly/components/NotificationBadge/examples/NotificationBadge.md, src/patternfly/components/OptionsMenu/examples/OptionsMenu.md, src/patternfly/components/OverflowMenu/examples/OverflowMenu.md, src/patternfly/components/TabContent/examples/TabContent.md, src/patternfly/demos/AboutModal/examples/AboutModal.md, src/patternfly/demos/BasicForms/examples/BasicForms.md, src/patternfly/demos/CardView/examples/CardView.md, src/patternfly/demos/DataList/examples/DataList.md, src/patternfly/utilities/BoxShadow/examples/BoxShadow.md
Fixes issue #2359 - these regressions were introduced with the recent awesome refactoring effort.
=> fix: sentence case post z_refactor

src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly-next/issues/2400
=> fix(page): fixed hamburger alignment on mobile

src/patternfly/components/DataToolbar/data-toolbar.scss, src/patternfly/components/DataToolbar/examples/DataToolbar.md
=> refactor(data-toolbar): move and wrap chips

src/patternfly/components/Form/form.scss, src/patternfly/components/Select/examples/Select.md, src/patternfly/components/Select/select-checkbox-checked.hbs, src/patternfly/components/Select/select-checkbox-groups-checked.hbs, src/patternfly/components/Select/select-checkbox-groups.hbs, src/patternfly/components/Select/select-menu-fieldset.hbs, src/patternfly/components/Select/select-menu-group-title.hbs, src/patternfly/components/Select/select-menu-group.hbs, src/patternfly/components/Select/select-toggle-typeahead-form.hbs, src/patternfly/components/Select/select-toggle-typeahead.hbs, src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly-next/issues/2379
=> fix(select): removed use of form element in toggle and menu

src/patternfly/components/DataToolbar/data-toolbar.scss, src/patternfly/components/DataToolbar/examples/DataToolbar.md
reverts changes from https://github.com/patternfly/patternfly-next/pull/2397/files
=> fix(data-toolbar): revert changes from refactor-data-toolbar branch

src/patternfly/components/DataToolbar/data-toolbar.scss, src/patternfly/components/DataToolbar/examples/DataToolbar.md
This reverts commit 30af6bd879b6513c06171bcaecb4da50621f8213.
=> fix(data-toolbar): merge refactor-data-toolbar branch (#2434)

src/patternfly/components/DataToolbar/data-toolbar.scss, src/patternfly/components/DataToolbar/examples/DataToolbar.md
update for parity w/react implementation
=> refactor(data-toolbar): update chip-group structure

src/patternfly/sass-utilities/colors.scss
fixes https://github.com/patternfly/patternfly-next/issues/2476
=> fix(colors): updated pf-color-black-200 and pf-color-black-600

src/patternfly/_chart-globals.scss, src/patternfly/patternfly-charts.scss
Updated threshold chart properties to match design guidelines.
Fixes https://github.com/patternfly/patternfly-next/issues/2485
=> fix(charts): update threshold properties

src/patternfly/components/Nav/nav.scss
fixes https://github.com/patternfly/patternfly-next/issues/2436
=> fix(nav): removed bold for tertiary link current, active, focus

src/patternfly/components/OptionsMenu/options-menu.scss
=> fix(options-menu-separator): removed margin-bottom:last-child

src/patternfly/components/Card/card.scss, src/patternfly/components/Card/examples/Card.md
=> feat(selectable-card): added selectable card

src/patternfly/components/EmptyState/examples/EmptyState.md
=> fix(empty-state): moved basic example

src/patternfly/components/AppLauncher/app-launcher.scss
fixes https://github.com/patternfly/patternfly-next/issues/2514
=> fix(app-launcher): fixed spacing between favorites search and next item

src/patternfly/components/Nav/nav.scss
=> fix(horizontal-nav-link-hover-color): updated color to #2b9af3

src/patternfly/components/DataList/data-list.scss
=> fix(data-list): split state vars

src/patternfly/components/DataToolbar/data-toolbar-content-section.hbs, src/patternfly/components/DataToolbar/data-toolbar-content.hbs, src/patternfly/components/DataToolbar/data-toolbar-icon-button-group-example.hbs, src/patternfly/components/DataToolbar/data-toolbar-item-chip-group.hbs, src/patternfly/components/DataToolbar/data-toolbar-overflow-menu-example.hbs, src/patternfly/components/DataToolbar/data-toolbar.scss, src/patternfly/components/DataToolbar/examples/DataToolbar.md, src/patternfly/demos/DataToolbar/examples/DataToolbar.md
Closes #2456 
- Toolbar needs a wrapper to separate static content from dynamically generated content
- Margins for groups and items need refinement
=> refactor(data-toolbar): added content wrapper, updated margins

src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly-next/issues/2443
=> fix(wizard): bolded current sub-step link

src/patternfly/components/EmptyState/empty-state.scss, src/patternfly/components/EmptyState/examples/EmptyState.md
=> feat(empty-state): xl variation

src/patternfly/components/Table/examples/Table.md, src/patternfly/components/Table/table-grid.scss
fixes https://github.com/patternfly/patternfly-next/issues/2557
=> fix(table): fixed bug with mobile inheritable grid-column property

src/patternfly/components/InputGroup/examples/InputGroup.md
closes #2299 
@mcarrano @mcoker @mattnolting do you think I should add any documentation for when to use the plain modifier over the control modifier for the button next to the input?
=> feat(input): add new example

src/patternfly/components/Table/table-grid.scss
=> fix(table): fix border

experimental-features.js, gatsby-browser.js, src/patternfly/components/DataToolbar/examples/DataToolbar.md, src/patternfly/components/Divider/examples/Divider.md, src/patternfly/components/Drawer/examples/Drawer.md, src/patternfly/components/OverflowMenu/examples/OverflowMenu.md, src/patternfly/components/Spinner/examples/Spinner.md, src/patternfly/components/_all.scss
=> chore(promote): datatoolbar, divider, overflowmenu and spinner

src/patternfly/components/AppLauncher/app-launcher-menu-item.hbs, src/patternfly/components/AppLauncher/app-launcher-toggle.hbs, src/patternfly/components/ClipboardCopy/clipboard-copy-group-copy.hbs, src/patternfly/components/ClipboardCopy/clipboard-copy-group-toggle.hbs, src/patternfly/components/ClipboardCopy/examples/ClipboardCopy.md, src/patternfly/components/Dropdown/dropdown-menu-item.hbs, src/patternfly/components/Dropdown/dropdown-toggle-button.hbs, src/patternfly/components/Dropdown/dropdown-toggle.hbs, src/patternfly/components/OptionsMenu/options-menu-menu-item.hbs, src/patternfly/components/OptionsMenu/options-menu-toggle.hbs, src/patternfly/components/Select/select-single.hbs, src/patternfly/components/Select/select-toggle.hbs, src/patternfly/components/Select/select-typeahead.hbs
fixes https://github.com/patternfly/patternfly-next/issues/2556
=> fix(clipboard-copy): assigned type="button" to prevent form submit

src/patternfly/components/Table/examples/Table.md, src/patternfly/components/Table/table-tbody.hbs, src/patternfly/components/Table/table-td.hbs, src/patternfly/components/Table/table-th.hbs, src/patternfly/components/Table/table-tr.hbs
=> fix(table): fix accessibility for mobile

src/patternfly/components/Table/table.scss
=> fix(table): update font-size for check

src/patternfly/components/Check/check-description.hbs, src/patternfly/components/Check/check.scss, src/patternfly/components/Check/examples/Check.md, src/patternfly/components/Radio/examples/Radio.md, src/patternfly/components/Radio/radio-description.hbs, src/patternfly/components/Radio/radio.scss
=> feat(radio): add optional description vertical

.circleci/config.yml, gulpfile.js, package.json, src/patternfly/components/Drawer/drawer.scss, src/patternfly/components/Page/page.scss
Towards https://github.com/patternfly/patternfly-org/issues/1625
Depends on #2586
=> build(lint): lint css size

package-lock.json, package.json
package name changed back to "@patternfly/patternfly"
=> chore(fix): pr comment fix

src/patternfly/components/Login/login.scss
fixes https://github.com/patternfly/patternfly-next/issues/2597
=> fix(login): prevented login container from shrinking based on content

build/npm-scripts/ie-convert-all.js
Closes #2595
Also added a quick wiki page: https://github.com/patternfly/patternfly-next/wiki/IE11-Build
=> chore(ie11): nicer ie11 error message

build/gulp/codeTransformer.js
fixes https://github.com/patternfly/patternfly-next/issues/2676
=> docs(workspace): added wrapper to examples to fix example specific css

src/patternfly/components/DataToolbar/data-toolbar-item-search-filter.hbs
=> fix(data-toolbar): updated input type to search

src/patternfly/components/Pagination/pagination.scss
closes #2663 
related to https://github.com/patternfly/patternfly-react/issues/3530#issuecomment-576937340
//cc @mcoker
=> feat(Pagination): allow updating input width with CSS vars

src/patternfly/components/Nav/nav.scss
fixes https://github.com/patternfly/patternfly-next/issues/2572
=> fix(nav): updated group title spacing so it changes responsively

src/patternfly/components/SimpleList/examples/SimpleList.md, src/patternfly/components/SimpleList/simple-list-item-link.hbs, src/patternfly/components/SimpleList/simple-list.scss
fixes https://github.com/patternfly/patternfly-next/issues/2674
=> fix(simple-list): added tabindex, button type, removed hover underline

src/patternfly/components/Select/examples/Select.css, src/patternfly/components/Select/examples/Select.md, src/patternfly/components/Select/select-toggle.hbs
fixes https://github.com/patternfly/patternfly-next/issues/2519
=> fix(select): made badge optional in checkbox select toggle

src/patternfly/layouts/Toolbar/toolbar.scss, src/patternfly/layouts/_all.scss
fixes https://github.com/patternfly/patternfly-next/issues/2688
=> fix(toolbar): added toolbar layout CSS

src/patternfly/components/DataList/data-list.scss
fixes https://github.com/patternfly/patternfly-next/issues/2690
=> fix(data-list): enabled hidden/visible feature to update display

src/patternfly/components/InlineEdit/inline-edit.scss
=> fix(inline-edit): firefox bug causes alignment issue

src/patternfly/components/DataList/data-list.scss, src/patternfly/components/DataList/examples/DataList.md
=> feat(data-list-compact): added compact version of data list

RELEASE-NOTES.md
Please review the release notes for 2020.02
=> (release-notes): updated release notes for 2020.02 release

build/gulp/html.js, build/gulp/ws-lite.css
=> chore(lite): add class to body of fullscreen examples

src/patternfly/components/AboutModalBox/about-modal-box.scss
Testing if PR previews and releasing to `prerelease-v4` on NPM will work.
=> fix(about-modal): add a comment to test v4 release

src/patternfly/components/Dropdown/dropdown-menu.hbs, src/patternfly/demos/Table/examples/Table.md, src/patternfly/demos/Table/table-toolbar.hbs
fixes https://github.com/patternfly/patternfly-next/issues/2626
they're the last demos under /demos/table
=> docs(demos): add table column management demo

src/patternfly/components/NotificationDrawer/examples/NotificationDrawer.md, src/patternfly/components/NotificationDrawer/notification-drawer-basic-list.hbs
fixes https://github.com/patternfly/patternfly-next/issues/2712
=> fix(notificationdrawer): updated dropdowns so they dont overflow parent

src/patternfly/components/DataToolbar/data-toolbar.scss, src/patternfly/components/Divider/divider.hbs, src/patternfly/components/Divider/divider.scss, src/patternfly/components/Divider/examples/Divider.css, src/patternfly/components/Divider/examples/Divider.md, src/patternfly/components/OverflowMenu/overflow-menu.scss, src/patternfly/layouts/Flex/examples/Flex.css, src/patternfly/layouts/Flex/examples/Flex.md
closes #2148 
**Divider component preview**
https://patternfly-next-pr-2734.surge.sh/documentation/core/components/divider
=> feat(vertical-divider): added vertical divider

src/patternfly/layouts/Flex/examples/Flex.css
fixes https://github.com/patternfly/patternfly-next/issues/2786
=> chore(flex): scoped flex layout workspace styles to layout examples

.circleci/upload-preview.js
=> chore(a11y): fix a11y upload report

src/patternfly/components/Wizard/examples/Wizard.css, src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly-next/issues/2804
=> fix(wizard): made active step bold, fixed in-page workspace example

src/patternfly/components/Check/check.scss, src/patternfly/components/Radio/radio.scss
fixes https://github.com/patternfly/patternfly-next/issues/2677
=> fix(radio, check): fixed radio left margin overflow, error in selector

build/gulp/ws-lite.css, src/patternfly/_variables.scss, src/patternfly/components/Accordion/accordion.scss, src/patternfly/components/Badge/badge.scss, src/patternfly/components/Chip/chip.scss, src/patternfly/components/ChipGroup/chip-group.scss, src/patternfly/components/Login/login.scss, src/patternfly/components/Nav/nav.scss, src/patternfly/components/SimpleList/simple-list.scss, src/patternfly/components/Wizard/wizard.scss, src/patternfly/sass-utilities/colors.scss, src/patternfly/sass-utilities/scss-variables.scss
fixes https://github.com/patternfly/patternfly-next/issues/2424
* `$pf-color-black-200` changes to `#f0f0f0`
* `$pf-color-black-600` changes to `#6a6e73`
* `$pf-global--BackgroundColor--200` changes to `$pf-color-black-200 `
* Removes `$pf-global--BackgroundColor--150` and `$pf-global--BackgroundColor--300`
* Updated all components that use `$pf-global--BackgroundColor--150` or `$pf-global--BackgroundColor--300` to use  `$pf-global--BackgroundColor--200` instead
=> fix(color): updated black global and background global/component vars

src/patternfly/components/Table/table.scss
closes #1948 
1. Changed `--pf-c-table--FontWeight` to `--pf-c-table-cell--FontWeight`
=> style(table-cell-font-weight): update table cell font weight var name

build/gulp/copy.js
=> fix(md): add example css to dist

.circleci/css-size-report/sizeReport.js, build/gulp/copy.js, build/gulp/lint.js
=> chore(lint): dont lint example CSS

src/patternfly/components/Page/page.scss
closes #2040 
1. Removed `--pf-c-page__header-tools--MarginTop: var(--pf-global--spacer--sm);`
2. Removed `--pf-c-page__header-tools--MarginBottom: var(--pf-global--spacer--sm);`
3. Removed `margin-top`
4. Removed `margin-bottom`
=> fix(page-header-tools-margin): removed margin-top/bottom

src/patternfly/components/Button/button-icon.hbs
=> Chore button icon

src/patternfly/sass-utilities/_all.scss, src/patternfly/sass-utilities/bs-variables.scss
fixes https://github.com/patternfly/patternfly/issues/2864
=> fix(sass-utilities): made bs-variables optional include

src/patternfly/demos/Table/examples/Table.md
fixes https://github.com/patternfly/patternfly/issues/2873
=> fix(table): updated text in column management demo modal

.circleci/upload-preview.js, README.md, RELEASE-NOTES.md, build/gulp/ie11.js, gatsby-config.js, package.json, src/patternfly/demos/DataList/data-list-content-1.hbs, src/patternfly/demos/DataList/data-list-content-4.hbs, src/patternfly/demos/MasterDetail/master-detail-data-list.hbs, src/site/pages/accessibility-guide.md, src/site/pages/guidelines.md
=> chore(repo): replace 288 occurences of patternfly-next with patternfly

RELEASE-NOTES.md
For v2.71.1 for the 2020.04 release
=> fix(repo): update release notes

RELEASE-NOTES.md
=> fix(repo): merge master for 2020.04 release

build/gulp/copy.js
Step 1 to add demos to staging.patternfly.org
=> fix(demos): publish demos to NPM

RELEASE-NOTES.md
=> fix(release-notes): fix formatting of release notes

build/gulp/codeTransformer.js, build/gulp/html.js
=> fix(dev-lite): create titles from path on disk rather than frontmatter

src/patternfly/components/Login/login.scss
fixes https://github.com/patternfly/patternfly/issues/2913
=> fix(login): keeps login from shrinking based on content size

README.md
One of the commits was to have both dev configurations in the readme file.
=> Readme fix 2947

build/gulp/html.js
=> chore(dev-lite): remove examples and components on delete

CODE_OF_CONDUCT.md, README.md, RELEASE-NOTES.md, build/gulp/html.js
=> chore(v4): merge master

src/patternfly/demos/Table/examples/Table.md
fixes https://github.com/patternfly/patternfly/issues/3033
=> chore(table): changed column management modal demo button to link

src/patternfly/components/AppLauncher/app-launcher.scss, src/patternfly/components/AppLauncher/examples/AppLauncher.md, src/patternfly/components/ContextSelector/context-selector.scss, src/patternfly/components/ContextSelector/examples/ContextSelector.md, src/patternfly/components/Dropdown/examples/Dropdown.md, src/patternfly/components/ExpandableSection/examples/ExpandableSection.md, src/patternfly/components/ExpandableSection/expandable-section.scss, src/patternfly/components/OptionsMenu/examples/OptionsMenu.md, src/patternfly/components/OptionsMenu/options-menu.scss, src/patternfly/components/Select/examples/Select.md, src/patternfly/components/Select/select.scss
=> fix(components): add pf-m-active to toggles

src/patternfly/components/AboutModalBox/about-modal-box.scss
fixes https://github.com/patternfly/patternfly/issues/3007
=> fix(aboutmodalbox): increased specificity of close button selector

src/patternfly/base/_variables.scss, src/patternfly/sass-utilities/scss-variables.scss
closes #2054 
* Removes `--pf-global--golden-ratio` and `$pf-global--golden-ratio` all instances of the variable should be removed in your application.
=> fix(vars): remove golden ratio var

src/patternfly/base/_variables.scss, src/patternfly/sass-utilities/scss-variables.scss, src/patternfly/utilities/Spacing/examples/Spacing.md
fixes https://github.com/patternfly/patternfly/issues/2989
=> feat(spacer): added 80px spacer

src/patternfly/components/Chip/chip.hbs, src/patternfly/components/ChipGroup/chip-group-label.hbs, src/patternfly/components/ChipGroup/chip-group-list.hbs, src/patternfly/components/ChipGroup/chip-group.hbs, src/patternfly/components/ChipGroup/chip-group.scss, src/patternfly/components/ChipGroup/examples/ChipGroup.md, src/patternfly/components/Select/select-chip-group-collapsed.hbs, src/patternfly/components/Select/select-chip-group-expanded.hbs, src/patternfly/components/Toolbar/examples/Toolbar.md, src/patternfly/components/Toolbar/toolbar-item-chip-group.hbs, src/patternfly/demos/Toolbar/examples/Toolbar.md
fixes https://github.com/patternfly/patternfly/issues/2990, fixes https://github.com/patternfly/patternfly/issues/2998, fixes https://github.com/patternfly/patternfly/issues/2390
TBD
=> fix(chip-group): refactored structure so chip-group no longer nests

src/patternfly/components/Dropdown/dropdown.scss
=> fix(dropdown): cleanup vars

src/patternfly/components/Table/examples/Table.css, src/patternfly/components/Table/examples/Table.md, src/patternfly/components/Table/table-grid.scss, src/patternfly/components/Table/table-th.hbs, src/patternfly/components/Table/table.scss
closes #3004 
Updates include 
- Fixed truncation is compound expansion cells
- Added examples for nested `.pf-c-table__text`
=> fix(table-modifier-bugs): fixed truncate and wrap mod bugs

src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly/issues/2985
=> fix(select): adjusted chip group margin in toggle

src/patternfly/components/Chip/chip.scss, src/patternfly/components/ChipGroup/chip-group.scss, src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly/issues/3078
=> fix(chip): adjusted chip top/bottom padding, chip group margin in select

src/patternfly/components/Accordion/accordion.scss
closes #1938  #1888  #2388
Will add to this once PR is reviewed
=> fix(accordion): clean up vars

src/patternfly/components/DataList/data-list.scss, src/patternfly/components/Page/examples/Page.md, src/patternfly/components/Page/page-header-tools-item.hbs, src/patternfly/components/Page/page.scss, src/patternfly/demos/Drawer/drawer-demo-default.hbs, src/patternfly/demos/Page/page-template-header-tools-elements.hbs
fixes https://github.com/patternfly/patternfly/issues/3089
=> fix(page): removed pf-m-mobile/icon/user, added hidden/visible

src/patternfly/components/FormControl/form-control.scss
=> fix(form-control-background): split declarations

src/patternfly/base/_common.scss, src/patternfly/base/_globals.scss, src/patternfly/components/ExpandableSection/expandable-section.scss, src/patternfly/components/Form/form.scss, src/patternfly/components/Label/label.scss
fixes https://github.com/patternfly/patternfly/issues/3097
=> fix(global): added global transparent, margin, and padding styles

src/patternfly/demos/Page/page-template-header-tools-elements.hbs, src/patternfly/demos/Page/page-template-header-tools-notification-badge.hbs
fixes https://github.com/patternfly/patternfly/issues/3114
=> fix(page): updated header tools icons in demos

src/patternfly/components/FormControl/form-control.scss, src/patternfly/components/Table/table.scss
fixes `pf-m-nowrap` behavior on sortable `th`
=> fix(table-sort-th-columns): fixing col def bug for nowrap

src/patternfly/components/Button/button.scss
=> fix(button): unused button vars

src/patternfly/components/Select/examples/Select.md, src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly/issues/3126
=> fix(select): added item modifier to apply focus styles for keyboard nav

src/patternfly/components/Drawer/drawer.scss, src/patternfly/components/Tabs/tabs.scss
fixes https://github.com/patternfly/patternfly/issues/3141
fixes https://github.com/patternfly/patternfly/issues/3140
=> fix(drawer/tabs): add missing breakpoints to breakpoint mods

.circleci/config.yml, src/patternfly/components/Drawer/drawer.scss
Revert part of #3146 for RC2 since @mattnolting was relying on some old behavior.
=> fix(drawer): revert md breakpoint

UPGRADE-GUIDE.md, gatsby-config.js
Move pretty-notes.md from patternfly-scripts to upgrade-guide.md and add to docs.
~~Still need a colors section from @mceledonia~~
Preview: https://patternfly-pr-3139.surge.sh/documentation/core/overview/upgrade-guide
=> fix(docs): add release notes v4

RELEASE-NOTES.md
=> fix(docs): add 2020.07 release notes

.circleci/config.yml
=> chore(circleci): deploy v3

.circleci/upload-preview.js
Fix `Aborted - you do not have permission to publish to patternfly.surge.sh`
=> fix(v3): fix v3 upload script

package.json, release.config.js
Commit to having prereleases from master. Depends on #3161
=> chore(npm): publish to prerelease tag

src/patternfly/components/Button/button.scss, src/patternfly/components/Button/examples/Button.css, src/patternfly/components/Button/examples/Button.md
fixes https://github.com/patternfly/patternfly/issues/2946
=> fix(button): added pf-m-aria-disabled state

src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly/issues/3175
cc @karelhala
=> fix(modal): allowed wizard height to shrink when used in modal

src/patternfly/base/_variables.scss, src/patternfly/components/Label/label.scss, src/patternfly/sass-utilities/colors.scss
fixes https://github.com/patternfly/patternfly/issues/3136
fixes https://github.com/patternfly/patternfly/issues/3137
=> fix(label): added purple-50, updated green/purple fill colors

src/patternfly/components/Tabs/tabs.scss
fixes https://github.com/patternfly/patternfly/issues/3120
=> fix(tabs): reduced secondary tab font-size

src/patternfly/components/AlertGroup/examples/AlertGroup.md
fixes https://github.com/patternfly/patternfly/issues/3133
=> chore(alertgroup): updated basic example to inline, removed actions

src/patternfly/components/Table/examples/Table.md, src/patternfly/components/Table/table.scss, src/patternfly/demos/Table/examples/Table.md, src/patternfly/demos/Table/table-simple-table.hbs
fixes https://github.com/patternfly/patternfly/issues/2838
=> feat(table): added sticky-header variation

src/patternfly/components/Divider/divider.scss
fixes https://github.com/patternfly/patternfly/issues/3190
=> fix(divider): added xs spacer to inset map

src/patternfly/components/Table/examples/Table.md, src/patternfly/components/Table/table-column-help-action.hbs, src/patternfly/components/Table/table-column-help.hbs, src/patternfly/components/Table/table-th.hbs, src/patternfly/components/Table/table.scss
fixes https://github.com/patternfly/patternfly/issues/3044
=> feat(table): added support for column header help

gatsby-config.js, package-lock.json, package.json
=> fix(docs): remove footer

src/patternfly/components/Table/table.scss
fixes https://github.com/patternfly/patternfly/issues/3196
=> fix(table): updated sticky header border var so border is visible

build/gulp/html.js, build/gulp/snippets.js, parseHbs.js
=> fix(dev-lite): change title to filepath

src/patternfly/components/FormControl/form-control.scss
fixes https://github.com/patternfly/patternfly/issues/3064
=> fix(form-control): adjusted select arrow size

src/patternfly/components/NotificationDrawer/notification-drawer-basic-list.hbs
=> fix(notificationdrawer): duplicate ids

src/patternfly/components/Toolbar/examples/Toolbar.md
=> fix(toolbar): remove beta flag from docs

.circleci/config.yml
=> fix(ci): don't run size report against master

src/patternfly/components/Chip/examples/Chip.md, src/patternfly/components/ChipGroup/examples/ChipGroup.md
fixes https://github.com/patternfly/patternfly/issues/3102
=> fix(chip): updated docs

src/patternfly/components/Chip/chip.scss, src/patternfly/components/ChipGroup/chip-group.scss
closes #2954 
Before update:
After update:
=> refactor: udpated text max-length

src/patternfly/components/Button/button.scss, src/patternfly/components/Button/examples/Button.md
closes #3099 
@mcarrano do you know why the Dark theme designs were included in the original issue?
=> feat(button): add cta variation to button

src/patternfly/components/Nav/nav-link.hbs, src/patternfly/components/Nav/nav.scss
Closes #3212. Once merged, I'll make the corresponding change in https://github.com/patternfly/patternfly-react/issues/4377.
=> feat(nav): adds button variation to nav-item

src/patternfly/components/Select/examples/Select.css, src/patternfly/components/Select/examples/Select.md, src/patternfly/components/Select/select-checkbox.hbs, src/patternfly/components/Select/select-menu-item-check.hbs, src/patternfly/components/Select/select.scss, src/patternfly/components/Toolbar/examples/Toolbar.md, src/patternfly/demos/Toolbar/examples/Toolbar.md
fixes https://github.com/patternfly/patternfly/issues/3222
this is needed for https://github.com/patternfly/patternfly-react/pull/4460
=> fix(select): added support for checkbox select with description

src/patternfly/components/InputGroup/examples/InputGroup.md
fixes https://github.com/patternfly/patternfly/issues/3134
=> chore(input-group): updated example aria-label

src/patternfly/components/Table/table-column-help-action.hbs
=> fix(table): add aria-label to help button

src/patternfly/components/Wizard/examples/Wizard.md, src/patternfly/components/Wizard/wizard-nav-link.hbs, src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly/issues/3215
=> fix(wizard): added support for buttons as nav items

src/patternfly/components/Hint/examples/Hint.md, src/patternfly/components/Hint/hint-actions.hbs, src/patternfly/components/Hint/hint-body.hbs, src/patternfly/components/Hint/hint-footer.hbs, src/patternfly/components/Hint/hint-header.hbs, src/patternfly/components/Hint/hint-title.hbs, src/patternfly/components/Hint/hint.hbs, src/patternfly/components/Hint/hint.scss, src/patternfly/components/_all.scss
=> Feat(Hint): Add hint component

src/patternfly/components/SearchInput/examples/SearchInput.md, src/patternfly/components/SearchInput/search-input-clear.hbs, src/patternfly/components/SearchInput/search-input-count.hbs, src/patternfly/components/SearchInput/search-input-icon.hbs, src/patternfly/components/SearchInput/search-input-nav.hbs, src/patternfly/components/SearchInput/search-input-text-input.hbs, src/patternfly/components/SearchInput/search-input-text.hbs, src/patternfly/components/SearchInput/search-input-utilities.hbs, src/patternfly/components/SearchInput/search-input.hbs, src/patternfly/components/SearchInput/search-input.scss, src/patternfly/components/_all.scss
fixes https://github.com/patternfly/patternfly/issues/3151
=> feat(search-input): added search input component

src/patternfly/components/AppLauncher/examples/AppLauncher.md, src/patternfly/components/Select/examples/Select.css, src/patternfly/components/Select/examples/Select.md, src/patternfly/components/Select/examples/select-disabled-example.hbs, src/patternfly/components/Select/examples/select-plain-example.hbs, src/patternfly/components/Select/examples/select-plain-expanded-example.hbs, src/patternfly/components/Select/examples/select-single-example.hbs, src/patternfly/components/Select/examples/select-single-expanded-example.hbs, src/patternfly/components/Select/examples/select-single-expanded-selected-example.hbs, src/patternfly/components/Select/examples/select-single-top-expanded-example.hbs, src/patternfly/components/Select/select-menu-descriptive.hbs, src/patternfly/components/Select/select-menu-favorites.hbs, src/patternfly/components/Select/select-menu-item-action-icon.hbs, src/patternfly/components/Select/select-menu-item-description.hbs, src/patternfly/components/Select/select-menu-item-favorite-icon.hbs, src/patternfly/components/Select/select-menu-item-main.hbs, src/patternfly/components/Select/select-menu-item.hbs, src/patternfly/components/Select/select-menu-wrapper.hbs, src/patternfly/components/Select/select-single.hbs, src/patternfly/components/Select/select-typeahead.hbs, src/patternfly/components/Select/select.hbs, src/patternfly/components/Select/select.scss
fixes https://github.com/patternfly/patternfly/issues/3209
=> feat(select): added favorites

src/patternfly/components/Tile/examples/Tile.css, src/patternfly/components/Tile/examples/Tile.md, src/patternfly/components/Tile/tile-body.hbs, src/patternfly/components/Tile/tile-header.hbs, src/patternfly/components/Tile/tile-icon.hbs, src/patternfly/components/Tile/tile-subtext.hbs, src/patternfly/components/Tile/tile-title.hbs, src/patternfly/components/Tile/tile.hbs, src/patternfly/components/Tile/tile.scss, src/patternfly/components/_all.scss
=> feat(tile): add tile component

src/patternfly/components/DescriptionList/description-list-description.hbs, src/patternfly/components/DescriptionList/description-list-group.hbs, src/patternfly/components/DescriptionList/description-list-order.scss, src/patternfly/components/DescriptionList/description-list-term.hbs, src/patternfly/components/DescriptionList/description-list-text.hbs, src/patternfly/components/DescriptionList/description-list.hbs, src/patternfly/components/DescriptionList/description-list.scss, src/patternfly/components/DescriptionList/description-list__example.hbs, src/patternfly/components/DescriptionList/examples/DescriptionList.md, src/patternfly/components/_all.scss
=> feat(description-list): added description list component

src/patternfly/components/Form/examples/Form.md, src/patternfly/components/Form/form.scss, src/patternfly/components/FormControl/examples/FormControl.md, src/patternfly/components/FormControl/form-control.scss
fixes https://github.com/patternfly/patternfly/issues/3277
cc @jessiehuff I added some a11y docs - would you mind reviewing and letting me know if it looks OK or you'd like to see any other updates?
=> fix(form-control): added warning state, updated docs

RELEASE-NOTES.md, src/patternfly/components/NotificationBadge/examples/NotificationBadge.md, src/patternfly/components/NotificationBadge/notification-badge-count.hbs, src/patternfly/components/NotificationBadge/notification-badge.scss, src/patternfly/components/Page/page.scss, src/patternfly/demos/Drawer/examples/Drawer.md, src/patternfly/demos/Page/page-template-header-tools-elements.hbs, src/patternfly/demos/Page/page-template-header-tools-notification-badge.hbs
fixes https://github.com/patternfly/patternfly/issues/3293
This reverts commit 3acd23a5735d18db0566911342e9b360cb09e0c0.
=> fix(notification-badge): reverted enhancements in #3231

src/patternfly/base/_common.scss, src/patternfly/sass-utilities/scss-variables.scss
fixes https://github.com/patternfly/patternfly/issues/3254
=> fix(global): enabled flag to exclude root font-size unset

src/patternfly/components/Wizard/examples/Wizard.css, src/patternfly/components/Wizard/wizard.scss
fixes https://github.com/patternfly/patternfly/issues/3280
=> fix(wizard): left aligned nav item element

gulpfile.js
=> fix(watch): watch more sass

src/icons/generatorConfig.js
fixes https://github.com/patternfly/patternfly/issues/3304
=> fix(icon): fixed svg filename in generator config

src/patternfly/components/DescriptionList/description-list.hbs
=> fix(description-list): change component to dl

src/patternfly/components/DescriptionList/description-list.scss
Closes #3326. Opening this PR to address @maryshak1996 's comment on https://github.com/patternfly/patternfly-react/pull/4586.
=> fix(description-list): change spacer width to 24px column gap

src/patternfly/components/Button/button.scss, src/patternfly/components/NotificationBadge/examples/NotificationBadge.css, src/patternfly/components/NotificationBadge/examples/NotificationBadge.md, src/patternfly/components/NotificationBadge/notification-badge.hbs, src/patternfly/components/NotificationBadge/notification-badge.scss, src/patternfly/components/Page/page-main-section-body.hbs, src/patternfly/components/Page/page.scss, src/patternfly/demos/Drawer/examples/Drawer.md, src/patternfly/demos/Page/page-template-header-tools-elements.hbs, src/patternfly/demos/Page/page-template-header-tools-notification-badge.hbs
closes #2994 
closes #3283 
closes #3284 
Updated design @mceledonia
=> fix(notification-badge-alignment): fixed notification badge alignment

src/patternfly/components/NotificationDrawer/examples/NotificationDrawer.md, src/patternfly/components/NotificationDrawer/notification-drawer-basic-list.hbs, src/patternfly/components/NotificationDrawer/notification-drawer-list-item-header-icon.hbs, src/patternfly/components/NotificationDrawer/notification-drawer-list-item-header-title.hbs, src/patternfly/components/NotificationDrawer/notification-drawer-list-item.hbs, src/patternfly/components/NotificationDrawer/notification-drawer.scss
=> feat(notificationdrawer): add recommendation option

src/patternfly/components/Label/examples/Label.md, src/patternfly/components/Label/label-text.hbs, src/patternfly/components/Label/label.scss
=> feat(label): add support for overflow

src/patternfly/components/TabContent/examples/TabContent.md, src/patternfly/components/TabContent/tab-content.scss, src/patternfly/components/Tabs/examples/Tabs.css, src/patternfly/components/Tabs/examples/Tabs.md, src/patternfly/components/Tabs/tabs.scss
=> feat(tab-background-color): added tab background modifiers

src/patternfly/components/Tile/tile.scss
fixes https://github.com/patternfly/patternfly/issues/3333
=> fix(tile): update basic tile icon color to match stacked

src/patternfly/components/Table/table-grid.scss, src/patternfly/components/Table/table.scss
https://github.com/patternfly/patternfly-react/issues/4613
=> fix(table): expect when applying pf-m-no-padding class

src/patternfly/components/Page/examples/Page.md, src/patternfly/components/Page/page-main-body.hbs, src/patternfly/components/Page/page-main-breadcrumb.hbs, src/patternfly/components/Page/page-main-nav.hbs, src/patternfly/components/Page/page-main-section-body.hbs, src/patternfly/components/Page/page-main-section.hbs, src/patternfly/components/Page/page-main-wizard.hbs, src/patternfly/components/Page/page.scss, src/patternfly/demos/Page/examples/Page.md, src/patternfly/demos/Page/page-template-breadcrumb.hbs, src/patternfly/demos/Page/page-template-gallery.hbs, src/patternfly/demos/Page/page-template-title.hbs, src/patternfly/demos/Table/examples/Table.md, src/patternfly/demos/Wizard/examples/Wizard.md
fixes https://github.com/patternfly/patternfly/issues/2910
new PR from a new fork
Old PR - https://github.com/patternfly/patternfly/pull/3340
=> feat(page): added ability to limit width of content in page section

src/patternfly/components/NotificationBadge/notification-badge.scss
fixes https://github.com/patternfly/patternfly/issues/3364
=> fix(notification-badge): allowed text to display on top of bg

RELEASE-NOTES.md, src/patternfly/components/NotificationBadge/notification-badge.scss, src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly/issues/3368
=> fix(page): fixed notification badge state and header item conflict

RELEASE-NOTES.md, src/patternfly/components/NotificationBadge/notification-badge.scss, src/patternfly/components/Page/page.scss
fixes https://github.com/patternfly/patternfly/issues/3388
=> fix(notification-badge): removed unread state border

src/patternfly/components/Page/examples/Page.md, src/patternfly/demos/Page/examples/Page.md
fixes https://github.com/patternfly/patternfly/issues/2144
=> docs(page): added blurb on enabling pf-c-page to fill viewport height

RELEASE-NOTES.md
=> fix(release notes): Staging fixes for release notes

.github/stale.yml
closes #3356 
Add enhancement & Feature labels to stalebot ignore
=> chore(repo): update stalebot ignored labels

release.config.js
Hopefully will leave a comment on PRs. Will also create a github release.
=> fix(release): added github plugin

src/patternfly/components/Table/examples/Table.md
fixes https://github.com/patternfly/patternfly/issues/1634
=> docs(table): added usage for using anchor to sort column headers

src/patternfly/components/Skeleton/examples/Skeleton.md, src/patternfly/components/ToggleGroup/examples/ToggleGroup.md, src/patternfly/demos/NotificationDrawer/examples/NotificationDrawer.md, src/patternfly/demos/Skeleton/examples/Skeleton.md
fixes https://github.com/patternfly/patternfly/issues/3362
=> chore(workspace): updated example titles/metadata

src/patternfly/demos/Table/table-loading-table.hbs
fixes https://github.com/patternfly/patternfly/issues/2490
=> chore(table): updated loading demo text

src/patternfly/components/Dropdown/dropdown.scss
fixes https://github.com/patternfly/patternfly/issues/3258
=> fix(dropdown): added border-radius to primary dropdown toggle

src/patternfly/components/Toolbar/examples/Toolbar.md, src/patternfly/components/Toolbar/toolbar.scss
fixes #3240
Initial PR here: https://github.com/patternfly/patternfly/pull/3317
=> fix(toolbar-padding): updated toolbar padding

src/patternfly/components/Page/examples/Page.md, src/patternfly/components/Page/page-header-brand-link.hbs
=> fix(page): add href to page-header-brand-link

src/patternfly/components/OverflowMenu/overflow-menu-control.hbs, src/patternfly/components/Toolbar/examples/Toolbar.md, src/patternfly/components/Toolbar/toolbar-expandable-content.hbs, src/patternfly/components/Toolbar/toolbar-icon-button-group-example.hbs, src/patternfly/components/Toolbar/toolbar-overflow-menu-example.hbs, src/patternfly/components/Toolbar/toolbar.scss, src/patternfly/demos/Page/examples/Page.md, src/patternfly/demos/Page/page-demo-default.hbs, src/patternfly/demos/PrimaryDetail/primary-detail-card-toolbar.hbs, src/patternfly/demos/PrimaryDetail/primary-detail-toolbar.hbs, src/patternfly/demos/Skeleton/table-skeleton-toolbar.hbs, src/patternfly/demos/Toolbar/examples/Toolbar.md
=> Feat add overflow menu to toolbar

src/patternfly/components/Label/examples/Label.css, src/patternfly/components/Label/examples/Label.md, src/patternfly/components/Label/label-content.hbs, src/patternfly/components/Label/label.hbs, src/patternfly/components/Label/label.scss, src/patternfly/components/LabelGroup/examples/LabelGroup.md, src/patternfly/components/LabelGroup/label-group-close.hbs, src/patternfly/components/LabelGroup/label-group-label.hbs, src/patternfly/components/LabelGroup/label-group-list-item.hbs, src/patternfly/components/LabelGroup/label-group-list.hbs, src/patternfly/components/LabelGroup/label-group.hbs, src/patternfly/components/LabelGroup/label-group.scss, src/patternfly/components/_all.scss
fixes https://github.com/patternfly/patternfly/issues/3376
@maryshak1996 let me know what you would like to do about a removable vertical label group
=> feat(label-group): added label group component, overflow label

src/patternfly/components/NotificationDrawer/examples/NotificationDrawer.md, src/patternfly/components/NotificationDrawer/notification-drawer-header-action-button.hbs, src/patternfly/components/NotificationDrawer/notification-drawer-header-action-close.hbs, src/patternfly/components/NotificationDrawer/notification-drawer.scss
=> fix(notificationdrawer): support close button 

src/patternfly/demos/Form/examples/BasicForms.md
Using a temporary patch downstream in the meantime, so no rush to merge.
=> fix(form): make demo id match component id

package-lock.json, package.json
=> chore(lint): bump stylelint

src/patternfly/demos/Table/table-empty-state-table.hbs, src/patternfly/demos/Table/table-loading-table.hbs
fixes https://github.com/patternfly/patternfly/issues/3123
=> chore(table): removed old code

src/patternfly/components/Drawer/drawer.scss, src/patternfly/components/LabelGroup/label-group-main.hbs
fixes https://github.com/patternfly/patternfly/issues/3459
=> fix(drawer): kept drawer panel from extending beyond drawer height

src/patternfly/components/Dropdown/dropdown.scss, src/patternfly/components/Menu/menu.scss
fixes https://github.com/patternfly/patternfly/issues/3411
=> fix(dropdown, menu): made menu text work in dark theme

src/patternfly/components/Button/button-progress-icon.hbs, src/patternfly/components/Button/button-progress.hbs, src/patternfly/components/Button/button.hbs, src/patternfly/components/Button/button.scss, src/patternfly/components/Button/examples/Button.md, src/patternfly/components/Spinner/examples/Spinner.md
fixes https://github.com/patternfly/patternfly/issues/3381
=> feat(button): added progress button

src/patternfly/components/FormControl/examples/FormControl.css, src/patternfly/components/FormControl/examples/FormControl.md, src/patternfly/components/FormControl/form-control.scss
fixes https://github.com/patternfly/patternfly/issues/3452
=> feat(form-control): added ability to specify custom icon for text inputs

src/patternfly/components/LabelGroup/label-group.scss
fixes https://github.com/patternfly/patternfly/issues/3465
=> fix(label-group): made left/right padding match in vertical layout

src/site/pages/guidelines.md
fixes https://github.com/patternfly/patternfly/issues/1228
=> docs(guidelines): added section for hover styles

src/patternfly/components/Page/page.scss, src/patternfly/demos/Page/examples/Page.md, src/patternfly/demos/Page/page-template-footer.hbs
fixes https://github.com/patternfly/patternfly/issues/3440
=> fix(page): fixed safari bug w/ sections shrinking shorter than content

src/patternfly/components/Progress/examples/Progress.md, src/patternfly/components/Progress/progress-indicator.hbs, src/patternfly/components/Progress/progress-status-icon.hbs, src/patternfly/components/Progress/progress-status.hbs, src/patternfly/components/Progress/progress.hbs, src/patternfly/components/Progress/progress.scss
fixes https://github.com/patternfly/patternfly/issues/2995
=> feat(progress): added warning state

src/patternfly/components/DescriptionList/description-list-term.hbs, src/patternfly/components/DescriptionList/description-list-text.hbs, src/patternfly/components/DescriptionList/description-list.scss, src/patternfly/components/DescriptionList/examples/DescriptionList.md
fixes https://github.com/patternfly/patternfly/issues/3369
=> fix(description-list): updated term text element to be inline

src/patternfly/components/Button/button.hbs, src/patternfly/components/Button/button.scss, src/patternfly/components/Button/examples/Button.md, src/patternfly/components/Hint/examples/Hint.md
=> fix(button): allowed inline link text to wrap and use with span element

src/patternfly/components/ChipGroup/chip-group-main.hbs, src/patternfly/components/ChipGroup/chip-group.scss, src/patternfly/components/ChipGroup/examples/ChipGroup.md
=> fix(chipgroup): position removable button at the top

src/patternfly/components/DataList/data-list-text.hbs, src/patternfly/components/DataList/data-list.scss, src/patternfly/components/DataList/examples/DataList.md
closes #3087 
Replaces https://github.com/patternfly/patternfly/pull/3159 which was the PR in the old PF repo.
=> feat(datalist): add text modifiers

gulpfile.js, scripts/gulp/copy.js, scripts/gulp/sass.js
Fix patternfly-charts crashing watchSASS and watching example CSS files/site JS and MD files.
=> fix(workspace): fix reloading bugs

package-lock.json, package.json
Keeps scroll position and hot-reloads browser rather than refreshing.
=> feat(workspace): add hmr for css

src/patternfly/components/AboutModalBox/examples/AboutModalBox.md, src/patternfly/components/ModalBox/examples/ModalBox.md, src/patternfly/components/Popover/examples/Popover.md, src/patternfly/components/Spinner/examples/Spinner.md
=> fix(docs): fix broken links

src/patternfly/components/Select/select-menu-descriptive.hbs, src/patternfly/components/Select/select-menu-favorites.hbs, src/patternfly/components/Select/select-menu-item.hbs, src/patternfly/components/Select/select-menu-wrapper.hbs, src/patternfly/components/Select/select-single.hbs, src/patternfly/components/Select/select-typeahead.hbs
fixes https://github.com/patternfly/patternfly/issues/3455
=> chore(select): fixed axe violations

src/patternfly/components/Menu/examples/Menu.md, src/patternfly/components/Menu/menu-item-action-icon.hbs, src/patternfly/components/Menu/menu-item-action.hbs
fixes https://github.com/patternfly/patternfly/issues/3454
=> chore(menu): updated example axe violations

README.md
https://github.com/patternfly/patternfly/issues/3514
=> fix(readme): added steps to updated screenshots

src/patternfly/patternfly-date-picker.scss
fixes https://github.com/patternfly/patternfly/issues/3520
=> fix(date-picker): kept text in month select from getting cut off

src/patternfly/components/FormControl/examples/FormControl.css
fixes https://github.com/patternfly/patternfly/issues/3523
there should be pizza 🍕 icon
=> chore(form-control): fixed icon not showing in custom icon example

src/patternfly/components/Alert/alert.scss
fixes https://github.com/patternfly/patternfly/issues/3451
=> fix(alert): allowed long strings in description to wrap

src/patternfly/components/EmptyState/empty-state.scss, src/patternfly/components/EmptyState/examples/EmptyState.md
fixes https://github.com/patternfly/patternfly/issues/3513
=> feat(empty-state): added xs variation

src/patternfly/layouts/Flex/flex.scss
=> fix(flex-max-width): added max-width to flex items

src/patternfly/components/LabelGroup/examples/LabelGroup.md, src/patternfly/components/LabelGroup/label-group-main.hbs, src/patternfly/components/LabelGroup/label-group.scss
=> fix(labelgroup): add close button to the top right always

src/patternfly/components/Table/examples/Table.md
This just extends the existing checkbox structure to support radio buttons.
fixes https://github.com/patternfly/patternfly/issues/3418
=> feat(table): added support for single row radio select

src/patternfly/components/ChipGroup/examples/ChipGroup.md, src/patternfly/components/Select/select-checkbox-checked.hbs, src/patternfly/components/Select/select-checkbox.hbs, src/patternfly/components/Select/select-chip-group-collapsed.hbs, src/patternfly/components/Select/select-chip-group-expanded.hbs, src/patternfly/components/Toolbar/toolbar-item-chip-group.hbs, src/patternfly/demos/Toolbar/examples/Toolbar.md
fixes https://github.com/patternfly/patternfly/issues/3525
=> fix(chip-group): updated all examples to use __main

src/patternfly/components/TreeView/examples/TreeView.md, src/patternfly/components/TreeView/tree-view-action.hbs, src/patternfly/components/TreeView/tree-view-node.hbs, src/patternfly/components/TreeView/tree-view.scss
=> feat(treeview): tree view node actions allows dropdowns and buttons

src/patternfly/components/DataList/data-list-grid.scss, src/patternfly/components/DataList/data-list.scss, src/patternfly/components/DataList/examples/DataList.md, src/patternfly/components/_all.scss
fixes https://github.com/patternfly/patternfly/issues/3228
=> feat(data-list): added grid modifiers
